### ISSUE TITLE
Search does not return any results

### ISSUE THREAD

**Issue by Elwetana** [cannatag/ldap3#1006]
I have the following code (Python 3.9, Ldap3 version 2.9.1):
````
from ldap3 import Server, Connection, SAFE_SYNC, SUBTREE, NTLM, ALL

root = "OU=Users,DC=company,DC=local"
filter = "(memberOf=CN=group_name,OU=Security Groups,DC=company,DC=local)"

server = Server('ldap://ad_server_on_lan', get_info=ALL)
conn = Connection(server, 'domain\\name', 'password', client_strategy=SAFE_SYNC, authentication=NTLM, auto_bind=True)
conn.search(search_base=root,
            search_filter = filter,
            search_scope=SUBTREE)

print(conn.result)
print(conn.entries)
````

This will return:
````
{'result': 0, 'description': 'success', 'dn': '', 'message': '', 'referrals': None, 'type': 'searchResDone'}
[]
````

i.e. it will not find anything. This behaviour persists regardless of the filter and search base I use. I can connect to the AD server using Sysinternals AD Explorer and I can also run the same query (with exactly the same parameters) with Python 2 and LDAP package installed from Gohlke's wheels (https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyldap) and it works fine. I have tried various authentication methods, SSL, TLS, various search filters and so on and the results are always the same -- there are none.

Please advise -- what should I try? Is there some information I can provide?

**Comment by Elwetana** [comment]
When I use:
`r = conn.search(...)`
the results I want are in r[2]

**Comment by zorn96** [comment]
Hi @Elwetana ! Seems like you got your solution. To clarify for other readers:

there’s 2 key aspects to what’s returned after an operation - the result and the response.
The response is the actual data in the case of a search (it’s a list of entries), while the result is always a dictionary with information about whether we failed, error codes, what type of response we got, etc.

**Comment by Elwetana** [comment]
I understand that but the documentation led me to believe, that the list of entries will be available as `connection.entries`. This is not the case -- in my code, `conn.entries == []` and `conn.response == None`

**Comment by zorn96** [comment]
Ah i just noticed you’re using a SAFE_* strategy. Those return the values and don’t store them within the connection because if multiple threads use the same connection then storing entries within the connection isn’t threadsafe and you could accidentally get the response from another search.
