### ISSUE TITLE
Argument conversion with submitting cross domain search, following referrals 

### ISSUE THREAD

**Issue by w-p** [cannatag/ldap3#101]
Short version: When searching from a top level domain against a sub-domain, an __LDAPInvalidScopeError__ is thrown.  When printed to the console, the arguments are of different types than those expected by the value checks.

With an authenticated bind to:
`dc=mydomain,dc=tld`

I submit the following to the search function:
`search_base` 'cn=users,dc=subdomain,dc=mydomain,dc=tld'
`search_filter` '(objectclass=*)'
`search_scope` 'SUBTREE'
`size_limit` 500

I put pass the arguments for __search_operation()__ in __ldap3/operation/search.py__ to __print()__, prior to any value checks, and get the following output:
`search_base` 'cn=users,dc=subdomain,dc=mydomain,dc=tld'
`search_filter` '(objectclass=*)'
`search_scope` 2
`dereference_aliases` 3
`attributes` ['1.1']
`size_limit` 0
`time_limit` 0
`types_only` False
`schema` None

Sorry for all the bug reports.  Ready to test changes, please advise.

**Comment by w-p** [comment]
Here's the __hack__ I made to get it working.  Basically check for the ldap3 value OR the equivalent protocol value:
__ldap3/operation/search.py__
  __search_operation()__
>
    if search_scope == BASE or search_scope == 0:
        request['scope'] = Scope('baseObject')
    elif search_scope == LEVEL or search_scope == 1:
        request['scope'] = Scope('singleLevel')
    elif search_scope == SUBTREE or search_scope == 2:
        request['scope'] = Scope('wholeSubtree')
    else:
        raise LDAPInvalidScopeError('invalid scope type')
>
    if dereference_aliases == DEREF_NEVER or dereference_aliases == 0:
        request['derefAliases'] = DerefAliases('neverDerefAliases')
    elif dereference_aliases == DEREF_SEARCH or dereference_aliases == 1:
        request['derefAliases'] = DerefAliases('derefInSearching')
    elif dereference_aliases == DEREF_BASE or dereference_aliases == 2:
        request['derefAliases'] = DerefAliases('derefFindingBaseObj')
    elif dereference_aliases == DEREF_ALWAYS or dereference_aliases == 3:
        request['derefAliases'] = DerefAliases('derefAlways')
    else:
        raise LDAPInvalidDereferenceAliasesError('invalid dereference aliases type')

**Comment by cannatag** [comment]
Hi Will, this bug was introduced when I moved from numeric constants to meaninful string constant. Thanks for noting it. I will fix it in the next release.

Bye,
Giovanni

**Comment by cannatag** [comment]
Can you check in dev?

thanks a lot for your precious debugging on Windows!

**Comment by w-p** [comment]
I try to run my tests against Samba, OpenLDAP, and Active Directory all at the same time.  I've checked out _dev_ but I won't be able to really validate until a little later this weekend.

**Comment by cannatag** [comment]
Ho Will, thanks a lot for the time you're spending on debugging and testing the ldap3 library. Take the time you need for testing. In the meanwhile I'm working on a substitute for the pyasn1 package because its ber decoder is very slow.

Bye,
Giovanni



-------- Messaggio originale --------
Da:Will Palmer <notifications@github.com>
Inviato:Sat, 22 Aug 2015 12:53:22 +0200
A:cannatag/ldap3 <ldap3@noreply.github.com>
Cc:Giovanni Cannata <cannatag@gmail.com>
Oggetto:Re: [ldap3] Argument conversion with submitting cross domain search, following referrals  (#101)

**Comment by cannatag** [comment]
Fixed in 0.9.9
