### ISSUE TITLE
Pronblems with SSL/TLS connections

### ISSUE THREAD

**Issue by tschloesser** [cannatag/ldap3#1014]
Sorry to bother you, but I am quite new to Python development and I started to use the LDAP3 module to write some code helping me with my eDirectory related projects.

 I managed to write some code, which is working in PyCharm  (both in the run and the terminal view), but when I am executing the same code on an individual terminal on the same MacBook I am getting this LDAP error:

Traceback (most recent call last):
  File "/Users/tschloesser/PycharmProjects/pythonProject/ShowAssociation.py", line 85, in <module>
    conn.bind()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: ("('socket ssl wrapping error: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)',)",)

BTW: When I am changing the connection parameters to use standard LDAP via port 389 anything is working.

In my code I wanted to ignore any certificates, but this does not seam to work - and I do not understand, why I am not seeing any error running the code in PyCharm. 

Can anybody provide some hints, please?

Kind regards,

Thorsten

**Comment by zorn96** [comment]
addressed in https://github.com/cannatag/ldap3/issues/925 - this relates to python's underlying ssl changes not working in your environment due to use of older TLS versions

**Comment by tschloesser** [comment]
Dear Azaria,

thanks for your answer, but unfortunately this  answer does not help me really.

I understand OpenSSL delivered with Pythion 3.10 and later is not 100% compatible with the OpenSSL in  MacOS!

But is there any way to use my code with current versions of Python?  
The certificate send by my LDAP server is valit, prides all neeeded SAN, but is a self-singed certificate. I thougt the Tls(validate=ssl.CERT_NONE) would solve the latter, butrit seams it needs more parameters to work in my case.

Can you provide some more advice, please?

Sorry, as I wrote I am quite new with Python and I might not see something wich is crystal clkear to you ;-)


Kind regards

Thorsten

===========================
Thorsten Schlößer
***@***.***

**Comment by tschloesser** [comment]
Hi Azaria,

after debugging the connection from the server-site, I found the root of this issue was related to the ciphers used to establish the connection.

According the debug data from the server tehere was no common cipher fond during the handshake.


After adding the ciphers parameter to my Tls object, the connection could be esabished as planed.

The question is: „!Is this a bug or a feature of OpenSSL 1.1.1?“

Kind regards

Thorsten



===========================
Thorsten Schlößer
***@***.***

**Comment by zorn96** [comment]
deprecation of certain ciphers by default is intended in newer versions of OpenSSL.

as OpenSSL continues to release versions, they'll remove support by default for weaker algorithms/those with known vulnerabilities. I suggest you either pin your openssl configuration or start upgrading your server, as this might just mean you have security vulnerabilities.

but this library isn't really about openssl, so I can't really provide guidance there

**Comment by tschloesser** [comment]
Hi !

Ido understand that the issue is not related to the ldap3 library, but maybe it would make sense to add the fact, the ciphers parameter is mandatory to the documentation.

I know, that certain ciphers (and protocols) are discontinued in newer version because of security concerns, and I am 100% happy with that fact. But I know for sure in older versions of openssl there was a negotiation between the client and server which cipher to  use during the handshake - in this case the client used all ciphers available in its (system) configuration. The difference after „upgrading“ to OpenSSL 1.1.1l or 1.1.1m is, that the client is not negotiation on any cipher until spelled out in the code.

So in my case the issue was not the server, which provides any compatible cipher defined for openSSL 1.0.2, but the client. As soon as I provided any of the ciphers available on the server-side or simply used the parameter ciphers=‚ALL“ in my Tls object anything was working as expected.

This is really related to the OpenSSL library provided with newer versions of Python and not the ldap3 library, but I guess it would save a lot of „beginners“ a lot of time, if the ldap3 documentation would add this fact to the documentation

Kind regards

Thorsten 

===========================
Thorsten Schlößer
***@***.***

**Comment by zorn96** [comment]
hi @tschloesser - the `ciphers` parameter is not necessary.
it might be necessary in your environment because of how your system has ssl configured, but it is not necessary in all environments. I've used ldap3 with TLS on python 3.10 in my personal lab environment without needing to specify ciphers.

the fact that beginners might read it is, in my opinion, a reason specifically to avoid any such misleading documentation. If we say "oh just throw in `ciphers=ALL` if TLS isn't working" then people will do that without understanding what it means or its implications, and that will make their setup susceptible to things like TLS downgrade attacks.

if someone's security configuration is running into issues, they should learn about them in order to fix them - not turn off security controls. being new to python doesn't mean you should follow bad security practices, so it's my personal opinion that libraries shouldn't encourage such practices.

**Comment by tschloesser** [comment]
Hi Azaria,

I totally agree, zthat it is a bad option to forget about security, but I still belive something is wrong how Python 3.10 is using openssl.

I did run another test from an SLES 15 server using OpenSSL 1.1.1d to check the check the connection and  I found the handshake succeeds at the end without specidfing any ciphers onth eclient side.

Running openssl s_client -connect server:port provides the following gata:

New, TLSv1.2, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated   


For my opinion AES256-GCM-SHA384 is a quite strong cipher, is it not?

So I would suspect I would not need to specyfy any cipher in the Python cond on the cilent side as well. 

Maybe there the OPenSSL installed with Python 3.10.x is not 100% installed corectly?

Kind regards

Thorsten


===========================
Thorsten Schlößer
***@***.***
