### ISSUE TITLE
_get_schema_info: search complains about objectClasses

### ISSUE THREAD

**Issue by larsesser** [cannatag/ldap3#1017]
During setup of the connection, the schema info is queried from the ldap server inside `_get_schema_info` in `core/server.py`. In [line 475](https://github.com/cannatag/ldap3/blob/040e09fe37cf06801960d494dfadf0a6ed94e38f/ldap3/core/server.py#L475) the server's `subschema` entry is searched for some attributes f.e. `objectClasses`.

Inside the `search` method in `core/connection.py`, this raises the `LDAPAttributeError: invalid attribute type objectClasses` in [line 836](https://github.com/cannatag/ldap3/blob/040e09fe37cf06801960d494dfadf0a6ed94e38f/ldap3/core/connection.py#L836). This may also be true for some of the other attributes explicitly searched in the first place.

Full stacktrace:
```
File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 531, in __enter__
    self.open()
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 59, in open
    self.connection.refresh_server_info()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 1421, in refresh_server_info
    self.server.get_info_from_server(self)
  File "/usr/lib/python3/dist-packages/ldap3/core/server.py", line 525, in get_info_from_server
    self._get_schema_info(connection)
  File "/usr/lib/python3/dist-packages/ldap3/core/server.py", line 475, in _get_schema_info
    result = connection.search(schema_entry,
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 829, in search
    raise LDAPAttributeError(self.last_error)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type objectClasses
```

**Comment by larsesser** [comment]
This is also true for `attributeTypes`, `createTimestamp` and `modifyTimestamp`.

**Comment by septatrix** [comment]
I think the problem is rather that you do not provide these as part of your servers schema. DS 389 for example has these as part of their core, mandatory schema: https://github.com/389ds/389-ds-base/blob/389-ds-base-2.4.4/ldap/schema/00core.ldif#L156, for OpenLDAP/slapd it is directly embedded into the C code instead of being part of the distributed schema files: https://github.com/openldap/openldap/blob/OPENLDAP_REL_ENG_2_6_6/servers/slapd/schema_prep.c#L781

**Comment by BastelBaus** [comment]
Finally, I found a quick&dirty fix for me which worked. 
Go inside the container, edit ldap3 config file:
vi /venv/lib/python3.12/site-packages/ldap3/utils/config.py
Line 33ff add to _ATTRIBUTES_EXCLUDED_FROM_CHECK both attributes 'modifyTimestamp', 'createTimestamp'.
Solution is of course not persistant and not a good one. But at least it worked for me ....
BR, BastelBaus
