### ISSUE TITLE
ad_modify_password raises ldap3.core.exceptions.LDAPConstraintViolationResult: LDAPConstraintViolationResult - 19 - constraintViolation - None - 0000052D: 

### ISSUE THREAD

**Issue by muratbedir** [cannatag/ldap3#1027]
I try to change AD user with

if len(conn.entries) == 1:
USER_DN = conn.response[0].get("dn")
enc_pwd = '{}'.format('bmB_943!*3QYY69r').encode('utf-16-le')
enc_pwd_current ='{}'.format('Ankara06').encode('utf-16-le')

r= ldap3.extend.microsoft.modifyPassword.ad_modify_password(conn, USER_DN, enc_pwd, enc_pwd_current,  controls=None)
but I face

ldap3.core.exceptions.LDAPConstraintViolationResult: LDAPConstraintViolationResult - 19 - constraintViolation - None - 0000052D: AtrErr: DSID-0319103B, https://github.com/cannatag/ldap3/pull/1:
0: 0000052D: DSID-0319103B, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)

modifyResponse - None
error, I try a lot of thing but I can not solve the problem;

Can someone please write a sample working code to use ldap3.extend.microsoft.modifyPassword.ad_modify_password function will it's appreciated

Regards.

**Comment by zorn96** [comment]
@muratbedir if you're using the ad_modify_password function, you shouldn't do the utf-16 encoding yourself I believe. the function should do that for you. may just be failing due to the current password aspect not matching

**Comment by muratbedir** [comment]
Minimal ad password change code below, I solved problem root cause of the problem 
![image](https://user-images.githubusercontent.com/48950062/159693318-179a27e9-46ff-4a41-a8fe-0fc1451ef367.png)

Min password age of the AD has been set 7 days so  I  try to change password prior to 7 days I got error. 

When I try with another account I successfully changed the password. Also there is no need to encode unicode  as mentioned upper response, function handles conversion automatically. 



import ldap3

BASEDN ="OU=Users,OU=Accounts,DC=xxx,DC=net,DC=tr"
server = ldap3.Server('domainname.net.tr', use_ssl=True, get_info='ALL')
conn =  ldap3.Connection(server, user='domain\\prvuser', password='xxxxxx', authentication=ldap3.NTLM,raise_exceptions=True)


Path_Root = BASEDN
Filter = "(&(objectclass=user)(&(sAMAccountName=username_must_be_changed)(!(objectclass=computer))))"
conn.search(search_base = Path_Root,
         search_filter = Filter,
         search_scope = ldap3.SUBTREE,
         attributes = ["cn", "sAMAccountName", "displayName"]
         )
if len(conn.entries) == 1:
    USER_DN = conn.response[0].get("dn")
    
    ru=ldap3.extend.microsoft.unlockAccount.ad_unlock_account(conn,USER_DN) # for unlock account 

    try:  # password change section. 
        r= ldap3.extend.microsoft.modifyPassword.ad_modify_password(conn, USER_DN, 'new password','old password',   controls=None)
    except Exception as e:
        print (e)
