### ISSUE TITLE
Python 3.10 with ldap3.NTLM - unsupported hash type MD4

### ISSUE THREAD

**Issue by Barsovski** [cannatag/ldap3#1038]
**Ubuntu 22.04 / Python 3.10.4 / ldap3==2.9 with authentication=ldap3.NTLM**

Exception:
Error: unsupported hash type MD4

**Comment by exploide** [comment]
See #1051 for an explanation and a possible workaround (manually installing `pycryptodome`).

**Comment by md5tack** [comment]
pip3 install pycryptodome --break-system-packages

**Comment by Wangwang2021** [comment]
> pip3 install pycryptodome --break-system-packages

successfully solved the problem
