### ISSUE TITLE
Do we have to explicitly bind to port 0?

### ISSUE THREAD

**Issue by stphnlyd** [cannatag/ldap3#1041]
I see from the source that ldap3 by default explicitly binds to port 0. 

https://github.com/cannatag/ldap3/blob/78c449dded29dad54e4e68055f7290ad8689fbd1/ldap3/core/connection.py#L304
https://github.com/cannatag/ldap3/blob/78c449dded29dad54e4e68055f7290ad8689fbd1/ldap3/strategy/base.py#L219

At my workplace we have a special environmnt where binding to port local 0 is kind of restricted. So I wonder if ldap3 can change the default to not binding to port 0 if user does not specify any source_port or source_port_list. I know in an ideal work it does no harm to bind a client to local port 0, but that's not a very common practice right?

**Comment by zorn96** [comment]
@stphnlyd binding to port 0 in python sockets just means "let the system routing decide what port to use dynamically"
`ldap3` already supports an option for specifying the source port if you have restrictions. but if the OS will handle those restrictions, the default should work
