### ISSUE TITLE
Active Directory connection - use current machine's connection?

### ISSUE THREAD

**Issue by robertlagrant** [cannatag/ldap3#108]
Is there a way to connect to the AD that the current machine is connected to, without supplying connection parameters?

**Comment by cannatag** [comment]
Hello Robert, 
I think you could use Kerberos, but I'm not an expert with Active Directory. Have a look at http://ldap3.readthedocs.org/en/latest/bind.html and let me know if this helps you.

Bye,
Giovanni

**Comment by nathanclayton** [comment]
I'm not on a domain-joined system, but to get the current domain server (which you can then inquiry using standard LDAP) you should be able to do:

```python
import os

print os.environ.get( "LOGONSERVER" )
```

**Comment by robertlagrant** [comment]
I'm also not on a domain-joined system any more; I should be able to test that in a few weeks when I'm back on, if someone doesn't get there first!

**Comment by w-p** [comment]
So, here's how I get the list of domain controllers from a given domain based the existence of ldap SRV records in DNS.  From this, you can build a server pool by simply providing a single domain rather than a list of servers.  Note that this has not been heavily tested...

@cannatag
Giovanni, is this worth integrating into __ldap3.core.pooling.ServerPool__ such that it could be instantiated with just a domain name?

```
import logging
from dns import resolver
from socket import getfqdn
from importlib import reload

logger = logging.getLogger(__name__)

def get_srv_records(service, protocol='TCP', domain=None):
    reload(resolver)
    local_domain = '.'.join(
        getfqdn().split('.')[1:]
    )
    query = '_{}._{}.{}'.format(
        service,
        protocol,
        domain or local_domain
    )
    records = []

    try:
        answers = resolver.query(query, 'SRV')
    except Exception as e:
        logger.exception('Query for {} failed.'.format(query))
        return records

    for record in answers:
        records.append({
            'host': record.target.to_text().rstrip('.'),
            'port': record.port,
            'priority': record.priority,
            'weight': record.weight
        })
    return records
```

So you just call the function and get back a list of domain controllers, hopefully suitable for a bind. You can specify the domain name or not.  If you don't, it attempts to get the domain configured on your machine via `socket.getfqdn()`.
```
>>> get_srv_records('ldap', domain='mydomain.com')
>>> [{'host': 'dc2.mydomain.com', 'weight': 100, 'priority': 0, 'port': 389}, {'host': 'dc2.mydomain.com', 'weight': 100, 'priority': 0, 'port': 389}]
```

**Comment by cannatag** [comment]
This is something peculiar to AD. I think it can be included but not as the default behavior of the ServerPool.

Will work on this.

Bye,
Giovanni

**Comment by w-p** [comment]
This makes the assumption that:
1. DNS is configured for the target domain
2. DNS holds ldap SRV records for the target domain

This works with Samba and Active Directory but I haven't tested it against any other servers / configurations yet.

**Comment by nathanclayton** [comment]
This is very true with AD and Samba - DNS is an integral part of all AD deployments, and may not hold true for traditional LDAP deployments using software such as OpenLDAP, ApacheDS, OpenDJ, 389, etc. which don't integrate with DNS out of the box (although it is advisable, as it makes it easier for 3rd party software to find a particular domain's authentication server).

One other thing to remember for AD is that the LDAP service is typically only advertised on port 389 for that domain, but you have to connect to port 3268 (3269 for SSL) if you want to query against the GC (all domains in a forest).

**Comment by jootuom** [comment]
Guys... If your AD is properly set up with DNS, as it most likely is, all you need to connect to Domain Controllers is to use "ad.example.com" as the DNS name (if your domain is "ad.example.com", of course). It will connect to a random Domain Controller.

This is because Domain Controllers add A records pointing to themselves onto the root of the AD DNS zone.

If you want even more "magic", you can use the "userdnsdomain" environment variable to get the current full domain name.

Automagic authentication is another matter, Kerberos would help there probably.

**Comment by cannatag** [comment]
Thanks Jonas,
I will include your info in the docs.

Bye,
Giovanni

**Comment by dinhngtu** [comment]
If you want the official way to find domain controllers on Windows, there is [DsGetDcName](https://msdn.microsoft.com/en-us/library/ms675983.aspx).

I would be very interested in Kerberos support for ldap3 on Windows.

**Comment by gnomic** [comment]
So my first experience with ldap3 isn't going as planned. I cannot figure out why this isn't working...

Code example from http://ldap3.readthedocs.io/abstraction.html
```
s = Server('server')
c = Connection(s, user = 'username', password = 'password')
query = 'Department: Accounting'  # explained in next paragraph
person_reader = Reader(c, person, 'o=test', query)
person_reader.search()
```
That seems simple enough. But my code, which works fine for the Server and Connection calls, blow chunks in the Reader call. Here's the code snippet:

```
query = 'department: Security Risk'  
person_reader = Reader(c, person, 'OU=All Businesses', query)
```
and the fugly result
```
```
AttributeError                            Traceback (most recent call last)
<ipython-input-37-d611d731109d> in <module>()
      1 query = 'department: Security Risk'
----> 2 person_reader = Reader(c, person, 'OU=All Businesses', query)

C:\Users\########\AppData\Local\Continuum\Anaconda3\lib\site-packages\ldap3\abstract\reader.py in __init__(self, connection, object_def, query, base, components_in_and, sub_tree, get_operational_attributes, controls)
     79         self.base = base
     80         self._components_in_and = components_in_and
---> 81         self.attributes = sorted([attr.name for attr in self._definition])
     82         self.get_operational_attributes = get_operational_attributes
     83         self.controls = controls

C:\Users\##########\AppData\Local\Continuum\Anaconda3\lib\site-packages\ldap3\abstract\reader.py in <listcomp>(.0)
     79         self.base = base
     80         self._components_in_and = components_in_and
---> 81         self.attributes = sorted([attr.name for attr in self._definition])
     82         self.get_operational_attributes = get_operational_attributes
     83         self.controls = controls

AttributeError: 'str' object has no attribute 'name'
```
Per conda list:
`
ldap3                     1.0.4                    py35_0`

What am I missing here?

**Comment by cannatag** [comment]
First of all you should upgrade ldap3 to its last version 2.1.1. The docs are intended for that version. Then if this is your first experience with LDAP your should try the tutorials on ldap3.readthedocs.io/tutorial.html and the  decide if you want to access your data directly with the Ldap operations or using the abstraction layer that hides all the Ldap machinery, but it's harder to debug. 

What is your intended use?

**Comment by cannatag** [comment]
This is very old. If still needed please reopen with the current v 2.2.x version of ldap3.
