### ISSUE TITLE
uidNumber empty

### ISSUE THREAD

**Issue by matzmz** [cannatag/ldap3#1084]
I'm using ldap3 library to extract information from an active directory.
I've already used it to extract uidNumber and gidNumber attributes. Currently, I'm getting empty results when I search it.

I'm using the 2.9.1 release running the following snippet:

```
connection.search(
    search_base=DC_QUERY,
    search_filter=f'(distinguishedName=###PRIVATE###,
    search_scope=SUBTREE, 
    attributes=['uidNumber','gidNumber','displayName']
)

print(connection.entries[0].entry_to_json())
```

I got the following result.

```
{
    "attributes": {
        "displayName": [
            "###PRIVATE###"
        ],
        "gidNumber": [],
        "uidNumber": []
    },
    "dn": "###PRIVATE###"
}
```
If I browse the same entry using the "Active Directory Explorer" application, I see the uidNumber and gidNumber values.
Also using ldapsearch I see the field values of: uidNumber and gidNumber.
I have no idea why I got this behavior. Could you please help me?

**Comment by cannatag** [comment]
Hi, are you sure that the account you’re using  has the rights for reading those attributes?Il giorno 25 mar 2023, alle ore 19:05, matzmz ***@***.***> ha scritto:﻿
I'm using ldap3 library to extract information from an active directory.
I've already used it to extract uidNumber and gidNumber attributes. Currently, I'm getting empty results when I search it.
I'm using the 2.9.1 release running the following snippet:
connection.search(
    search_base=DC_QUERY,
    search_filter=f'(distinguishedName=###PRIVATE###,
    search_scope=SUBTREE, 
    attributes=['uidNumber','gidNumber','displayName']
)

print(connection.entries[0].entry_to_json())

I got the following result.
{
    "attributes": {
        "displayName": [
            "###PRIVATE###"
        ],
        "gidNumber": [],
        "uidNumber": []
    },
    "dn": "###PRIVATE###"
}

If I browse the same entry using the "Active Directory Explorer" application, I see the uidNumber and gidNumber values.
I have no idea why I got this behavior. Could you please help me?

**Comment by matzmz** [comment]
Yes, I'm using the same user in both applications, "AD Explorer" and "ldapsearch" and also from ldap3 library.
I also tried using another python library (python-ldap), and I got the same result (empty: gidNumber & uidNumber).

I don't know the internal aspects of LDAP (I just want to extract some information). 

The entry that I'm browsing has the following objectClasses: top;person;organizationalPerson;user

**Comment by matzmz** [comment]
I finally found the issue, but I don't know why it's happening.

I contacted AD, specifying port: 3269. If I use the standard port, it works.

Doing some search, I found the following statements: <<LDAP over port 3269 is actually querying LDAP using Global Catalog using SSL>>

Thanks for your help; sorry for bugging you. Ciao
