### ISSUE TITLE
How to set the filter_string argument for the SEARCH operation?

### ISSUE THREAD

**Issue by kfkhalili** [cannatag/ldap3#110]
Hello ldap3 team,

I'm trying to use your library to authenticate with an LDAP server. I'm not sure I'm performing the search operation correctly and would really appreciate it if you guys could help with the expected syntax (RFC4515 compliant) of the `search_filter` argument. I've opened a [question](http://stackoverflow.com/questions/32695696/ldap3-operation-search-seems-to-fail-search-filter-syntax-vs-rfc4515) on stackoverflow and would really appreciate it if you guys could help.

Please find the link below:

Thank you.

Regards,
Khalid F. Al Khalili

**Comment by cannatag** [comment]
Hi, pls check the answer on stackoverflow and let me know if it works for you.

Bye,
Giovanni

-------- Messaggio originale --------
Da:Khalid F Al Khalili <notifications@github.com>
Inviato:Mon, 21 Sep 2015 17:04:56 +0200
A:cannatag/ldap3 <ldap3@noreply.github.com>
Oggetto:[ldap3] How to set the filter_string argument for the SEARCH operation? (#110)

**Comment by kfkhalili** [comment]
Hi Giovanni,

I found the answer to my problem. I posted the answer on the stackoverflow post.
Thanks for your help!

Regards,
Khalid F. Al Khalili
