### ISSUE TITLE
nTsecurityDescriptor

### ISSUE THREAD

**Issue by C3ald** [cannatag/ldap3#1124]
How do I read the ntsecuritydescriptor? It keeps getting returned as bytes and I can't find a way to decode it.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,

ldap3 does not support parsing out of the box afaik, In [my project](https://github.com/the-useless-one/pywerview/blob/master/pywerview/functions/net.py#L81-L83) I use [impacket](https://github.com/fortra/impacket)'s implementation to parse the `ntsecuritydescriptor`.

:sunflower:

**Comment by zorn96** [comment]
hi @C3ald - the ms_active_directory library contains utilities for parsing and manipulating security desriptors
https://github.com/zorn96/ms_active_directory
it has utilities for adding/removing permissions, and updating the descriptors in AD
