### ISSUE TITLE
Exhaustive server pool is too exhaustive

### ISSUE THREAD

**Issue by nickw444** [cannatag/ldap3#113]
When using a server pool with `active=True` and `exhaust=True`, if an LDAP server goes offline, it is never able to be used again. In a case where there may only be 2 servers in the pool, this is really detrimental to a stateful app, and requires the app to be restarted in order to re-negotiate connections to these LDAP servers. 

To try combat this, I have attempted to use `exhaust=False`. With the server offline, I attempt to make an LDAP connection, however the pool ends up in a loop attempting to find an active server. The loop never breaks when the server comes back online, and leads to an endless loop of polling.

**Comment by cannatag** [comment]
HI Nick,
you're right. My original idea when developing the ServerPool object was quite simple: a list of server to contact when opeing the connection. Then I added the ``active`` parameter to check connectivity to each server and the ``exhaust`` to remove not-active servers from the list. Actually this leads to an endless cycle if the exhaust parameter is False and to an empty list if it's True. A solution could be to change the exhaust parameter to the number of seconds to keep the unresponsive server out the ServerPool list and add a new parameter for the max number ot cycles to repeat before reaising the LDAPServerPoolExhaustedError exception.

What do you think?

Bye,
Giovanni

**Comment by nickw444** [comment]
Hi Giovanni,

That sounds like a fantastic solution! That will solve all of the problems I've been having. (I maintain [flask-ldap3-login](https://github.com/nickw444/flask-ldap3-login))

Cheers.

**Comment by cannatag** [comment]
HI, can you try the code in dev? 
Now when defining a ServerPool you can set active to the number of cycles the pool tries before giving up, and exhaust to the number of sencods

**Comment by nickw444** [comment]
It's working perfectly. Thanks for the fix!

**Comment by cannatag** [comment]
Good. I will include the fix in the next release of ldap3.

Bye,
Giovanni
