### ISSUE TITLE
I can not get SASL/EXTERNAL working

### ISSUE THREAD

**Issue by croessner** [cannatag/ldap3#114]
These are my first steps to ldap3. I have an OpenLDAP server that accepts StartTLS on port 389.

 want to use SSL-certs to authz-to to a special user. This all works perfectly with python-ldap in python2.7. Now that I try to port some software to python3.4, I wanted to use ldap3.

Here is what I tried so far:

-------------------------------------------------------------------------------------------------------------------
#!/usr/bin/python3

import ssl

from ldap3 import Server, Connection, Tls, AUTH_SASL, SUBTREE

tls_configuration = Tls(local_private_key_file='/etc/ssl/private/mx.roessner-net.de.key',
                        local_certificate_file='/etc/ssl/certs/mx.roessner-net.de.crt',
                        ca_certs_file='/etc/ssl/certs/ca-certificates.crt',
                        validate=ssl.CERT_REQUIRED,
                        version=ssl.PROTOCOL_TLSv1)

server = Server('db.roessner-net.de',
                tls=tls_configuration)

conn = Connection(server,
                  authentication=AUTH_SASL,
                  sasl_mechanism='EXTERNAL',
                  sasl_credentials=())

conn.open()
conn.start_tls()

bind = conn.do_sasl_bind(controls=None)
print("bind: %s" % str(bind))

i_am = conn.extend.standard.who_am_i()
print(i_am)

conn.search(search_base='ou=people,ou=it,dc=roessner-net,dc=de',
            search_filter='(objectclass=*)',
            attributes=['cn'],
            search_scope=SUBTREE)

print(conn)
print(conn.entries)
-------------------------------------------------------------------------------------------------------------------

Trying to use this, I receive an error:

bind: {'type': 'bindResponse', 'dn': '', 'saslCreds': b'', 'referrals': None, 'message': 'SASL(0): successful result: ', 'description': 'saslBindInProgress', 'result': 14}
Traceback (most recent call last):
  File "./ldap-test.py", line 27, in <module>
    i_am = conn.extend.standard.who_am_i()
  File "/usr/lib64/python3.4/site-packages/ldap3/extend/__init__.py", line 53, in who_am_i
    return WhoAmI(self._connection).send()
  File "/usr/lib64/python3.4/site-packages/ldap3/extend/operation.py", line 57, in send
    self.decode_response()
  File "/usr/lib64/python3.4/site-packages/ldap3/extend/operation.py", line 69, in decode_response
    raise LDAPExtensionError('extended operation error: ' + self.result['description'] + ' - ' + self.result['message'])
ldap3.core.exceptions.LDAPExtensionError: extended operation error: operationsError - SASL bind in progress

I spent hours now, but I do not get it to work. I have no idea, if I did something wrong or if I just encountered a bug. So I ask you, if you can give me a hint.

I want ldap3 for automx, which you also find as an OSS here on Github ;-)

**Comment by cannatag** [comment]
Hi Christian, please try with conn.bind() instead of conn.do_sasl_bind(). Let me know what the result is.
Also, are you sure you want to use the EXTERNAL SASL mechanism?

Bye,
Giovanni

**Comment by croessner** [comment]
I tried this before :-) Here is the result:

bind: False
Traceback (most recent call last):
  File "./ldap-test.py", line 28, in <module>
    i_am = conn.extend.standard.who_am_i()
  File "/usr/lib64/python3.4/site-packages/ldap3/extend/__init__.py", line 53, in who_am_i
    return WhoAmI(self._connection).send()
  File "/usr/lib64/python3.4/site-packages/ldap3/extend/operation.py", line 57, in send
    self.decode_response()
  File "/usr/lib64/python3.4/site-packages/ldap3/extend/operation.py", line 69, in decode_response
    raise LDAPExtensionError('extended operation error: ' + self.result['description'] + ' - ' + self.result['message'])
ldap3.core.exceptions.LDAPExtensionError: extended operation error: operationsError - SASL bind in progress

bind() seems not to bind.

And yes, I want SASL/EXTERNAL. Here is the authz-to from openldap that works perfectly over 8 servers:

authz-policy    to

authz-regexp
        cn=mx\.roessner-net\.de,ou=Mail,o=R.N.S.,l=Alsfeld,st=Hessen,dc=roessner-net,dc=de,c=DE$
        cn=mail,ou=people,ou=it,dc=roessner-net,dc=de

And the object cn=mail:

dn: cn=mail,ou=people,ou=it,dc=roessner-net,dc=de
objectClass: simpleSecurityObject
objectClass: organizationalRole
structuralObjectClass: organizationalRole
cn: mail
description: LDAP administrator for the mail system (read-only)
userPassword:: *****
authzTo: {0}dn.regex:uid=.*,ou=([^,].+),ou=people,ou=it,dc=roessner-net,dc=de

This user can switch to different other users like this:

authz-regexp
        uid=([^,]+),(cn=[^,]+,)?cn=[^,]+,cn=auth
        ldap:///ou=people,ou=it,dc=roessner-net,dc=de??sub?(&(objectclass=rnsMSPostfixAccount)(|(rnsMSRecipientAddress=$1)(uniqueIdentifier=$1)))

You see, I want SASL/EXTERNAL :-)

**Comment by cannatag** [comment]
Hi,
this is the SASL EXTERNAL test that is working for me:

```
    def test_sasl_with_external_certificate(self):
        tls = Tls(local_private_key_file=test_user_key_file, local_certificate_file=test_user_cert_file, validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1, ca_certs_file=test_ca_cert_file, valid_names=[ '192.168.137.101'])
        server = Server(host=test_server, port=test_port_ssl, use_ssl=True, tls=tls)
        connection = Connection(server, auto_bind=False, authentication=SASL, sasl_mechanism='EXTERNAL')
        connection.open()
        connection.bind()
        print connection.result
        self.assertTrue(connection.bound)
        connection.unbind()
        self.assertFalse(connection.bound)
```

Can you try this code, with the proper variable values for your environment?

Thanks,
Giovanni

**Comment by croessner** [comment]
I had to modify your code a little bit, to get a result:

mport ssl

from ldap3 import Server, Connection, Tls, SASL, SUBTREE

    def test_sasl_with_external_certificate():
        tls = Tls(local_private_key_file="/etc/ssl/private/mx.roessner-net.de.key",
                  local_certificate_file="/etc/ssl/certs/mx.roessner-net.de.crt",
                  validate=ssl.CERT_REQUIRED,
                  version=ssl.PROTOCOL_TLSv1,
                  ca_certs_file="/etc/ssl/certs/ca-certificates.crt")

        server = Server(host="db.roessner-net.de", port=389, use_ssl=False, tls=tls)

        connection = Connection(server, auto_bind=False, authentication=SASL, sasl_mechanism='EXTERNAL')
        connection.open()
        connection.start_tls()
        connection.bind()

        print(connection.result)
        assert connection.bound == True
        connection.unbind()
        assert connection.bound == True


The result is:

{'type': 'bindResponse', 'dn': '', 'message': 'SASL(0): successful result: ', 'referrals': None, 'saslCreds': b'', 'result': 14, 'description': 'saslBindInProgress'}
Traceback (most recent call last):
  File "./ldap-test.py", line 28, in <module>
    test_sasl_with_external_certificate()
  File "./ldap-test.py", line 23, in test_sasl_with_external_certificate
    assert connection.bound == True
AssertionError

If I use use_tls=True, it fails to connect:

Traceback (most recent call last):
  File "./ldap-test.py", line 27, in <module>
    test_sasl_with_external_certificate()
  File "./ldap-test.py", line 18, in test_sasl_with_external_certificate
    connection.open()
  File "/usr/lib64/python3.4/site-packages/ldap3/strategy/sync.py", line 55, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib64/python3.4/site-packages/ldap3/strategy/base.py", line 132, in open
    raise exception_history[0][1](exception_history[0][2])
ldap3.core.exceptions.LDAPSocketOpenError: (LDAPSocketOpenError('socket ssl wrapping error: EOF occurred in violation of protocol (_ssl.c:598)',),)

**Comment by cannatag** [comment]
HI,
it seems that your server doesn't accept the certificate. 
Also, if you want to use the ``use_ssl=True`` parameter you must also set the port to 636 (the default for ldap over tls).
 
I see I can reach your server for testing. Would it be possible for you to send me the certificate files to troubleshoot this problem? 

Thanks,
Giovanni

**Comment by croessner** [comment]
Yes. I can give you the cert and key by email. Would be nice if you have s/mine or pgp 😊 c@roessner.co 

If you give me a mail address, I can send you stuff

It's also possible to send you pyldap code and configuration that already works with SASL/EXTRRNAL

**Comment by cannatag** [comment]
my address is cannatag@gmail.com. I'm sorry I haven't s/mine or pgp. If you don't feel secure just let me have a look at the pyldap code. then if I need I will set up a secure mailbox  and ask you for the certificates.

**Comment by cannatag** [comment]
Or if you prefer I can give you access to a server in my test lab and we can perform the test together.

Bye,
Giovanni

**Comment by cannatag** [comment]
Hi, I think I found the problem. OpenLDAP expects an empty sasl credentials while binding. IMO this is not correct because in RFC 4511 the sasl_credentials is defined as Optional. (so an empty payload don't need to be sent). Anyway if you set the sasl_credentials='' in the Connection definition and change line 58 from:

```
if sasl_credentials:
```

to 
```
if sasl_credentials is not None:
```
in the /usr/lib/python3.4/site-packages/ldap3/operation/bind.py (or wherever your python site-packages is located).

I will include the fix in the next release of ldap3.

You can check the ldap3-test.py script in the /home/croessner/bin on labldap09.

Let me know if this works for you.

Bye,
Giovanni

**Comment by croessner** [comment]
I tried it and it works!! :-) Thank you very much for fixing this bug

**Comment by cannatag** [comment]
Do you still need the account on labldap09?

**Comment by croessner** [comment]
No thanks. Fixing it was great. 😊
