### ISSUE TITLE
referrals to trusting domains

### ISSUE THREAD

**Issue by cornelinux** [cannatag/ldap3#120]
I have two active directory domains trusted.com and trusting.com
There is a one way trust: trusting.com is trusting the users from trusted.com
Thus the administrator@trusted.com can view and manage the users in trusting.com.

I am running such a script, to perform a search for users in the trusting domain:

    LDAPURI = "ldap://domain2.trusted.com"
    LDAPBASE = "cn=users,dc=trusting,dc=com"
    BINDDN = "cn=administrator,cn=users,dc=trusted,dc=com"
    BINDPW = "password"
    
    import ldap3
    FILTER = "(sAMAccountName=*)"
    ATTRIBUTES = ["sAMAccountName"]
   
    server = ldap3.Server(LDAPURI, port=389, use_ssl=False, connect_timeout=5)
    l = ldap3.Connection(server,
                     user=BINDDN,
                     password=BINDPW,
                     auto_bind=True,
                     auto_referrals=True,
                     authentication=ldap3.SIMPLE,
                     raise_exceptions=True)
    l.open()
    if not l.bind():
        raise Exception("Wrong credentials")

    l.search(search_base=LDAPBASE,
         search_scope=ldap3.SUBTREE,
         search_filter=FILTER,
         attributes=ATTRIBUTES)

    r = l.response
    for entry in r:
        print entry.get("dn")
    print("%s entries found." % len(r))
    l.unbind()

I get 0 entries. Doing a tcpdump on the ldap port, just shows me, that a referral is returned::

    0?...`:....+cn=administrator,cn=users,dc=trusted,dc=com..password0........a.....
    ......0S...cN..cn=users,dc=trusting,dc=com
    ..
    .............sAMAccountName0...sAMAccountName0........e.....
    .
    ...Q0000202B: RefErr: DSID-0310082F, data 0, 1 access points
    .ref 1: 'trusting.com'
    ......1./ldap://trusting.com/cn=users,dc=trusting,dc=com0....B.

What is the recommended way to deal with referrals in such a case?

Thanks a lot

**Comment by w-p** [comment]
Try passing `allowed_referral_hosts=[('*', True)]` to `ldap3.Server()`.

**Comment by cornelinux** [comment]
Thanks a lot. This helps...
...a bit.
As the referrals of the Active Directory returns ldap://trusting.com (which is no host but a domain) I need to resolve the domain name to a host. After I have done so, I get:

    Traceback (most recent call last):
      File "ldap-test.py", line 30, in <module>
        attributes=ATTRIBUTES)
      File "/usr/lib/python2.7/dist-packages/ldap3/core/connection.py", line 563, in search
        response = self.post_send_search(self.send('searchRequest', request, controls))
      File "/usr/lib/python2.7/dist-packages/ldap3/strategy/sync.py", line 140, in post_send_search
        responses, result = self.get_response(message_id)
      File "/usr/lib/python2.7/dist-packages/ldap3/strategy/base.py", line 317, in get_response
        ref_response, ref_result = self.do_operation_on_referral(self._outstanding[message_id],     responses[-2]['referrals'])
      File "/usr/lib/python2.7/dist-packages/ldap3/strategy/base.py", line 584, in     do_operation_on_referral
        controls=request['controls'])
      File "/usr/lib/python2.7/dist-packages/ldap3/core/connection.py", line 560, in search
        request = search_operation(search_base, search_filter, search_scope, dereference_aliases,    attributes, size_limit, time_limit, types_only, self.server.schema if self.server else None)
      File "/usr/lib/python2.7/dist-packages/ldap3/operation/search.py", line 349, in search_operation
        raise LDAPInvalidScopeError('invalid scope type')
    ldap3.core.exceptions.LDAPInvalidScopeError: invalid scope type

The tcpdump tells me different. After receiving the referral from trusted.com, I can see an LDAP request to trusting.com:

    0?...`:....+cn=administrator,cn=users,dc=trusted,dc=com..password0....h...a...._
    .1...X80090308: LdapErr: DSID-0C0903C5, comment: AcceptSecurityContext error, data 52e,   v2580.

But with the credentials of adminstrator@trusted.com. Which fails.

**Comment by cornelinux** [comment]
Checking with wireshark within active directory when connecting to trusting.com from trusted.com, I can see that they are using SASL GSS API.

**Comment by w-p** [comment]
I don't remember exactly but I think that a simple bind on 389 won't be allowed across domains.  Have you attempted binding with NTLM or GSSAPI (even with something simple like MD5)?

**Comment by cornelinux** [comment]
NTLM does not work out and DIGEST-MD5 gives me this exception:

    Traceback (most recent call last):
      File "ldap-test.py", line 26, in <module>
        raise_exceptions=True)
      File "/usr/lib/python2.7/dist-packages/ldap3/core/connection.py", line 281, in __init__
        raise LDAPBindError(self.last_error)
    ldap3.core.exceptions.LDAPBindError: automatic bind not successful

Phew. Using SASL GSSAPI shows me, that I probably need to do an LDAP setup. And probably I have to add the linux machine which to the trusted.com domain. With GSSAPI I get this exception.

    Traceback (most recent call last):
      File "ldap-test.py", line 26, in <module>
        raise_exceptions=True)
      File "/usr/lib/python2.7/dist-packages/ldap3/core/connection.py", line 270, in __init__
        self.bind(read_server_info=True)
      File "/usr/lib/python2.7/dist-packages/ldap3/core/connection.py", line 424, in bind
        response = self.do_sasl_bind(controls)
      File "/usr/lib/python2.7/dist-packages/ldap3/core/connection.py", line 933, in do_sasl_bind
        result = sasl_gssapi(self, controls)
      File "/usr/lib/python2.7/dist-packages/ldap3/protocol/sasl/kerberos.py", line 50, in sasl_gssapi
        target_name = gssapi.Name('ldap@' + connection.server.host,     gssapi.NameType.hostbased_service)
    AttributeError: 'module' object has no attribute 'NameType'

But thanks a lot. That helped a lot.
So now I know my next steps...

**Comment by cannatag** [comment]
Hi Cornelius, the ldap3.core.exceptions.LDAPInvalidScopeError:exception should definitively not happens. Please can you try the same operation with the latest version 0.9.9.2 of ldap3? This has been fixed in 0.9.9.

Thanks,
Giovanni

**Comment by cornelinux** [comment]
Hi Giovanni,

with ldap3.SIMPLE I get:

    Traceback (most recent call last):
      File "ldap-test.py", line 35, in <module>
        attributes=ATTRIBUTES)
      File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 609, in search
        response = self.post_send_search(self.send('searchRequest', request, controls))
      File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/sync.py", line 141, in post_send_search
        responses, result = self.get_response(message_id)
      File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/base.py", line 299, in get_response
        responses = self._get_response(message_id)
      File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/sync.py", line 166, in _get_response
        ldap_resp = decode_message_fast(response)
      File "/usr/local/lib/python2.7/dist-packages/ldap3/utils/asn1.py", line 72, in decode_message_fast
        decoded = decode_sequence(message, ber_value_offset, ber_len + ber_value_offset,   LDAP_MESSAGE_CONTEXT)
      File "/usr/local/lib/python2.7/dist-packages/ldap3/utils/asn1.py", line 92, in decode_sequence
        value = ber_decoder(message, start, start + ber_len, context_decoders)  # call value decode function
      File "/usr/local/lib/python2.7/dist-packages/ldap3/utils/asn1.py", line 94, in decode_sequence
        value = context_decoders[ber_type](message, start, start + ber_len)  # call value decode function   for context class
    KeyError: 3

with ldap3.SASL, DIGEST-MD5 I get:
    
    ldap3.core.exceptions.LDAPBindError: automatic bind not successful

and with ldap3.SASL, GSSAPI I get:
    
        target_name = gssapi.Name('ldap@' + connection.server.host,     gssapi.NameType.hostbased_service)
    AttributeError: 'module' object has no attribute 'NameType'

So I think I have to bite the bullet and setup my kerberos....
thanks a lot 
Cornelius

**Comment by cannatag** [comment]
Ho, can you try with fast_decoder=False in the Connection object? 

Thanks a lot for your testing.

Giovanni

-------- Messaggio originale --------
Da:Cornelius Kölbel <notifications@github.com>
Inviato:Fri, 30 Oct 2015 08:11:44 +0100
A:cannatag/ldap3 <ldap3@noreply.github.com>
Cc:Giovanni Cannata <cannatag@gmail.com>
Oggetto:Re: [ldap3] referrals to trusting domains (#120)

**Comment by cornelinux** [comment]
With which 
    authentication=ldap3.SASL
should this work? 

Disclaimer: I assume my machine running ldap3 needs to be member of trusted.com. Which is not at the moment. And I assume that ldap.SIMPLE will not work.
So I guess I am lacking some prerequisites.
Thanks
COrnelius

**Comment by cannatag** [comment]
Please try with ldap3.SIMPLE because I'm interested in the error message you get with the fast encoder. You should not get an exception anyway because the response from the server should be a well formed ldap message. If the message is properly decoded you could find some more useful information on the connection.result attribute.

Giovanni

-------- Messaggio originale --------
Da:Cornelius Kölbel <notifications@github.com>
Inviato:Fri, 30 Oct 2015 11:24:50 +0100
A:cannatag/ldap3 <ldap3@noreply.github.com>
Cc:Giovanni Cannata <cannatag@gmail.com>
Oggetto:Re: [ldap3] referrals to trusting domains (#120)

**Comment by w-p** [comment]
FWIW regarding referrals and binding, your computer doesn't need to be a member of the domain.  Further, regarding authentication mechanisms:
For Kerberos: setup kerberos client and kinit the user before binding. `kinit user@DOMAIN.TLD`
For MD5: create reverse pointer records for the domain controllers.
For NTLM: username = `DOMAIN\user` rather than `user@domain.tld`.

Note that in the Microsoft world, if you're credentials were not sent/received in a secure fashion, you're capabilities will be limited.

**Comment by cornelinux** [comment]
@w-p: thanks for the wrap up

@cannatag 
Doing a ldap3.SIMPLE results in this output:

    Traceback (most recent call last):
      File "ldap-test.py", line 36, in <module>
        attributes=ATTRIBUTES)
      File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 609, in search
        response = self.post_send_search(self.send('searchRequest', request, controls))
      File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/sync.py", line 141, in post_send_search
        responses, result = self.get_response(message_id)
      File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/base.py", line 344, in get_response
        raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'],   message=result['message'], response_type=result['type'])
    ldap3.core.exceptions.LDAPOperationsErrorResult: LDAPOperationsErrorResult - 1 -  operationsError - None - 000004DC: LdapErr: DSID-0C090728, comment: In order to perform this    operation a successful bind must be completed on the connection., data 0, v2580 - searchResDone -    None

What happened is that the referral pointed to trusting.com.
then a SIMPLE bind with the user@trusted.com is performed to trusting.com (which will fail).
The search of course then will complain about the missing bind.

**Comment by cannatag** [comment]
Hi Cornelius, could you please send me your ldap-test.py file? I'm trying to replicate the error but I can't get the exceptions you have. 

Thanks.
Giovanni

**Comment by cornelinux** [comment]
Here it is:

    # change this
    LDAPURI = "ldap://domain2.trusted.com"
    #LDAPURI = "ldap://domain1.trusting.com"
    LDAPBASE = "cn=users,dc=trusting,dc=com"
    #LDAPBASE = "cn=users,dc=trusted,dc=com"
    BINDDN = "administrator@trusted.com"
    BINDPW = "password"

    import ldap3
    FILTER = "(sAMAccountName=*)"
    AT TRIBUTES = ["sAMAccountName"]

    server = ldap3.Server(LDAPURI, port=389, use_ssl=False, connect_timeout=5,
		allowed_referral_hosts=[('*', True)])
    sasl_credentials = (str(BINDDN), str(BINDPW))
    l = ldap3.Connection(server,
                   fast_decoder=False,
                     user=BINDDN,
                     password=BINDPW,
                    auto_bind=True,
                     auto_referrals=True,
                     authentication=ldap3.SIMPLE,
    #                     authentication=ldap3.SASL,
    #			sasl_mechanism="DIGEST-MD5",
    #		sasl_credentials=sasl_credentials,
                     raise_exceptions=True)
    l.open()
    if not l.bind():
        raise Exception("Wrong credentials")

    l.search(search_base=LDAPBASE,
    	 search_scope=ldap3.SUBTREE,
         search_filter=FILTER,
         attributes=ATTRIBUTES)

    r = l.response
    for entry in r:
        print entry.get("dn")
    print("%s entries found." % len(r))
    l.unbind()

**Comment by cannatag** [comment]
Hi Cornelius, 
the problem with the fast decoder (KeyError 3) is fixed in dev. Can you check it?

Thanks,
Giovanni

**Comment by cornelinux** [comment]
Hi Giovanni,

thx a lot! I will do so. 
Please give me some(TM) time.

Kind regards
Cornelius

**Comment by cannatag** [comment]
some minor refinment to uri processing sre in 1.0.2.

**Comment by cornelinux** [comment]
Hi Givanni,

I finally have found my test machines ;-)
I updated to ldap 1.0.2 in a virtualenv. But now I get this result:

<pre>
Successful bind!
Traceback (most recent call last):
  File "ldap-test.py", line 38, in <module>
    attributes=ATTRIBUTES)
  File "/root/test/local/lib/python2.7/site-packages/ldap3/core/connection.py", line 614, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/root/test/local/lib/python2.7/site-packages/ldap3/strategy/sync.py", line 142, in post_send_search
    responses, result = self.get_response(message_id)
  File "/root/test/local/lib/python2.7/site-packages/ldap3/strategy/base.py", line 346, in get_response
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPOperationsErrorResult: LDAPOperationsErrorResult - 1 - operationsError - None - 000004DC: LdapErr: DSID-0C090728, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580 - searchResDone - None
</pre>

Kind regards
Cornelius

**Comment by cannatag** [comment]
Hi, It looks that bind() is not performed on the new server connection. 
Which kind of authentication are you using? Is the  ``allowed_referral_hosts=[('*', True)]`` present in the Server definition (this will be true by default in 1.0.3)? 

If possible can you send me the log with EXTENDED mode (this print a trace of all LDAP messages).

Thanks,
Giovanni

**Comment by cornelinux** [comment]
The bind is successfully performed on the trusted domain. (see the script from 10/31 above)
Which also sets allowed_referrals.

How am I supposed to activate "EXTENDED mode"?
Thanks a lot
Cornelius

**Comment by cannatag** [comment]
I mean the bind to the "reffered" server. It is performed automatically when ``auto_referrals=True`` and  ``allowed_referral_hosts=[('*', True)]``. 

To set extended log please add this at the beginning of your code:

```
from os.path import join
from ldap3.utils.log import OFF, ERROR, BASIC, PROTOCOL, NETWORK, EXTENDED, set_library_log_detail_level
test_log_detail = EXTENDED
test_logging_filename = join(gettempdir(), 'ldap3.log')
import logging
logging.basicConfig(filename=test_logging_filename, level=logging.DEBUG)
set_library_log_detail_level(test_log_detail)
```

You should get a ldap3.log in your TEMP directory. Could you send it back to me? (It should automatically hide sensitive data as passwords).

thanks,
Giovanni

**Comment by cornelinux** [comment]
Looks like my 2012R2 **Foundation** are complaining about the trust setup. I think I first have to check and fix the windows side.
Kind regards
Cornelius

**Comment by cornelinux** [comment]
I had a problem with my action pack and will be only able to install the test environment in a few days...

**Comment by cannatag** [comment]
HI, in latest version 1.1.2 I've worked on referrals. Can you check if your problem is solved?

Giovanni

**Comment by cornelinux** [comment]
Hello Giovanni,
I am sorry - at the moment I can not verify this as I have no access to the corresponding testing environment. You may close this issue and I would reopen it if necessary.
Thanks a lot!
Cornelius

PS: Oh, I can close it - so I do so...

**Comment by minli1** [comment]
@cannatag 
Hi, I am wondering what is the correct way to do a query in a trusted forest B while logging in with A.
I've met issue when I SIMPLE bind to log in with A and search users in trusted domain B. A and B are trusting each other.
Then I captured packets in B, there is error complains that `a successful bind must be completed`.
And the packets in A told, `RefErr DSID-031007F9`.
Does SIMPLE bind support operations on a trusted domain?
Any help will be appreciated.
