### ISSUE TITLE
LDAPSessionTerminatedByServer not in base module namespace

### ISSUE THREAD

**Issue by w-p** [cannatag/ldap3#121]
Attempting to import LDAPSessionTerminatedByServer from the base module namespace fails.
`from ldap3 import LDAPSessionTerminatedByServer`

Other exceptions can be imported from the base namespace without issue.
`from ldap3 import LDAPInvalidScopeError`

Am I missing something?

**Comment by cannatag** [comment]
HI, you can import it from ldap3.core.exceptions. I forgot to include it in the ldap3 __init__.py file. I will do that in the next release.

Bye,
Giovanni

**Comment by cannatag** [comment]
Fixed in 0.9.9.3
