### ISSUE TITLE
How to modify userPassword according to RFC 3062?

### ISSUE THREAD

**Issue by Kentzo** [cannatag/ldap3#122]
Hi,

I'd like to set new password for a user by using SSHA. How would I do that with ldap3?

I found that it implements [RFC 3062](http://ldap3.readthedocs.org/ldap3.protocol.rfc3062.html?highlight=#module-ldap3.protocol.rfc3062) but I'm not sure how to properly use this with package.

**Comment by cannatag** [comment]
HI, it should be easy to modify passwords with ldap3, please try the examples in http://ldap3.readthedocs.org/extended.html and let me know if this works for you.

Bye,
Giovanni

**Comment by Kentzo** [comment]
Thanks, I'll give it a shot later today.

Btw, tremendous work :) I only wish for asyncio compatible implementation. Then, I believe, you will be able to get enough help from the community of https://github.com/aio-libs

**Comment by cannatag** [comment]
I've worked with asyncio in another project (sldap3) to implement an asynchronous LDAP server in pure Python. I've stopped developing it because in asyncio is still not possible to wrap a socket with ssl and this is needed for the startTls operation. I open a ticket on https://bugs.python.org/issue23749 and I hope it will be included in asyncio soon.

Bye,
Giovanni

**Comment by Kentzo** [comment]
@cannatag I've noticed that the hashed util does not use `pbkdf2_hmac`. I think it would make sense to give user a chance to request it, e.g. when hashing is done directly from web request.

**Comment by Kentzo** [comment]
@cannatag Unfortunately I cannot make `modify_password` to set password I supply. It indeed modifies password of a record. But set password is something different than I pass.

**Comment by Kentzo** [comment]
Could you explain how hashing algorithm is propagated to LDAP server? I'm using Apache Directory Studio to verify passwords and it shows both hashing algo and salt for current password. However RFC 3062 does not seem to propagate this values. Therefore I'm a little puzzled how sending has directly to LDAP server is supposed to work…

**Comment by Kentzo** [comment]
Another strange thing is that return value of connection.extend.standard.modify_password is None.

**Comment by Kentzo** [comment]
It does work without specification of hashing algorithm though.

I realize that I lack some basic understanding of how LDAP works, but I'm still puzzled :)

**Comment by cannatag** [comment]
Hi, pbkdf2_hmac is available only in python >= 3.4 and >= 2.7.8. I could try to include this as an option. 

Actually the hash is computed with:  ``hashlib.new(algorithm, value + salt).digest() + salt`` in ldap3/utils/hashed.py.

In my tests I obtain the same hashed values of Apache Directory Studio. If you still have problems can you tell me which ldap server version are you using?

Giovanni

**Comment by Kentzo** [comment]
Indeed. I don't get where ADS obtains salt and current hashing algorithm though...

Best Regards
Ilya Kulakov

**Comment by Kentzo** [comment]
@cannatag I think my question can be properly as following: where in rfc 3062 or any other related rfc is defined ability for ad-hoc hashing of newPasswd?

**Comment by cannatag** [comment]
HI Ilya
RFC3062 doesn't specify how the userPassword should be encrypted. That's something related to the server implementation and obviously evolves with the proceeding of decrypting techinques.

If you use extend.modify_password() without any hash algorithm you follow the original RFC3062 behaviour, but servers usually expect an hashed password, so I have hadded the ``hash_algorithm`` parameter to be current with servers implementation.
 
For openldap have a look at http://www.openldap.org/faq/data/cache/1347.html and point 14.4 of http://www.openldap.org/doc/admin24/security.html. Other servers can have different usage or do not accept at all the ModifyPassword() extended operation.

Bye,
Giovanni
