### ISSUE TITLE
Recent change for ALL_ATTRIBUTES in search seems to be wrong (it breaks current code)

### ISSUE THREAD

**Issue by Ernest0x** [cannatag/ldap3#124]
Hello,

With recent commit 9f539fbf3d6f70d83f3560eba5f40ef25add8234  the search operation was changed to send an empty list when `ALL_ATTRIBUTES` is passed for the `attributes` parameter, while, previously, was sending `['*']`. Was there any specific reason for this? Unfortunately, this breaks current code in which both `ALL_ATTRIBUTES` is used and `get_operational_attributes` parameter is set `True`. In that case, a `['+']` list is sent (instead of a `['*', '+']`) which will give back only the operational attributes as the result and not all user attributes AND all operational attributes as it is clearly the intention. That is checked with OpenLDAP 2.4.31 shipped with Debian Wheezy.

**Comment by cannatag** [comment]
Hi,
probably it was a mistake while testing microsoft.extend.dirsync. I will revert it the next release of ldap3.

Sorry for the inconvenience.

Giovanni

**Comment by cannatag** [comment]
Fixed in 0.9.9.3
