### ISSUE TITLE
Can't access dn of a search result

### ISSUE THREAD

**Issue by Schrottfresse** [cannatag/ldap3#129]
Hey everybody,

right now the dn of a search result is "private". I would like to access it like a normal attribute but i have to use `result._dn`. Why is the dn not exposed and is it possible to expose it?

Thank you, guys.

**Comment by cannatag** [comment]
Hi Michael, when performing a search you will find the response in the "response" or in the "entries" attribute of the connection object. The "result" attribute contains the result code and description of the LDAP operation.

For more details you can look at the docs at ldap3.readthedocs.org/searches.html


-------- Messaggio originale --------
Da:Michael Schlapa <notifications@github.com>
Inviato:Sat, 21 Nov 2015 17:15:27 +0100
A:cannatag/ldap3 <ldap3@noreply.github.com>
Oggetto:[ldap3] Can't access dn of a search result (#129)
