### ISSUE TITLE
Active Directory - User password reset

### ISSUE THREAD

**Issue by t0neg** [cannatag/ldap3#130]
Hi guys,

Can you please advise if User password reset/change for AD is currently supported by ldap3? I've checked extend.standard.modify_password but apparently it's not working for AD. 

Thanks in advance,
Anton

**Comment by cannatag** [comment]
Hi, 
Microsoft AD doesn't follow RFC 3062 (standard modify password) so ``extend.standard.modify_password()`` doesn't work with AD. You can follow https://support.microsoft.com/en-us/kb/269190 to change the AD password via LDAP. There is a tricky part in this kb that is about coding in BER. If this is too difficult I could think of adding a extend.microsoft.modify_password() method for simpler operation.

Let me know if you need it.

Bye,
Giovanni

**Comment by w-p** [comment]
If you're simply interested in assigning a value to the `unicodePwd` attribute, you can use `connection.modify` with an operation type of `ldap3.MODIFY_REPLACE`.

**Comment by t0neg** [comment]
Hi Giovanni,

I would appreciate if you could add such function for AD. Meanwhile I'll try to follow the article and check if I can do it myself.

@w-p ,
If I've got you correctly, I have tried to push the password in clear text, base64 encoded to this field, but  in all cases I get an error:
```
{
	'dn' : '',
	'description' : 'unwillingToPerform',
	'referrals' : None,
	'type' : 'modifyResponse',
	'message' : '0000001F: SvcErr: DSID-031A1248, problem 5003 (WILL_NOT_PERFORM), data 0\n\x00',
	'result' : 53
}
```
Best regards,
Anton

**Comment by w-p** [comment]
Is your bind encrypted?  Microsoft doesn't allow setting passwords (and some other things) if you've authenticated in the clear.  The easiest solution is to setup LDAPS / SSL on your DC (which I highly recommend doing anyway) or use SASL with MD5.

**Comment by t0neg** [comment]
Yes, connection is encrypted with LDAPS/SSL:
```
server = Server(host,use_ssl=True, get_info=ALL)
conn = Connection(server, user=username, password=password, authentication=NTLM, auto_bind=True)
print(conn)

ldaps://<ip>:636 - ssl - user: <Domain>\svc_ad - bound - open - <local: <local_ip>:61176 - remote: <ip>:636> - tls not started - listening - SyncStrategy - internal decoder
```

**Comment by w-p** [comment]
That error code could also point to an issue with permissions or password complexity. I suggest getting the Microsoft error lookup tool, err.exe. I don't have Windows box handy at the moment. It may also help to turn on ldap3 extended logging.

**Comment by w-p** [comment]
On encoding, I think utf-16 little endian is what you want:
`'"{}"'.format(password).encode('utf-16-le')`

Reference:
[MSDN unicodePwd docs](https://msdn.microsoft.com/en-us/library/cc223248.aspx)
[ldap3 tests, line 349](https://github.com/cannatag/ldap3/blob/cdf6f7f784f41ac044fe8a021df53af0f4c1a8b8/test/__init__.py#L349)

**Comment by cannatag** [comment]
You don't need to b64encode the password. Just use the suggestion from w-p.

**Comment by t0neg** [comment]
Thank you guys, works perfectly!
To summarize:
```
server = Server(host,use_ssl=True, get_info=ALL)
conn = Connection(server, user=username, password=password, authentication=NTLM, auto_bind=True)
print(conn)

pwd = '<you_password_here>'
enc_pwd = '"{}"'.format(password).encode('utf-16-le')
conn.modify('<DistinguishedName>', {'unicodePwd': [(MODIFY_REPLACE, [enc_pwd])]})
print(conn.result)
```

Best regards,
Anton

**Comment by cannatag** [comment]
Hi,
please could you try the version in dev? I've included a method to change password, either as admin or a normal user:

```
# old_password must be sent if a normal user wants to change its password, else a reset by an admin is done
 connection.extend.microsoft.modify_password(dn, new_password, old_password=None)
```

I'm not able to test it now in a AD enviroment, so I'd like to know it it's working as supposed.

Thanks,
Giovanni

**Comment by t0neg** [comment]
Hi Giovanni,

I'm trying to perform from account with Domain Admin permissions. 
Request:
```
r = conn.extend.microsoft.modify_password(user=dn, new_password=new_password, old_password=None)
```
I get:
```
ldaps://192.168.0.11:636 - ssl - user: TST\svc_ad - bound - open - <local: 192.168.0.76:55333 - remote: 192.168.0.11:636> - tls not started - listening - SyncStrategy - internal decoder

{
	'message' : '0000001F: SvcErr: DSID-031A1248, problem 5003 (WILL_NOT_PERFORM), data 0\n\x00',
	'dn' : '',
	'type' : 'modifyResponse',
	'result' : 53,
	'description' : 'unwillingToPerform',
	'referrals' : None
}
```

**Comment by t0neg** [comment]
Hi Giovanni,

It seems like encoding is not working correctly. I've tried to compare these 2 lines:
```
new_password = 'P@ssw0rd123##'
enc_pwd1 = '"%s"' % (new_password.encode('utf-16-le'))
enc_pwd2 = '"{}"'.format(new_password).encode('utf-16-le')

print('{}: {}'.format(type(enc_pwd1), enc_pwd1))
print('{}: {}'.format(type(enc_pwd2), enc_pwd2))
```
And output is different. 
```
<class 'str'>: "b'P\x00@\x00s\x00s\x00w\x000\x00r\x00d\x001\x002\x003\x00#\x00#\x00'"
<class 'bytes'>: b'"\x00P\x00@\x00s\x00s\x00w\x000\x00r\x00d\x001\x002\x003\x00#\x00#\x00"\x00'
```
Works fine with bytes, but not with string.

**Comment by cannatag** [comment]
You're right, with the former the utf-16 encoding is applied only to the password, while with the latter the encoding is applied also to the quotes.

Thanks,
will fix it and release in the next release of ldap3.

Bye,
Giovanni

**Comment by cannatag** [comment]
Can you check the code in dev? It should work now.

**Comment by t0neg** [comment]
Hi Giovanni,

I've tested a password change from admin account. It works fine.
However, if i try to change password from unpriviledged account I get error.
Test:
```
dn = 'CN=Test Account,OU=Service Accounts,DC=tst,DC=int'
user = 'TST\\ad_test'
old_password = '9r**CrU!3mnLdeY$'
new_password = 'P@ssw0rd123##456'

server = Server(host,use_ssl=True, get_info=ALL)
conn = Connection(server, user=user, password=old_password, authentication=NTLM, auto_bind=True)
print(conn)

r = conn.extend.microsoft.modify_password(user=dn, new_password=new_password, old_password=old_password)
print(conn.result)
```
Output:
```
ldaps://192.168.0.11:636 - ssl - user: TST\ad_test - bound - open - <local: 192.168.0.76:57077 - remote: 192.168.0.11:636> - tls not started - listening - SyncStrategy - internal decoder
{'result': 19, 'dn': '', 'description': 'constraintViolation', 'type': 'modifyResponse', 'referrals': None, 'message': '00000056: AtrErr: DSID-03190F80, #1:\n\t0: 00000056: DSID-03190F80, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)\n\x00'}
```
[debug.txt](https://github.com/cannatag/ldap3/files/50840/debug.txt)

**Comment by cannatag** [comment]
Hi,
i suspect the message ConstraintViolation is someway related to your AD password policy. For what I know constraints are not verified when you reset a user password as an Administrator. 

In my case I had a minimum age of a password of 1 day and this obviously broke the test (where the user is created with a password and then immediately changed). In my case I solved with 


 net accounts /MINPWAGE:0

in powershell (run as administrator)


Bye,
Giovanni

**Comment by cannatag** [comment]
Released in 1.0.1

**Comment by gig-code** [comment]
I try to change AD user with 

if len(conn.entries) == 1:
    USER_DN = conn.response[0].get("dn")
    enc_pwd = '{}'.format('bmB_943!*3QYY69r').encode('utf-16-le')
    enc_pwd_current ='{}'.format('Ankara06').encode('utf-16-le')
    
    r= ldap3.extend.microsoft.modifyPassword.ad_modify_password(conn, USER_DN, enc_pwd, enc_pwd_current,  controls=None)

but I face 

ldap3.core.exceptions.LDAPConstraintViolationResult: LDAPConstraintViolationResult - 19 - constraintViolation - None - 0000052D: AtrErr: DSID-0319103B, #1:
        0: 0000052D: DSID-0319103B, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)
  - modifyResponse - None

error, I try a lot of thing but I can not solve the problem;

Can someone please write a sample working code to use ldap3.extend.microsoft.modifyPassword.ad_modify_password function will it's appreciated

Regards.

**Comment by zorn96** [comment]
@gig-code if you're using the `ad_modify_password` function, you shouldn't do the utf-16 encoding yourself I believe. the function should do that for you. may just be failing due to the current password aspect not matching

**Comment by shyamkkhadka** [comment]
> Hi, i suspect the message ConstraintViolation is someway related to your AD password policy. For what I know constraints are not verified when you reset a user password as an Administrator.
> 
> In my case (I had a 0000052D error code) I had a minimum age of a password of 1 day and this obviously broke the test (where the user is created with a password and then immediately changed). In my case I solved with `net accounts /MINPWAGE:0` in powershell (run as Administrator).
> 
> In your example the error code is 00000056 that should mean that the old password is not the right one.
> 
> Bye, Giovanni

I got success result as `{'result': 0, 'description': 'success', 'dn': '', 'message': '', 'referrals': No                                                                                                                     ne, 'type': 'modifyResponse'}
`
But the user password is not changed in Active Directory itself.
