### ISSUE TITLE
cannot pass controls to modify_password

### ISSUE THREAD

**Issue by Gollam** [cannatag/ldap3#143]
Hi,
I have to send the ppolicy control with the `modify_password` standard extended operation, but unfortunately I cannot pass it as a parameter. The solution is very simple, I already forked your code, because I needed a quick solution. Controls just have to be passed all the way down in the call graph, to the `ExtendedOperation.__init__` function, and it will be sent. Should I provide a diff, or make a pull request... etc.?

**Comment by cannatag** [comment]
Thanks, you're right. Controls are only sent  when you perform an extended operation directly from the Commection object. I will include a fix to let you attach controls in operations defined in the extend package. If you want please send me a diff  with your modifications, so I can check them and include in the next release of ldap3.

Bye,
Giovanni

**Comment by cannatag** [comment]
thanks, please check code in dev. I added controls to all extended operation in the extend package.
Let me know if it works for you.

Giovanni

**Comment by Gollam** [comment]
Yes, I've tried it, and it's working. Thank you for the quick fix!

**Comment by Gollam** [comment]
Can you please given an estimate of when will v1.0.4 be released? Thank you!

**Comment by cannatag** [comment]
Hi Hinel, I will release 1.0.4 in this weekend. It should include only your fix.

Bye,
Giovanni

**Comment by cannatag** [comment]
Hi, I've just release ldap3 1.0.4. Sorry for the delay.

Bye,
Giovanni

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Questa
e-mail è stata inviata da un computer privo di virus protetto da Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-22 11:25 GMT+01:00 Hinel Balázs <notifications@github.com>:
