### ISSUE TITLE
Don't clear result of LDAP operations: ADD, DELETE, and etc into docs 

### ISSUE THREAD

**Issue by MySmile** [cannatag/ldap3#145]
Hello!

I'm read the docs and don't understand how get result of LDAP operation as True/False (boolean type).

Thx!

**Comment by cannatag** [comment]
Hi,
every operation returns a True/False valu, for example:

```
from ldap3 import Server, Connection
server = Server('myserver')
conn = Connection(server, 'myuser', 'mypassword')

if conn.bind():
    # do other operations
else:
    print('unable to connect!')
```

The same is ifor add, delete, modify and modifydn.

For searches you get False if the search is not successful, True if it returns some values. You can read the values in conn.entries.

**Comment by MySmile** [comment]
Hello!

I used MODIFY operation. Below my example of conn.results.

My successfull conn.result =  {'type': 'modifyResponse', 'referrals': None, 'description': 'success', 'result': 0, 'dn': '', 'message': ''}. 
  
My unsucceessfull conn.result = result modify -  {'description': 'noSuchObject', 'dn': 'ou=XXX', 'type': 'modifyResponse', 'message': '', 'result': 32, 'referrals': None}

For check result of MODIFY operation I'm want use code like

if conn.result['result']:
     print('Ok')
else:
   print('Error of modify operation')

But amazingly my successfull conn.result['result'] will be False (as 0) and my unsucceessfull conn.result['result'] will be True (as 32)!

**Comment by cannatag** [comment]
Hi,
in your example conn.result['result']:is equal to 0 when the operation is successful (that's the code returned by the ldap server) but 0 in python means False so your if statement goes in the wrong direction!

You can check for ``conn.result['description'] == 'success'`` or just check the return value of the modify operation:

```
if conn.modify(.....);
    print('OK')
else:
    print('Error')
```

**Comment by MySmile** [comment]
Thanks!
