### ISSUE TITLE
Getting recursive groups using ldap3

### ISSUE THREAD

**Issue by AMMullan** [cannatag/ldap3#147]
I'm working on authentication for a web application and I need to find out the user is a member of a group but I'm having problems getting information between domains in a forest. We basically have the following domain structure

DOMAIN.COM
UK.DOMAIN.COM
US.DOMAIN.COM

All user accounts are in the child domains but the groups are in the parent domain. The groups in the parent domain have groups from the child domains which we are members of.

I can get a list of all groups that I'm a member of and this works well but it only retrieves the memberOf attribute, it doesn't recurs up the tree. I also can't get groups below the parent domain.

Is there an option that I'm missing to allow recursive results? And is traversing between the domains going to be an issue?

**Comment by cannatag** [comment]
Hi, 
the LDAP protocol doesn't provide any way to recurse group membership.  You must query the groups by yourself.  It should be quite simple, just cycle over the response memberOf attributes of the first group and query any subsequent group. 

I don't use active directory,  so I can't answer your question about domain boundaries, sorry.

**Comment by tingtang66** [comment]
We are using extensible matching. But seems ldap3 lib didn't process the match correctly.
The search filter is: (&(member:1.2.840.113556.1.4.1941:=CN=something))
I added following code at line 190 to search.py which is from ldap3 lib:
```
print(search_filter)
```
and at line 224 just before 'raise' added
```
print("state:%s, search_match_or_close:%s, search_open_or_close:%s, search_match_or_control:%s, c:%s" % (state, SEARCH_MATCH_OR_CLOSE, SEARCH_OPEN_OR_CLOSE, SEARCH_MATCH_OR_CONTROL, c))
```
I got following error message

```
(objectClass=*)
(objectClass=subschema)
(&(member:1.2.840.113556.1.4.1941:=CN=something))
(objectClass=*)
(objectClass=subschema)
(objectClass=*)
(objectClass=subschema)
(&(ExtensibleMatch(componentType=NamedTypes(OptionalNamedType('matchingRule', MatchingRule()), OptionalNamedType('type', Type()), NamedType('matchValue', MatchValue()), DefaultedNamedType('dnAttributes', DnAttributes('False')))).setComponents(MatchingRule(b'1.2.840.113556.1.4.1941'), Type(b'member'), MatchValue(b'CN=something'), DnAttributes('False'))))

state:22, search_match_or_close:22, search_open_or_close:21, search_match_or_control:23, c:(

Traceback (most recent call last):
  File "active_directory.py", line 117, in <module>
    ad.ldap_init()
  File "active_directory.py", line 79, in ldap_init
    get_operational_attributes=True
  File "/home/nicholas/.local/lib/python3.5/site-packages/ldap3/core/connection.py", line 616, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/home/nicholas/.local/lib/python3.5/site-packages/ldap3/strategy/sync.py", line 142, in post_send_search
    responses, result = self.get_response(message_id)
  File "/home/nicholas/.local/lib/python3.5/site-packages/ldap3/strategy/base.py", line 322, in get_response
    ref_response, ref_result = self.do_operation_on_referral(self._outstanding[message_id], responses[-2]['referrals'])
  File "/home/nicholas/.local/lib/python3.5/site-packages/ldap3/strategy/base.py", line 675, in do_operation_on_referral
    controls=request['controls'])
  File "/home/nicholas/.local/lib/python3.5/site-packages/ldap3/core/connection.py", line 613, in search
    request = search_operation(search_base, search_filter, search_scope, dereference_aliases, attributes, size_limit, time_limit, types_only, self.server.schema if self.server else None)
  File "/home/nicholas/.local/lib/python3.5/site-packages/ldap3/operation/search.py", line 363, in search_operation
    request['filter'] = build_filter(search_filter, schema)  # parse the searchFilter string and compile it starting from the root node
  File "/home/nicholas/.local/lib/python3.5/site-packages/ldap3/operation/search.py", line 310, in build_filter
    return compile_filter(parse_filter(search_filter, schema).elements[0])
  File "/home/nicholas/.local/lib/python3.5/site-packages/ldap3/operation/search.py", line 225, in parse_filter
    raise LDAPInvalidFilterError('malformed filter')
ldap3.core.exceptions.LDAPInvalidFilterError: malformed filter
```

I don't know why 'c' stop at '(', is a bug?

I would appreciate you have a look at this issue.

**Comment by w-p** [comment]
Querying across domain boundaries is tricky depending on configuration and permissions. Giovanni is right that it's easiest to right some recursive logic to read all the group membership information. Just take care to catch duplicates within the recursion as memberOf relationships can loop. Further, you can apply this logic to other LDAP servers than MS AD that don't support such search controls.

**Comment by cannatag** [comment]
HI, sorry for asnwering late to your question. I've tried your code and didn't get any error. Maybe there is some not allowed character in the "something" portion of your search. Furthermore why are you using the AND (&) filter with a single condition? It should be the same of  
```
(member:1.2.840.113556.1.4.1941:=CN=something)
```

Can you give me a snippet of code that actually fails, so I could try to debug it in a better way?

Thanks,
Giovanni

**Comment by tingtang66** [comment]
@cannatag Thanks for you reply.
The '&' is that we copy from Active Directory filter, but I have tried without '&' filter which didn't work too and the filter works OK on Active Directory...

The following snippet is what I use to test AD. When I removed ':1.2.840.113556.1.4.1941:', the code can run without error (not expected result). Because I am not expert of LDAP/Active Directory, please let me know anything wrong of my filter or my code. Many thanks
```
def ldap_init(self):
        ad_server, base = self.get_ad_details(self.domain)
        server = Server(ad_server, get_info=SCHEMA)
        conn = Connection(server, read_only=True, user=self.domain + '\\' + self.username, password=self.password, lazy=False, raise_exceptions=True)

        try:
            bind = conn.bind()
            
            criteria = "(member:1.2.840.113556.1.4.1941:=CN=MY, Name,OU=Users,OU=MY Home,OU=Domain Objects,DC=sample,DC=Sample,DC=net)"
            conn.search(
                search_base=r"DC=Sample,DC=net",
                search_filter=criteria,
                search_scope=SUBTREE,
                attributes=[ALL_ATTRIBUTES, ALL_OPERATIONAL_ATTRIBUTES],
                get_operational_attributes=True
            )
            self.result = conn.response

            print(self.result)
```

**Comment by cannatag** [comment]
HI,
I've arranged your code snippet to my test lab but got no error:

```
import logging
from ldap3 import Server, Connection, SUBTREE, ALL_OPERATIONAL_ATTRIBUTES, ALL_ATTRIBUTES, SCHEMA
from ldap3.utils.log import set_library_log_detail_level, EXTENDED

logging.basicConfig(filename='tingtang-ldap3.log', level=logging.DEBUG)
set_library_log_detail_level(EXTENDED)

ad_server, base, domain, user, password = 'win1.hyperv', 'o=test', 'FOREST', 'Administrator', 'password'
server = Server(ad_server, get_info=SCHEMA)
conn = Connection(server, read_only=True, user=domain + '\\' + user, password=password, lazy=False, raise_exceptions=True, fast_decoder=False)

bind = conn.bind()
criteria = "(member:1.2.840.113556.1.4.1941:=CN=MY Name,OU=Users,OU=MY Home,OU=Domain Objects,DC=sample,DC=Forest,DC=lab)"
conn.search(
    search_base=r"DC=Forest,DC=lab",
    search_filter=criteria,
    search_scope=SUBTREE,
    attributes=[ALL_ATTRIBUTES, ALL_OPERATIONAL_ATTRIBUTES],
    get_operational_attributes=True
)

result = conn.response

print(result)
```

prints out:

```
[{'type': 'searchResRef', 'uri': ['ldap://ForestDnsZones.FOREST.LAB/DC=ForestDnsZones,DC=FOREST,DC=LAB']}, {'type': 'searchResRef', 'uri': ['ldap://DomainDnsZones.FOREST.LAB/DC=DomainDnsZones,DC=FOREST,DC=LAB']}, {'type': 'searchResRef', 'uri': ['ldap://FOREST.LAB/CN=Configuration,DC=FOREST,DC=LAB']}]
```

I noticed there is an error in your criteria: there should not be a comma in ``CN=MY, Name`` but this is not checked by the filter parser.

Can you send me the extended log of the above code arranged and run in your environment? You should find the tingtang-ldap3.log file in the folder where the script is run. The fast_decoder=False give a better description of ldap messages in the log but should not modify the behaviour of the connection.Sensitive data (as password) are automatically removed in the log.

Bye,
Giovanni

**Comment by tingtang66** [comment]
Hi Giovanni, 

Thanks for your quick reply. I will double check and rerun my code tomorrow. 

Thanks for your help again indeed!

Best Regards,

Nic 

2016年2月15日 星期一 +0000 下午10:36 发件人 notifications@github.com  <notifications@github.com>:
>HI,
>I've arranged your code snippet to my test lab but got no error:
>import logging
from ldap3 import Server, Connection, SUBTREE, ALL_OPERATIONAL_ATTRIBUTES, ALL_ATTRIBUTES, SCHEMA
from ldap3.utils.log import set_library_log_detail_level, EXTENDED

logging.basicConfig(filename='tingtang-ldap3.log', level=logging.DEBUG)
set_library_log_detail_level(EXTENDED)

ad_server, base, domain, user, password = 'win1.hyperv', 'o=test', 'FOREST', 'Administrator', 'password'
server = Server(ad_server, get_info=SCHEMA)
conn = Connection(server, read_only=True, user=domain + '\\' + user, password=password, lazy=False, raise_exceptions=True, fast_decoder=False)

bind = conn.bind()
criteria = "(member:1.2.840.113556.1.4.1941:=CN=MY Name,OU=Users,OU=MY Home,OU=Domain Objects,DC=sample,DC=Forest,DC=lab)"
conn.search(
    search_base=r"DC=Forest,DC=lab",
    search_filter=criteria,
    search_scope=SUBTREE,
    attributes=[ALL_ATTRIBUTES, ALL_OPERATIONAL_ATTRIBUTES],
    get_operational_attributes=True
)

result = conn.response

print(result)

**Comment by tingtang66** [comment]
Hi @cannatag 
I attached the log file. 
Thank you very much!!

[tingtang-ldap3.txt](https://github.com/cannatag/ldap3/files/132336/tingtang-ldap3.txt)

**Comment by cannatag** [comment]
Hi,
sorry for late answer, I don't see any error in your log. Do you still have this issue?

Giovanni

**Comment by tingtang66** [comment]
@cannatag Yeah, we still have this issue. We have decided not to use extensible matching to achieve our goal. 
Thanks for your help.

**Comment by cannatag** [comment]
ok. I close the issue. Contact me if you have any problem.

Bye,
Giovanni
