### ISSUE TITLE
[Q} ldap3.MODIFY_DELETE dont delete if something missing

### ISSUE THREAD

**Issue by colttt** [cannatag/ldap3#149]
Hello

i would do something like:
```
conn.modify('uid=colttt,cn=users,dc=example,dc=de',{'telephoneNumber': [(ldap3.MODIFY_DELETE, [])], 'roomNumber': [(ldap3.MODIFY_DELETE, [])]})
```
this works only if _telephoneNumber_ AND _roomNumber_ exist, if some of this not exist it dont work. is that ok?

For example if a user expired (I won't to delete the complete user), I would like to delete things like roomnumber, telephone number,  location, department etc, but some values are not set, how can i do this?

**Comment by cannatag** [comment]
HI you should try to use the MODIFY_REPLACE flag with an empty list. 
This is from RFC 4511 the official current LDAP specification:

```
           replace: replace all existing values of the modification
           attribute with the new values listed, creating the attribute
           if it did not already exist.  A replace with no value will
           delete the entire attribute if it exists, and it is ignored
           if the attribute does not exist.
```

So you should try:

```
conn.modify('uid=colttt,cn=users,dc=example,dc=de',{'telephoneNumber': [(ldap3.MODIFY_REPLACE, [])], 'roomNumber': [(ldap3.MODIFY_REPLACE, [])]})
```

Obviously that the server follows the current ldap specifications.

Bye,
Giovanni
