### ISSUE TITLE
`ssl.SSLError` exception not raised on certificate error

### ISSUE THREAD

**Issue by jerrykan** [cannatag/ldap3#15]
Somewhere between commits 568b69af4a...6e918c307d the `ssl.SSLError` exception is no longer raised when a certificate issue is detected. Using the following example:
 ```python
import inspect
import ssl

import ldap3

# username, password, host, port defined here
server = ldap3.Server(host, port=port, use_ssl=True,
                      tls=ldap3.Tls(validate=ssl.CERT_REQUIRED))
conn = ldap3.Connection(server, user=username, password=password,
                        raise_exceptions=True)
try:
    conn.open()
except Exception as e:
    from pprint import pprint
    pprint(inspect.getmro(type(e)))
```

the following is output in 568b69af4a
```python
(<class 'ldap3.core.exceptions.LDAPSocketOpenError'>,
 <class 'ldap3.core.exceptions.LDAPSocketOpenError'>,
 <class 'ldap3.core.exceptions.LDAPCommunicationError'>,
 <class 'ldap3.core.exceptions.LDAPExceptionError'>,
 <class 'ldap3.core.exceptions.LDAPException'>,
 <class 'ssl.SSLError'>,
 <class 'socket.error'>,
 <type 'exceptions.IOError'>,
 <type 'exceptions.EnvironmentError'>,
 <type 'exceptions.StandardError'>,
 <type 'exceptions.Exception'>,
 <type 'exceptions.BaseException'>,
 <type 'object'>)
```

but in 6e918c307d it is as follows:
```python
(<class 'ldap3.core.exceptions.LDAPSocketOpenError'>,
 <class 'ldap3.core.exceptions.LDAPCommunicationError'>,
 <class 'ldap3.core.exceptions.LDAPExceptionError'>,
 <class 'ldap3.core.exceptions.LDAPException'>,
 <type 'exceptions.Exception'>,
 <type 'exceptions.BaseException'>,
 <type 'object'>)
```

There should be some way to differentiate between a connection error due to a port not actually being open and an error due to certificate verification problems.

**Comment by cannatag** [comment]
Hello jerrykan,
Problem is that now if the dns name is resolved to more than 1 address (ipv4 or ipv6) they are checked for availability as per the "mode" parameter of the Server object. Exceptions raised while checking the "candidate" addresses are stored in a list and returned in the args attribute of the exception. So you get a generic "unable to open socket" exception, with all other exceptions in the args attribute, with additional info (the candidate address and the datetime of the operation).

Thanks to your excellent example I understand your point and it makes sense to have the real exception when you have only one address to connect, so I modified the code to return the original exception if only one is presente in the args attribute. This should restore the original behaviour when using a single address.

Can you check the version in dev? Your example should work fine with it.

Bye,
Giovanni

**Comment by jerrykan** [comment]
Hello Giovanni,

I have just run my test suite against the dev branch and it is once again behaving as I would expect.

Cheers,
John.

**Comment by cannatag** [comment]
Thanks, I will include the fix in the next release.

Bye,
Giovanni
