### ISSUE TITLE
Connection context manager, bind and start_tls order

### ISSUE THREAD

**Issue by usischev** [cannatag/ldap3#152]
Hi Giovanni,

My setup has LDAP servers with TLS enabled on port 389. I create Server objects with a properly configured Tls object. Then I want to use connection for example to check user password like this:
```
with ldap3.Connection(server, user=user, password=password, **kwargs) as conn:
    conn.start_tls()
    login_correct = conn.bind()
    ...
```
However I noticed in extended log that first connection binds without TLS, then starts TLS, and then binds again, this time over TLS. I guess this happens because `__enter__` binds the connection before returning it so I don't have a way to start TLS before anything else:

https://github.com/cannatag/ldap3/blob/dev/ldap3/core/connection.py#L416

This is bad because login data gets transferred unencrypted once despite TLS being configured and started. I am not quite sure if this is a bug or I am just using the context manager in a wrong way.

Logfile in case it is needed: [pavel-ldap3-log-tls.txt](https://github.com/cannatag/ldap3/files/159362/pavel-ldap3-log-tls.txt)

**Comment by cannatag** [comment]
Hi Pavel, you can set the auto_bind feature in the Connection object if you set

```
from ldap3 import Connection, AUTO_BIND_TLS_BEFORE_BIND
conn = Connection(..., auto_bind=AUTO_BIND_TLS_BEFORE_BIND)
```

it should automatically try the start_tls() before the bind() 

it should work in a context manager too.

Let me know if it's working right.

Bye,
Giovanni

**Comment by usischev** [comment]
With `auto_bind=AUTO_BIND_TLS_BEFORE_BIND`, TLS is started before the first bind() indeed. But now in case of invalid credentials I get an exception:
```
Traceback (most recent call last):
  File "ldap_bind.py", line 35, in <module>
    with Connection(server, user=user, password=password, auto_bind=AUTO_BIND_TLS_BEFORE_BIND) as conn:
  File "/Users/pavel/Documents/ldap3-test/ldap3/core/connection.py", line 301, in __init__
    raise LDAPBindError(self.last_error)
ldap3.core.exceptions.LDAPBindError: automatic bind not successful - invalidCredentials
```
I guess I can add a try/except clause to check for failed automatic bind. Thanks.

**Comment by cannatag** [comment]
Yes, you must catch the exception. If you think of a better way to handle it let me know.

Giovanni
