### ISSUE TITLE
how to escape bracktes in search_filter?

### ISSUE THREAD

**Issue by braindumped** [cannatag/ldap3#153]
I want to query for members of a group that contains brackets in its DN.
when using ldapsearch I just escape them by `\( \) `but with ldap3 I get 
`ldap3.core.exceptions.LDAPInvalidFilterError: invalid filter`
Am I doing something wrong?
Thanks!

**Comment by cannatag** [comment]
Hi,
the ldap3 library strictly follows the standard RFCs for LDAP. RFC4515 specify that in a filter the left bracket must be encoded as \28 and the right bracket as \29. There is an helper function in ldap3.utils.conv called escape_filter_chars() that automatically does this for you. You don't have to pass the whole filter but only the values for example:

```
>>> '(cn=%s)' % escape_filter_chars('printer (second floor)') 
'(cn=printer \\28second floor\\29)'
```

Can you see if this works for you?

Thanks,
Giovanni

**Comment by braindumped** [comment]
Hi Giovanni,
Thanks for your fast response.
I have now

`searchfilter='(&(objectClass=user)((memberof=CN=AB %s,OU=Mailverteiler,OU=MSX,OU=Adressbuch,DC=x,DC=y,DC=z))' % escape_filter_chars('(UMH)')
print (searchfilter)
conn.search(search_base='dc=x,dc=y,dc=z',
                search_filter=searchfilter, attributes = ['sAMAccountName'])`

and the print gives:

`(&(objectClass=user)((memberof=CN=AB \28UMH\29,OU=Mailverteiler,OU=MSX,OU=Adressbuch,DC=x,DC=y,DC=z))
`

but unfortunately I still get `ldap3.core.exceptions.LDAPInvalidFilterError: invalid filter`

Thanks,
Thomas

**Comment by cannatag** [comment]
Hi, I think there is an unneeded open bracket in your filter that is not matched by a closing bracket:
..
(&(objectClass=user)((memberof=CN=AB \28UMH\29,OU=Mailverteiler,OU=MSX,OU=Adressbuch,DC=x,DC=y,DC=z)) 
```

should be:
```
(&(objectClass=user)(memberof=CN=AB \28UMH\29,OU=Mailverteiler,OU=MSX,OU=Adressbuch,DC=x,DC=y,DC=z)) 
```

There are two brackets before  ``memberof=...``. There should be only one.

Let me know if this solves the problem.

Bye,
Giovanni

**Comment by braindumped** [comment]
bingo! Thanks a lot for your help!
Kind Regards,
Thomas

**Comment by braindumped** [comment]
bingo! Thanks a lot for your help!
Kind Regards,
Thomas

**Comment by braindumped** [comment]
bingo! Thanks a lot for your help!
Kind Regards,
Thomas
