### ISSUE TITLE
paged search in Active Directory. 2nd search is empty.

### ISSUE THREAD

**Issue by cornelinux** [cannatag/ldap3#155]
Hi,

I am trying to use paged search.

My code looks like this:

        paged_search = True
        paged_cookie = None
        while paged_search:
            self.l.search(search_base=self.basedn,
                          search_scope=self.scope,
                          search_filter=filter,
                          attributes=attributes,
                          paged_size=self.sizelimit,
                          paged_cookie=paged_cookie)
            # returns a list of dictionaries
            for entry in self.l.response:
                try:
                    attributes = entry.get("attributes")
                    user = self._ldap_attributes_to_user_object(attributes)
                    user['userid'] = self._get_uid(entry, self.uidtype)
                    ret.append(user)
                except Exception as exx:  # pragma: no cover
                    log.error("Error during fetching LDAP objects: %r" % exx)
                    log.debug("%s" % traceback.format_exc())
            paged_cookie = self.l.result.get('controls', {}).get(
                '1.2.840.113556.1.4.319', {}).get('value', {}).get('cookie')
            paged_search = bool(paged_cookie)

self.l being my LDAP3 connection. It works pretty well for an OpenLDAP server.

I get the following controls

    {'1.2.840.113556.1.4.319': {
            'value': {
                   'cookie': '\x0c\x00\x00\x00',
                   'size': 0},
           'description': 1.2.840.113556.1.4.319 - LDAP Simple Paged Results - Control - RFC2696,
           'criticality': False}}

But when I access an MS AD 2012R2 I also get the first page and the cookie looks like this:

         '\x00\x00\x00\x004\x02\x00\x00\xff\xff....'

But when I do the 2nd run through the while loop the result is empty. Although 
1. I got a cookie, that indicates that there is more, 
2. there is more.

When I increase the self.sizelimit, I get up to 1000 entries in the first run (limit from AD).
But the 2nd run will always be empty.

Stepping into the search function: Cookie looks like this:

[Size(100), Cookie(hexValue='0100000034020000ffffffff030021b1dce3ca5a37f1097de9fac9620b628e951ae139c87a328dfc6706d670b07ce3fe44551a4d89840a7eec610d26000000000100000000000000081b000005000000050000000200000000000000000000000400000017000300de070000d7070000d707000000000000929c2306501fd74ab13007bdb570d70a0000000002000000010000000000000000000000ffffffff68000000640000000000000000000000000000000000000000000000000000000000000001000000ffffffffbddb89432a94d64cee7b09274e63d29549dffd93e01beb9f53ed5c9ca26d9044000000007f800100067f80001b080000000000000000000000000000ffffffff00000000000000000e0000000500000000010000494e4445585f30303030303030307f800100067f80010006ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000')]

**Comment by cannatag** [comment]
Hi Cornelius, have you tried to use the connection.extend.standard.paged_search() method? It hdes all the machinery requested by the RFCs. Have a look at http://ldap3.readthedocs.org/standard.html for an example.

Let me know if you still have problem. In that case I'll try to setup a lab for testing.

Bye,
Giovanni

**Comment by cornelinux** [comment]
Hi Giovanni,

thanks a lot for the hint!

works well with the 3000 test objects in an AD 2012. But: I am running this code:

    g = self.l.extend.standard.paged_search(
                search_base=self.basedn,
                search_filter=filter,
                search_scope=self.scope,
                attributes=attributes,
                paged_size=100,
                size_limit=self.sizelimit,
                controls=paged_controls)

Then I am iterating over "g".
BUT: even if my size_limit is 200 I get all 3000 entries. What am I missing here?
What is the controls for (honestly I did not read the RFC :-)

Thanks a lot 
Cornelius

**Comment by cannatag** [comment]
Hi Cornelius, you don't have to send the paged_controls when using this function. Also try with generator=False to see if you get the same result. If you still get the whole 3000 entries please send me a log of the first two searches.

Bye,
Giovanni

**Comment by cornelinux** [comment]
Hi Giovanni,

I still get all users when searching like this:

        g = self.l.extend.standard.paged_search(search_base=self.basedn,
                                                search_filter=filter,
                                                search_scope=self.scope,
                                                attributes=attributes,
                                                paged_size=100,
                                                size_limit=300,
                                                generator=False)

Can you please specify what kind of log you need from which searches?
Thanks for all your effort.

Cornelius

**Comment by cannatag** [comment]
Hi Cornelius,
I've done some test in my lab, it seems that in AD the size_limit refers to each iteration of the paged search. I think you have to perform the full paged search and then get only the needed number of entries.

I don't know why it's working this way, it seems quite useless.

Bye,
Giovanni

**Comment by cornelinux** [comment]
Hi Giovanni,

thanks. I started wireshark..

I am running this code:

        ret = []
        g = self.l.extend.standard.paged_search(search_base=self.basedn,
                                                search_filter=filter,
                                                search_scope=self.scope,
                                                attributes=attributes,
                                                paged_size=100,
                                                size_limit=self.sizelimit,
                                                generator=True)
        # returns a generator of dictionaries
        for entry in g:
            # Simple fix for ignored sizelimit with Active Directory
            if len(ret) >= self.sizelimit:
                break
            ret.append(entry)

And obviously since I break the for-loop the generator will not pull any more ldap objects.
I end up with the desired result, that only self.sizelimit ldap objects are transmitted over the wire!

Thanks fine. Although strange ;-)

Thanks again for your help and this great module.

Kind regards
Cornelius
