### ISSUE TITLE
Allow certificate validation by passing options to the Tls class

### ISSUE THREAD

**Issue by NotSqrt** [cannatag/ldap3#157]
Hi,

The call to ``self.server.tls = Tls()`` does not take options, that's too bad !

A setup à-la-python-requests would be nice:
* ``verify=False`` -> no verification
* ``verify=True`` -> standard verification (``ssl.CERT_REQUIRED``)
* ``verify=filename`` -> verification against a given public key certificate (useful for self-signed certificates)
* ...

Thanks !

**Comment by cannatag** [comment]
You can create the tls object with all the options needed to establish a secure tls connection. Have a look at the documentation at http://ldap3.readthedocs.org/ssltls.html
and let me know if you need anything more.

Bye,
Giovanni

**Comment by NotSqrt** [comment]
oh, I missed this ..
I guess I expected a more direct approach, but this is more flexible.

Thanks,
