### ISSUE TITLE
Oracle Unified Directory server: attributes are missing

### ISSUE THREAD

**Issue by kellerkind** [cannatag/ldap3#158]
When performing a search against a user with ldapsearch I can retrieve attributes like 'mail', 'telephoneNumber', ....

	$ ldapsearch -x '(&(uid=user001)(objectClass=shadowAccount))' -a never

	#
	# LDAPv3
	# base <o=com> (default) with scope subtree
	# filter: (&(uid=user001)(objectClass=shadowAccount))
	# requesting: ALL
	#

	# user001, People, example, com
	dn: uid=user001,ou=People,ou=example,o=com
	sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAAEAMjexamplewAAAIEAio99MXXdD+qZpmsovxPtlgyo
	 lUJ9bxqpbRWITiWmmbUQj5Aun+G/9GSJ/nHGrB22IzkUhn9aFtmpw6zZUsxfmKy7jymh1CdrIQv2x
	 bHkx5OpP9h0rgjSUkKrwL/brnjbe+7BeEO8WSBZFKQi7NOn3cYJRxeoTs434cazAjUy1Bk= exter
	 n.hans.mustermann@example.de issuer=/DC=com/DC=com/DC=examplePKI/CN=example-CA-OTH
	 R-08 serial=16F8B0
	uid: user001
	businessCategory:
	loginShell: /bin/bash
	objectclass: person
	objectclass: SolarisUserAttr
	objectclass: inetOrgPerson
	objectclass: ldapPublicKey
	objectclass: posixAccountNISExtension
	objectclass: shadowAccount
	objectclass: posixAccount
	objectclass: top
	givenName: hans
	cn: mustermann, hans
	telephoneNumber: 123-123-123-123
	sn: mustermann
	gecos: Mr. hans mustermann,,,
	homeDirectory: /home/user001
	l: niswob
	uidNumber: 49774
	mail: extern.hans.mustermann@example.de
	gidNumber: 49774

	# search result
	search: 2
	result: 0 Success

	# numResponses: 2
	# numEntries: 1

When performing the same search with ldap3 these attributes are missing in output, also when defining ALL_ATTRIBUTES or specific of these attributes and also when performing a bind connection.

	server = Server('oracleunifieddir1.example.com', port=636, use_ssl=True, get_info=ALL)

	user_conn.search(search_base = 'ou=People,ou=example,o=com',
	     search_filter = '(uid=user001)',
	     search_scope = LEVEL,
	     attributes = ALL_ATTRIBUTES,
	     paged_size = 5
	     )

	for e in user_conn.entries:
	    print(e.entry_to_ldif())

	version: 1
	dn: uid=user001,ou=People,ou=example,o=com
	objectclass: inetOrgPerson
	objectclass: top
	objectclass: posixAccountNISExtension
	objectclass: person
	objectclass: posixAccount
	objectclass: shadowAccount
	loginShell: /bin/bash
	gidNumber: 49774
	uidNumber: 49774
	l: niswob
	cn: Mr. hans mustermann
	sn: user001
	gecos: Mr. hans mustermann,,,
	homeDirectory: /home/user001
	uid: user001
	userPassword: ******
	# total number of entries: 1

**Comment by kellerkind** [comment]
[oracle-unified-directory.txt](https://github.com/cannatag/ldap3/files/189484/oracle-unified-directory.txt)

**Comment by cannatag** [comment]
Hi, are you performing the search locally on the same server? 

Also are you accessing with the same user? Anonymous ACL could be different from bound user.

Could you send me a trace with the 'EXTENDED' level of the ldap3 operation? Have a look at the docs on ldap3.readthedocs.org. No sensitive data saved in the log.

Bye,
Giovanni

**Comment by kellerkind** [comment]
In both cases running search only remote. The ldap3 search is bound to the user the search is performed for. Attached log of the extended search using [this](http://www.zytrax.com/books/ldap/ape/core-schema.html#mail) OID. I'd recreate the log if I have missed st in the last step.

Rgds,
Gunnar

**Comment by kellerkind** [comment]
[ldap3.txt](https://github.com/cannatag/ldap3/files/191048/ldap3.txt)

**Comment by cannatag** [comment]
I see you are performing many bind operations. There is a reason for that?

I expect to find only one bind and one search request in the log. Can you send me your source code? Also can you use the fast_decoder=False parameter in the connection object? It gives better log details.

Thanks,
Giovanni

**Comment by kellerkind** [comment]
Hi,
i got the example code from [here](https://github.com/ensky/taiga-contrib-ldap-auth/blob/master/taiga_contrib_ldap_auth/connector.py) where 
the use case is to first search the dn of the object either by uid (later by email address) using anonymous bind. The later bind is for authentication.

**Comment by kellerkind** [comment]
Another Log attached created with this code:
	server = Server('ldapserver.example.com', port=636, use_ssl=True, get_info=ALL)
	user_conn = Connection(server,
		        client_strategy=STRATEGY_SYNC,
		        auto_bind=True,
		        authentication = AUTH_ANONYMOUS,
		        raise_exceptions=False,
		        check_names = True,
		        lazy = False,
		        fast_decoder=False)

	result = user_conn.extended('0.9.2342.19200300.100.1.3', 'mail')

	print(result)
	quit()
[ldap3.txt](https://github.com/cannatag/ldap3/files/191696/ldap3.txt)

**Comment by cannatag** [comment]
Hi,
This code is malformed, the extend operation is not valid. 

Please try something as:

server = Server('ldapserver.example.com', port=636, use_ssl=True)
user_conn = Connection(server,
client_strategy=STRATEGY_SYNC,
auto_bind=True,
authentication = AUTH_ANONYMOUS,
raise_exceptions=False,
check_names = True,
lazy = False,
fast_decoder=False)

result = user_conn.search(<your search goes here>) 
 print(user_conn.entries)
Let me know if this works.

Bye,
Giovanni

**Comment by kellerkind** [comment]
Log created with the code above + the extended operation with the OID. Let me know if this is the correct way.

    result = user_conn.extended('0.9.2342.19200300.100.1.3', 'mail')

Rgds,
Gunnar

[ldap3.txt](https://github.com/cannatag/ldap3/files/193162/ldap3.txt)

**Comment by cannatag** [comment]
Hi Gunnar,
That extended operation is not valid: your server respond with "There is no extended operation handler registered with the Directory Server for handling extended operations with a request OID of 0.9.2342.19200300.100.1.3"

In fact that OID doesn't identify any extended operation, but it's used to specify the email address syntax. What is your intended purpose with that extended operation?

Giovanni

**Comment by kellerkind** [comment]
Hi Giovanni,
hm, I think i missinterpreted your comment to perform a log with EXTENDED loglevel. That's why I put the extended search at the end of my snippet. 

> Could you send me a trace with the 'EXTENDED' level of the ldap3 operation? 

My assumption was that defining the OID in the function would make the mail attribute visible. Sorry for the confusion!

**Comment by cannatag** [comment]
Sorry for not being clear!

Anyway I don't see anything wrong in the log, you are performing an anonymous bind and the search returns the following attributes:

<< messageID=2<< protocolOp=ProtocolOp: << searchResEntry=SearchResultEntry: << object=b'uid=user001,ou=People,ou=example,o=com' << attributes=PartialAttributeList: << PartialAttribute: << type=b'objectclass' << vals=Vals: << b'inetOrgPerson' b'top' b'posixAccountNISExtension' b'person' b'posixAccount' b'shadowAccount' << PartialAttribute: << type=b'uid' << vals=Vals: << b'user001' << PartialAttribute: << type=b'cn' << vals=Vals: << b'Mr. Gunnar Thielebein' << PartialAttribute: << type=b'loginShell' << vals=Vals: << b'/bin/bash' << PartialAttribute: << type=b'sn' << vals=Vals: << b'user001' << PartialAttribute: << type=b'gecos' << vals=Vals: << b'Mr. Gunnar Thielebein,K-SIO/D2,,' << PartialAttribute: << type=b'homeDirectory' << vals=Vals: << b'/home/user001' << PartialAttribute: << type=b'l' << vals=Vals: << b'niswob' << PartialAttribute: << type=b'uidNumber' << vals=Vals: << b'49774' << PartialAttribute: << type=b'gidNumber' << vals=Vals: << b'49774'
Are  you sure that in the same condition (same client and server, anonymous bind, request for all attributes) you get more attributes?
If this is true I can think of only one reason for that but I have to send you a patch of the search module of the ldap3 library to test with.

Giovanni

**Comment by kellerkind** [comment]
Your last question was making me check the config again. Damn, my mistake. The server configured in /etc/openldap/ldap.conf is another then the one I want to perform the search. Seems the servers are configured differently. I'll get in contact with my local ldap admin. Thx for your time. Ldap3 works fine!

**Comment by cannatag** [comment]
Good!
Let me know if you need more support. Thanks for using the ldap3 library.

Bye.
Giovanni
