### ISSUE TITLE
Newbie question: How to retrieve an entry directly

### ISSUE THREAD

**Issue by seyhbold** [cannatag/ldap3#16]
Hi, 

I have a DN and want to get the data for this object. I could not figure how to to this with ldap3.

Thank you very much
Regards
Ludwig

**Comment by cannatag** [comment]
Hello Ludwig, you need to perform a search operation with the BASE scope. Try the following:

from ldap3 import Server, Connection, BASE, ALL
server = Server('<your_server>', get_info=ALL)
connection = Connection(server, '<your_user>', '<your_password>')
connection.bind()
connection.search(search_base='<dn_object>', search_filter='(objectclass=*)', search_scope=BASE, attributes=['list','of','needed','attributes'])

You should find the search response in the connection.responses[0] and a simpler representation of it in connection.entries[0].

Let me know if this helps you.

Bye,
Giovanni

**Comment by seyhbold** [comment]
Great, this did the trick.

Thank you very much
Regards Ludwig
