### ISSUE TITLE
document getting the list of supported attributed for a class

### ISSUE THREAD

**Issue by ssbarnea** [cannatag/ldap3#17]
I tried to look inside the documentation but it wasn't clear on how someone can get a list of supported attributes for a certain LDAP class.

I want to get a list of attributes for the person class. Thanks.

**Comment by cannatag** [comment]
HI Sorin,
just read the schema info:

    from ldap3 import Server, Connection, SCHEMA
    s = Server('your_server', get_info=SCHEMA)
    c = Connection(s, user='your_user', password='your_password')
    c.bind()
    print(s.schema.object_classes['Person'])

you can find the mandatory attributes in the must_contain attribute of the objectclass and the optional attributes in the may_contain attribute.

Bye,
Giovanni
