### ISSUE TITLE
ldap3.core.exceptions.LDAPStartTLSError: wrap socket error: cafile, capath and cadata cannot be all omitted

### ISSUE THREAD

**Issue by DelboyJay** [cannatag/ldap3#173]
Since upgrading to the latest ldap3 V1.2.2 I can no longer authenticate with my LDAP server and an exception is thrown (see below for full stack trace). I am using LDAPConn which sits on top of your library so the issue could be there but wanted to check with you first for your thoughts.

NOTE: Everything starts working again as normal If I revert only the ldap3 library to 1.1.2 or 1.0.3.

I have the following packages installed in my virtual environment:
```
>>>pip3 freeze
blinker==1.4
dominate==2.2.0
Flask==0.10.1
Flask-Bootstrap==3.3.5.7
Flask-HTTPAuth==3.1.2
Flask-LDAPConn==0.6.12
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-PageDown==0.2.1
Flask-Script==2.0.5
Flask-SQLAlchemy==2.1
Flask-SSLify==0.1.5
Flask-Testing==0.4.2
Flask-WTF==0.12
itsdangerous==0.24
Jinja2==2.8
jira==1.0.3
ldap3==1.2.2
MarkupSafe==0.23
oauthlib==1.1.1
p4python==2015.2.1348262
pyasn1==0.1.9
pyodbc==3.0.10
requests==2.10.0
requests-oauthlib==0.6.1
requests-toolbelt==0.6.0
six==1.10.0
SQLAlchemy==1.0.12
tlslite==0.4.9
visitor==0.1.2
Werkzeug==0.11.9
WTForms==2.1
```
The exception is raised when I execute the following command where ldap is an LDAPConn object.

`retval = ldap.authenticate(form.data["username"], form.data["password"], 'samaccountname', base_dn, search_filter)`

Here is the stack trace that is generated with the exception.

```
ERROR:app:wrap socket error: cafile, capath and cadata cannot be all omitted
Traceback (most recent call last):
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\venv\engwebserver\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:/Scripts/Licenses\app\auth\views.py", line 44, in login
    base_dn, search_filter)
  File "D:\venv\engwebserver\lib\site-packages\flask_ldapconn\__init__.py", line 152, in authenticate
    self.connection.search(base_dn, user_filter, search_scope,
  File "D:\venv\engwebserver\lib\site-packages\flask_ldapconn\__init__.py", line 119, in connection
    current_app.config['LDAP_SECRET']
  File "D:\venv\engwebserver\lib\site-packages\flask_ldapconn\__init__.py", line 96, in connect
    read_only=current_app.config['LDAP_READ_ONLY'],
  File "D:\venv\engwebserver\lib\site-packages\ldap3\core\connection.py", line 294, in __init__
    self.start_tls(read_server_info=False)
  File "D:\venv\engwebserver\lib\site-packages\ldap3\core\connection.py", line 1022, in start_tls
    if self.server.tls.start_tls(self) and self.strategy.sync:  # for async connections _start_tls is run by the strategy
  File "D:\venv\engwebserver\lib\site-packages\ldap3\core\tls.py", line 236, in start_tls
    return self._start_tls(connection)
  File "D:\venv\engwebserver\lib\site-packages\ldap3\core\tls.py", line 251, in _start_tls
    raise start_tls_exception_factory(LDAPStartTLSError, exc)(connection.last_error)
ldap3.core.exceptions.LDAPStartTLSError: wrap socket error: cafile, capath and cadata cannot be all omitted
```

*** EDIT *** - I've seen this problem with python 3.4.4

**Comment by cannatag** [comment]
Hi, which version of python are you using? The message is raised by the underlying ssl python implementation when trying to verify the ssl certificate configuration.

Anyway you should avoid this exception modifying the ldap3/core/tls.py in your site-packages directory adding the "if" statement at line 171 and indenting the next line:
```
            else:  # code from create_default_context in the Python standard library 3.5.1, creates a ssl context with the specificd protocol version
                ssl_context = ssl.SSLContext(self.version)
                if self.ca_certs_file or self.ca_certs_path or self.ca_certs_data:
                    ssl_context.load_verify_locations(self.ca_certs_file, self.ca_certs_path, self.ca_certs_data)
```

let me know if this solves your problem.

Bye,
Giovanni

**Comment by DelboyJay** [comment]
Hi Giovanni,

Sorry, totally forgot to mention that important piece of information!  I've seen this problem with python 3.4.4. I'll try it as is with Python 3.5.1 on Monday and also with the code fix you have specified and get back to you.

Thanks for having a look at this for me.
Cheers,
Del

**Comment by DelboyJay** [comment]
Hi Giovanni,

I can confirm that I get the same error message for python 3.5 and LDAP3 V1.2.2. However LDAP3 V1.1.2 works as expected with python 3.5

I have also applied the fix to core/tls.py for ldap3 V1.2.2 as suggested and run it with python 3.4 and 3.5 but they both raise the same but a different error than before.

`ERROR:app:('wrap socket error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:600)',)
Traceback (most recent call last):
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\venv\engwebserver\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\venv\engwebserver\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:/Scripts/Licenses\app\auth\views.py", line 41, in login
    base_dn, search_filter)
  File "D:\venv\engwebserver\lib\site-packages\flask_ldapconn\__init__.py", line 152, in authenticate
    self.connection.search(base_dn, user_filter, search_scope,
  File "D:\venv\engwebserver\lib\site-packages\flask_ldapconn\__init__.py", line 119, in connection
    current_app.config['LDAP_SECRET']
  File "D:\venv\engwebserver\lib\site-packages\flask_ldapconn\__init__.py", line 96, in connect
    read_only=current_app.config['LDAP_READ_ONLY'],
  File "D:\venv\engwebserver\lib\site-packages\ldap3\core\connection.py", line 294, in __init__
    self.start_tls(read_server_info=False)
  File "D:\venv\engwebserver\lib\site-packages\ldap3\core\connection.py", line 1022, in start_tls
    if self.server.tls.start_tls(self) and self.strategy.sync:  # for async connections _start_tls is run by the strategy
  File "D:\venv\engwebserver\lib\site-packages\ldap3\core\tls.py", line 237, in start_tls
    return self._start_tls(connection)
  File "D:\venv\engwebserver\lib\site-packages\ldap3\core\tls.py", line 252, in _start_tls
    raise start_tls_exception_factory(LDAPStartTLSError, exc)(connection.last_error)
ldap3.core.exceptions.LDAPStartTLSError: ('wrap socket error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:600)',)`

**Comment by cannatag** [comment]
I cannot replicate this. Are you sure your ldap server accepts ssl?

**Comment by DelboyJay** [comment]
According to my IT department SSL and TLS are supported but obviously I could still be doing something wrong in my code. 

I did check the connection with Microsoft's ldp.exe to make sure that SSL is supported and it connects properly showing this in the log:
`Host supports SSL, SSL cipher strength = 256 bits`

For clarity ldp.exe is also happy with port 389 if I do not tick the SSL box.

I have been using TLS on port 389, which I have since found to be incorrect and I should have been using port 636 but Flask-LDAPConn 0.6.12 and ldap3 1.1.2 seems to work with that as I can authenticate with my AD server which is very strange???

I have since tried port 636 with SSL V3 and TLS 1.2 set in the flask-LDAPConn config and again I can authenticate through Flask-LDAPConn with ldap3 1.1.2 but as soon as I switch ldap3 back to V1.2.2 regardless of the port number used 389 or 636 I get the following:

Using TLS yields this error:
`ldap3.core.exceptions.LDAPSocketReceiveError: error receiving data: [WinError 10054] An existing connection was forcibly closed by the remote host`

Using SSL yields this error:
`ldap3.core.exceptions.LDAPSocketOpenError: socket ssl wrapping error: cafile, capath and cadata cannot be all omitted`

Again I'm not using ldap3 directly but via the Flask-LDAPConn package so it could be that they need to move forward and incorporate your latest code changes? Obviously the problem could still be with myself but I am using the example code off of Flask-LDAPConn pypi page which is working for ldap3 V1.1.2 hence the confusion.

I'll try and come up with a minimal code example that simulates the problem to see if you are then able to recreate it.

Thanks,
Del

**Comment by cannatag** [comment]
you can start a clear connection on port 389 then issue a start_tls() operation to "wrap" the socket in an ssl connection, so you can have a secure connection even on 389.

You should try to use the ldap3 library to connect just to see if the problem is in Flask-LDAPConn. Please try from the command line:
```
from ldap3 import Server, Connection
# clear connection
my_server = 'real_server_name'
my_user = 'real_user_name'
my_password = 'real_user_password'
s0 = Server(my_server)
c0 = Connection(s0, my_user, my_password)
c0.bind()
print(c0.result)
#
# start_tls connection over the clear port connection
c1 = Connection(s0, my_user, my_password)
c1.open()
c1.start_tls()
c1.bind()
print(c1.result)
#
# ssl port connection
s2 = Server(my_server, use_ssl=True)
c2 = Connection(s2, my_user', my_password)
c2.bind()
print(c2.result)
```
If you get an exception or a result different from 'success' it could help to understand where the problem is.

If you want to try NTLM authentication instead of standard just use the authentication='NTLM' parameter in the connection object. You should also provide a Tls() object with the ssl configuration if you have the correct public key of the target server. Then use tls=Tls(...) while defining the s2 server object.


let me know the results of your tests.

Bye,
Giovanni

**Comment by bersace** [comment]
Hi,

Thanks @cannatag  for the details.

I'm hitting some issue on LDAP3 usage with SSL/TLS. I set up a local openldap container with TLS and self-signed certificate. I checked this with `ldapsearch` and it works \o/ . However, I can't get it the right way with LDAP3. Your help is welcome :) Here are some details 

```
$ export | grep LDAP
declare -x LDAPTIMEOUT="1"
declare -x LDAPURI="ldaps://ldap.ldap2pg.docker:636"
$ cat ldaprc
BINDDN  cn=admin,dc=ldap,dc=ldap2pg,dc=docker
BASE    dc=ldap,dc=ldap2pg,dc=docker
TLS_REQCERT allow
$ ldapsearch -xv -w $LDAPPASSWORD '(objectClass=groupofNames)' dn
ldap_initialize( <DEFAULT> )
filter: (objectClass=groupofNames)
requesting: dn
...

# numResponses: 4
# numEntries: 3
$ docker-compose logs --tail=15 ldap
Attaching to ldap2pg_ldap_1
ldap_1      | 5965c6cb conn=1093 fd=16 ACCEPT from IP=172.22.0.1:60118 (IP=0.0.0.0:636)
ldap_1      | 5965c6cb conn=1093 fd=16 TLS established tls_ssf=256 ssf=256
ldap_1      | 5965c6cb conn=1093 op=0 BIND dn="cn=admin,dc=ldap,dc=ldap2pg,dc=docker" method=128
ldap_1      | 5965c6cb conn=1093 op=0 BIND dn="cn=admin,dc=ldap,dc=ldap2pg,dc=docker" mech=SIMPLE ssf=0
ldap_1      | 5965c6cb conn=1093 op=0 RESULT tag=97 err=0 text=
ldap_1      | 5965c6cb conn=1093 op=1 SRCH base="dc=ldap,dc=ldap2pg,dc=docker" scope=2 deref=0 filter="(objectClass=groupOfNames)"
ldap_1      | 5965c6cb conn=1093 op=1 SRCH attr=dn
ldap_1      | 5965c6cb conn=1093 op=1 SEARCH RESULT tag=101 err=0 nentries=3 text=
ldap_1      | 5965c6cb conn=1093 op=2 UNBIND
ldap_1      | 5965c6cb conn=1093 fd=16 closed
$
```

But this fails : :(:

``` python
def connect():
    options = dict(
        URI='ldaps://ldap.ldap2pg.docker:636',
        HOST=None,
        PORT=None,
        BINDDN='cn=admin,dc=ldap,dc=ldap2pg,dc=docker',
        PASSWORD='communication',
        TIMEOUT=5,
        TLS_REQCERT=ssl.CERT_NONE,
    )
    host = options['URI'] or options['HOST']
    logger.debug("Connecting to LDAP server %s.", host)

    tls = ldap3.Tls(validate=options['TLS_REQCERT'])
    server = ldap3.Server(
        host=host, port=options['PORT'],
        connect_timeout=options['TIMEOUT'],
        tls=tls,
    )
    conn = ldap3.Connection(server, options['BINDDN'], options['PASSWORD'])
    conn.open()
    conn.bind()
    logger.debug("Connected %s.", conn.result)
    return conn
```

And the output is:

``` console
$ python -V
Python 3.5.3
$ ldap2pg -v
[ldap2pg.ldap        DEBUG] Connecting to LDAP server ldaps://ldap.ldap2pg.docker:636.
[ldap2pg.script   CRITICAL] Failed to connect to LDAP: (LDAPSocketOpenError('socket ssl wrapping error: [SSL: WRONG_CURVE] wrong curve (_ssl.c:720)',),)
$ docker-compose logs --tail=10 ldap
Attaching to ldap2pg_ldap_1
...
ldap_1      | 5965c98d conn=1099 fd=16 ACCEPT from IP=172.22.0.1:60150 (IP=0.0.0.0:636)
ldap_1      | TLS: can't accept: A TLS fatal alert has been received..
ldap_1      | 5965c98d conn=1099 fd=16 closed (TLS negotiation failure)
$
```

@cannatag Do you have a clue ?

Anyway, thanks for ldap3. A pythonic LDAP client library with py2 and py3 support is very valuable ! Kudo !

**Comment by bersace** [comment]
@cannatag I hit the same error with `ldap3-cli`:

``` console
$ python ldap3cli.py -h ldap.ldap2pg.docker -p 636 -s -u cn=admin,dc=ldap,dc=ldap2pg,dc=docker -w communication info
Error: unable to connect to ldap.ldap2pg.docker on port 636 - reason: ('socket ssl wrapping error: [SSL: WRONG_CURVE] wrong curve (_ssl.c:720)',)
```

**Comment by bersace** [comment]
This looks like an error in the container or in openldap.

``` python
    addr = socket.getaddrinfo(options['HOST'], options['PORT'])[0][4][0]
    logger.debug("addr=%s", addr)
    sock = socket.socket()
    sock.connect((addr, options['PORT']))
    sock = ssl.wrap_socket(sock, cert_reqs=ssl.CERT_NONE)
```

This code works with `google.com:443` but fails with container. I continue to investigate.

**Comment by cannatag** [comment]
Probably your server is using an old cipher for TLS. Maybe you have to configure your server.

Bye,
Giovanni

**Comment by maludwig** [comment]
To everyone having this issue, I'm on Mac OSX, connecting to our Windows Domain Controller. I was using the IP address of our server, I also tried the specific domain controller FQDN. I wasn't supposed to do either of those. Just use the domain itself. So if you're: maludwig@github.com, and your domain controller is, "dc01-03.github.com" with an IP of "10.0.1.13", then forget about the IP and the hostname, just use the domain "github.com", ex:

```
    server = Server("github.com", use_ssl=True, get_info=ALL)
    conn = Connection(server, user="github.com/maludwig", password="ULTASECUREPASSWORD", authentication=NTLM)
    conn.bind()
    print(conn.extend.standard.who_am_i())
    print(conn)
```

**Comment by raphaeldavidf** [comment]
> To everyone having this issue, I'm on Mac OSX, connecting to our Windows Domain Controller. I was using the IP address of our server, I also tried the specific domain controller FQDN. I wasn't supposed to do either of those. Just use the domain itself. So if you're: [maludwig@github.com](mailto:maludwig@github.com), and your domain controller is, "dc01-03.github.com" with an IP of "10.0.1.13", then forget about the IP and the hostname, just use the domain "github.com", ex:
> 
> ```
>     server = Server("github.com", use_ssl=True, get_info=ALL)
>     conn = Connection(server, user="github.com/maludwig", password="ULTASECUREPASSWORD", authentication=NTLM)
>     conn.bind()
>     print(conn.extend.standard.who_am_i())
>     print(conn)
> ```

Thanks maludwig, that worked for me trying to connect to a Windows DC from a windows machine

**Comment by amitch50** [comment]
I had the similar issue with a self signed certificate, how I fixed it is, I just re-generated the certificate with Base64-Encoded (initially which was DER-encoded-binary). Dont know the reason for it; but it worked for me.
