### ISSUE TITLE
connection switch silently to anonymous bind if password is empty, failing auth

### ISSUE THREAD

**Issue by brianmay** [cannatag/ldap3#174]
Hello,

This bug was reported against the Debian package [here](http://bugs.debian.org/823488):

When creating a connection with the Connection object the code defaults to 
AUTH_ANONYMOUS (doing so an anonymus bind) also when _only_ the password
is empty (not, as said by documentation, when both user and password are 
empty). 

These the lines of /usr/lib/python3/dist-packages/ldap3/core/connection.py
where the problem is:

```python
self.user = user
self.password = password
if self.user and self.password and not authentication:
    self.authentication = AUTH_SIMPLE
elif not authentication:
    self.authentication = AUTH_ANONYMOUS
elif authentication in [AUTH_SIMPLE, AUTH_ANONYMOUS, AUTH_SASL]:
    self.authentication = authentication
else:
    self.last_error = 'unknown authentication method'
    raise LDAPUnknownAuthenticationMethodError(self.last_error)
```

If password is empty, according to default of None for authentication, the 
first if fails and then is selected the second elif.

That means that you will get a valid object with anonymous bind, 
the user presence will be simply ignored but, and so when you use 
object also to check autentication, looking if you get a connection 
(as it should be), you will got authentication for every user just 
giving an empty password.

That's plain wrong, contrary to what is said in the documentation here:

http://ldap3.readthedocs.io/connections.html

and very dangerous (the more plain way to use the library will bring people 
to enable empty password access for any user).

**Comment by cannatag** [comment]
Hi Brian,
this behaviour has changed in version 1.0.3. Before I was strict following the LDAP3 standard that allows this kind of bind and call it  "unauthenticated authentication mechanism". The same RFC states that this is insicure and should be disabled on the client or on the server. It was probably intended in the standard for testing and logging purpose.


Documentation on readthedocs refers to the last released version, so it states that this behaviour is not allowed.

Please upgrade the Debian package accordingly. Current version is 1.2.2 and I'm about to release 1.3.0, probably in the next week.

**Comment by brianmay** [comment]
Oh, sorry, hadn't noticed the bug report was against the old version in Debian Jessie. Debian unstable does have the latest version. Will close this issue.
