### ISSUE TITLE
My LDAP server connection gets disconnected every 5 minutes. How to automatically reconnect?

### ISSUE THREAD

**Issue by yugansh20** [cannatag/ldap3#181]

**Comment by cannatag** [comment]
Hi, 
Try the RESTARTABLE connection strategy.
Just import RESTARTABLE from ldap3 and set client_strategy=RESTARTABLE while defining the Connection object.

This connection strategy will try to reconnect if the connection is lost. 

Let me know if this fix your problem.

Bye,
Giovanni

**Comment by yugansh20** [comment]
I will u[date you after testing this.

**Comment by yugansh20** [comment]
Thanks a lot.  It is working..
