### ISSUE TITLE
adminCount Active Directory

### ISSUE THREAD

**Issue by PAFsec** [cannatag/ldap3#183]
Hello,

I was playing around with the ldap3 python package. Thank you a lot, it is awesome!!

I am facing one problem and I really don't understand where it is comming from.. LDAP Active directory seems to create a LDAP attribute called "adminCount" on specific users. (it is posible to visualize it via ldap tools)

Although, when retrieving all the information of my user, this field (among others) are not retrieved (even in the "other" object that is suppose to hold non RFC 4511 compliant attributes..)
The search through that attribute doesn't retrieve anything as well:

```
server = ldap3.Server(host="ad.local", get_info=ldap3.ALL)
connection = ldap3.Connection(server, user, pw, auto_bind=True)
connection.ldap_search(search_base"DC=.., DC=fr", search_filter="(adminCount=1)", search_scope=ldap3.SUBTREE, attributes=ldap3.ALL_ATTRIBUTES)
print(connection.entries)
```
Do you have any idea where it could come from?

Thank you in advance.

**Comment by cannatag** [comment]
Hi, have you tried to explicitly request the attribute with ``attributes=['adminCount']`` in the search operation? Also you could include ``get_operational_attributes=True`` in the search to request all auto-generated attributes of an object. Obviously the user you're using for connecting must have sufficient privileges to read that attribute.

**Comment by PAFsec** [comment]
Hello,

Yes, I tried by explicitly requesting the attribute and nothing was returned. Adding the operational attribute did not do the trick either.
The user I am playing aroud with, is the Domain Admin of the Active Directory so he should have sufficient privileges to read this attribute.

Do you have other ideas?

**Comment by cannatag** [comment]
Hi,
I've tried on a test AD domain eith the Administrator user and had no problem in getting all the user with the adminCount attribute: 
```
from ldap3 import Server, Connection
s = Server('my_ad_server)
c = Connection(s, 'CN=Administrator,CN=Users,DC=FOREST,DC=LAB', 'password') 
c.bind()
c.search('dc=forest,dc=lab', '(adminCount=*)', attributes=['adminCount'])
print(c.entries)
```

gives me back:

```
[DN: CN=Administrator,CN=Users,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Administrators,CN=Builtin,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Print Operators,CN=Builtin,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Backup Operators,CN=Builtin,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Replicator,CN=Builtin,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=krbtgt,CN=Users,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Controller di dominio,CN=Users,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Schema Admins,CN=Users,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Enterprise Admins,CN=Users,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Domain Admins,CN=Users,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Server Operators,CN=Builtin,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Account Operators,CN=Builtin,DC=FOREST,DC=LAB
    adminCount: 1
, DN: CN=Controller di dominio di sola lettura,CN=Users,DC=FOREST,DC=LAB
    adminCount: 1
```

so it should work as expected.

Let me know if you are still experiencing this issue.

Bye,
Giovanni
