### ISSUE TITLE
Typo in server.py, line #530 when using IP_V4_PREFERRED mode (for version 1.3.1)

### ISSUE THREAD

**Issue by eva8668** [cannatag/ldap3#185]
There may be a typo in server.py line #530 when using IP_V4_PREFERRED mode:

`candidates += [address for address in addresses if address[0] == socket.AF_INET6 and (addresses[5] or address[5] is None)]`

I think that `addresses[5]` should be `address[5]`. Otherwise, an IndexError may occur when using IP_V4_PREFERRED mode in the network in which both IPv4 and IPv6 exists.

**Comment by cannatag** [comment]
You're right. I will fix it in the next release of ldap3.

Thanks a lot,
Giovanni

**Comment by cannatag** [comment]
fixed in 1.3.3
