### ISSUE TITLE
check_escape wrong works with bytes-like objects

### ISSUE THREAD

**Issue by Anjuta** [cannatag/ldap3#186]
Hello. This looks like a bug:

https://github.com/cannatag/ldap3/blob/master/ldap3/utils/conv.py#L85

If a function will come a bytes-like object, there is an error: "TypeError: a bytes-like object is required, not 'str'".

**Comment by cannatag** [comment]
Thanks, I inverted the sequence of conditions in the if. Now it's working. bytes type are returned unchanged now. 

I will release it in the next version of ldap3.

Bye,
Giovanni

**Comment by cannatag** [comment]
released in 1.3.3
