### ISSUE TITLE
Getting an entry by DN?

### ISSUE THREAD

**Issue by BonkaBonka** [cannatag/ldap3#187]
I'm generating some reports from LDAP and have a list of DNs that I need to look up to pull additional information.  Short of decomposing the DN myself and using a search, I can't find a way to fetch an entry by DN.  What am I missing?

**Comment by cannatag** [comment]
Hi, you must perform a BASE search. This means that you provide the dn as searc_base and a generic filter like (objectclass=*)  as search_filter. This actually read the dn object without performing any search.

for example:

from ldap3 import Server, Connection, BASE, ALL_ATTRIBUTES
dn = 'cn=object,dc=abc,dc=com'
s = Server('my_server')
c = Connection(s, user='username', password='password')
c.search(search_base = dn,
         search_filter = '(objectClass=*',
         search_scope = BASE,
         attributes = ALL_ATTRIBUTES)

print(c.entries)

**Comment by BonkaBonka** [comment]
Aha, that cured my issue!  Thanks!
