### ISSUE TITLE
Modify object class

### ISSUE THREAD

**Issue by Dharmik8478** [cannatag/ldap3#189]
How can i add or remove object classes of entry?

**Comment by cannatag** [comment]
Hi,
there are 3 type of object class in ldap, abstract, structural and auxiliary. An entry can have only one structural object class and many auxiliary classes. The classes specify what attributes can be stored in the entry. The structural object class is defined at entry creation time and cannot be changed. Auxiliary object classes can be added at creation or later and can be removed. Usually you have to delete all the attributes related to the auxiliary class before removing it. Abstract classes are automatically added to the entry and follow the class hierarchy. They cannot be manually removed.

So you can add or remove only auxiliary classes using the standard modify() operation.
