### ISSUE TITLE
Example for SASL DIGEST-MD5

### ISSUE THREAD

**Issue by cornelinux** [cannatag/ldap3#19]
Is there an example for using the SASL credentials with creating the connection?
This does not work for me:

    c = Connection(s,
               auto_bind = False,
               client_strategy = SYNC,
               sasl_mechanism="DIGEST-MD5",
               sasl_credentials=('cn=mydn,dc=organization,'mypassword'),
               authentication=SASL,
               check_names=True)
    c.open()
    r = c.bind()
    c.unbind()

r will always be False.

**Comment by cannatag** [comment]
HI,
you should get the error description in c.result. Can you print it out after the bind()

Thanks,
Giovanni

**Comment by cornelinux** [comment]
Hm, something am I missing here?
c.bind() returns false and c.result is None.

I was doing a bit debugging.
in connection.bind() it calls

    response = self.do_sasl_bind(controls)

with controls==None. controls None feels not right?

OK, i debugged into sasl_digest_md5. Obivously my sasl_credentials are wrong.
It expecst a tuple or four:

    not len(connection.sasl_credentials) == 4:

being (realm, user, password, authorization_id)

If I choose some arbitrary values for realm and auth_id I get c.result:

    {'dn': '', 'saslCreds': 'None', 'referrals': None, 'description': 'invalidCredentials', \
     'result': 49, 'message': 'SASL(-13): authentication failure: realm changed: authentication aborted',  \
     'type': 'bindResponse'}

I thought! the realm should be the FQDN of the requesting host a.k.a. the client.
Only when I change the realm to be the FQDN of the server i get:

     {'dn': '', 'saslCreds': 'None', 'referrals': None, 'description': 'invalidCredentials', \
      'result': 49, 'message': 'SASL(-13): user not found: no secret in database', \
      'type': 'bindResponse'}

Interesting. 
Hm, user not found. A simple bind find the user by its DN...

Thanks for your help. I am going on investigating...
Thanks
Cornelius

**Comment by cornelinux** [comment]
OK, I understand. 
My openldap does not contain the plain text passwords to handle DIGEST-MD5 and the Active Directory does not support DIGEST-MD5. It runs SASL NTLM (or GSSAPI...)

**Comment by mdewall** [comment]
Hi - I was searching for a solution to this "authentication failure: realm changed" message and just wanted to correct the comment.  AD does support DIGEST-MD5.  You can run ldp.exe (one of the semi-builtin apps from MS) and when you do a bind you'll get an option of "Advanced: Digest" and it works if you go directly to a server and not a VIP on a load balancer.  The default without specifying DIGEST-MD5 (which requires the client have the pw on hand) is GSS-SPNEGO from what I recall.  I'm having trouble getting DIGEST-MD5 to pass through my OpenLDAP proxy to AD, but AD (2008R2 at least) directly with MD5 certainly works with a few tools I've tried.  Good luck!  :)  My OpenLDAP server seems to be unhappy about which realm is being passed to it.

**Comment by cannatag** [comment]
HI mdewall. thanks for the correction. i developed also NTLMv2 authentication to AD. You can use it with the authentication = ldap3.NTML argument in the Connection definition.

Giovanni

**Comment by mdewall** [comment]
Hi cannatag - nice.  I'll give it a shot.
