### ISSUE TITLE
ldap3 with gssapi on Windows

### ISSUE THREAD

**Issue by keithhendry** [cannatag/ldap3#190]
After failing to get gssapi compiled on Windows I decided to patch kerberos.py to use pykerberos. This allows me to drop in winkerberos and everything works great on windows. Is there any way we can make the SASL mechanisms more pluggable or support using the pykerberos library instead? I am happy to submit a pull request if so.

**Comment by cannatag** [comment]
Hi Keith, I'd be happy to see your pull request. I have no direct experience with kerberos on Windows, so it would be greatly appreciated!

Thanks,
Giovanni

**Comment by moalexmonk** [comment]
@keithhendry: Any update on this? It would be really helpful for https://stackoverflow.com/questions/32710365/how-to-install-gssapi-python-module-on-windows

**Comment by keithhendry** [comment]
Sorry, I left my previous company where I was working on this. Essentially I remember creating a slightly modified ldap3kerberos https://github.com/Morgan-Stanley/treadmill/blob/master/lib/python/treadmill/ldap3kerberos.py which works with WinKerberos https://pypi.org/project/winkerberos/. I then monkey patched them in at runtime.
