### ISSUE TITLE
LDAPInvalidCredentialsResult exception not thrown when connecting to server in MOCK_SYNC mode

### ISSUE THREAD

**Issue by nocturnaltortoise** [cannatag/ldap3#199]
I'm trying to test login, and normally connection.bind() throws an exception if the credentials (username, password) entered are invalid. When using connection_strategy=MOCK_SYNC though, no exception is thrown when I use invalid credentials and attempt to bind. Is there a way I can turn on such exceptions, or another way I can test binding with invalid credentials?

**Comment by cannatag** [comment]
Are you using raise_exceptions=True in the connection object? The MOCK_SYNC strategy still doesn't honor it. I will add that functionality soon. In the meanwhile you can check the return value of the bind() method to check if it is successful.

**Comment by cannatag** [comment]
HI, please check code in dev. It should work now.

**Comment by cannatag** [comment]
released in 1.4.0
