### ISSUE TITLE
Timeout does not appear to be honored

### ISSUE THREAD

**Issue by kjwilcox** [cannatag/ldap3#208]
I recently observed some code using ldap3 lasting well beyond the configured timeout.

```
server = ldap3.Server(LDAP_URL, connect_timeout=10)
connection = ldap3.Connection(server, username, password, auto_bind=True)
success = connection.search(
  search_base,
  search_filter,
  attributes=ldap3.ALL_ATTRIBUTES,
  search_scope=search_scope,
  time_limit=10
) 
```

Looking at the ldap3 source seemed to indicate that the receive_timeout on the connection object would be set to whatever the server had, so changing that didn't affect anything in my testing.

But when I introduced severe network latency, I saw this code running for 40+ seconds before succeeding.

It would be nice to be able to reason about the upper limit on how long this code could be running for. So this is either a bug report (if timeouts are maybe not working correctly), or a feature request for a time limit when connecting. Please let me know, and I can try to produce a more complete repro if this is a bug.

**Comment by cannatag** [comment]
Hi, there are two kind of timeout in ldap3. The ``connect_timeout `` defined in the Server object, honored when the tcp connection is being established and the ``receive_timeout`` defined in the Connection object that set the socket in non-blocking mode and wait for the specified number of seconds before raising an exception. I'm not sure if both works on every OS. Can you give me information about your system?

Thanks,
Giovanni

**Comment by kjwilcox** [comment]
Running Ubuntu 14.04 on Python 2.7.6

I seemed to be able to replicate this behavior both when setting just a connect_timeout, and also when setting both a connect_timeout and receive_timeout.

**Comment by cannatag** [comment]
I'll try to replicate in lab. So you have the problem either when establish a connection either when performing an operation. In both cases the timeout are not honoured?

**Comment by kjwilcox** [comment]
The part that appeared to not be honoring the timeout was the creation of the `ldap3.Connection`.

I had the connect timeout set to 10s, and was introducing 5s of network latency (to try to simulate a misbehaving LDAP server we were dealing with recently).

Thank you for taking a look at this!

**Comment by kjwilcox** [comment]
Any luck repro-ing this?

**Comment by cannatag** [comment]
HI,
I've created a little script to test connect and receive timeouts and it works as expected in windows and ubuntu. The difference is that in ubuntu the receive timeout is set to 0 by default and this means infinite. I think you should use the ``receive_timeout`` parameter to set the timeout to a reasonable value.

If you want to check your system you can use the script changing the SERVER variable to your test server. You can find the script in the ldap3 directory in dev repository or attached to this message as a zip file.

Let me know the results, the script create a test_connection_ldap3.txt log file with the results. 


[testTimeouts.zip](https://github.com/cannatag/ldap3/files/423715/testTimeouts.zip)


Bye,
Giovanni

**Comment by kjwilcox** [comment]
Thank you for looking into this. I was able to come up with a concise repro that I think demonstrates an issue with receive_timeout.

By running the following command in a terminal (using Ubuntu for this example), you can simulate an ldap server that allows you to connect, but is non-responsive and will not send any bytes over the open connection.
```
netcat -l -p 636
```

When running the following code, it will hang forever despite the receive timeout being set.
```
server = Server('ldaps://localhost:636', connect_timeout=5)  # This succeeds
connection = Connection(server, receive_timeout=5)  # This hangs forever
```

I would expect the receive timeout to kick in and raise an exception, but it does not. Is this something you would expect the receive timeout to handle gracefully?

**Comment by cannatag** [comment]
When that code is supposed to hang? Defining Server() and Connection() doesn't try to connect to the ldap server. The first operation that is tried by the library is connection.open(). In this case is the connect_timeout that should be honored.

Anyway this should happens with ldaps only. I've just tested your code (with a connection.open()) and it hangs while waiting for the tls handshake. I'm not sure I can set a timeout in this condition.

Giovanni

**Comment by cannatag** [comment]
I've found the problem. The connect_timeout were used to establish the connection, but when the socket is "wrapped" in tls the socket is detached and connected again. In this case the connect_timeout were not applied. 

I've fixed it in dev. Can you try it and see if it works for you?

Thanks for your debugging effort.

Giovanni

**Comment by kjwilcox** [comment]
I tried it out and it works exactly as expected. Thank you for your responsiveness on this issue and for fixing it!

Any idea when 1.5.0 will get a PyPI release? I am eager to make use of this.

**Comment by cannatag** [comment]
I'm working on the abstraction layer to make it write-capable. Hope to release 1.5 next week.

Thanks for testing.
Giovanni

**Comment by kjwilcox** [comment]
Great, thank you!
