### ISSUE TITLE
ldap3.SEQUENCE_TYPES is used to check for iterables

### ISSUE THREAD

**Issue by cfelder** [cannatag/ldap3#211]
It seems that ``ldap3.SEQUENCE_TYPES`` is used to check for iterables. If this is correct I would prefer to check for iterables using ``isinstance(<iterable>, collections.Iterable)``. This would also cover ``set`` which are not sequences but also iterable. Otherwise I would like to change at least the code in the ``add`` method of ``Connection`` class which includes the following code::

    parm_object_class = list(object_class) if isinstance(object_class, SEQUENCE_TYPES) else [object_class]

I would change the is instancecheck to ``isinstance(object_class, SEQUENCE_TYPES + (set,))`` because I expect each object class appears only once which corresponds to a ``set``.

At the moment passing ``object_class`` of type ``set`` results in ``[set(...)]``.

**Comment by cannatag** [comment]
added "set" to SEQUENCE_TYPES. 
Can't use Iterable instead of SEQUENCE_TYPES because Iterable includes str and bytes that must not be considered sequence in ldap3.

**Comment by cfelder** [comment]
Thanks. I just recognized that you accidentally imported ``Iterable`` from ``collections`` but do not use it for good reason as mentioned above. Can you remove the unused import please.

Best
Christian

**Comment by cannatag** [comment]
Sure!

Thanks.
