### ISSUE TITLE
Bind a user over multiple organizational units

### ISSUE THREAD

**Issue by mkermani144** [cannatag/ldap3#214]
Is there an _easy_ way to simple-bind a user over multiple organizational units? That is, instead of giving the `connection` object full `dn` of the user, I provide a parent `ou` and the `ldap3` will search the user in that `ou` (that may contain child `ou`s) and authenticate the user.

**Comment by cannatag** [comment]
Hi,
when binding you must provide a full context, so you cannot provide a "key" to search for in multiple organization.

If you're sure that your names are unique troughtout your LDAP tree you have thre different approach for accomplish what you need:

1. Perform a search (anonymous or with a user that can read all other user names) on the whole tree for the naming attribute and then perform a bind with the dn you've found
2. Perform a search with a user that can read all the other user names and can make a Compare operation on the userPassword attribute) and then perform a compare operation for the attribute userPassword in the dn you've found. (Not sure if this works for Active Directory)
3. If your tree is not deep nested you can try the bind operation with the user and password in all the ou where users are defined.

I'd suggest the first option, but this means that you have to include the admin password (or an equivalent) in your code in case your LDAP server doesn't returns users in an anonymous search.

Let me know if you need some examples.

Bye,
Giovanni
