### ISSUE TITLE
Connect to a serverless implementation (Active Directory)

### ISSUE THREAD

**Issue by ry99** [cannatag/ldap3#220]
I'd like to connect to my organization's Active Directory implementation. They use a "serverless" mode, so the host url is "ldap://rootDSE" Is this possible with ldap3? If so, what is the correct host string to use? I've tried that one and "", but no luck.

**Comment by cannatag** [comment]
In Active Directory when you don't specify a server name it implicitly means that you're connecting to your default domain controller. You should simply add the did name of the server to the host URL as in ldap://myserver.myorg and do not specify the rootDSE that is the server entry where the schema (and other server specific information) is stored.
