### ISSUE TITLE
How to properly use client strategy REUSABLE

### ISSUE THREAD

**Issue by moz54321abc** [cannatag/ldap3#221]
```
def tls():
            tls = Tls(local_private_key_file=LOCAL_PRIVATE_KEY_FILE,
                    local_certificate_file=LOCAL_CERTIFICATE_KEY_FILE,
                    validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1,
                    ca_certs_file=CA_CERTS_FILE)
            return tls

bind = AUTO_BIND_TLS_BEFORE_BIND
server_connection = Server(LDAP_SERVER, PORT, tls=tls(), get_info=ALL)

with Connection(server_connection, 'cn=admin,dc=test,dc=com', 'password',
                            auto_bind=bind, client_strategy=REUSABLE) as conn:
                print(conn)
                pool_counter = conn.search(*args, **kwargs)
                response, result = conn.get_response(pool_counter)
                return {'response': response, 'result': result}
```

print(conn)
`ldap://ldap.test.com:389 - cleartext - user: cn=admin,dc=test,dc=com - not lazy - bound - open - <no socket> - tls not started - not listening - ReusableStrategy - internal decoder`

why is tls not started?
but if I use client strategy SYNC, tls is all started.

I have another operation let's say modify. How to reuse the connection I just opened earlier?
doesn't this `with Connection(server_connection, 'cn=admin,dc=test,dc=com', 'password',
                            auto_bind=bind, client_strategy=REUSABLE) as conn:` create a new connection?

I see client strategy REUSABLE as connection pooling. Is this concept correct? But how to share the same connection through out my application without creating/opening another new connection?

**Comment by cannatag** [comment]
Hi,
The reusable strategy is needed for pooling connections in long standing server applications. Are you sure you need it? It's much easier to use the SYNC or RESTARTABLE strategy.

**Comment by moz54321abc** [comment]
I need to use connection pooling like I use it with database. I'll do a lot of searching and I think open and close connection for each search operation will slows down ldap server. 
I'm thinking something like connect to ldap when authenticating user and use the same connection until the user log out.

**Comment by cannatag** [comment]
You can use the sync connection strategy because you can keep it open without closing the connection. It's the faster way.

Have a look at the tutorial at ldap3.readthedocs.org.

**Comment by link89** [comment]
ldap3.core.exceptions.LDAPSocketSendError occurs when using SYNC strategy after connection idle for a long time, even when I set pool_lifttime=300.

**Comment by cannatag** [comment]
Try to use the RESTARTABLE strategy. It tries to re-establish the
connection if any error occours. You don't need the pool_lifetime parameter
because it is useful only for the REUSABLE strategy.


2016-10-20 13:59 GMT+02:00 link89 <notifications@github.com>:

**Comment by link89** [comment]
@cannatag I will give it a try, thanks~
