### ISSUE TITLE
connect_timeout with sasl gssapi auth not working

### ISSUE THREAD

**Issue by styleex** [cannatag/ldap3#223]
There are code:
          
            servers = [Server(host, get_info=ALL, connect_timeout=5) for host in ldap_hosts]
            pool = ServerPool(servers, pool_strategy=POOLING_STRATEGY_FIRST, active=True, exhaust=True)
            conn = Connection(pool, authentication=AUTH_SASL, sasl_mechanism=GSSAPI,
                                            raise_exceptions=False)
            log.error('before')
            ret = self.connections[domain].bind()
            log.error('after b=%s', ret)

If before start i setup drop all ldap packets with iptables:

    iptables -t filter -A OUTPUT -p tcp --dport 389 -j DROP
    # OR
    iptables -t filter -A OUTPUT -p tcp --dport 389 -j REJECT --reject-with tcp-reset

The program will be locked permanently

**Comment by cannatag** [comment]
Hi Styleex. Thanks for your support. I'm about to release version 2 of ldap3. Will check your issues against that version.

Giovanni

**Comment by cannatag** [comment]
this should be already fixed in version 2.0.3. will be released soon, thanks

**Comment by cannatag** [comment]
Released in 2.0.7.
