### ISSUE TITLE
Can't reestablish connection after conn.bind() failed

### ISSUE THREAD

**Issue by styleex** [cannatag/ldap3#225]
If first conn.bind() is failed, i can't reestablish connection with executing conn.bind() again. 
MVP:

    server = ldap3.Server(server, connect_timeout=5)
    #c = ldap3.Connection(s, authentication=ldap3.SASL, sasl_mechanism=ldap3.GSSAPI)
    conn = ldap3.Connection(server, user='IDECO.RU\\Администратор', password='12dc6912DC69', raise_exceptions=True, authentication=ldap3.NTLM)
    
    # Before start: iptables -t filter -A OUTPUT -p tcp --dport 389 -j DROP
    print("bind1")
    try:
        conn.bind()
    except Exception as e:
        print(e) # raises "unable to open socket"
    
    # Before bind2: iptables -t filter -D OUTPUT -p tcp --dport 389 -j DROP
    print("sleep")
    time.sleep(5)
    
    # Run bind() again
    print("bind2")
    conn.bind()

Second conn.bind() raises exception with traceback:

    Traceback (most recent call last):
      File "test.py", line 25, in <module>
        conn.bind()
      File "/usr/lib/python3.5/dist-packages/ldap3/core/connection.py", line 469, in bind
        self.open(read_server_info=False)
      File "/usr/lib/python3.5/dist-packages/ldap3/strategy/sync.py", line 55, in open
        BaseStrategy.open(self, reset_usage, read_server_info)
      File "/usr/lib/python3.5/dist-packages/ldap3/strategy/base.py", line 142, in open
        raise LDAPSocketOpenError('invalid server address')
    ldap3.core.exceptions.LDAPSocketOpenError: invalid server address

**Comment by styleex** [comment]
I found workaround: before second `conn.bind()` need call `server.check_availability()`

**Comment by cannatag** [comment]
Hi Styleex. Thanks for your support. I'm about to release version 2 of ldap3. Will check your issues against that version.

**Comment by cannatag** [comment]
this should already be fixed in version 2.0.3. Will be released soon. thanks

**Comment by cannatag** [comment]
Released in 2.0.7.
