### ISSUE TITLE
SSLv3 not working on python version with SSL Context

### ISSUE THREAD

**Issue by jgrip** [cannatag/ldap3#23]
I can't get SSLv3 to work on my install. I have an LDAP that for various reasons is not TLS capable, only SSLv3.

Trying:
s = Server('ldaps.oldserver.com', port=636, use_ssl=True)
c = Connection(s, user='test', password='test', auto_bind=True)

Yields:
LDAPSocketOpenError: ('socket ssl wrapping error: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:600)',)

I then tried:
s = Server('ldaps.oldserver.com', port=636, use_ssl=True, tls=Tls(version=ssl.PROTOCOL_SSLv3)
c = Connection(s, user='test', password='test', auto_bind=True)
with the same result.

Reading into the python ssl module documentation (https://docs.python.org/dev/library/ssl.html#context-creation) shows that the default is to have SSLv3 disabled.

I tried adding the workaround in the documentation to the ldap3 code, but it still doesn't work.
In the end, I changed the code where the SSL context is created from using create_default_context to creating an SSLContext with protocol on creating and then adding the settings, though I doubt this is the correct solution.

**Comment by cannatag** [comment]
Are you using python 3.4 or 2.7? I think that constrains are very strict now to avoid vulnerability on the SSL protocol. Could you try the same operation with python 3.3 or python 2.6?

thanks,
Giovanni

**Comment by jgrip** [comment]
I am indeed using python 3.4. I also tried with 2.7 giving the same result.
Testing on earlier python version works as expected.

**Comment by cannatag** [comment]
So this is a matter of local system configuration. Latest versions of python disable the weakest ssl protocols.

Bye,
Giovanni
