### ISSUE TITLE
SEARCH_SCOPE_WHOLE_SUBTREE moved

### ISSUE THREAD

**Issue by jaraco** [cannatag/ldap3#233]
With the 2.0.7 release, it seems that the following fails where it worked before:

```
from ldap3 import SEARCH_SCOPE_WHOLE_SUBTREE
```

I don't see a mention of this in the changelog. Has the feature moved or just the constant?

**Comment by cannatag** [comment]
Hi Jason, I'm version 2 I have removed the older 0.x version constants. I wrote a generic  "ldap3 namespace decluttered" in the changelog, thinking that nobody uses them anymore. I should update the changelog specifying which constants are not present anymore. In your case you can just use 'SUBTREE'.

Is this a problem to you?
I have also mentioned this in the Readme.

Giovanni

**Comment by jaraco** [comment]
With this clarification, no, it should not be a problem. And since 'SUBTREE' is the default, I shouldn't have to pass it at all. I'll just double-check that 'SUBTREE' was the default in our minimum required version and all should be well.

**Comment by jaraco** [comment]
Indeed, we just removed all references to that value, and our tests still pass with less code.

**Comment by cannatag** [comment]
Keep in mind that other default values have been changed. They should not impact the standard use of the library.vif you're accessing AD the auto_range parameter is now set to True by default. This should help when querying members in large groups.
