### ISSUE TITLE
Error passing simple username during connect

### ISSUE THREAD

**Issue by jaraco** [cannatag/ldap3#235]
In the past, we used to be able to connect with `LDAP3Connection(server, user='username', password='pw')`, but with 2.0, the sanitization of the DN fails when a simple username is being passed.

```
_______________________________ ERROR at setup of test_get_humans ________________________________

creds = ('service_user', '########'), server_url = 'ldap://contoso.local'

    @pytest.fixture(scope="module")
    def simple_conn(creds, server_url):
>       return yg.ldap.SimpleConnection(*creds, url=server_url)

yg/ldap/tests/conftest.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
yg/ldap/connections.py:45: in __init__
    self.con = self._get_bound_connection(dn, pw)
yg/ldap/connections.py:58: in _get_bound_connection
    con = LDAP3Connection(self.server, user=dn, password=pw)
/Users/jaraco/Dropbox/code/yg/support/yg.ldap/.eggs/ldap3-2.0.8-py3.6.egg/ldap3/core/connection.py:280: in __init__
    self.user = safe_dn(self.user)
/Users/jaraco/Dropbox/code/yg/support/yg.ldap/.eggs/ldap3-2.0.8-py3.6.egg/ldap3/utils/dn.py:318: in safe_dn
    for component in parse_dn(dn, escape=True):
/Users/jaraco/Dropbox/code/yg/support/yg.ldap/.eggs/ldap3-2.0.8-py3.6.egg/ldap3/utils/dn.py:286: in parse_dn
    if not validate_attribute_type(attribute_type):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

attribute_type = ''

    def validate_attribute_type(attribute_type):
        if not attribute_type:
>           raise LDAPInvalidDnError('attribute type not present')
E           ldap3.core.exceptions.LDAPInvalidDnError: attribute type not present

/Users/jaraco/Dropbox/code/yg/support/yg.ldap/.eggs/ldap3-2.0.8-py3.6.egg/ldap3/utils/dn.py:156: LDAPInvalidDnError
```

Disabling `check_names` works around the issue, but I worry that has broader implications. Is there a way to pass the username without knowing the full distinguished name?

**Comment by cannatag** [comment]
What ldap server are you connecting to? Simple password should always accept a full dn. I probably must relax the sanitation in the bind operation.

**Comment by jaraco** [comment]
It's an Active Directory server. I wonder if perhaps we should be passing `authentication=NTLM`.

**Comment by jaraco** [comment]
I tried NTLM, but that didn't work either - that demands a domain.

> I probably must relax the sanitation in the bind operation.

That's my instinct at this point.

**Comment by cannatag** [comment]
Yes, try the Domain/user username with NTLM as authentication method.

Let me know.

**Comment by cannatag** [comment]
Can't you pass the Domain?

**Comment by jaraco** [comment]
Passing the username with a domain does seem to bypass the issue, although the code to make this work seems a bit crufty:

```
diff -r c5607ced6466 yg/ldap/connections.py
--- a/yg/ldap/connections.py	Fri Oct 28 09:33:33 2016 -0400
+++ b/yg/ldap/connections.py	Fri Oct 28 10:05:47 2016 -0400
@@ -55,7 +55,11 @@
     def _get_bound_connection(self, dn, pw):
         if not pw:
             raise LDAPBindError('Empty password')
-        con = LDAP3Connection(self.server, user=dn, password=pw)
+        params = dict()
+        if '=' not in dn:
+            params['authentication'] = 'NTLM'
+            dn = 'YG\\' + dn
+        con = LDAP3Connection(self.server, user=dn, password=pw, **params)
         con.open()
         if not con.bind():
             description = con.result['description']
```

I'd rather not have to require the domain be specified, and instead rely on the default domain of the server, which was the behavior in 1.0.

**Comment by cannatag** [comment]
I agree. Will remove sanitation of username. Still not sure if for NTLM only or for Simple Bind  too. The RFC states that for Simple Bind the full dn must be used, but some server could have used a simple name as a shortcut.

**Comment by cannatag** [comment]
Please check version 2.0.9. It should have removed the safe_dn() sanitize in the bind and rebind methods. Also I've included the list of dropped constansts in the changelog.

**Comment by jaraco** [comment]
Yes - 2.0.9 is working wonderfully for establishing the connection. Thanks!
