### ISSUE TITLE
filtered lookup no longer matches

### ISSUE THREAD

**Issue by jaraco** [cannatag/ldap3#237]
With ldap3 1.x, our code queries with a filter and it matches, but in 2.0.9, it does not:

```
(Pdb) member_dn
'CN=sg_de_fs_Datenanalyse (beschränkt),OU=OU Filesystem,OU=OU Security Groups,OU=OU Groups,OU=OU Psychonomics,OU=Companies,DC=YOUGOV,DC=local'
(Pdb) from yg.ldap.connections import eb
(Pdb) filter = '(distinguishedName=' + eb(member_dn) + ')'
(Pdb) filter
'(distinguishedName=CN=sg_de_fs_Datenanalyse \\28beschränkt\\29,OU=OU Filesystem,OU=OU Security Groups,OU=OU Groups,OU=OU Psychonomics,OU=Companies,DC=YOUGOV,DC=local)'
(Pdb) root
'OU=OU Filesystem,OU=OU Security Groups,OU=OU Groups,OU=OU Psychonomics,OU=Companies,DC=YOUGOV,DC=local'
(Pdb) self.con.search(root, filter)
False
```

I see a note of "escaped filter by default", so I tried removing the escaping of the filter, but that only results in an exception: `ldap3.core.exceptions.LDAPInvalidFilterError: malformed filter`. I've tried reading the docs and the RFCs, but I'm struggling to find an example of how a filtered search is done in ldap3 2.x. Can you suggest what might have changed or how to fix this search to work with 2.x?

**Comment by jaraco** [comment]
In another tests that does pass, the same code is invoked, but the distinguishedName doesn't have an umlaut nor parentheses in it, so presumably one or both are implicated in this failure to filter.

**Comment by jaraco** [comment]
The `eb` used there is defined thus:

```
def eb(query):
    """
    Escape characters in a query according to RFC4515
    ‘*’ -> ‘\\2A’, ‘(‘ -> ‘\\28’, ‘)’ -> ‘\\29’, ‘\’ -> ‘\\5C’, chr(0) -> ‘\\00’
    """
    return (
        query
            .replace('\\', '\\5C')
            .replace('(', '\\28')
            .replace(')', '\\29')
            .replace('*', '\\2A')
            .replace('\x00', '\\00')
    )
```

**Comment by jaraco** [comment]
If I had to guess, the issue lies in how the non-ascii characters are (not) being escaped:

```
(Pdb) from ldap3.utils.conv import escape_filter_chars 
(Pdb) escape_filter_chars(member_dn)
'CN=sg_de_fs_Datenanalyse \\28beschr\\c3\\a4nkt\\29,OU=OU Filesystem,OU=OU Security Groups,OU=OU Groups,OU=OU Psychonomics,OU=Companies,DC=YOUGOV,DC=local'
```

**Comment by jaraco** [comment]
Okay, using `escape_filter_chars` in place of our own `eb` seems to address the issue, so we'll use that instead. Still, this does feel a little bit like a regression and deviation from the expectation I get by [reading the docs](http://ldap3.readthedocs.io/searches.html?highlight=filter#the-ldap-filter).

**Comment by cannatag** [comment]
You're right, ldap3 now tries to use the default encoding of your platform to convert attribute values to unicode. You must use
escape_filter_chars() to escape the filter assertions and it applies your encoding.

I

**Comment by cannatag** [comment]
I will activate the auto_escape feature in version 2.1. I still have to do some testing.

**Comment by cannatag** [comment]
2.1.0 released
