### ISSUE TITLE
escape_filter_chars chokes on Unicode (Python 2)

### ISSUE THREAD

**Issue by jaraco** [cannatag/ldap3#239]
Consider this:

```
$ python2.7 -c "import ldap3.utils.conv; ldap3.utils.conv.escape_filter_chars(u'foo')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-s4G1m_/ldap3/utils/conv.py", line 71, in escape_filter_chars
    text = to_unicode(text, encoding)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-s4G1m_/ldap3/utils/conv.py", line 49, in to_unicode
    raise UnicodeError("Unable to convert to unicode %r" % obj)
UnicodeError: Unable to convert to unicode u'foo'
```

Since we're now relying on `escape_filter_chars` to process all of our filters, this causes broad failures when running our test suite on Python 2. Since the function passes through Unicode text on Python 3, it probably should do the same on Python 2.

**Comment by cannatag** [comment]
I already fixed in 2.1, where I've added a auto_escape option. Still needs more testing. Hope to release it soon.
Thanks

**Comment by cannatag** [comment]
pls check code in dev. it should work now.

**Comment by jaraco** [comment]
Yes, that does work. Thanks.

I look forward to the release.

**Comment by jaraco** [comment]
I did find that with the dev branch, another test starts failing, apparently due to the other change (default client strategy), as we had a test that would disconnect and then assert that a search failed. Explicitly passing SYNC restores the prior expectation.

**Comment by cannatag** [comment]
This implicitly means that the RESTARTABLE connection strategy works right?

**Comment by jaraco** [comment]
Yes, that appears to be the case. I plan to port our code to use RESTARTABLE once I understand the implications better.

**Comment by cannatag** [comment]
2.1.0 released.
