### ISSUE TITLE
Attribute returned as a list instead of a string when searching against mocked LDAP server

### ISSUE THREAD

**Issue by mprahl** [cannatag/ldap3#240]
Hello,
I am writing unit tests for my code that uses ldap3 on Python 2.7, but when querying for attributes that should be strings, I am getting back a list with just one string. It seems that the `raw_attributes` are being returned instead of the `attributes`.

I am mocking an Active Directory instance with:
```
mock_server = ldap3.Server('ldaps://server.domain.local:636', get_info=ldap3.OFFLINE_AD_2012_R2)
mock_ldap_connection = ldap3.Connection(
    mock_server, client_strategy=ldap3.MOCK_SYNC, authentication=ldap3.SIMPLE)
ldap_entries = path.join(path.abspath(path.dirname(__file__)), 'ad_ldap_directory.json')
mock_ldap_connection.strategy.entries_from_json(ldap_entries)
mock_ldap_connection.open()
mock_ldap_connection.user = 'CN=Test User,OU=PostMaster,DC=postmaster,DC=local'
mock_ldap_connection.password = 'P@ssW0rd'
mock_ldap_connection.bind()
```
Here is the JSON file that I'm using (I added the userPassword attributes for authentication to work):
http://pastebin.com/6nui0XDd

I then search with the following:
```
mock_ldap_connection.search('DC=postmaster,DC=local', '(distinguishedName=CN=Test User,OU=PostMaster,DC=postmaster,DC=local)', attributes=['sAMAccountName'])
username = mock_ldap_connection.response[0]['attributes']['sAMAccountName']
```

I expect `username` to be equal to `'testUser'` as this is how it is returned when querying Active Directory, but instead `username` is equal to  `['testUser']` instead.

Thank you for your help and writing ldap3.

Edit: 
After looking through the code, only the "raw" attributes are passed to the `add_entry` function:
https://github.com/cannatag/ldap3/blob/80a9bef0c0ce1a48ffa50eadf2bd9ae1f5c64acf/ldap3/strategy/mockBase.py#L125

**Comment by jaraco** [comment]
I suspect this is due to how ldap3 now uses the server schema to determine how to transform the various elements. My guess is your mock LDAP server doesn't implement the schema, so what you get for attributes aren't _exactly_ the same as the raw attributes, but probably text-decoded versions of the raw attributes, e.g. `raw_attributes={'username': ['testUser']}` but `attributes={'username': [u'testUser']}` (or just `'testUser'` on Python 3).

It's quite likely that we'll encounter this issue as well once we update our API service to use the latest ldap3, as our API service also uses a mock LDAP server for its tests.

**Comment by mprahl** [comment]
@jaraco I was passing in the `get_info=ldap3.OFFLINE_AD_2012_R2` flag hoping that would provide the appropriate schema to the mock LDAP server. Perhaps I can try saving the schema of a real server to a file, and loading it to see if that helps, but ultimately, I'd like to avoid this.

**Comment by cannatag** [comment]
this should definitively work as mprahl stated. will check as soon as possibile.

**Comment by cannatag** [comment]
Check code in dev. It should work now. Schema was erroneously removed during bind.

**Comment by mprahl** [comment]
@cannatag thank you. Your changes fixed it.

Any chance you will release a new version of ldap3 with this fix soon?

**Comment by cannatag** [comment]
2.1.0 released now
