### ISSUE TITLE
Multiple results returned on Mock LDAP server when they shouldn't be (dev branch)

### ISSUE THREAD

**Issue by mprahl** [cannatag/ldap3#245]
Hello,
On the latest dev branch, when I use the search filter `'(sAMAccountName=testUser)'` on the mock LDAP server, I am getting results back for any user that has 'testUser' in their sAMAccountName, instead of just the one.

Thank you for your help.

**Comment by cannatag** [comment]
fixed. check code in dev.

thanks.

**Comment by mprahl** [comment]
@cannatag thank you.
