### ISSUE TITLE
Proper user DN and password raises LDAPInvalidCredentialsResult

### ISSUE THREAD

**Issue by monkut** [cannatag/ldap3#25]
using python 3.4.0 with ldap3 '0.9.7.4'. 

The following code raises LDAPInvalidCredentialsResult when proper user DN and password are used. 

```python
from ldap3 import Server, Connection, AUTH_SIMPLE, STRATEGY_SYNC, ALL
s = Server(HOST, port=389, get_info=ALL)
c = Connection(s, authentication=AUTH_SIMPLE, user=user_dn, password=PASSWORD, check_names=True, lazy=False, client_strategy=STRATEGY_SYNC, raise_exceptions=True)
c.open()
c.bind()
```

However, within the exception, 'description': 'success' seems to point to the fact that the user bind is successful, since when the password is given as incorrect, this 'success' message does *not* appear in the returned exception.

Correct password exception example:
```python
ldap3.core.exceptions.LDAPInvalidCredentialsResult: LDAPInvalidCredentialsResult - 49 - invalidCredentials - [{'dn': '', 'message': '', 'type': 'bindResponse', 'result': 0, 'saslCreds': 'None', 'description': 'success', 'referrals': None}]
```

See the below link for more details:
http://stackoverflow.com/questions/28575359/how-to-bind-authenticate-a-user-with-ldap3-in-python3/28616485?noredirect=1#comment45568301_28616485

Not sure how to query for the remote ldap server info.   I tried the following, but it didn't seem to give me much:

$ ldapsearch -LLL -h host -b "" -s base -D "DNstuff" -W "(objectclass=*)" vendorversion objectClass isGlobalCatalogReady vendorname
Enter LDAP Password:
dn:
objectClass: top
objectClass: OpenLDAProotDSE

**Comment by cannatag** [comment]
Hi, 
probably your server is not returning any info. Can you try the same without the get_info parameter?

**Comment by monkut** [comment]
Hmmm... I tried once using `s = Server(host)` without setting `get_info=ALL`, and the bind went through successfully.

However, when I tried again rebuilding the server and connection including `get_info=ALL`, I got an 'LDAPUnavailableResult' result.  After that result, I reset the server and connection to be instantiated without `get_info=ALL`, and I got the previously seen, `LDAPInvalidCredentialsResult` with the `description: success` text.

It would seem the ldap server I'm trying to work with may be a bit unstable.

**Comment by cannatag** [comment]
What kind of server are you connecting to? It's publicy available?
It seems that it doesn't return DSA info or schema Info, but I don't understand why you get the invalidcredential with the success message. Are you able to capture a trace of the connection between the client and the server? You can use tcpdump or wireshark.

Thanks,
Giovanni

**Comment by monkut** [comment]
It's a company internal sever.  I don't have details about it, just the host information.  I suspect it's some kind of windows enterprise server.  If I can find the time I'll try to get the wireshark dump.

**Comment by cannatag** [comment]
Hi can you try the version in dev with the new logging system? It could help you to find the problem. If you get the 0.9.8.4 version from dev you can set the detail level to NETWORK_EXTENDED and get the content of each ldap message.

Bye,
Giovanni

**Comment by szborows** [comment]
I'm having similar trouble with our corporate LDAP server. With python-ldap it was working like a charm. Any ideas what could be the cause of this?

**Comment by szborows** [comment]
I used EXTENDED logging and this is what I see:

    <<{'controls': None,
    << 'messageID': 9,
    << 'payload': [(0, False, 10, 49),
    <<             (0, False, 4, b''),
    <<             (0,
    <<              False,
    <<              4,
    <<              b'80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1\x00')]
<< 'protocolOp': 1}`

**Comment by cannatag** [comment]
Hi Slawomir,
Can you please send me a whole logging if the bind operation with fast_decoder=False in the connection object? It gives a better logging, sensitive data are stripped. 

Bye, 
Giovanni

**Comment by makimat** [comment]
I very likely reproduced the same issue with version `ldap3==2.3` from pypi.

With a certain LDAP server, there's an issue that for certain users it returns two responses to a single bind request. First response is "success", second is "invalidCredentials. I reproduced the same behavior with this server using both `ldapsearch` utility and the ldap3 library. The difference is that ldapsearch considers this a successful binding and can execute LDAP search commands after binding. ldap3 library thinks it's unsuccessful and refuses to continue.

Unfortunately I don't know details of the LDAP server in question but will post here later if I can somehow find out the vendor, product name, and version.

Here are the requests and responses as logged by ldap3 with EXTENDED logging and fast_decoder=False:

```
LDAPMessage:
 messageID=8
 protocolOp=ProtocolOp:
  bindRequest=BindRequest:
   version=3
   name=uid=myuser,ou=People,ou=SOMETHING,o=ELSE
   authentication=AuthenticationChoice:
    simple=<stripped N characters of sensitive data>
  controls=Controls:

LDAPMessage:
 messageID=8
 protocolOp=ProtocolOp:
  bindRequest=BindResponse:
   resultCode=success
   matchedDN=
   diagnosticMessage=
   referral=Referral:
   serverSaslCreds=<stripped 10 characters of sensitive data>
  controls=Controls:

LDAPMessage:
 messageID=8
 protocolOp=ProtocolOp:
  bindRequest=BindResponse:
   resultCode=’invalidCredentials’
   matchedDN=
   diagnosticMessage=
   referral=Referral:
   serverSaslCreds=<stripped 10 characters of sensitive data>
  controls=Controls:
```

Here are requests and responses captured with tcpdump on `ldapsearch`

```
(real end user):

4	0.000846	222.222.222.222	111.111.111.111	LDAP	129	bindRequest(1) "uid=myuser,ou=People,ou=SOMETHING,o=ELSE" simple
6	0.097554	111.111.111.111	222.222.222.222	LDAP	80	bindResponse(1) success 
8	0.097595	111.111.111.111	222.222.222.222	LDAP	80	bindResponse(1) invalidCredentials

("service" account)

22	29.809932	222.222.222.222	111.111.111.111	LDAP	129	bindRequest(1) "cn=serviceuser,ou=SystemUsers,o=ELSE" simple 
24	29.813218	111.111.111.111	222.222.222.222	LDAP	80	bindResponse(1) success
```

For reference, I also tried end user binding with intentionally wrong password and it returned only one response, "invalidCredentials".

Is there any way that I can configure ldap3 to treat the binding in this case as a success, like ldapsearch does? I'm even fine with monkeypatching.
