### ISSUE TITLE
AttributeError is raised if no stdin is present

### ISSUE THREAD

**Issue by osemenovsky** [cannatag/ldap3#250]
When running script using ldap3 lib without a tty, an AttributeError exception is raised

**Comment by cannatag** [comment]
Updated in dev. Can you check it? Thanks

**Comment by cannatag** [comment]
will be released in 2.1.1

**Comment by cannatag** [comment]
Released in 2.1.1

**Comment by osemenovsky** [comment]
Awesome, thanks
