### ISSUE TITLE
paged search olcSizeLimit

### ISSUE THREAD

**Issue by reimarstier** [cannatag/ldap3#26]
I think i found an issue within the PagedSearch.py
Line 67: cookie = result['controls']['1.2.840.113556.1.4.319']['value']['cookie']

Suppose the openldap server has a result limit (olcSizeLimit) of 500 and the client requests a query which yields more than 500 results. This will raise an KeyError on the given line. This is probably due to the fact that the server cleared the cookie when the client hit the hard limit of 500 results. Can this be handled some how on the client side? 

Thanks a lot btw for a great library :-)

**Comment by cannatag** [comment]
please try to modify line 67 in PagedSearch.py with:

        try:
            cookie = result['controls']['1.2.840.113556.1.4.319']['value']['cookie']
        except KeyError:
            cookie = None

tell me if this fix the problem. If it's a working solution I will include in the next release of ldap3.

Thanks,
Giovanni

**Comment by reimarstier** [comment]
yes. this works :-)

**Comment by cannatag** [comment]
Thanks, I will include it in the next release.

Bye,
Giovanni
