### ISSUE TITLE
timeout does not work in 2.1.0

### ISSUE THREAD

**Issue by cornelinux** [cannatag/ldap3#260]
Again I have issues with the timeout. 

I am checking with a python virtualenv running ldap3==2.1.0.
I am running your test script from #208 on Ubuntu 16.04LTS.

I am connecting to an AD DC 2012R2 on port 389.
When the system is up, everything is fine.

     Please ensure server is REACHABLE, then press Enter

But when I simply shut down the domain controller. the test 

    Please make server UNAVAILABLE, then press Enter

hangs. 

# Working

Interesting enough it works with version 2.0.9!

I tested this, since the ldap3 which I am using in my project did not return after the timeout in the first place.

**Comment by cannatag** [comment]
Hi, I switched to RESTARTABLE strategy in 2.1.0, so it tries to recover
from the timeout for a few times before giving up. I understand this adds
too much "magic" as default so I'm reverting to SYNC strategy in version
2.1.1. With 2.1.0 you can set client_strategy=SYNC in the Connection object.



2016-11-17 8:37 GMT+01:00 Cornelius Kölbel <notifications@github.com>:

**Comment by cornelinux** [comment]
Hi, thanks for the quick answer. Great, after adding client_strategy=SYNC to "Connection" is works again with 2.1.0.

**Comment by cornelinux** [comment]
Hi, one last question. 
It works ok with the single server, now.
But when I put the server in a server pool:

     p = ServerPool(s, ROUND_ROBIN, active=True, exhaust=True)

And connect with the serverpool

     c = Connection(p, receive_timeout=receive_timeout, client_strategy=SYNC)

It again hangs.
Is there a way to timeout the serverpool?

**Comment by cannatag** [comment]
Must check. You mean that if you have more than one server in the pool and
the connection is not working it doesn't raise any exception? Does it work
the same if only one server is in the pool?

2016-11-17 9:16 GMT+01:00 Cornelius Kölbel <notifications@github.com>:

**Comment by cornelinux** [comment]
No, I have only one server in the pool. This server is down. And the timeout is not used. It hangs.
( I have not checked with two servers)

If I connect with the single server (not the pool) the timeout is honored.

I am using a pool, since the application allows to enter several servers - or only one server.
And for simplicity I do not care about how many servers are in the pool.

**Comment by cornelinux** [comment]
OK, I just confirmed this with two 2012R2 DCs.

Using a Pool with **two** LDAP servers, strategy ROUND_ROBIN and **one** (the first mentioned) being down, gets me the results after timeout. Obviously the code waits for the first one (down) -> timeout and finds the second one.

But in case of the pooling with only **one** server if looks like if it fails after timeout and tries the next server in the pool (which is the only first one).

So there might be a logic missing, what happens if **all** servers in the pool are down.

I shut down **both** servers in the pool and I receive **no** timeout. 

-> pooltimeout is missing?

**Comment by cannatag** [comment]
Please try to se active=2 while defining the pool. Its default it's True
that means "check forever",.If you specify a number it is used as the
number of loop to try for. Each loop tests all the available server. If you
set exhaust=10 (or another number of seconds) it means that an irresponsive
server will be kept out from the pool for that number of seconds. The
POOLING_LOOP_TIMEOUT is the sleep time (in seconds) in each pool cycle.

I know the argument naming is very poor... I'm sorry for that. Will fix in
a next release.

2016-11-17 11:01 GMT+01:00 Cornelius Kölbel <notifications@github.com>:

**Comment by cornelinux** [comment]
WOW! This is so cool! I was not aware of this flexibility. Thanks a lot.

Is there anything I can contribute? 
Maybe some code example or documentation?

Thanks a lot for this module and for your help!

**Comment by cannatag** [comment]
Thanks!

**Comment by cannatag** [comment]
Please just check if everything work as intended! Let me know if you find anything wrong.

Have fun,
Giovanni

**Comment by cornelinux** [comment]
version >= 2.0.7 runs well. With pool and timeout.
With one server up in pool or two servers up in pool.
both servers down in pool raise a timeout exception in the reasonable time. Looks good.

I had some trouble making my code run with ldap3==1.0.2 and ldap3==2.0.7. But I it is fine, now.
The code needs to run with both major versions, sind debian comes with ldap3 1.x

**Comment by Ruby0510** [comment]
Hi,
there is only one ldap server added my server_pool and it was down.
I set the active=2 to ServerPool and pass receive_timeout=5 to Connection. I only get the exception:
ldap3.core.exceptions.LDAPServerPoolExhaustedError: no active server available in server pool after maximum number of tries
not an obviously timeout exeption. And actually I can get the above exhausted exception  without any timeout arguments. 

So anyone can help here: where I am wrong to get reasonable timeout exception ?

thanks!
