### ISSUE TITLE
connection.extend.microsoft.modify_password issue

### ISSUE THREAD

**Issue by florck** [cannatag/ldap3#264]
Hi,
I get an issue with latest version of ldap3 (same code was working one month ago).

When I want to do 

```python
conn.extend.microsoft.modify_password(ad_dn, new_password=newpwd, old_password=oldpwd)
```

I get now
```
 ldap3.core.exceptions.LDAPConstraintViolationResult: LDAPConstraintViolationResult - 19 - constraintViolation - None - 0000216C: AtrErr: DSID-03190FB3, #1:
         0: 0000216C: DSID-03190FB3, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)
  - modifyResponse - None
```
Whatever the case and even if I respect the configured AD policy. Error is strictly the same if I provide a false old password.

I have searched lot of things without success for the moment. If you get any idea about the troubleshooting, I would be very happy.

Thank you

**Comment by cannatag** [comment]
Does it work with the older (1.4.0) version?

2016-11-28 18:10 GMT+01:00 florck <notifications@github.com>:

**Comment by florck** [comment]
hum...

I deinstalled ldap3, installed it in version 1.4.0, it worked.

I deinstalled ldap3 again, installed it in latest, it worked whereas it was not yesterday...

I have changed nothing. Maybe I was not in the very latest version of the package, my single clue.
Anyway, I think we can close, sorry for this.
