### ISSUE TITLE
Retrieve a list of all attributes in ldap3 

### ISSUE THREAD

**Issue by gitstercode** [cannatag/ldap3#266]
Server is not returning same number of attributes for python-ldap and ldap3 Libraries.

The missing attributes are the one that I have to perform some operations.

This is the sample of the search query I used for ldap3:
```
from ldap3 import Server,Connection,ALL_ATTRIBUTES, ALL_OPERATIONAL_ATTRIBUTES,ALL,SEARCH_SCOPE_WHOLE_SUBTREE,SUBTREE

host = something1
user = something2
password = something3
baseDn = something4
search_filter = "(uid=something5)"

server = Server(host, get_info=ALL)
conn = Connection(server,user, password,auto_bind=True,check_names=True)
conn.search(baseDn,search_filter, search_scope=SEARCH_SCOPE_WHOLE_SUBTREE, attributes=['*'])

entry = conn.entries
print(json.loads(entry[0].entry_to_json()))
```

Search query used with python-ldap:
```
  searchScope = ldap.SCOPE_SUBTREE
  ## retrieve all attributes - again adjust to your needs - see documentation for more options
  retrieveAttributes = None
  ldap_result_id = l.search(baseDn, searchScope, searchFilter, retrieveAttributes)
  result_set = []
  while 1:
        result_type, result_data = l.result(ldap_result_id, 0)
        if (result_data == []):
            break
        else:
            ## here you don't have to append to a list
            ## you could do whatever you want with the individual entry
            ## The appending to list is just for illustration.
            if result_type == ldap.RES_SEARCH_ENTRY:
                result_set.append(result_data)

  print json.loads(result_set)
```
If someone can post, is there any way to retrieve all the attributes that are available for given query in ldap3.

**Comment by cannatag** [comment]
Are you sure that the user has the rights to read the missing attributes?

**Comment by gitstercode** [comment]
Thanks for responding.


yes, because the same attribute can be viewed using python-ldap for the same user.


________________________________

**Comment by cannatag** [comment]
Please can you provide the ldap code and the lsap3 code?

**Comment by gitstercode** [comment]
It's been updated in the question section. Please let me know if I have to update anything else.

On Dec 2, 2016 8:18 AM, Giovanni Cannata <notifications@github.com> wrote:
Please can you provide the ldap code and the lsap3 code?

**Comment by cannatag** [comment]
I read it on stackoveflow. Are you sure the parameters (base filter, ... ) are the same?
If so please update to the latest version of ldap3 (2.1.1) and try the following code:

```
from ldap3 import Server, Connection

s = Server('my_server')
c = Connection(s, 'my_user', 'my_password')
c.bind()
print(c.result)
c.search('my_base', 'my_filter', attributes=['*'])
print(c.result)
print(c.response)
c.unbind()
```
Obviuosly you must substitute all the my_* variable with your real values.

Can you give me the output of the code?

Thanks
Giovanni

**Comment by gitstercode** [comment]
Its on the latest ldap3(2.1.1)
Here is the output

```
>>> s = Server(param.get('host'))
>>> c = Connection(s, param.get('user'), param.get('password'))
>>> c.bind()
True
>>> print("1st", c.result)
1st {'result': 0, 'description': 'success', 'message': '', 'saslCreds': None, 'referrals': None, 'dn': '', 'type': 'bindResponse'}
>>> c.search(param.get('baseDn'), my_filter , attributes=['*'])
True
>>> print("2nd", c.result)
2nd {'result': 0, 'description': 'success', 'message': '', 'referrals': None, 'dn': '', 'type': 'searchResDone'}
>>> print("3rd", c.response)
3rd [{'attributes': {'uid': ....................
```

**Comment by cannatag** [comment]
So you get back some responses. What is the missing attribute? Have you tried to query it explicitly with attributes=['my_attribute']? If it's an operational attribute you can request all of them with '+' in the attribute list.

**Comment by gitstercode** [comment]
```
>>> c.search(param.get('baseDn'), my_filter , attributes=['mailDeliveryOption'])
True
>>> print("2nd", c.result)
2nd {'result': 0, 'description': 'success', 'message': '', 'referrals': None, 'dn': '', 'type': 'searchResDone'}
>>> print("3rd", c.response)
3rd [{'attributes': {'mailDeliveryOption': []}, 'dn': 'uid=myuid,ou=people,o=domain.com,o=email', 'raw_attributes': {'mailDeliveryOption': []}, 'type': 'searchResEntry'}]
```
I got an empty list returned for mailDeliveryOption.
But it is suppose to be (from python-ldap):
 `"mailDeliveryOption": ["mailbox"]`

I am not sure that changes should I have to make in the search query to fill the list, instead of getting an empty list.

**Comment by cannatag** [comment]
There is no apparent reason for this behaivour in the client code. What version of LDAP server are you connecting to? It seems that the server acts differently. Are you able to send me a capture of the session with tcpdump? I need both (python-ldap and ldap3) to compare and check for differences in the protocol. 

To use tcpdump in linux:

```
tcpdump -s 0 -w my_file.cap host x.x.x.x 
```

In Windows just use the wireshark GUI to do the same.

You can send me all the capture, at least II need the bind, and the search packets to understand what's going on.

**Comment by cannatag** [comment]
no response from user

**Comment by ahalyarekha** [comment]
Hi, I have a similar issue I can see the group members name and I'd but couldn't find there email address. Do I need any permission to get the AD group member email address? When I try to query with attribute =[`mail`] I get empty list. Does the AD group members doesn't have email address set or I don't have permission to access them?
