### ISSUE TITLE
response_to_ldif creates false LDIF

### ISSUE THREAD

**Issue by m7four** [cannatag/ldap3#267]
I have made my search query with "conn.response_to_ldif()" as LDIF. Doing so, I realized that there is no empty line among the "LDAP entries". An import via ActiveDirectoryStudio or parsing with LdiParser (python-ldap) ends with error.

I found out that the function in rfc2849.py "search_response_to_ldif" inserts a line, but this line is removed by the function "operation_to_ldif".

Removing line "if line:" at the end of the function "operation_to_ldif" brought the desired result.

**Comment by cannatag** [comment]
fixed in 2.1.2. still in dev. Can you test it?

Thanks,
Giovanni

**Comment by m7four** [comment]
i have tested it. it has worked successfully.

Thanks,

Manfred
