### ISSUE TITLE
connection.response attributes are no longer always lists

### ISSUE THREAD

**Issue by abrasive** [cannatag/ldap3#268]
The documentation describes the `connection.response` dicts' `attributes`:
attributes: a dictionary of returned attributes and their values. Values are list. Values are in UTF-8 format

Since commit 8e30080b33d094eb576258501557c683583e3a73 that is no longer the case, at least in Python2. Single-valued attributes are unicode strings rather than lists:
```
{'attributes': {u'distinguishedName': u'CN=James Laird-Wah,OU=XXX,DC=XXX'},
 'dn': u'CN=James Laird-Wah,OU=XXX,DC=XXX',
 'raw_attributes': {u'distinguishedName': ['CN=James Laird-Wah,OU=XXX,DC=XXX']},
 'type': 'searchResEntry'}
```

The `raw_attributes` entry is unaffected.

**Comment by cannatag** [comment]
Thanks, will update the docs. Starting from version 2 ldap3 reads the schema by default so it is aware of the single or multi valued property of each attribute and this is reflected in the attributes dictionary.

**Comment by cannatag** [comment]
docs updated.
