### ISSUE TITLE
Feature Request -- Get Effective Rights control

### ISSUE THREAD

**Issue by boweeb** [cannatag/ldap3#269]
It would be very handy to be able to use the "Get effective rights" control that 389 Directory Server uses.

The OID is `1.3.6.1.4.1.42.2.27.9.5.2`.

Documented here: https://access.redhat.com/documentation/en-US/Red_Hat_Directory_Server/10.1/html-single/Administration_Guide/index.html#Viewing_the_ACIs_for_an_Entry-Get_Effective_Rights_Control

**Comment by boweeb** [comment]
Turns out this is already possible with search's `controls` arg.  Sorry for the noise.

Example:
Get Luke Skywalker's effective rights for his own entry.
```python
connection.search('uid=lukeskywalker,ou=Users,dc=desktop,dc=local,dc=prv',
                  '(objectClass=inetOrgPerson)',
                  attributes=['*'],
                  get_operational_attributes=True,
                  controls=[
                      ('1.3.6.1.4.1.42.2.27.9.5.2', True, 'dn:uid=lukeskywalker,ou=Users,dc=desktop,dc=local,dc=prv')
                  ],
                  )
```

**Comment by cannatag** [comment]
Good to know. Thanks for using ldap3.
