### ISSUE TITLE
Can't modify 'initials' attribure

### ISSUE THREAD

**Issue by asand3r** [cannatag/ldap3#270]
Good day,
Trying to modify attribute 'initials' on some user account in Active Directory and get 'False' return.
`ldap_connection.modify('CN=USER1,OU=Users,DC=domain,DC=company,DC=com', {'initials': [(MODIFY_REPLACE, ['Niko', 'L. N.'])]})`
In 'result' I have this information:
`'{'result': 16, 'referrals': None, 'description': 'noSuchAttribute', 'type': 'modifyResponse', 'message': '00002085: AtrErr: DSID-03152367, #1:\n\t0: 00002085: DSID-03152367, problem 1001 (NO_ATTRIBUTE_OR_VAL), data 0, Att 2b (initials):len 72\n\x00', 'dn': ''}'`
But I'm sure that 'initials' attribute is present. By the way, for example 'company' attribute replacing successfully.
ldap3 version - 2.1.1
Python 3.5.2
Could you help me? Maybe I should attach some examples?

--
Best regards,
Alexander

**Comment by cannatag** [comment]
The "initials " attribute is single valued in Active Directory. I see you're trying to add two values. Can you try with a single one?

**Comment by asand3r** [comment]
You know, maybe I found key of the problem. Yes, in my example above I've send incorrect data - usually I using single value to update 'initials', sorry. =)
OK, so, I've just noticed, that problem appears when using Cyrillic data (I'm from Russia, so many data in AD in Cyrillic). Please, look at this:
```
ldap_connection.modify('CN=Толстой Лев Николаевич,OU=RGr Users,DC=shuvoe,DC=rg-rus,DC=ru', {'initials': [(MODIFY_REPLACE, ['L. N.'])]})
True
ldap_connection.modify('CN=user1,OU=Users,DC=domain,DC=company,DC=com', {'initials': [(MODIFY_REPLACE, ['Л. Н.'])]})
False
```
Now 'result' has this error:
{'result': 19, 'referrals': None, 'description': 'constraintViolation', 'type': 'modifyResponse', 'message': '00002082: AtrErr: DSID-03151768, #1:\n\t0: 00002082: DSID-03151768, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 2b (initials):len 30\n\x00', 'dn': ''}

**Comment by cannatag** [comment]
Hi it seems that in ad the initials attribute has a length limitation of 6 chars. (https://msdn.microsoft.com/en-us/library/ms676202(v=vs.85).aspx ). Maybe the Unicode translation from Cyrillic uses more than 6 bytes. Can you try adding just a single Cyrillic character and see if it works?

**Comment by asand3r** [comment]
I'm sorry for late answer.
Yes, you are totally right - one Cyrillic symbol writes successfully.
```
ldap_connection.modify('CN=Толстой Лев Николаевич,OU=RGr Users,DC=shuvoe,DC=rg-rus,DC=ru', {'initials': [(MODIFY_REPLACE, ['Л'])]})
True
```
As result, I've this symbols in user properties.
\d0\9b
![capture](https://cloud.githubusercontent.com/assets/13959303/21416154/84ce3870-c821-11e6-81ca-2706580e09c7.PNG)
OK, now I understand it's encoding issue. Could you give me a advice how to resolve it, please?

**Comment by asand3r** [comment]
ОК, so I've resolved the issue by using encode() method of string:
ldap_connection.modify('CN=user1,OU=users,DC=domain,DC=company,DC=com', {'initials': [(MODIFY_REPLACE, ['Л. Н.'.encode()])]})
It should be in 'bytes', not 'str'. Thank you. )

**Comment by cannatag** [comment]
Good to know.

Thanks.
Giovanni
