### ISSUE TITLE
Question about ``get_info`` parameter in Server Object.

### ISSUE THREAD

**Issue by cornelinux** [cannatag/ldap3#276]
Hi Giovanni,

I am wondering how the ``get_info`` parameter in the ``Server`` object is supposed to be used.
https://github.com/cannatag/ldap3/blob/master/ldap3/core/server.py#L71

Looking at the [BIND documentation](http://ldap3.readthedocs.io/bind.html?highlight=get_info) you say that the parameter should be used to determine the mechanisms of SASL?
All your examples contain ``get_info=ALL``, but this results in an extra LDAP query for the subschema. But  if I am doing a simple bind, there is no need to know the SASL mechanisms. So is it safe to set ``get_info=NONE``?

Thanks
Cornelius

**Comment by cannatag** [comment]
Hi Cornelius, 
``get_info`` is used to let the ldap3 library to know the schema (with ``get_info=SCHEMA``) or which functionality are available on the server (with ``get_info=INFO``) or both (with ``get_info=ALL``). If the schema is known to the ldap3 library it can apply many checks on the data sent and received in the ldap session. This information is extensively used in the version 2 of ldap3, especially in the Abstraction Layer.
Also, if Info is known the library can perform additional checks (i.e. if a control can be sent or not to the server). 

Both of these are not mandatory, even if the RFCs states that the client must be aware of the schema and of the server info. If you're sure that you don't need these additional checks you can use ``get_info=NONE``

In version 2 of ldap3 the ``get_info`` parameter defaults to ``SCHEMA``.

**Comment by cornelinux** [comment]
Hi Giovanni,
thanks a lot for the explanation. But do I need the ``get_info=SCHEMA`` on each bind and search request?
Probably not on the bind. I guess we could run a ``get_info=NONE`` there.
But do you need the SCHEMA for search requests like mapping data/attributes?
Thanks

**Comment by cannatag** [comment]
get_info is honored only when opening the connection and when performing a bind not when searching. So it should slow down only when starting the Ldap session. Are you continuously opening and closing sessions?

**Comment by cornelinux** [comment]
I am doing an LDAP bind to verify the password of the user. As there can be many authentication request to verify the LDAP password _and_ a second factor (OTP) there are a lot of bind requests and schema requests.

**Comment by cornelinux** [comment]
Thanks a lot! :+1:
