### ISSUE TITLE
Potentially unneeded (and little costly) escaping in conv.escape_filter_chars

### ISSUE THREAD

**Issue by rtasarz** [cannatag/ldap3#279]
One other minor thing catched my eye. I think following lines unnecessarily convert high UTF-8 codepoints to escapes:

    # escape all octets greater than 0x7F that are not part of a valid UTF-8
    output = ''.join(c if c <= '\x7f' else escape_bytes(to_raw(to_unicode(c, encoding))) for c in output)

RFC 4515 says that its needed only for bytes that make bytestring invalid UTF-8 otherwise (like mentioned in your comment) but allows regular multibyte characters unescaped (it is marked as UTFMB in ABNF grammar, UTFMB itself is specified in RFC 4512) but as `to_unicode()` is called on the `output` earlier, one can be pretty sure it contains valid characters only.

**Comment by cannatag** [comment]
Removed from check_escape

**Comment by cannatag** [comment]
included in v.2.2.0
