### ISSUE TITLE
Filtering on objectGUID

### ISSUE THREAD

**Issue by sif77** [cannatag/ldap3#287]
I'd like to search AD user filtering on objectGUID :

connection.search(OU, '(objectGUID=' + escape_bytes(uuid.UUID(guid).bytes) + ')', attributes=[ 'sAMAccountName' ])

This doesn't work, is it the good way to do it ?

**Comment by cannatag** [comment]
Try to use .bytes_le (little endian) instead of .bytes in  escape_bytes(uuid.UUID(guid).bytes):

 connection.search(OU, '(objectGUID=' + escape_bytes(uuid.UUID(guid).bytes_le) + ')', attributes=[ 'sAMAccountName' ])

should work.

**Comment by sif77** [comment]
Thank you, it works now
