### ISSUE TITLE
Connection.search returns None with empty LDAP attributes

### ISSUE THREAD

**Issue by asand3r** [cannatag/ldap3#289]
Hi,

I've noticed that when I searching user objects with some attributes and it's empty, 'entries' returns None for this. For example:
```
LDAP_CONN.connection.search(search_base='DC=domain,DC=company,DC=com', search_filter='(samaccountname=GorkiyMN)', attributes=['physicalDeliveryOfficeName', 'mobile', 'samaccountname'])
True
LDAP_CONN.connection.entries
[DN: CN=Gorkiy Maksim Nikolaevich,DC=domain,DC=company,DC=com - STATUS: Read - READ TIME: 2017-01-23T13:27:09.176989
    mobile: +7 (915) 239-97-11
    sAMAccountName: GorkiyMN
```
So, I have list with 2 attributes. Can I tune my search request to return empty values like empty string? Like this:
[DN: CN=Gorkiy Maksim Nikolaevich,DC=domain,DC=company,DC=com - STATUS: Read - READ TIME: 2017-01-23T13:27:09.176989
    mobile: +7 (915) 239-97-11
    sAMAccountName: GorkiyMN
    physicalDeliveryOfficeName: ''

Best regards,
Alexander

**Comment by cannatag** [comment]
This is already done in the response using the return_empty_attributes parameter of the connection. Will include in the entries too.

**Comment by asand3r** [comment]
Oh, thank you. Probably I should read docs more closely. )
But, unfortunately I've just tried to do this and got wrong result:
```
>>> conn
Connection(server=Server(host='dc01', port=389, use_ssl=False, allowed_referral_hosts=[('*', True)], get_info='ALL'), user='domain\\user', password='password', auto_bind='NONE', version=3, authentication='NTLM', client_strategy='SYNC', auto_referrals=True, check_names=True, read_only=False, lazy=False, raise_exceptions=False, fast_decoder=True, auto_range=True, return_empty_attributes=True)
>>> conn.search('DC=domain,DC=company,DC=com', search_filter='(samaccountname=Ltolstoy)', attributes=['sn', 'mobile', 'telephonenumber'])
True
>>> conn.entries[0]
DN: CN=Толстой Лев Николаевич,DC=domain,DC=company,DC=com - STATUS: Read - READ TIME: 2017-01-26T08:23:08.919488
    sn: Толстой
>>> 
```
mobile and telephoneNumber attributes is empty now, but entries doesn't show them, though I set "return_empty_attributes=True" to my ldap3.Connection copy.

**Comment by cannatag** [comment]
Ok. Will work on this in the weekend.

**Comment by cannatag** [comment]
Non existent attributes have their value set to None. They just do not show in the representation of the entry, but can be used in code.

For example if you request the "mobile" attribute in a search and the object returned has no "mobile" attribute value set when you print conn.entries[0]  you won't get it printed out, but if you print conn.entries[0].mobile you'll get back <no value>. In the code you can you conn.entries[0].mobile == None or conn.entries[0].mobile is None to check for the non-existence of the attribute.

Is this good for you?

**Comment by asand3r** [comment]
OK, thank you for reply. Yes, I think it could be good for me.

**Comment by maddin2016** [comment]
Hi @cannatag,
i have the same problem like @asand3r. I have to sync two different ldap directories. Here is my config
```python
sourceConnection = Connection(
        "server", "user", "pass", return_empty_attributes=True)

sourceConnection.search(search_base="cn=my_search_base",
                            search_filter="(objectClass=person)",
                            attributes=[ALL_ATTRIBUTES, ALL_OPERATIONAL_ATTRIBUTES], get_operational_attributes=True)

attributes = {"sn": "sn", "ou": "company", "telephoneNumber": "telephoneNumber",
                  "cn": "cn", "mail": "mail", "email": "proxyAddresses", "givenName": "givenName",
                  "postalCode": "postalCode",
                  "facsimileTelephoneNumber": "facsimileTelephoneNumber",
                  "street": "streetAddress", "l": "l", "description": "description"}

for entry in sourceConnection.entries:
        for attr in attributes:
            if entry[attributes[attr]].value is None:
                mappedUser.append({attr: None})
            else:
                mappedUser.append({attr:entry[attributes[attr]].values})

```
I allways get `LDAPKeyError: "key 'facsimiletelephonenumber' not found"`. Something i did wrong?

**Comment by cannatag** [comment]
Try to explicitly request the attribute you need in the search operation instead of using ALL_ATTRIBUTES.

Which version on ldap3 are you using?

**Comment by cannatag** [comment]
Try to explicitly request the attribute you need in the search operation instead of using ALL_ATTRIBUTES.

Which version on ldap3 are you using?

**Comment by maddin2016** [comment]
>Try to explicitly request the attribute you need

That did the trick. Whats wrong with `ALL_ATTRIBUTES`?

**Comment by maddin2016** [comment]
I use version `2.2.1`

**Comment by cannatag** [comment]
When you request all the attributes for an entry the server returns only attributes that have a value, not all the attributes defined in the object classes of the returned entry, so the ldap3 library can't guess what attributes are missing. 

If you want the "record" approach (where all "fields" are always returned) you must specify what attributes you need and set the return_empty_attributes parameter to True. Or you can use the Abstraction Layer that has an object oriented approach and reads the schema and builds the relevant attribute list to request. Have a look at the tutorials at ldap3.readthedocs.io.

Bye,
Giovanni

**Comment by maddin2016** [comment]
Ok. Sounds good. Thanks for the detailed explanation!
