### ISSUE TITLE
Changing own AD password using version 0.9.4.2-1

### ISSUE THREAD

**Issue by Comm4nd0** [cannatag/ldap3#290]
Hi, 
So i'm on Debian and I'm trying to make a script that allows a user to change their own password.

I've created an interface using tkinter which does all the error checking before evening sending the request to the server. However, sending the request to the AD server is where i'm getting stuck. I cannot work out how you send a request to modify your own password. All the documentation is for the latest version so i'm having to look throug the packages code too see what it wants.

code i'm using is:

`#!/usr/bin/python3

from ldap3 import Server, Connection

server = Server('ldaps://192.168.0.2', use_ssl=True)

conn = Connection(server, user='DEV\\dctest', password='MyPassword123', auto_bind=True)

res = conn.extend.standard.modify_password('dctest', old_password='MyPassword123', new_password='MyNewPassword123')
`

Any idea's what i'm doing wrong?!

**Comment by Comm4nd0** [comment]
Just to add, i've searched and searched for the answer to this and tried lots of different variations of the above code. i've also made a stackoverflow question here: http://stackoverflow.com/questions/41816278/python-3-5-ldap3-and-modify-password

**Comment by cannatag** [comment]
Can you try with the latest 2.2 version? It should work out of the box. To upgrade you could use pip:

```
pip install ldap3 --upgrade
```

**Comment by Comm4nd0** [comment]
unfortunately i don't have access to the internet on the box that's running the script. I might download the package manually instead. are you confirming that on the version i'm using it does not work?

**Comment by cannatag** [comment]
I think it's better for you to upgrade to version 2.2. Your version is very old and still not ready for production.

You can get the 2.2 version on pypi at https://pypi.python.org/pypi/ldap3/2.2.0

**Comment by Comm4nd0** [comment]
ok so i've upgraded to 2.2.0:
please can you let me know what this line needs to look like?
res = conn.extend.standard.modify_password('dctest', old_password='MyPassword123', new_password='MyNewPassword123')

**Comment by Comm4nd0** [comment]
ignore my last message, i've worked it out! i've posted the answer here:
http://stackoverflow.com/questions/41816278/python-3-5-ldap3-and-modify-password

**Comment by cannatag** [comment]
Good. Thanks for using ldap3!
