### ISSUE TITLE
ldap3 with active directory issues

### ISSUE THREAD

**Issue by alexandrerua** [cannatag/ldap3#295]
I started to use the package, and I'm really fun of it already, but I've some issues, I would like help

1. not able to connect with ssl (maybe my active directory is missing some configuration, when I telenet to port 636 I get no response, as oposed to port 389)
can you suggest the way to connect with ssl

2.I can search and create OU, users,
but I cannot set some attributes, for example
   msNPAllowDialin
   userAccountControl
nor modify later them after creation
get 'InvalidAttributeSyntax' errors on the logs
it seems that on non string values I get this error!

3. modify password
I'll get the error, 'unwiling to modify'
from what I read from previous answers it maybe related no nonsecure connection

Can you help me on these questions
Thanks in advance

import logging
from ldap3.utils.log import set_library_log_activation_level, set_library_log_detail_level, EXTENDED
from ldap3 import Server, Connection, ALL, NTLM

set_library_log_activation_level(logging.DEBUG)
set_library_log_detail_level(EXTENDED)

server = Server('192.168.0.101', get_info=ALL)
conn = Connection(server, user='cclocal\\administrator', password='xolagut855', auto_bind=True)

# I can create a user
conn.add('cn=alex4fun,ou=ldap3-tutorial,dc=cc,dc=local', 'user')

#I can search the user
conn.search('cn=alex4fun,ou=ldap3-tutorial,dc=cc,dc=local', '(objectclass=user)')

#create other user more attibutes OK
conn.add('cn=alex4fun2,ou=ldap3-tutorial,dc=cc,dc=local', 'user', attributes={'givenname': 'alex'})

#create user 3 ERROR
conn.add('cn=alex4fun2,ou=ldap3-tutorial,dc=cc,dc=local', 'user', attributes={'msNPAllowDialin': True})

#######cpoy of the log of the last command
>>LDAPMessage:
>> messageID=13
>> protocolOp=ProtocolOp:
>>  addRequest=AddRequest:
>>   entry=b'cn=alex4fun2,ou=ldap3-tutorial,dc=cc,dc=local'
>>   attributes=AttributeList:
>>    Attribute:
>>     type=b'msNPAllowDialin'
>>     vals=Vals:
>>      b'True'
>>    Attribute:
>>     type=b'objectClass'
>>     vals=Vals:
>>      b'user'
DEBUG:ldap3:NETWORK:sent 106 bytes via <ldap://192.168.0.101:389 - cleartext - user: cclocal\administrator - not lazy - bound - open - <local: 192.168.2.189:60116 - remote: 192.168.0.101:389> - tls not started - listening - SyncStrategy - internal decoder>
DEBUG:ldap3:NETWORK:received 120 bytes via <ldap://192.168.0.101:389 - cleartext - user: cclocal\administrator - not lazy - bound - open - <local: 192.168.2.189:60116 - remote: 192.168.0.101:389> - tls not started - listening - SyncStrategy - internal decoder>
DEBUG:ldap3:NETWORK:received 1 ldap messages via <ldap://192.168.0.101:389 - cleartext - user: cclocal\administrator - not lazy - bound - open - <local: 192.168.2.189:60116 - remote: 192.168.0.101:389> - tls not started - listening - SyncStrategy - internal decoder>
DEBUG:ldap3:EXTENDED:ldap message received via <ldap://192.168.0.101:389 - cleartext - user: cclocal\administrator - not lazy - bound - open - <local: 192.168.2.189:60116 - remote: 192.168.0.101:389> - tls not started - listening - SyncStrategy - internal decoder>:
<<{'controls': None,
<< 'messageID': 13,
<< 'payload': [(0, False, 10, 21),
<<             (0, False, 4, b''),
<<             (0,
<<              False,
<<              4,
<<              b'00000057: LdapErr: DSID-0C090DB1, comment: Error in attribut'
<<              b'e conversion operation, data 0, v2580\x00')],
<< 'protocolOp': 9}
DEBUG:ldap3:PROTOCOL:ADD response <[{'result': 21, 'description': 'invalidAttributeSyntax', 'referrals': None, 'dn': '', 'type': 'addResponse', 'message': '00000057: LdapErr: DSID-0C090DB1, comment: Error in attribute conversion operation, data 0, v2580\x00'}]> received via <ldap://192.168.0.101:389 - cleartext - user: cclocal\administrator - not lazy - bound - open - <local: 192.168.2.189:60116 - remote: 192.168.0.101:389> - tls not started - listening - SyncStrategy - internal decoder>
DEBUG:ldap3:BASIC:done ADD operation, result <False>

**Comment by cannatag** [comment]
Hi, to set password in Active Directory you must use a secure TLS connection. If you're the Administrator of the Windows box you have to set up the certification authority and create a certificate for your AD instance. This is quite complex and depends on the Windows version you're using. You can anyway finds additional information in the Windows knowledge base.

Regarding the msNPAllowDialin attribute try to set it to the "TRUE" string:

```
conn.add('cn=alex4fun2,ou=ldap3-tutorial,dc=cc,dc=local', 'user', attributes={'msNPAllowDialin': 'TRUE'})
```

**Comment by alexandrerua** [comment]
1. "TRUE" string has worked (had tried boolean and string, but not all uppercase)

2.Add a certification authority to my domain controller, will do asap.

Thanks for fast response, and for the great package

**Comment by cannatag** [comment]
Thanks for using ldap3.

Bye.
Giovanni
