### ISSUE TITLE
Query to Active Directory subnet returns empty value for siteObject

### ISSUE THREAD

**Issue by sinfloodmusic** [cannatag/ldap3#303]
Hi.  Trying to have python determine the best active directory controller to connect to.  I'm connecting to the AD configuration partition and searching the subnet objects.  Everything in the ldap3 library's been working great but seems that one particular value isn't coming through when I query 'subnet' objects.  I think it's because it's a backlink or reference to another object that isn't being handled correctly.

Verified today with 2.1.1 and latest 2.2.1

I can see the siteObject value just find using ldapsearch as well as other command line tools:

    using ldapsearch

    ldapsearch -x -h mycontroller.mydomain.com -b "CN=Subnets,CN=Sites,CN=Configuration,dc=mydomain,dc=com" -D "ldapaccount@mydomain.com" -W "(cn=10.20.0.0/16)" siteObject

    **Output:**
    Enter LDAP Password: *********
    # extended LDIF
    #
    # LDAPv3
    # base <CN=Subnets,CN=Sites,CN=Configuration,dc=mydomain,dc=com> with scope subtree
    # filter: (cn=10.20.0.0/16)
    # requesting: siteObject
    #

    # 10.20.0.0/16, Subnets, Sites, Configuration, mydomain.com
    dn: CN=10.20.0.0/16,CN=Subnets,CN=Sites,CN=Configuration,DC=mydomain,DC=com
    siteObject: CN=MYSITENAME,CN=Sites,CN=Configuration,DC=mydomain,DC=com

    # search result
    search: 2
    result: 0 Success

    # numResponses: 2
    # numEntries: 1

The output above shows siteObject coming back with the DN of the site I'm looking for...

Same goes for other tools using the same account, so not a permission issue.  However, when using ldap3 and asking for all attributes '*' siteObject isn't returned at all.

    {'uSNCreated': 11713, 'dSCorePropagationData': [datetime.datetime(1601, 1, 1, 0, 0, tzinfo=OffsetTzInfo(offset=0, name='UTC'))], 'cn': '10.20.0.0/16', 'description': ['My site location'], 'whenChanged': datetime.datetime(2017, 1, 18, 18, 11, 15, tzinfo=OffsetTzInfo(offset=0, name='UTC')), 'objectGUID': 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxx', 'objectClass': ['top', 'subnet'], 'name': '10.20.0.0/16', 'whenCreated': datetime.datetime(2009, 4, 2, 11, 23, 21, tzinfo=OffsetTzInfo(offset=0, name='UTC')), 'uSNChanged': 7401058, 'instanceType': 4, 'objectCategory': 'CN=Subnet,CN=Schema,CN=Configuration,DC=mydomain,DC=com', 'distinguishedName': 'CN=10.20.0.0/16,CN=Subnets,CN=Sites,CN=Configuration,DC=mydomain,DC=com'}

If I ask for just 3 attributes (cn,distinguishedname, and siteObject) I get an empty array for siteObject.

    {'siteObject': [], 'distinguishedName': 'CN=10.20.0.0/16,CN=Subnets,CN=Sites,CN=Configuration,DC=mydomain,DC=com', 'cn': '10.20.0.0/16'}

**Comment by cannatag** [comment]
Hi, it should work as expected. Are you sure you're binding with the same user?
Can you send me the ldap3 code you're using? 

Also, are you able to perform a trace of the working ldapsearch and a trace of the failing ldap3 bind/search using tcpdump or wireshark? 

Thanks,
Giovanni

**Comment by cannatag** [comment]
I've tried in a test lab and I get them properly:

```
from ldap3 import Server, Connection
>>> s = Server('myserver.com')
>>> c = Connection(s, 'CN=Giovanni,CN=Users,DC=AD2012,DC=LAB', 'password')
>>> c.bind()
>>> print(c.result)
{'result': 0, 'description': 'success', 'dn': '', 'message': '', 'referrals': None, 'saslCreds': None, 'type': 'bindResponse'
>>> c.search('CN=Subnets,CN=Sites,CN=Configuration,DC=AD2012,DC=LAB', '(objectClass=subnet)', attributes=['siteObject'])
>>> c.response[0]['attributes']['siteObject']
'CN=TestSiteA,CN=Sites,CN=Configuration,DC=AD2012,DC=LAB'
```

As you can see I get the siteObject attribute.

Can you adapt this code to your environment and test it?

Thanks,
Giovanni

**Comment by cannatag** [comment]
I've tried in a test lab and I get them properly:

```
from ldap3 import Server, Connection
>>> s = Server('myserver.com')
>>> c = Connection(s, 'CN=Giovanni,CN=Users,DC=AD2012,DC=LAB', 'password')
>>> c.bind()
>>> print(c.result)
{'result': 0, 'description': 'success', 'dn': '', 'message': '', 'referrals': None, 'saslCreds': None, 'type': 'bindResponse'
>>> c.search('CN=Subnets,CN=Sites,CN=Configuration,DC=AD2012,DC=LAB', '(objectClass=subnet)', attributes=['siteObject'])
>>> c.response[0]['attributes']['siteObject']
'CN=TestSiteA,CN=Sites,CN=Configuration,DC=AD2012,DC=LAB'
```

As you can see I get the siteObject attribute.

Can you adapt this code to your environment and test it?

Thanks,
Giovanni

**Comment by sinfloodmusic** [comment]
Ugh.  Giovanni - I apologize.  It's because I was connecting to the global catalog port (3268/3269) with my ldap3 code and turns out those attributes aren't replicated to GC's.  :/

If I use the same code against port 389/636 I'm good to go.

Thank you for the very quick response!

**Comment by cannatag** [comment]
No problem! Thanks for using the ldap3 library.

Bye,
Giovanni
