### ISSUE TITLE
ERROR: Cannot bind to ldap server: invalidDNSyntax in Python2

### ISSUE THREAD

**Issue by bolkedebruin** [cannatag/ldap3#305]
For Apache Airflow we use ldap3. Our Python3 builds are fine but our Python2 builds are not with version 2.2.1

This is how we build the connection:

```
    server = Server(configuration.get("ldap", "uri"), use_ssl, tls_configuration)
    conn = Connection(server, dn, password)
```

This is the error we get:

```
airflow.contrib.auth.backends.ldap_auth: ERROR: Cannot bind to ldap server: invalidDNSyntax 
```

dn is just a string passed to the function.

**Comment by cannatag** [comment]
Where in the code the error come from? Are you catching the dap3 exceptions?

**Comment by bolkedebruin** [comment]
```
def get_ldap_connection(dn=None, password=None):
    tls_configuration = None
    use_ssl = False
    try:
        cacert = configuration.get("ldap", "cacert")
        tls_configuration = Tls(validate=ssl.CERT_REQUIRED, ca_certs_file=cacert)
        use_ssl = True
    except:
        pass

    server = Server(configuration.get("ldap", "uri"), use_ssl, tls_configuration)
    conn = Connection(server, dn, password)

    if not conn.bind():
        LOG.error("Cannot bind to ldap server: %s ", conn.last_error)
        raise AuthenticationError("Cannot bind to ldap server")

    return conn
```

This is the error log from CI:

```
======================================================================
1) ERROR: test_group_belonging (tests.LdapGroupTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/core.py line 1824 in test_group_belonging
      auth = LdapUser(mu)
    <string> line 4 in __init__
      
    .tox/py27-cdh-airflow_backend_mysql/lib/python2.7/site-packages/sqlalchemy/orm/state.py line 414 in _initialize_instance
      manager.dispatch.init_failure(self, args, kwargs)
    .tox/py27-cdh-airflow_backend_mysql/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py line 60 in __exit__
      compat.reraise(exc_type, exc_value, exc_tb)
    .tox/py27-cdh-airflow_backend_mysql/lib/python2.7/site-packages/sqlalchemy/orm/state.py line 411 in _initialize_instance
      return manager.original_init(*mixed[1:], **kwargs)
    airflow/contrib/auth/backends/ldap_auth.py line 121 in __init__
      conn = get_ldap_connection(configuration.get("ldap", "bind_user"), configuration.get("ldap", "bind_password"))
    airflow/contrib/auth/backends/ldap_auth.py line 67 in get_ldap_connection
      raise AuthenticationError("Cannot bind to ldap server")
   AuthenticationError: Cannot bind to ldap server
   -------------------- >> begin captured logging << --------------------
   airflow.contrib.auth.backends.ldap_auth: ERROR: Cannot bind to ldap server: invalidDNSyntax 
   --------------------- >> end captured logging << ---------------------

```

If you need a full trace, that will need to wait a little due to test environment.

**Comment by cannatag** [comment]
I dont' see any code from ldap3. Probably the code is executed and then an error is raised and catched by airflow. Are you sure that ``configuration.get("ldap", "bind_user")`` returns the same value for python3 and python2? 

I still don't need a trace (but will probably need it later), can you insert 
```
print(conn.request)
print(conn.response)
``

inside the ``if not conn.bind():`` statement? This should print the values sent/received  to/from the server.

Thanks,
Giovanni

**Comment by bolkedebruin** [comment]
This is the output:

```
   -------------------- >> begin captured logging << --------------------
   root: INFO: server ldap://localhost:3890 - cleartext, dn: cn=Manager,dc=example,dc=com password: insecure
   root: INFO: None
   root: INFO: None
   airflow.contrib.auth.backends.ldap_auth: ERROR: Cannot bind to ldap server: invalidDNSyntax 
   --------------------- >> end captured logging << ---------------------
```

from:

```
def get_ldap_connection(dn=None, password=None):
    tls_configuration = None
    use_ssl = False
    try:
        cacert = configuration.get("ldap", "cacert")
        tls_configuration = Tls(validate=ssl.CERT_REQUIRED, ca_certs_file=cacert)
        use_ssl = True
    except:
        pass

    server = Server(configuration.get("ldap", "uri"), use_ssl, tls_configuration)
    conn = Connection(server, dn, password)

    logging.info("server {}, dn: {} password: {}".format(server, dn, password))
    logging.info(conn.request)
    logging.info(conn.response)
    if not conn.bind():
        LOG.error("Cannot bind to ldap server: %s ", conn.last_error)
        raise AuthenticationError("Cannot bind to ldap server")

    return conn
```

As mentioned it does work on Python 3.

**Comment by cannatag** [comment]
Please try again with the following code. In conn.request you should have the user_dn that is sent to the server and in conn.result the error code. With my test lab it works without problems with python3 and python2.

```
def get_ldap_connection(dn=None, password=None):
    tls_configuration = None
    use_ssl = False
    try:
        cacert = configuration.get("ldap", "cacert")
        tls_configuration = Tls(validate=ssl.CERT_REQUIRED, ca_certs_file=cacert)
        use_ssl = True
    except:
        pass

    server = Server(configuration.get("ldap", "uri"), use_ssl, tls_configuration)
    conn = Connection(server, dn, password)

    logging.info("server {}, dn: {} password: {}".format(server, dn, password))
    if not conn.bind():
        logging.info(conn.request)
        logging.info(conn.result)
        LOG.error("Cannot bind to ldap server: %s ", conn.last_error)
        raise AuthenticationError("Cannot bind to ldap server")

    return conn
```

**Comment by bolkedebruin** [comment]
Ah should have caught that. Running now: https://travis-ci.org/bolkedebruin/airflow/builds/208344500

Someone mentioned on our mailinglist that it is an issue between the py2 lib and py3 lib (not exactly sure what lib was meant .so or something else).

I couldn't reproduce the issue in a notebook either, but our builds fail consistently

**Comment by bolkedebruin** [comment]
```
   AuthenticationError: Cannot bind to ldap server
   -------------------- >> begin captured logging << --------------------
   root: INFO: server ldap://localhost:3890 - cleartext, dn: cn=Manager,dc=example,dc=com password: insecure
   root: INFO: {'controls': None, 'name': "b'cn=Manager,dc=example,dc=com'", 'type': 'bindRequest', 'version': 3, 'authentication': {'sasl': None, 'simple': 'insecure'}}
   root: INFO: {'dn': u'', 'referrals': None, 'message': u'invalid DN', 'result': 34, 'saslCreds': None, 'description': 'invalidDNSyntax', 'type': 'bindResponse'}
   airflow.contrib.auth.backends.ldap_auth: ERROR: Cannot bind to ldap server: invalidDNSyntax 
```

**Comment by cannatag** [comment]
I see that the dn is **"b'cn=Manager,dc=example,dc=com'"** with the byte prefix. This doens't happen in my tests. I can't say if this is the passed dn value or if the ldap3 erroneously adds it. Will try to replicate it.

**Comment by bolkedebruin** [comment]
Ah ok. So work around would be to do a 'dn.decode("utf-8")' maybe. If that works something underlying might have changed for some reason.

**Comment by bolkedebruin** [comment]
Ok, I have reproduced this in a notebook:


```
from __future__ import print_function, unicode_literals ;
from builtins import bytes
from builtins import str

import ldap3

from ldap3 import Server, Connection, Tls, LEVEL, SUBTREE, BASE

uri = "ldap://localhost:32769"
tls_configuration = None
use_ssl = False
password = "admin"

server = Server(uri, use_ssl, tls_configuration)
dn = str(b"cn=admin, dc=example, dc=org")

conn = Connection(server, dn, password)

test = conn.bind()

```

Test will be false, and the error will be "invalidDNSyntax"

**Comment by cannatag** [comment]
The problem is in the 
``from builtins import str``
statement. I see you're using the "future" package for python2-3 compatability. It probably has some side-effect on str behaviour. 

WIll try to debug the code and find a fix for it.

**Comment by bolkedebruin** [comment]
It seems so. I tried 

```
from future.utils import native

...

dn = native(dn)

```

which resolves the connection issue, but then more issues pop up down the line.

**Comment by cannatag** [comment]
Anyway you can leave the dn in byte format. The ldap3 library should properly handle it in python2 and python3.

**Comment by bolkedebruin** [comment]
FWIW: to make it pass I had to wrap every string that gets passed to ldap3 with "native()", I would definitely would appreciate something cleaner :).

**Comment by cannatag** [comment]
I see. I should try to "intercept" the "future" library and trasform the future str in a normal str.  ldap3 works well with python3 and python2 so I never tested it against "compatibility" library. Will work on this tomorrow. Hope to find a solution for version 2.2.2 that I'd like to release on Sunday. 

I'm sorry for bothering your project.

Bye,
Giovanni

**Comment by bolkedebruin** [comment]
No problem, very thankful for the existence of your project!

**Comment by cannatag** [comment]
Please check code in dev. It should now pass your test. The fix is specific to the bind operation when using the *future* compatability package in Python 2.

Are you only binding for authentication purpose in your code or are you performing other LDAP operations (search, modify, delete)? I fear that other operations are concerned by this problem.

Anyway this snippet of code work well for me in python 2 and 3 either with or without the future package:

```
from __future__ import print_function, unicode_literals
try:
    from builtins import str
except ImportError:
    pass

from ldap3 import Server, Connection
uri = "ldap://my_server"
password = "my_password"

server = Server(uri)
dn = str("cn=admin, dc=example, dc=org")
print(type(dn))
conn = Connection(server, dn, password)
test = conn.bind()
print(conn.request)
print(conn.result)
print(test)
```

I removed the b' prefix because is useless. Also in Python 3 when you convert a bytes type to a str you must specify the encoding.

**Comment by bolkedebruin** [comment]
We are also using the other operations (mainly search).

**Comment by cannatag** [comment]
Can you tell me if you have troubles with them? Not all strings are treated the same way. I must identify where in the code they are sent to the pyasn.1 library that builds the message sent to the server.

Thanks,
Giovanni

**Comment by cannatag** [comment]
Python 3 docs fot ``str()`` states that passing a bytes object to str() without the encoding or falls under the case of returning the informal string representation. For example:

```
>>> str(b'Zoot!')
"b'Zoot!'"
```

So you should define an encoding when converting to str(). In Python3 this is easy:
```
>>> str(b'Zoot!', encoding='utf-8')
'Zoot!'
```
and this works also in Python 2 with the future package.


In Python 2 without the future package you can use:
```
>>> a.decode('utf-8')
u'abc'
```

that converts to unicode()

I think this is not a bug in ldap3 or in pyasn.1 but is something you have to deal with in your code.

**Comment by cannatag** [comment]
https://docs.python.org/3/library/stdtypes.html
