### ISSUE TITLE
Unable to install ldap3-2.2.1 on Windows 2012 64 bit system

### ISSUE THREAD

**Issue by TrumSteven** [cannatag/ldap3#307]
I already have Python ldap 2.4.10 installed on this system and was able to use the executable to install it. This is a Windows 2012 R2 Standard 64 bit OS

I need to install version ldap3 now and the download from https://pypi/python.org/pypi/ldap3 seems to have the wrong download version. The file is called 'ldap3-2.2.1.win-amd64.exe but when I try and run the install i get the following error: 

Python version -32 required, which was not found in the registry

I am unable to use the pip installer on this server as the proxy will not allow the connection. 

Please help!

**Comment by cannatag** [comment]
Will investigate on this. In the meanwhile you can download the source and use *python setup.py install* because ldap3 is a pure python package. Remember to install the pyasn1 package too.

Bye,
Giovanni

**Comment by cannatag** [comment]
Can you tell me the python version you're using? Just launch python (probably with the py command) and copy here the output.

Thanks

**Comment by TrumSteven** [comment]
Python 2.7.13

**Comment by TrumSteven** [comment]
Thanks for the quick response.

Update: I was able to get ldap 3 installed using a different method.

Using Easy_install this time and setting my proxy up in the environment variables enabled me to install it using the .egg file download “ldap3-2.2.1-py2.7.egg.

It would have been much easier to use the .exe though as I ran into multiple issues when attempting this method.

Regards,


--
Steven Costello
925-303-6177
TRUM Partners | www.trumpartners.com<http://www.trumpartners.com/>
This email and any attachments thereto may contain private, confidential, and privileged material for the sole use of the intended recipient. Any review, copying, or distribution of this email (or any attachments thereto) by others is strictly prohibited. If you are not the intended recipient, please contact the sender immediately and permanently delete the original and any copies of this email and any attachments thereto.
Please consider the environment before printing this email

**Comment by TrumSteven** [comment]
We should figure out why the .exe that is out there won't install on a 64 bit system though

**Comment by cannatag** [comment]
This IX a bug in the Python installation package. It should be fixed in 3.6.1. See http://bugs.python.org/issue28680

**Comment by cannatag** [comment]
I've tested with 3.5.3 and it works. Will build the installer for next release with this version.

**Comment by TrumSteven** [comment]
Nice!  Thank you for the update.

Steven Costello CSP, SCS
Trum Partners, LLC
Principal Consultant
925-303-6177



On Mar 3, 2017, at 12:34 AM, Giovanni Cannata <notifications@github.com<mailto:notifications@github.com>> wrote:


I've tested with 3.5.3 and it works. Will build the installer for next release with this version.

**Comment by cannatag** [comment]
released in 2.2.2
