### ISSUE TITLE
Zero byte b'0' raw value in datetime attributes resolves to datetime 1601-01-01 00:00:00+00:00

### ISSUE THREAD

**Issue by atulatri** [cannatag/ldap3#308]
For example, if accountExpires is not set in Active directory, ldap3 will resolve it to datetime 1601-01-01 00:00:00+00:00

I think such values should resolve to None or maybe some custom type NOT_SET.

**Comment by cannatag** [comment]
Because that's the youngest date that can be stored in AD. So '0' means exactly that. 

Are you sure that the attribute is not set? In that case it's raw value should non contain b'0' and ldap3 should set it to None.
