### ISSUE TITLE
Is it possible somehow to set timeout fot bind connection with conn.bind()?

### ISSUE THREAD

**Issue by kiddick** [cannatag/ldap3#309]

**Comment by cannatag** [comment]
Hi, there are two different timeout in ldap3:
* **connect_timeout**: timeout in seconds for the connect operation, defined in the Server object
* **receive_timeout**: set the socket in non-blocking mode - raising an exception after the specified amount of seconds if nothing is received over the wire, defined in the Connection object


The first one is used when opening to socket to the server, the second one is used in every communication after the connection has been established, so I think you should try to change the latter.

Let me know if you need more help.

Bye,
Giovanni
