### ISSUE TITLE
Attempts to connect to an LDAP server fail with "LDAPSocketOpenError: invalid server address" on FreeBSD

### ISSUE THREAD

**Issue by andriy-s** [cannatag/ldap3#31]
Any attempt to connect to an LDAP server fails with "LDAPSocketOpenError: invalid server address" on FreeBSD. This is because getaddrinfo(3) on FreeBSD does not accept AI_V4MAPPED flag as a hint, and fails with error code 3 ("Invalid value for ai_flags") if this flag is set. The following patch fixed (or worked around) the problem for me: https://gist.github.com/andriy-s/ac502e1d27ba4f19912d

**Comment by andriy-s** [comment]
Hello and sorry for late reply.

As a followup to your comment at https://gist.github.com/andriy-s/ac502e1d27ba4f19912d,
I have tested your new implementation of the address_info property, and it appears to work fine for me.

Thanks,
Andriy.

**Comment by cannatag** [comment]
Good to know, I will include the fix in the next release.

Bye,
Giovanni

----- Messaggio originale -----
Da: "Andriy Syrovenko" <notifications@github.com>
Inviato: ‎11/‎03/‎2015 15:01
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Oggetto: Re: [ldap3] Attempts to connect to an LDAP server fail with"LDAPSocketOpenError: invalid server address" on FreeBSD (#31)

Hello and sorry for late reply.
As a followup to your comment at https://gist.github.com/andriy-s/ac502e1d27ba4f19912d,
I have tested your new implementation of the address_info property, and it appears to work fine for me.
Thanks,
Andriy.

**Comment by cannatag** [comment]
Please check 0.9.8.1 version. It should fix the problem.

Bye,
Giovanni
