### ISSUE TITLE
ad_remove_members_from_groups with fix=True does not handle case differences in attribute keys

### ISSUE THREAD

**Issue by mattcl** [cannatag/ldap3#315]
Members can silently fail being removed from a group if there are case differences in attribute keys
```
# ldap3/extend/microsoft/removeMembersFromGroups.py
def ad_remove_members_from_groups(...):
    ...
    member_to_remove = [member for member in members_dn if member in existing_member]
```
Where
```
existing_member = ['CN=bar,CN=Users,DC=foo,DC=local'] 
```
and
```
members_dn = ['cn=bar,cn=Users,dc=foo,dc=local'] 
```
(or vice versa).

I'm not familiar enough with LDAP to know if you can just lowercase the whole dn string without breaking something.

**Comment by cannatag** [comment]
You're right. DN should be not case sensitive. I've udpated the add_members_to_groups and remove_members_to_groups to handle this.

Can you please check code in dev to see if it works now?

Thanks,
Giovanni

**Comment by mattcl** [comment]
Thanks for the quick turnaround. Looks like it works. I'll close this ticket.

**Comment by cannatag** [comment]
Will release it in the next version of ldap3.

Bye,
Giovanni
