### ISSUE TITLE
ldap3 connection issue 

### ISSUE THREAD

**Issue by justin-wf** [cannatag/ldap3#324]
ldap3 installed through pip. but I am able to open a connection. see below error. what could be the issue?
---------------------------------------------
>>> from ldap3 import Server, Connection, ALL
>>> server = Server('scglobaluat.aduat.scotiacapital.com')
>>> conn = Connection(server)
>>> conn.bind()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/csw/lib/python2.7/site-packages/ldap3/core/connection.py", line 508, in bind
    self.open(read_server_info=False)
  File "/opt/csw/lib/python2.7/site-packages/ldap3/strategy/sync.py", line 55, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/opt/csw/lib/python2.7/site-packages/ldap3/strategy/base.py", line 144, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(datetime.datetime(2017, 3, 21, 14, 21, 32, 639937), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 128] Network is unreachable',), ('::ffff:172.26.12.101', 389, 0, 0)), (datetime.datetime(2017, 3, 21, 14, 21, 32, 640219), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 128] Network is unreachable',), ('::ffff:172.26.12.100', 389, 0, 0)), (datetime.datetime(2017, 3, 21, 14, 21, 32, 640482), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 128] Network is unreachable',), ('::ffff:172.31.113.21', 389, 0, 0)), (datetime.datetime(2017, 3, 21, 14, 21, 32, 640746), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 128] Network is unreachable',), ('::ffff:172.31.42.162', 389, 0, 0)), (datetime.datetime(2017, 3, 21, 14, 21, 32, 641018), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 128] Network is unreachable',), ('::ffff:172.22.4.57', 389, 0, 0)), (datetime.datetime(2017, 3, 21, 14, 21, 32, 641295), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 128] Network is unreachable',), ('::ffff:172.22.52.167', 389, 0, 0)), (datetime.datetime(2017, 3, 21, 14, 21, 32, 641579), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 128] Network is unreachable',), ('::ffff:172.20.193.67', 389, 0, 0)), (datetime.datetime(2017, 3, 21, 14, 21, 32, 641869), <class 'ldap3.core.exceptions.LDAPSocketOpenError'>, LDAPSocketOpenError('socket connection error while opening: [Errno 128] Network is unreachable',), ('::ffff:172.20.126.160', 389, 0, 0))])

**Comment by cannatag** [comment]
It looks like a connection problem. Are you sure you're able to reach your Server? Also try to stay with the IPv4 setting  the parameter 'mode' of the Server object to IP_V4_ONLY.

Please have a look at http://ldap3.readthedocs.io/server.html#server-object for more info.

Let me know if this solves your problem.


Bye,
Giovanni
