### ISSUE TITLE
Cannot decode ber_type 10

### ISSUE THREAD

**Issue by jceel** [cannatag/ldap3#325]
I found following traceback on a customer system while talking to an AD DC:

```
Exception in thread Thread-20897:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/ldap3/strategy/async.py", line 94, in run
    ldap_resp = decode_message_fast(unprocessed[:length])
  File "/usr/local/lib/python3.6/site-packages/ldap3/utils/asn1.py", line 71, in decode_message_fast
    decoded = decode_sequence(message, ber_value_offset, ber_len + ber_value_offset, LDAP_MESSAGE_CONTEXT)
  File "/usr/local/lib/python3.6/site-packages/ldap3/utils/asn1.py", line 94, in decode_sequence
    value = context_decoders[ber_type](message, start, start + ber_len)  # call value decode function for context class
KeyError: 10
```

Sadly I can't provide any more details yet - that traceback was part of bug report submitted for application using ldap3 (FreeNAS Corral middleware) and that's all I found so far in debug info provided by the user.

Library version: 2.1.1

**Comment by cannatag** [comment]
Hi, this should definitely not happen. Are you able to reproduce the issue? Also can you try with the fast_decoder=False parameter in the connection object? 

It could be very helpful to have a trace of the session to inspect the Ldap messages between the server and the client. 

Giovanni

**Comment by etingof** [comment]
Debugging idea: if you use `fast_decoder=False` and enable pyasn1 debugging in your script by adding this:

    from pyasn1 import debug
    debug.setLogger(debug.Debug('all'))

that should dump all ASN.1 encoded packets to stderr what might help further troubleshooting. ;-)

**Comment by jceel** [comment]
It's a pity that I can't reproduce it on my end. User claims he's trying to talk to Windows Server 2008 R2 DC. I'm preparing a test script for the user with ASN.1 logging turned on.

**Comment by cannatag** [comment]
I've never got this error in my AD tests, but in my lab I use a Windows 2012 R2 server.

It would be very useful to have a trace of the sent and received packets. In your script could you enable the ldap3 logging at Extended level in addition to the pyasn1 debug as suggested by Ilya. Ldap3 logging docs are at ldap3.readthedocs.io/logging.

Thanks.

**Comment by cannatag** [comment]
Do you have any news on this issue?

Type 10 is for the "Delete Request" and this is only going from the client to the server. That's the reason why it's non decoded as a valid response.

**Comment by texcoffier** [comment]
The issue is always here with version 2.5.1
It seems related to server side connection timeout.
The error is also raised when: fast_decoder=False

There is the not parsable message:

```python
b'0\x84\x00\x00\x00\x80\x02\x01\x00x\x84\x00\x00\x00_\n\x014\x04\x00\x04X00000003: LdapErr: DSID-0C060469, comment: Error decrypting ldap message, data 0, v1db1\x00\x8a\x161.3.6.1.4.1.1466.20036'
```

I hope this may help.
