### ISSUE TITLE
Using keys in attrdef makes the writer fire 'Attributes non in Definition' error

### ISSUE THREAD

**Issue by profhase** [cannatag/ldap3#326]
The steps: 
1. define an attribute like `myattr = AttrDef(name='myname', key='myKey'...)`
2. attach this `AttrDef` to `ObjectDef`
3. Find object with `Reader`
4. Create `Writer.from_cursor(reader)`

I get 
    
    LDAPCursorError('Attributes \'%s\' non in definition' % ', '.join(not_defined_attributes))

The reason: `cursor.py` has the following code in line 83

            for attribute in attributes:
                if attribute not in self.definition._attributes:
                    not_defined_attributes.append(attribute)

the `_attributes` is an CaseInsensitiveDict with `key` of the `AttrDef` as Keys.
The attributes property contains the set of Attributes as they are called in Directory. So there are some attributes that cannot be found.

**Comment by cannatag** [comment]
Please look at the proposed solution for #311 and let me know if it works for you. Alternately you can try to define the server object with get_info=None to disable schema checking.

**Comment by profhase** [comment]
I also get analogous issues if I 
1. create a writer using `w_entry = entry.entry_writable()`
2. change a field value with `w_entry.myparam = 'new_value'`
3. w_entry.commit_changes()

```
  File "/home/ilya/.virtualenvs/ndstools/lib/python3.4/site-packages/ldap3/operation/search.py", line 299, in build_attribute_selection
    raise LDAPAttributeError('invalid attribute type in attribute list: ' + attribute)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type in attribute list:
```

**Comment by cannatag** [comment]
It's the same reason. The server is returning some attributes in the schema but not the one you're requesting to change. The #311 issue is a similar to yours.

**Comment by profhase** [comment]
Thanks for the quick help. Though I don't understand why it only happens if I use keys. If I create the `AttrDef` without `key=...` the problem does not occur

**Comment by cannatag** [comment]
Will check this in my lab. 

Thanks,
Giovanni

**Comment by cannatag** [comment]
You were right, there was an error in the Writer cursor that was not fully aware of the "friendly" name of an AttrDef. I've hopefully fixed it now. Can you try the code in dev?

Thanks,
Giovanni

**Comment by profhase** [comment]
Ah, thanks, works now
