### ISSUE TITLE
Get recursive group members

### ISSUE THREAD

**Issue by AMMullan** [cannatag/ldap3#327]
I'm trying to use ldap3 to recursively get all users in a group for an authentication project but not having too much luck.

So far I have:

```
ad_server = Server(
    AD_HOST,
    use_ssl=True,
    get_info=ALL
)

connection = Connection(
    ad_server,
    auto_bind=AUTO_BIND_TLS_BEFORE_BIND,
    read_only=True,
    check_names=True,
    user='%s\%s' % (AD_USER_DOMAIN, AD_USER),
    password=AD_PASS,
    return_empty_attributes=True
)

def get_group_users(cn):
    with connection as conn:
        conn.search(
            search_base=cn,
            search_filter='(|(objectCategory=group)(objectCategory=user))',
            search_scope=SUBTREE,
            attributes = ['member', 'objectClass', 'userAccountControl'],
            size_limit=0
        )

        group_data = json.loads(conn.response_to_json())
        attributes = group_data['entries'][0]['attributes']

        for member in attributes['member']:
            get_group_users(member)
        else:
            # Don't want disabled accounts
            if not attributes['userAccountControl'] in [546, 514, 66050, 66082]:
                return group_data['entries'][0]['dn']

        conn.unbind()

print(get_group_users(GROUP_DN))
```

But this isn't quite right, not sure if it's just me being daft, and I can't find any examples of how this could be done. Have you done/seen this done previously that I could pick up some clues from?

**Comment by cannatag** [comment]
Active directory has a specific filter for nested groupmembership:

```
(&(objectClass=user)(memberof:1.2.840.113556.1.4.1941:=%s)) 
```
just replace ``%s`` with your root group dn.

Your code should be similar to this:

```
from ldap3 import Server, Connection, ALL, AUTO_BIND_TLS_BEFORE_BIND, SUBTREE

AD_HOST='my_server'
AD_USER_DOMAIN = 'my_domain'
AD_USER = 'my_user'
AD_PASS = 'my_password'
AD_BASE = 'my_base'
GROUP_DN = 'my_group'

ad_server = Server(
    AD_HOST,
    use_ssl=True,
    get_info=ALL
)

connection = Connection(
    ad_server,
    auto_bind=AUTO_BIND_TLS_BEFORE_BIND,
    read_only=True,
    check_names=True,
    user='%s\%s' % (AD_USER_DOMAIN, AD_USER),
    password=AD_PASS,
    return_empty_attributes=True
)

def get_group_users(cn):
    with connection as conn:
        conn.search(
            search_base=AD_BASE,
            search_filter='(&(objectClass=user)(memberof:1.2.840.113556.1.4.1941:=' + cn +'))',
            search_scope=SUBTREE,
            attributes = ['objectClass', 'userAccountControl'])
        members = []
        for entry in conn.entries:
            if not entry.userAccountControl in [546, 514, 66050, 66082]:
                members.append(entry.entry_dn)

        print(members)
        print(len(members))

get_group_users(GROUP_DN)
```

You have all the active members in the member list. Let me know if this works for you.

Bye,
Giovanni

**Comment by AMMullan** [comment]
Hey Giovanni,

Thanks for that. I had tried that but I get an error:
> ldap3.core.exceptions.LDAPInvalidFilterError: malformed filter

Cheers,
Allan

**Comment by AMMullan** [comment]
Ah, I just realised that this might be because the group that I'm trying to get members for is in the parent domain (i.e. DOMAIN.COM) and my members are in child domains (i.e. UK.DOMAIN.COM)....?

**Comment by AMMullan** [comment]
I do have a working function, it's just really slow:

```
def get_group_users(cn, staff=[], checked_groups=[], checked_users=[]):
    with connection as conn:
        conn.search(
            search_base=cn,
            search_filter='(|(objectCategory=group)(objectCategory=user))',
            search_scope=SUBTREE,
            attributes = [
                'member',
                'objectClass',
                'userAccountControl',
                'sAMAccountName'
            ],
            size_limit=0
        )

        # while True:
        if 'group' in conn.entries[0].objectClass.values:
            # Dedupe
            checked_groups.append(conn.entries[0].entry_dn)

            for member in conn.entries[0].member:
                # Check for duplicates
                if member not in checked_groups and member not in staff:
                    get_group_users(member, staff, checked_groups)

        elif 'person' in conn.entries[0].objectClass:
            # Dedupe
            checked_users.append(conn.entries[0].entry_dn)

            # Check for duplicates
            if not conn.entries[0].sAMAccountName.value in staff:
                if not conn.entries[0].userAccountControl.value in [546, 514, 66050, 66082]:
                    return staff.append(conn.entries[0].sAMAccountName.value)

        return staff

        conn.unbind()
```

Not sure if there is any way to speed it up, takes about 4 minutes for each group I'm checking depending on how many groups it has to search. I've tried turning off using SSL but that didn't make much difference. Seems to be the search() function that takes the main time obviously but only for some items.

**Comment by cannatag** [comment]
Probably your filter is not properly written. You need the full dn of the group, including the  base. You don't have to cycle through all the objects. A single ldap query should suffice.

**Comment by AMMullan** [comment]
I'm passing it the group distinguishedName as the search_base, the search filter I guess is pretty much pointless as all I'm doing is getting attributes from that object...

Basically the idea is that I get the members of that group and then loop through picking the members out and looping through any members which are groups, while ensuring it doesn't check things it has already checked.

Is there any better way of doing it? I guess the problem is that I can't search for all group members as you suggested as we have a forest meaning the group members could be in DOMAIN.COM, UK.DOMAIN.COM, US.DOMAIN.COM etc and the groups I'm checking are all in DOMAIN.COM...

**Comment by cannatag** [comment]
You should check for each group in each domain. But in each domain you should have only 1 search for each group using the Microsoft specific filter for nested groupmembership: http://stackoverflow.com/questions/6195812/ldap-nested-group-membership


My example runs in a few seconds for a 1000 member group

**Comment by baileyds** [comment]
> Hey Giovanni,
> 
> Thanks for that. I had tried that but I get an error:
> 
> > ldap3.core.exceptions.LDAPInvalidFilterError: malformed filter
> 
> Cheers,
> Allan

I realize this is a bit old, but I was able to fix this issue by editing the search_filter line as below:
`search_filter='(&(objectClass=user)(memberof:1.2.840.113556.1.4.1941:=%s)) % cn',`

to:
`search_filter='(&(objectClass=user)(memberof:1.2.840.113556.1.4.1941:=%s))' % cn,`

Note moving the % cn to outside the quotes did the trick, for C style variable substitution. From [https://stackoverflow.com/questions/35974056/string-substitution-in-python-3](url)

**Comment by smanross** [comment]
and while this is still a super old thread, this line is better written like so... so that no mater what attributes are ANDed together in **userAccountControl**, you always know that it's a disabled account because the 2 property is the only thing IF should be checking for.

`
if not conn.entries[0].userAccountControl.value & 2 == 2:
`
https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/useraccountcontrol-manipulate-account-properties  

ACCOUNTDISABLE = 2
