### ISSUE TITLE
Credential error on bind

### ISSUE THREAD

**Issue by gnomic** [cannatag/ldap3#328]
I am getting the following error from ldap3 version 2.2.0  and python version:  3.5.3

> LDAPInvalidCredentialsResult: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - None - bindResponse - None

I have verified the credentials are correct. I've tried extended logging but it does not appear to work in this version. Please advise. Code snippet below.

```python
def get_person(sso_id, field_list = None):
    service_sso = 'ABCDEFG'
    pword = 'XYZ'
    ldap_name = 'ldap.corporate.mycorp.com'
    ldap_port = 1234
    ldap_base = 'OU=All Businesses,DC=MYCORP,DC=com'  # Base search string
    # Select the fields you want to return
    if field_list == None:
        field_list = [
            'cn', 'displayName', 'myBusinessUnit', 'department', 'myHRjobid',
            'mySupervisorId', 'mySupervisorName', 'employeeType', 'mail',
            'title']
    # Connection: http://ldap3.readthedocs.io/connection.html
    # Server http://ldap3.readthedocs.io/server.html
    with Connection(Server(ldap_name, port=ldap_port, use_ssl=False),
                    user=service_sso,
                    password=pword,
                    auto_bind =  None,
                    raise_exceptions=True,
                    read_only=True) as c:

        c.search(
            search_base=ldap_base,
            search_filter='(' + 'CN=' + str(sso_id) + ' )',
            search_scope=SUBTREE,
            attributes=ALL_ATTRIBUTES,
            get_operational_attributes=True)
        
        # see all fields so that you can pick and choose what to return, uncomment the next line
        print(c.response_to_json())
        <snip>
        return ldap_entry
```

**Comment by cannatag** [comment]
The server is rejecting your credentials. what kind of LDAP server are you connecting to? You're using basic authentication, so your user name should be in the dn format. 

Can you try with the following code and send me the result?
```
from ldap3 import Server, Connection
s = Server('my_server', port=my_port)
c = Connection(s, 'my_user', 'my_password')
c.bind()
print(c.request)
print(c.response)
```

Please change the my_* strings to your actual values and hide any sensitive data in the response you send back.

Thanks,
Giovanni

**Comment by gnomic** [comment]
This is what is returned - the SSO and Password are masked but correct.
```
False
{'type': 'bindRequest', 'controls': None, 'authentication': {'simple': 'password', 'sasl': None}, 'name': '123456789', 'version': 3}
None
```

**Comment by cannatag** [comment]
Sorry. My mistake the last print should be 

print(c.result)

Could you try again? Are you connecting to an AD server? In this case you could try with  NTLM authentication too.

**Comment by gnomic** [comment]
No problem
```
False
{'type': 'bindRequest', 'controls': None, 'authentication': {'simple': 'password', 'sasl': None}, 'name': 'SSO', 'version': 3}
{'dn': '', 'type': 'bindResponse', 'message': '', 'description': 'invalidCredentials', 'result': 49, 'referrals': None, 'saslCreds': None}
```
Tried NTLM and got LDAPSessionTerminatedByServerError: session terminated by server

**Comment by gnomic** [comment]
print(s.info.supported_sasl_mechanisms) gives me the result ['EXTERNAL'] which is not overly helpful to me, but may suggest something to you.

**Comment by cannatag** [comment]
This means that you can trry to authenticate with a client certificate, but you need an internal CA that issues the certificate for your user. 

Your server is clearly stating that the credentials you're passing are wrong. Are you sure they are right? Is the name in the full dn format or are you using some other format?

**Comment by gnomic** [comment]
Not sure what you mean by "full dn format"  No one has mentioned that I need a certificate (I get blank looks). Our support people ran this command which looks very much like what I've coded.

ldapsearch -p 1234 -D "CN=2XXXXXXXX,ou=All Businesses,dc=cdiad,dc=XXXXX,dc=com" -w - -b "OU=All Businesses, dc=cdiad,dc=XXXXX,dc=com" cn=3XXXXXXXX dn
Enter bind password:
ldap_simple_bind: Invalid credentials
ldap_simple_bind: additional info: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903A8, comment: AcceptSecurityContext error, data 52e, v1db1

**Comment by cannatag** [comment]
So it's not working with ldapsearch either. 
The "data 52e" message means that the username is correct but the password is not valid. Have a look at http://ldapwiki.com/wiki/Common%20Active%20Directory%20Bind%20Errors

Are you sure your credentials are correct?

**Comment by gnomic** [comment]
Am digging into this. I can't login with the credentials, but that's not definitive as interactive login should be denied. I've asked the AD team to prove that my credentials work. Stand by. 

I've debuggered through the code with PyCharm and didn't see any issues with the credentials not being sent correctly.

**Comment by gnomic** [comment]
OK, got it working with 'CN=3XXXXXXXX,ou=All Businesses,dc=cdiad,dc=XXXXX,dc=com'  I have not found an example in the doc that shows this form of the user, but it works. Domain/sso and sso for user name did not work. The example may be there and I just missed it.

Thanks for the help.

**Comment by cannatag** [comment]
Good. That's the full dn format I was talking about in my previous messages.

Bye,
Giovanni
