### ISSUE TITLE
tests failed on import

### ISSUE THREAD

**Issue by socketpair** [cannatag/ldap3#333]
```
DEBUG: ERROR: Failure: ImportError (cannot import name 'random_id')
DEBUG: ----------------------------------------------------------------------
DEBUG: Traceback (most recent call last):
DEBUG:   File "/usr/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
DEBUG:     raise self.exc_val.with_traceback(self.tb)
DEBUG:   File "/usr/lib/python3.5/site-packages/nose/loader.py", line 414, in loadTestsFromName
DEBUG:     addr.filename, addr.module)
DEBUG:   File "/usr/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
DEBUG:     return self.importFromDir(dir_path, fqname)
DEBUG:   File "/usr/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
DEBUG:     mod = load_module(part_fqname, fh, filename, desc)
DEBUG:   File "/usr/lib64/python3.5/imp.py", line 234, in load_module
DEBUG:     return load_source(name, filename, file)
DEBUG:   File "/usr/lib64/python3.5/imp.py", line 172, in load_source
DEBUG:     module = _load(spec)
DEBUG:   File "<frozen importlib._bootstrap>", line 693, in _load
DEBUG:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
DEBUG:   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
DEBUG:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
DEBUG:   File "/builddir/build/BUILD/ldap3-2.2.2/test/testAbandonOperation.py", line 28, in <module>
DEBUG:     from test import random_id, get_connection, drop_connection
DEBUG: ImportError: cannot import name 'random_id'
```

also, PLEASE make `setup.py test` working (not just return success).

**Comment by cannatag** [comment]
Are you trying the test suite of ldap3? The random_id function is in the test directory, it should be easily found by the test runner. 

Instead of using nose you can also try with the unittest python module.  Try with 'python -m unittest' at the ldap3 folder level. Also you must have a target ldap server to use.

**Comment by socketpair** [comment]
Yes, I'm testing ldap3.
1. Inserting big bunch of code in `__init__.py`  is very wrong pattern, as I think.
2. It will be nice if tests can be completed without ldap-server.
3. You did not mentioned in documentation how to run tests, so I looked into https://travis-ci.org/cannatag/ldap3 to know how to run tests.

**Comment by cannatag** [comment]
I know. Tests are most for my internal lab, so I didn't document it well. Anyway you can test against an LDAP server I have in cloud, that's the one used when tests are running on Travis. 

Being a client library ldap3 features must be tested against a real server. That's different from when you use ldap3 in an application. In that case you can use the ldap3 internal mocking capability to perform unit tests of your application without the need of a real ldap server.

**Comment by cannatag** [comment]
Hi,
I've moved test configuration from __init__,py to config.py. Also have performed some minor changes to tests. Now running tests should be as easy as ``python -m unittest discover test`` from the project directory.

Let me know if this works for you.

**Comment by socketpair** [comment]
Do they still require real LDAP-server ?

**Comment by cannatag** [comment]
Yes, you can use the server defined for Travis testing.
