### ISSUE TITLE
do_next_range_search doesn't fetch all group members

### ISSUE THREAD

**Issue by jamesdoherty** [cannatag/ldap3#336]
We have some large AD groups (5000+ members) and I've found that auto_range behaves inconsistently (Python 3.5). When retrieving group members multiple times, I end up with a different number of group members (either the real number or a multiple of 1500). I believe that I have found the source of this issue here in the do_next_range_search method: [https://github.com/cannatag/ldap3/blob/master/ldap3/strategy/base.py#L668](url)

```python
if not done:
    attr_name = list(filter(lambda a: ';range=' in a, current_response['raw_attributes'].keys()))[0]
    continue
```

In my testing, current_response['raw_attributes'].keys() returns two 'member' attributes (eg 'member;range=4500-5999', 'member;range=4500-*') but it doesn't always return them in the same order. When the attributes are returned in a different order, the other member attribute is used, causing the loop to finish prematurely.

I have been able to correct this behaviour by sorting and reversing the list of attributes before the first list element is selected.

```python
current_attributes = list(filter(lambda a: ';range=' in a, current_response['raw_attributes'].keys()))
attr_name = sorted(current_attributes, reverse=True)[0]
```

This may be related to #314

**Comment by cannatag** [comment]
I've slightly modified the do_next_range_search_method. The problem should be that for the last range AD doens't return in the range the exact number of entries found but keeps the * used in the query. This could lead to ambiguity when collecting the values found.

Can you check code in dev? Let me know if you still have the problem.

Thanks,
GIovanni

**Comment by jamesdoherty** [comment]
Thank you, that seems to have fixed the problem. All group members are now consistently retrieved.

**Comment by cannatag** [comment]
Good. Will be released in version 2.2.3.

**Comment by cannatag** [comment]
Released in ldap3 v. 2.2.3.

**Comment by nevillemendonca** [comment]
Hi Giovanni,
I have a setup where I have configured OpenLDAP as a Proxy to Active Directory. I am trying to use ldap3 to fetch members (member attribute) from an AD group via the OpenLDAP Proxy, the member count is more than 1500. The results are returned in ranges, ldapsearch and other LDAP browsers return the range 0-1499. However, when I do the search using the ldap3 (ldap3 __version__ = '2.8.1', Python version 3.6.8) API below I get an error. Can you help?

Here is the code:

server = ldap3.Server(host='myhost.org:1389', allowed_referral_hosts=True, tls=tls)
connection = Connection(server, auto_bind=auto_bind, auto_range=True)
connection.search(search_base='cn=mygroup,ou=Universal Groups,ou=my Groups,dc=my,dc=company,dc=org', search_filter='(objectClass=*)', search_scope=ldap3.BASE, attributes=['member'])


Here is the error:

    connection.search(search_base='cn=mygroup,ou=Universal Groups,ou=my Groups,dc=my,dc=company,dc=org', search_filter='(objectClass=*)', search_scope=ldap3.BASE, attributes=['member'])
  File "/usr/lib/python3.6/site-packages/ldap3/core/connection.py", line 846, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/lib/python3.6/site-packages/ldap3/strategy/sync.py", line 139, in post_send_search
    responses, result = self.get_response(message_id)
  File "/usr/lib/python3.6/site-packages/ldap3/strategy/base.py", line 409, in get_response
    if self.do_search_on_auto_range(self._outstanding[message_id], response):
  File "/usr/lib/python3.6/site-packages/ldap3/strategy/base.py", line 733, in do_search_on_auto_range
    self.do_next_range_search(request, resp, attr_name)
  File "/usr/lib/python3.6/site-packages/ldap3/strategy/base.py", line 717, in do_next_range_search
    attr_name = list(filter(lambda a: ';range=' in a, current_response['raw_attributes'].keys()))[0]
IndexError: list index out of range

Thank you,
Neville
