### ISSUE TITLE
oid - asn1 definitions

### ISSUE THREAD

**Issue by profhase** [cannatag/ldap3#340]
Hi, thanks again for great work.
I need a lot of novell extended Operations and I wanted to contribute to this library by implementing it.

The functions that you are using are easy to read and to extend (cudos), I just don't understand where you could find the asn1 specs for the responses:

## Example:
I wanted to add a Replica, so I defined analogously to your classes

```
class AddReplicaRequestValue(Sequence):
    tagSet = TagSet()
    componentType = NamedTypes(NamedType('flags', Integer()),
                               NamedType('replica_type', Integer()),
                               NamedType('server_dn', LDAPDN()),
                               NamedType('partition_dn', LDAPDN())
                               )
```
This definition I got from:
https://www.novell.com/documentation/developer/jldap/jldapenu/api/com/novell/ldap/extensions/AddReplicaRequest.html

The Response has the OID: `2.16.840.1.113719.1.27.100.8`

For this OID there is no Java Class documentation, nor could I find an ASN.1 definition anywhere. How did you proceed

**Comment by cannatag** [comment]
Hi, thanks for your message. eDirectory is my primary LDAP production environment at work so I have done some additional research on the novell extension operations. You can find some info in a rare documents or  in the NDK examples. Also there are some outdated RFC from Novell that refers to replica operations, for example  https://tools.ietf.org/html/draft-khan-ldapext-replica-mgmt-00

I would be glad to include more operations for eDirectory, let me know if you need additional help.

Bye,
Giovanni
