### ISSUE TITLE
connection.result['controls'] KeyError with MOCK_SYNC strategy

### ISSUE THREAD

**Issue by kiddick** [cannatag/ldap3#343]
Trying to perform tests for paged search so using following request:
```
connection.search('DC=org,DC=com', '(objectclass=person)', paged_size=2, size_limit=2)

>>> connection.result
python.py:1574
{'message': '', 'type': 'searchResDone', 'description': 'success', 'result': 0, 'referrals': None, 'dn': ''} 
```
but there is no `controls` in result

Server mocked with
```
        schema = SchemaInfo.from_json(ad_2012_r2_schema)
        info = DsaInfo.from_json(ad_2012_r2_dsa_info, schema)
```

Entries added dynamically by:
```
connection.strategy.add_entry(entry['dn'], entry['raw'])
```

**Comment by kiddick** [comment]
Looks like `def post_send_search(self, payload):` from `mockSync.py` doesn't care about paginated search :(

**Comment by cannatag** [comment]
Hi, 
the mock strategy recognize only the standard ldap operations. Paginated search is done through controls and these are not read by the strategy. I know that paginated search is widely used, I will eventually implement it in the mock strategies.

**Comment by kiddick** [comment]
Would be great!

**Comment by cannatag** [comment]
I've added paged search in mock strategies. Can you check the code in dev?

**Comment by kiddick** [comment]
Great work! I've tested pagination in tests. It is ok :+1:

**Comment by kiddick** [comment]
I am trying to perform search with reestablishing connection.
```
server = Server(IP,  get_info=ALL)
conn = Connection(server, USER_DN, PASSWORD, raise_exceptions=True)
conn.bind()
conn.search('OU=Test,DC=test,DC=demo', '(&(objectclass=person)(cn=filter*))', paged_size=100)
cookie = conn.result['controls']['1.2.840.113556.1.4.319']['value']['cookie']
conn2 = Connection(server, USER_DN, PASSWORD, raise_exceptions=True)
conn2.bind()
conn2.search('OU=Test,DC=test,DC=demo', '(&(objectclass=person)(cn=filter*))', paged_size=100, paged_cookie=cookie)
```
On live server that wokrs ok. So new connection could return next page by cookie from another connection,
But in tests I am getting failure. Seems `PagedSearchSet` shoul be global. And we need somehow match existing instance by provided cookie value. What do you think?


https://github.com/cannatag/ldap3/blob/dev/ldap3/strategy/mockBase.py#L618

**Comment by cannatag** [comment]
Hi, 
In my opinion the server should not accept a cookie from a different connection. RFC 2696 states that: 

"""
Returning cookies from previous searchResultDone responses besides the last one is undefined, as the server implementation may restrict cookies from being reused.
"""

So if you start a search in a session and then use the received cookie in another session you don't have a "previous searchResultDone" so the cookie from the previous session should have no meaning on the current one.

Also, what if in the new session the authenticated user has rights that differ from those of the first session user?

What ldap server are you using? I've not tried this on a real server (will do anyway) but I think that cookies are local to the user session and should not be shared.

Lastly, what is your use case? Why do you need to change your session during a paged search?

**Comment by kiddick** [comment]
It is Windows Active Directory server. I have certain user to interact with AD (mainly search entries). So I am reestablishing connection with same user.

Yeah that it kinda weird behavior, but it is business logic requirements.
