### ISSUE TITLE
Server Mocking

### ISSUE THREAD

**Issue by s0undt3ch** [cannatag/ldap3#352]
I haven't had the time to take the new mock approach for a spin and I'd like to find out something before I do.

Even though we create a server object, all the mocking happens on the client side connection right?

I'm unable to create that server, feed it the schema, etc,**and** entries, and then connect to that server instance using TCP as if it was running on a separate process, right?

My testing needs requires that my application runs on a subprocess and it needs to connect to an LDAP server using your library, so, I can't really mock the client side of the connection....

**Comment by cannatag** [comment]
Hi Pedro,
the "fake" server is  embedded in the Mock strategy so it's completely included in the client side. In your case you can define the connection in your subprocess and the server will "live" in the same subprocess. You don't need to care about the TCP/IP session, all you have to do is to populate the fake server DIT as explained in the ldap3 documentation. This doesn't works  if you must access the same server from two or more subprocesses. If this is your case you must use a different approach, where each subprocess uses its own fake server that is synchronized with the other (as a multi-replica scenario).

Let me know what is your intended use.

Bye,
Giovanni
