### ISSUE TITLE
.search() on a Mocked Connection Returns False

### ISSUE THREAD

**Issue by shuchow** [cannatag/ldap3#359]
Hi, I'm not sure if I'm doing this correctly.  I've created a fake connection, copying most of the example doc code on mocking.  This function is designated as the side effect in my test and is definitely getting successfully called instead of the real function when the test is run.

    def not_a_ldap_hit(self, login, password):

        # Create a fake server from the info and schema json files
        fake_server = Server('my_fake_server', get_info=OFFLINE_AD_2012_R2)

        # Create a MockSyncStrategy connection to the fake server
        fake_connection = Connection(fake_server, user='cn=my_user,ou=test,o=lab', password='my_password',
                                     client_strategy=MOCK_SYNC)

        # Add a fake user for Simple binding
        fake_connection.strategy.add_entry('cn=my_user,ou=test,o=lab',
                                           {'userPassword': 'my_password', 'sn': 'user_sn', 'revision': 0})

        # Bind to the fake server
        fake_connection.bind()
        search_filter = '(objectclass=*)'
        fake_connection.search("ou=test,o=lab", search_filter, attributes=ALL_ATTRIBUTES)

        return fake_connection.entries

The problem is that fake_connection.search() always returns False, and thus, fake_connection.entries is always empty.  The fake_connection, though, is successfully being set up.

Am I using .search() in this context correctly?

**Comment by cannatag** [comment]
Hi,
you didn't specify an objectClass in the entry, so the ``(objectclass=*)`` filter correctly doesn't return anything. Please change the filter to something like ``(sn=*)`` or add the ``'objectClass': 'inetOrgPerson'`` attribute to the entry.

**Comment by shuchow** [comment]
Ah, great.  Thank you.  That did it. 

However, I see that the search results are not populating fake_connection.entries.   fake_connection.response_to_file() does work, and I see the search results in the output file.  Is there a way to populate fake_connection.entries after a search operation under mocking?

**Comment by cannatag** [comment]
In my tests it works, please try the following:

```
from ldap3 import Server, Connection, OFFLINE_AD_2012_R2, MOCK_SYNC, ALL_ATTRIBUTES

def not_a_ldap_hit(login, password):

    # Create a fake server from the info and schema json files
    fake_server = Server('my_fake_server', get_info=OFFLINE_AD_2012_R2)

    # Create a MockSyncStrategy connection to the fake server
    fake_connection = Connection(fake_server, user='cn=my_user,ou=test,o=lab', password='my_password',
                                 client_strategy=MOCK_SYNC)

    # Add a fake user for Simple binding
    fake_connection.strategy.add_entry('cn=my_user,ou=test,o=lab',
                                       {'objectClass': 'inetOrgPerson',
                                           'userPassword': 'my_password',
                                        'sn': 'user_sn',
                                        'revision': 0})

    # Bind to the fake server
    fake_connection.bind()
    search_filter = '(sn=*)'
    fake_connection.search("ou=test,o=lab", search_filter, attributes=ALL_ATTRIBUTES)

    return fake_connection.entries

if __name__ == '__main__':
    entries = not_a_ldap_hit('cn=my_user,ou=test,o=lab', 'my_password')
    print(entries)
```

**Comment by shuchow** [comment]
Sorry for the delay.  Entries is still not getting populated.  I ran your script as is:

`/Users/user1/Development/ff/bin/python3 /Users/user1/Development/ff-app/server/flaskapps/ff-app/ldap_mock.py
Traceback (most recent call last):
  File "/Users/user1/Development/ff-app/server/flaskapps/ff-app/ldap_mock.py", line 27, in <module>
    entries = not_a_ldap_hit('cn=my_user,ou=test,o=lab', 'my_password')
  File "/Users/user1/Development/ff-app/server/flaskapps/ff-app/ldap_mock.py", line 24, in not_a_ldap_hit
    return fake_connection.entries
  File "/Users/user1/Development/ff/lib/python3.6/site-packages/ldap3/core/connection.py", line 1392, in entries
    self._entries = self._get_entries(self.response)
  File "/Users/user1/Development/ff/lib/python3.6/site-packages/ldap3/core/connection.py", line 1420, in _get_entries
    Reader(self, object_def, self.request['base'], self.request['filter'], attributes=attr_set) if self.strategy.sync else Reader(self, object_def, '', '', attributes=attr_set))
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1`

**Comment by cannatag** [comment]
I have no problems running the code. This is what I get:
```
# python test1.py
[DN: cn=my_user,ou=test,o=lab - STATUS: Read - READ TIME: 2017-06-13T19:59:28.403738
    cn: my_user
    entryDN: cn=my_user,ou=test,o=lab
    objectClass: organizationalPerson
                 user
                 person
                 top
                 inetOrgPerson
    revision: 0
    sn: user_sn
    userPassword: my_password
```

 Are you using the latest version of ldap3 (2.2.4)?

**Comment by cannatag** [comment]
Any news on this issue? I'm going to release the 2.2.5 version of ldap3 and I'd like to include any fix needed for your issue.

Giovanni

**Comment by shuchow** [comment]
Shoot, my apologies.  I was out of down and wasn't able to get back to this.  It turns out our server had 2.1.1 installed.  Once I got it upgraded to 2.2.4, search() is working correctly and entries is updated with results.
