### ISSUE TITLE
Functionality to keep connections open with ResuableStrategy

### ISSUE THREAD

**Issue by mikebarris** [cannatag/ldap3#367]
Does the reusable strategy support sending TCP keep-alives on pooled connections to prevent server side closures? The hope is to keep a minimum number of connections open and bound in the pool. Low traffic volumes cause connections to close and slowness as the pool is rebuilt.

**Comment by cannatag** [comment]
Hi Mike, 
To "keep alive" he connection usually you can use an Abandon(0) operation that is a harmless operation. I could include this in the worker thread of each connection inside a Reusable connection. Do you think this could be a good solution to this issue?

Giovanni

**Comment by mikebarris** [comment]
As an alternative what are your thoughts for enabling keep-alive directly on the sockets. Please check out  my changes in this commit as an example.

https://github.com/mikebarris/ldap3/commit/25966b40acc6f7a539aaa1144f035b95625bd85c

Please note, I am unable to check these changes against Windows and OSX but did my best to account for them based on internet examples.

**Comment by cannatag** [comment]
I'm not sure if this works. The LDAP server could be not aware of the socket status and could simply close the connection if there is no LDAP operations in a specific amount of time, even if the socket is active. Sending a valid LDAP operation should reset the timeout both at the socket and at the server level.

**Comment by cannatag** [comment]
Please check code in dev. I've added a ``pool_keepalive`` parameter to the Connection object. This parameter sets the number of seconds to wait before sending and Abandon(0) operation in an open connection in the connection pool. 

I think this could be better than keepalive at the socket level.

Let me know if this works for you.

**Comment by cannatag** [comment]
Fixed in release 2.3 of ldap3.
