### ISSUE TITLE
Re-licensing to BSD

### ISSUE THREAD

**Issue by amarjayr** [cannatag/ldap3#374]
I'd really like to use this library in [Redash](https://github.com/getredash/redash) (https://github.com/getredash/redash/pull/1836), but can't because this is LGPL3 licensed and Redash is BSD3. Would you consider re-licensing this project to BSD or having a dual license?

**Comment by cannatag** [comment]
I think you can use an LGPL3 licensed project in your BSD3 licensed project. You don't need to include only BSD3 licensed projects in a BSD3 licensed project.

Just declare that the ldap3 project uses the LGPL3 project and you're ok.

Bye,
Giovanni
