### ISSUE TITLE
Modify uid

### ISSUE THREAD

**Issue by Mioleris** [cannatag/ldap3#375]
How to modify users UID ? When using modify it returns False. I have permissions to modify uid.

Or just simply delete user and create new one ?

**Comment by cannatag** [comment]
Hi, after the modify operation you can check the error message in the connection.result dictionary. 

It should include an error code and a description. What is its content? 

What ldap server are you connecting to? Maybe it has some limitations on changing uid, maybe it's used in the dn. In the latter case you could try a modify_dn operation.
