### ISSUE TITLE
Docs related to Server Pool seems outdated

### ISSUE THREAD

**Issue by kiddick** [cannatag/ldap3#377]
http://ldap3.readthedocs.io/server.html?highlight=round#server-pool

Can't find POOLING_STRATEGY_ROUND_ROBIN

**Comment by cannatag** [comment]
In version 2 of ldap3 I've simplified some CONSTANT names. POOLING_STRATEGY_ROUND_ROBIN is just ROUND_ROBIN and is documented in the page you're referring to.
