### ISSUE TITLE
modify operations not preserved through referral

### ISSUE THREAD

**Issue by Busuwe** [cannatag/ldap3#383]
When connecting to an LDAP server that returns a referral on modify, only the last operation is performed for an attribute. The same behavior is not observed when connecting directly to the master server, where all operations are performed.

The connection object is setup the same in both cases, with only the "hostname" in one case being the master and in the other case a slave (which returns a referral to the master)

    serverLDAP = ldap3.Server(host = hostname, port = 636, 
        use_ssl = True, connect_timeout = 3, get_info=ldap3.ALL)
    conn = ldap3.Connection(serverLDAP, lazy = False, raise_exceptions = True,
        authentication = ldap3.SIMPLE, check_names=True, user=userDN, password=password)
    conn.bind()

I then modify an object's description field, which has been manually reset to ["foo"] after each attempt.

    conn.modify("cn=my_test_group,ou=Groups,dc=domain,dc=local",
        {'description': [
            (ldap3.MODIFY_ADD, ["bar"]),
            (ldap3.MODIFY_DELETE, ["foo"])
    ]})

The expected behavior is of course that the description field should contain ["bar"] afterwards.
When making the change directly on the LDAP master, the audit logs the change as expected:

    dn: cn=my_test_group,ou=Groups,dc=domain,dc=local
    changetype: modify
    add: description
    description: bar
    -
    delete: description
    description: foo

But when making the change on the slave and following the referral the master audit logs the following:

    dn: cn=my_test_group,ou=Groups,dc=domain,dc=local
    changetype: modify
    delete: description
    description: foo

If I reverse the order of the two operations or add additional operations on the same object, it's still only the last operation that is actually performed.
The same behavior is seen when the attribute has multiple values before the modification.
If I attempt to modify two attributes at the same time (with more than one operation each) then only the last operation in each of the attributes is performed.

The test was done towards OpenLDAP/slapd v2.4.44, using python 3.5.0 and 3.6.1 with ldap3 v2.2.4.

**Comment by Busuwe** [comment]
Seems like the culprit is ldap3.protocol.convert.prepare_changes_for_request (called from do_operation_on_referral in ldap3.strategy.base).
Data that goes in:

    [{'operation': 0, 'attribute': {'type': 'description', 'value': ['hiho']}}, {'operation': 1, 'attribute': {'type': 'description', 'value': ['moo']}}]
Data that comes out:

    {'description': (1, ['moo'])}

**Comment by cannatag** [comment]
thanks for your thorough analysis, I will include your fix in the next release of ldap3.

**Comment by cannatag** [comment]
Fixed in release 2.3 of ldap3.
