### ISSUE TITLE
LDAPSocketOpenError('socket ssl wrapping error: [SSL: WRONG_VERSION_NUMBER] wrong version number 

### ISSUE THREAD

**Issue by katul27** [cannatag/ldap3#385]
I am getting above error for below tls ctx,
tls = Tls(local_private_key_file = 'www.example.com.key.pem',
              local_certificate_file = 'www.example.com.cert.pem',
              validate = ssl.CERT_OPTIONAL,
              version = ssl.PROTOCOL_TLSv1_2,
               ca_certs_file = 'ca-chain.cert.pem')

 have below version of
openssl: OpenSSL 1.0.1e-fips
python: Python 2.7.5

i can understand that this error is coming because of some version mismatch, can some guide me to resolving this issue.

**Comment by cannatag** [comment]
Are you sure that the server you're connecting to is listening in SSL mode?
This error commonly occurs when trying to connect with SSL on a socket that is not negotiating SSL.

**Comment by katul27** [comment]
My local LDAP test server will wait on TCP connection, once it will receive extended TLS request, then it will go to TLS handshake, after that i m doing connection.start_tls(), but again getting same error,

thinking some sequence is missing. Can guide me the creating TLS connection with LDAP server.

**Comment by cannatag** [comment]
What happens if you try without any Tls() configuration? ldap3 has a Tls default configuration that let you accept any certificate. Please try the following:

```
from ldap3 import Server, Connection
s = Server('my_server')
c = Connection(s, 'my_user', 'my_password')
c.bind()
print(c)  # to check the connection status
c.start_tls()
print(c)  # to check the connection status
...
```

send me the output of this snippet of code with server, username and password adjusted to your configuration.

Bye,
Giovanni

**Comment by katul27** [comment]
I am running below script,

#!/usr/bin/python

# import class and constants
import ssl
from ldap3 import Server, Connection, Tls, ALL

# define the server
t = Tls(validate=ssl.CERT_NONE)
server = Server(host='localhost', port=*********, use_ssl=True, tls=t)
# define the connection
c = Connection(server, user='****************', password='*************', auto_bind='NONE', version=3, authentication='SIMPLE')
c.start_tls()
c.bind()
print(c.result)
#close connection
c.unbind()

Getting below error, but I run python LDAP module same thing then it is working, so I am not able to figure out what and where is the problem.

**Comment by katul27** [comment]
Output of above script 
ldap://localhost:389 - cleartext - user: username - not lazy - bound - open - <local: [::1]:39618 - remote: [::1]:389> - tls not started - listening - SyncStrategy - internal decoder
Traceback (most recent call last):
  File "./temp.py", line 8, in <module>
    c.start_tls()
  File "build/bdist.linux-x86_64/egg/ldap3/core/connection.py", line 1205, in start_tls
  File "build/bdist.linux-x86_64/egg/ldap3/core/tls.py", line 244, in start_tls
  File "build/bdist.linux-x86_64/egg/ldap3/core/connection.py", line 1169, in extended
  File "build/bdist.linux-x86_64/egg/ldap3/strategy/base.py", line 298, in send
  File "build/bdist.linux-x86_64/egg/ldap3/strategy/base.py", line 623, in decode_request
  File "build/bdist.linux-x86_64/egg/ldap3/operation/extended.py", line 58, in extended_request_to_dict
  File "build/bdist.linux-x86_64/egg/pyasn1/type/base.py", line 240, in __nonzero__
  File "build/bdist.linux-x86_64/egg/pyasn1/type/base.py", line 159, in plug
pyasn1.error.PyAsn1Error: Uninitialized ASN.1 value ("__nonzero__" attribute looked up)

**Comment by cannatag** [comment]
Do not set use_ssl=True because y
ou told me that the server is listening on a plain (insecure) socket. Also try without the tls=t parameter in the connection object,letting ldap3 to use its default.

**Comment by etingof** [comment]
Just a friendly hint that this error happens because you are trying to evaluate a ASN.1 value which did not come from the remote end. I'd suggest changing the condition like this:

     return {'name': str(request['requestName']), 'value': bytes(request['requestValue']) 
                 if request['requestValue'].isValue else None}

Or adding another one (first see if the value is present then see if it's not an empty string / numeric zero):

     return {'name': str(request['requestName']), 'value': bytes(request['requestValue'])
                 if request['requestValue'].isValue and request['requestValue'] else None}

If you need to maintain backward compatibility with the older pyasn1, then the `.hasValue()` function call can be used instead.

**Comment by katul27** [comment]
remove use_ssl and remove tls=t, then starting start_tls() getting below error

Traceback (most recent call last):
  File "./newwithtlsldapbindwithldap3.py", line 16, in <module>
    c.start_tls()
  File "build/bdist.linux-x86_64/egg/ldap3/core/connection.py", line 1205, in start_tls
  File "build/bdist.linux-x86_64/egg/ldap3/core/tls.py", line 244, in start_tls
  File "build/bdist.linux-x86_64/egg/ldap3/core/connection.py", line 1169, in extended
  File "build/bdist.linux-x86_64/egg/ldap3/strategy/base.py", line 305, in send
ldap3.core.exceptions.LDAPSocketOpenError: unable to send message, socket is not open

**Comment by cannatag** [comment]
You must bind() or open() the connection before using start_tls().

**Comment by katul27** [comment]
Just one query c.start_tls() send first extended request for start tls and then client hello??? how is implemented??

**Comment by katul27** [comment]
@cannatag again got below error,

  File "./newwithtlsldapbindwithldap3.py", line 16, in <module>
    c.start_tls()
  File "build/bdist.linux-x86_64/egg/ldap3/core/connection.py", line 1205, in start_tls
  File "build/bdist.linux-x86_64/egg/ldap3/core/tls.py", line 244, in start_tls
  File "build/bdist.linux-x86_64/egg/ldap3/core/connection.py", line 1169, in extended
  File "build/bdist.linux-x86_64/egg/ldap3/strategy/base.py", line 298, in send
  File "build/bdist.linux-x86_64/egg/ldap3/strategy/base.py", line 623, in decode_request
  File "build/bdist.linux-x86_64/egg/ldap3/operation/extended.py", line 58, in extended_request_to_dict
  File "build/bdist.linux-x86_64/egg/pyasn1/type/base.py", line 240, in __nonzero__
  File "build/bdist.linux-x86_64/egg/pyasn1/type/base.py", line 159, in plug
pyasn1.error.PyAsn1Error: Uninitialized ASN.1 value ("__nonzero__" attribute looked up)

**Comment by cannatag** [comment]
start_tls() wraps a plain socket in a ssl socket. So the socket must exist. If you don't want to send the password in cleartext just open() the connection, issue the start_tls() and then bind() with your credentials.

**Comment by cannatag** [comment]
Which version of pyasn1 are you using?

**Comment by katul27** [comment]
@cannatag  did same but still getting same error, 
version info is below
Name: pyasn1
Version: 0.2.4

**Comment by cannatag** [comment]
Could you try reverting to a previous pyasn1 version?

**Comment by cannatag** [comment]
Thanks Ilya, will check the code later.

**Comment by etingof** [comment]
> Could you try reverting to a previous pyasn1 version?

I doubt the reverting would help. It looks like this problem is triggered by a missing SSL cert extension that particular server serves to the client.

**Comment by katul27** [comment]
with pyasn1 0.1.9 version below script is woking,

import ssl
from ldap3 import Server, Connection, Tls, ALL
t = Tls(validate=ssl.CERT_NONE)
server = Server(host='myserver', port=port, tls=t)
c = Connection(server, user=username, password=password, auto_bind='NONE', version=3, authentication='SIMPLE')
c.open()
c.start_tls()
c.bind()
c.unbind()


just one query that Tls is an object is used during handshake on start_tls() or it is using default object??

**Comment by etingof** [comment]
Interesting! Let me look into that on pyasn1 side to figure out why it apparently used to work...

**Comment by katul27** [comment]
When i am chaning ssl protocol version getting below error,

version=ssl.PROTOCOL_TLSv1_1

File "./newwithtlsldapbindwithldap3.py", line 15, in <module>
    c.start_tls()
  File "build/bdist.linux-x86_64/egg/ldap3/core/connection.py", line 1205, in start_tls
  File "build/bdist.linux-x86_64/egg/ldap3/core/tls.py", line 265, in start_tls
  File "build/bdist.linux-x86_64/egg/ldap3/core/tls.py", line 280, in _start_tls
ldap3.core.exceptions.LDAPStartTLSError: wrap socket error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:579)

**Comment by cannatag** [comment]
The Tls object you pass is used either when opening a ssl socket and when wrapping a plain socket in a ssl transport layer. In this case you are requesting to not check the certificate.

**Comment by katul27** [comment]
it work for on TLSv1 version not for other TLSv1_1 and TLSv1_2

**Comment by cannatag** [comment]
Maybe your server doesn't understand TLS1.1 and TLS1.2?

**Comment by cannatag** [comment]
@etingof I updated the code as you suggested, inverting the sequence of conditions to check for existence of the attribute and used hasValue() to maintain compatibility:
```
return {'name': str(request['requestName']), 'value': bytes(request['requestValue'])
    if request['requestValue'] and request['requestValue'].hasValue() else None}
```

If this is ok I could use this checking pattern also in other portions of code.

**Comment by etingof** [comment]
@cannatag I believe you should first make sure that the [optional] `requestValue` field is present in the response by calling `.isValue` (or [.hasValue()](http://pyasn1.sourceforge.net/docs/type/univ/octetstring.html#pyasn1.type.univ.OctetString.hasValue)), if it evaluates to `True` you can attempt to evaluate the value e.g. not the other way round:

    if request['requestValue'].isValue and request['requestValue']:
        pass

Here is a small screencast on the matter:

    >>> from pyasn1_modules import rfc2251
    >>> r = rfc2251.ExtendedRequest()
    >>> list(r)
    ['requestName', 'requestValue']
    >>> r['requestName'].isValue
    False
    >>> r['requestValue'].isValue
    False
    >>> r['requestName'] = 'xxx'
    >>> r['requestName'].isValue
    True
    >>> if r['requestValue']: pass
    Traceback (most recent call last):
    ...
    pyasn1.error.PyAsn1Error: Uninitialized ASN.1 value ("__nonzero__" attribute looked up)
    >>> r['requestValue'] = 'yyy'
    >>> r['requestValue'].isValue
    True
    >>> if r['requestValue']: pass
    >>>

**Comment by cannatag** [comment]
Now I understand, thanks. In ldap3 for each production I have a function that returns a dict from the pyasn1 definition. Do you think that I have to add this additional check to every optional field in my pyasn1 definitions?

**Comment by etingof** [comment]
In general, you might want to check that the optional field is indeed present before doing anything with it.  You can't verify that by simple truth evaluation because that would make (for example) zero value indistinguishable from a missing field.

Could you point me to such case in the code?

**Comment by cannatag** [comment]
I have only 2 cases in my code (newSuperior in modifyDN requests and requestValue in Extended request). I've changed them to:

```
...
def modify_dn_request_to_dict(request):
    return {'entry': str(request['entry']),
            'newRdn': str(request['newrdn']),
            'deleteOldRdn': bool(request['deleteoldrdn']),
            'newSuperior': str(request['newSuperior']) if 'newSuperior' in request and request['newSuperior'] and request['newSuperior'].hasValue()  else None}

```
and
```
def extended_request_to_dict(request):
    # return {'name': str(request['requestName']), 'value': bytes(request['requestValue']) if request['requestValue'] else None}
    return {'name': str(request['requestName']), 'value': bytes(request['requestValue']) if 'requestValue' in request and request['requestValue'] and request['requestValue'].hasValue()  else None}
```

So I check first for presence, then for not being None and then for having a value. If I check for a a value before cheching for None I get a NoneType has not hasValue() method exception.

**Comment by katul27** [comment]
why connection.open() send ldapsearch request to LDAPServer, i see the in TCP Dump goes while open connection.

**Comment by cannatag** [comment]
Because when you open the connection the schema is read from the server, as requested by the LDAP RFCs. If you don't want this just use get_info=NONE when defining the server object. You must import NONE from the ldap3 namespace.

**Comment by katul27** [comment]
Getting "Read Error : short read" at server side while server receive unbind request, but when server receives LDAP unbind from ldapsearch from openldap, then there is no error, can some tell me how to close the unbind connection like below,

#close connection
connection.unbind()

and how openldap unbind is different than ldap3 unbind

**Comment by katul27** [comment]
From my analysis, TLS shutdown is not handled while sending unbind request.

**Comment by cannatag** [comment]
Fixed in release 2.3 of ldap3.

**Comment by katul27** [comment]
used 2.3 version but still facing same issue

**Comment by yassipo** [comment]
Facing same issue too

**Comment by maludwig** [comment]
To everyone having this issue, I'm on Mac OSX, connecting to our Windows Domain Controller. I was using the IP address of our server, I also tried the specific domain controller FQDN. I wasn't supposed to do either of those. Just use the domain itself. So if you're: maludwig@github.com, and your domain controller is, "dc01-03.github.com" with an IP of "10.0.1.13", then forget about the IP and the hostname, just use the domain "github.com", ex:

```
    server = Server("github.com", use_ssl=True, get_info=ALL)
    conn = Connection(server, user="github.com/maludwig", password="ULTASECUREPASSWORD", authentication=NTLM)
    conn.bind()
    print(conn.extend.standard.who_am_i())
    print(conn)
```

**Comment by DiegoPadillaZ** [comment]
In RHEL 8.1

vi /etc/crypto-policies/back-ends/opensslcnf.config

# Aggregate lines to the end of file:

#[system_default_sect]
MinProtocol = TLSv1.0
CipherString = DEFAULT@SECLEVEL=1

Works for me!
