### ISSUE TITLE
LDAPInvalidCredentialsResult after setting pwdLastSet

### ISSUE THREAD

**Issue by naaaargle** [cannatag/ldap3#389]
Hi! Ever since updating from ldap3 v1.3.3 to v2.2.4, the code I used to force users to reset their passwords on next login has instead been preventing users from logging in, raising an `LDAPInvalidCredentialsResult`:
```python
        with conn:
            conn.add(
                dn,
                object_class,
                attributes=attributes,
            )
            conn.extend.microsoft.modify_password(
                dn,
                'password',
            )
            conn.modify(
                dn,
                {
                    # 2 = modify/replace
                    # This enables the user. This can only happen once password is set.
                    # http://www.netvision.com/ad_useraccountcontrol.php
                    'userAccountControl': (2, '512'),
                    # Force user to reset password on login
                    'pwdLastSet': (2, 0),
                },
            )
```
In regards to the above code block, if I run the same code without modifying the `pwdLastSet` attribute, I am able to authenticate that user. 

Prior to the upgrade, I could manually set the password using the Active Directory interface, and then set `pwdLastSet` to `['0']`, and would be forced to change my password upon login. I don't immediately notice any difference in the user's attributes from before this upgrade vs. after - the `raw_attributes` still show `pwdLastSet: ['0']`. 

What's also interesting is that the `badPwdCount` does not increase when I try and fail to log in on these accounts.

Unsure if this is a bug or if there's something about this code that needs to change. Appreciate your help!

__Update:__ The point about badPwdCount not increasing is actually confirms that the password was set correctly at some point. Looks like it wasn't incrementing because [I was typing in one of the recent passwords](https://supportforums.cisco.com/discussion/12628401/ad-users-getting-locked-when-they-change-password). I was able to get it to increment when I typed in a bunch of random letters instead of the password I expected.

**Comment by naaaargle** [comment]
Update: The point about `badPwdCount` not increasing is probably irrelevant to what's happening. Looks like it wasn't incrementing because [I was typing in one of the recent passwords](https://supportforums.cisco.com/discussion/12628401/ad-users-getting-locked-when-they-change-password). I was able to get it to increment when I typed in a bunch of random letters instead of the password I expected.

**Comment by cannatag** [comment]
Hi, the code looks right to me. Is the older version still running? Are you able to send a log with the old and the new version?

**Comment by cannatag** [comment]
If I run your script I get an error because the "password" password is too simple. I have modified it as follow and it works:

```
from ldap3 import Server, Connection

s = Server('<MY_SERVER>', use_ssl=True)
conn = Connection(s, 'CN=Administrator,CN=Users,dc=AD2012,dc=LAB', '<MY_ADMIN_PASSWORD>')
domain_name = 'ad2012.lab'
dn = 'cn=test01,cn=users,dc=ad2012,dc=lab'
username = 'test01'
password = 'Ab123456cdef'

attributes = dict({'sn': username,
                   'sAMAccountName': username[-20:],  # 20 is the maximum user name length in AD
                   'userPrincipalName': username[-20:] + '@' + domain_name,
                   'displayName': username[-20:],
                   'unicodePwd': ('"%s"' % password).encode('utf-16-le'),
                   'userAccountControl': 512})


with conn:
    conn.add(
        dn,
        ['person', 'user', 'organizationalPerson', 'top', 'inetOrgPerson'],
        attributes=attributes,
    )

    conn.modify(
        dn,
        {
            # 2 = modify/replace
            # This enables the user. This can only happen once password is set.
            # http://www.netvision.com/ad_useraccountcontrol.php
            'userAccountControl': (2, '512'),
            # Force user to reset password on login
            'pwdLastSet': (2, 0),
        },
    )
```
In my case the domain is AD2012.LAB. Please substitute it and the MY_* variable with valid values for your environment. With this code I'm able to logon with test01 and password Ab123456cdef and the system force me to change the password. I'm using a Windows Server 2012 R2 server.

**Comment by naaaargle** [comment]
Haha I just put `password` as a placeholder, sorry that wasn't clear. I'll give this a try and loop back. Thanks for your quick response!

**Comment by naaaargle** [comment]
@cannatag Currently when I attempt to include `unicodePwd` in `attributes` I get an `LDAPUnwillingToPerformResult` exception. This is why instead I use the `extend.microsoft.modify_password` operation. I have been able to successfully modify passwords and authenticate using that function, but subsequently updating `pwdLastSet` results in the user being unable to log in.

I set up my `server` and `connection` a little differently than you did:

```python
server = ldap3.Server(
        host=host,
        use_ssl=True,
        tls=ldap3.Tls(
            ca_certs_file=ca_cert_path,
            version=ssl.PROTOCOL_TLSv1,
        ),
    )
conn = ldap3.Connection(
            server=server,
            auto_bind=ldap3.AUTO_BIND_TLS_BEFORE_BIND,
            read_only=False,
            raise_exceptions=True,
            user='{}\\{}'.format(<MY_ORG>, username),
            password=password,
        )
```
Unsure if that has anything to do with why I can't update `unicodePwd` directly.

Either way, though, it's clear that when I use `.modify_password`, and then reset `pwdLastSet`, the user is unable to log in. It almost seems as though setting `pwdLastSet` to 0 fully expires the password, rather than leads to the change password flow.

**Comment by cannatag** [comment]
The ``extend.microsoft.modify_password`` function uses the same ``unicodePwd`` I used in my snippet of code.  

The UnwillingToPerform result returned by the server means that some criteria are not met. For changing the password the connection must be secured over SSL, the password must be encoded with UTF-16 little endian encoding and the password policies set in your AD must be followed. 

In your code you've defined the server with the use_ssl parameter set to True. This means that the socket is open with TLS from the very beginning, so the auto_bind parameter can just set to True (it has no sent to issue a StartTLS operation on an already secured connection). Also, are you sure that the user used in the connection has the administrative role needed for creating new users?

**Comment by cannatag** [comment]
Please check your issue with the latest ldap3 2.3 version (just released). 

Thanks,
Giovanni

**Comment by naaaargle** [comment]
This wound up being an issue with our login software being incompatible with our Active Directory setup, not an ldap3 issue. Apologies for the false bug and thank you for your help! It did in the end help me find the issue.

Interestingly, though, due to how my server has to be set up, I cannot change unicodePwd directly, even if I enter it exactly as you did. However, the modify_password extension works quite well. This isn't an immediate problem for me, just throwing it in in case that's useful to know.

Take care!

**Comment by cannatag** [comment]
Ok, thanks for letting me know what the problem was. Don't hesitate to ask for help if you need.

Have fun,
GIovanni
