### ISSUE TITLE
Default Server Encoding docs don't match experience

### ISSUE THREAD

**Issue by jaraco** [cannatag/ldap3#390]
Using ldap3 2.2.4 on Python 2.7 and struggling with encoding issues (DN is latin-1 decoded UTF-8), I read [the docs]() which suggest to set the SERVER_DEFAULT_ENCODING, but when I do that, I get an error:

```
>>> ldap3.set_config_parameter('DEFAULT_SERVER_ENCODING', 'utf-8')
Traceback...
LDAPConfigurationParameterError: unable to set configuration parameter DEFAULT_SERVER_ENCODING
```

I also find if I only attempt to query for that parameter, I get a similar error.

The docs are a little confusing, demonstrating setting the config parameter to the literal `"server_encoding"`. That seems wrong, which is why I used `'utf-8'`. What's the correct usage there? What's causing the LDAPConfigurationParameterError? Do you have any advice for when non-ascii text in the dn attribute is appearing improperly decoded (using latin-1)?

Here's an example result I'm getting from a query:

`{'raw_dn': 'CN=G\xc3\xb6pel,OU=group,DC=local', 'raw_attributes': {}, 'dn': u'CN=G\
xc3\xb6pel,OU=group,DC=local', 'attributes': {}, 'type': 'searchResEntry'}`

As you can see, the non-ascii letter is incorrectly decoded.

**Comment by jaraco** [comment]
I see now the text from those docs was committed in 5b17b53c395, which has no release tag, so that functionality is probably not present.

Do you have any suggestions for us running on ldap3 2.2.4?

**Comment by jaraco** [comment]
Also, I should note that this behavior appears to be a regression. We have tests that ensure that this DN decodes properly before the app deploys. On a deployment of our app running against ldap3 2.2.2, the behavior seems to work, so I'm suspecting there's a regression between 2.2.2 and 2.2.4.

**Comment by cannatag** [comment]
You're right, I'm about to release version 2.2.5 but the changes in pyasn1 are delaying the release of this version. In the meanwhile you could try with the version in dev on github. You can also check the ADDITIONAL_ENCODINGS parameter, that in 2.2.4 is limited to DN encodings, but in 2.2.5 is applied to all strings received from the server.

**Comment by cannatag** [comment]
ldap3 version 2.3 released.
