### ISSUE TITLE
Rebind with empty password could lead to a potential security issue

### ISSUE THREAD

**Issue by dmanchon** [cannatag/ldap3#393]
Problem: Rebind is comparing making this comparison to validate input data:
```python
if password:
    self.password = password
```
That condition is false in case of `password = ''`, so the old value of the object will be keep in that case, including case where the bind was correct.

This is a potential security hole, since a correct bind followed by a rebind with empty password will complete the binding correctly.

I have changed the way the password is checked to only check if None.
https://github.com/cannatag/ldap3/pull/392

**Comment by cannatag** [comment]
Thanks, will include your fix in the next release of ldap3.

**Comment by dmanchon** [comment]
Thanks a lot @cannatag

**Comment by cannatag** [comment]
Fixed in v2.4
