### ISSUE TITLE
ldap3.core.exceptions.LDAPAttributeError: invalid attribute SAMACCOUNTNAME

### ISSUE THREAD

**Issue by matthew-carroll** [cannatag/ldap3#398]
Using v2.2.4

I'm trying to run a search for a particular sAMAccountName and I'm getting the following exception:
ldap3.core.exceptions.LDAPAttributeError: invalid attribute SAMACCOUNTNAME

The same search works as expected in a ruby version of the script, but fails in python.  I also tried different capitalizations of sAMAccountName just in case its case sensitive, but I get the same exception in all cases.

Here is the code I'm using to run the bind and search:

```
server = Server(
    'ldaps://address', 
    port=636,
    use_ssl=True, 
    get_info=ALL
)

print "Connecting and binding..."
conn = Connection(
    server, 
    user='dn_user',
    password='password',
    authentication=SIMPLE,
    auto_bind=True
)
print conn
print ""

conn.search(search_base, '(SAMACCOUNTNAME=xxxx)', attributes=ALL_ATTRIBUTES)
print conn.entries
```

**Comment by cannatag** [comment]
Probably your ldap server is not returning the schema, so the attribute names validation fails. Try to set get_info=NONE. If it still fails please send me the full back trace of the exception.

**Comment by matthew-carroll** [comment]
Changing get_info to None appears to have solved the issue.  Thanks for the help.
