### ISSUE TITLE
how to turn results from search_paged into Entry objects

### ISSUE THREAD

**Issue by thomaswar** [cannatag/ldap3#404]
When doing a search_paged i do not (longer) get abstracted Entry objects, but a dict.

Is there a way to get abstracted entries from search_paged?

**Comment by cannatag** [comment]
Hi, I'm not able to replicate this with the Reader cursor, can you give me a snippet of code showing the issue?

Thanks

**Comment by thomaswar** [comment]
Hi,

the code that is creating the Readers (both show the same behaviour) is in:

https://github.com/edushare-at/py-etd/blob/dry-run/classes/ldap.py#L88

and

https://github.com/edushare-at/py-etd/blob/dry-run/classes/ldap.py#L103

its returns are iterated by:

https://github.com/edushare-at/py-etd/blob/dry-run/classes/loader.py#L157

ldap3==2.3

Context: The project is about converting and syncing data from LDAP->AD

Thanks

**Comment by cannatag** [comment]
I see that you use ``self.sync_dn.as_dn_string()`` as base of the Reader object. I presume that this method returns the Distinguished Name of the user you're about to sync. So the reader will always return 1 entry, there is no reason for the paged search (with size of 1000 entries) at all, you can just use the search() method of the Reader.

Anyway the paged search with only 1 entries should generate one entry and not a dict. Will have a look at the code to fix it.

**Comment by cannatag** [comment]
I've fixed the paged_search. It always return a list of entries All entries if generator=false and a generator if generator=True.

**Comment by thomaswar** [comment]
Sorry, that it took me so long to be able to test it: That fixed the behaviour. Thank you.

Btw: The base for the Reader is the ou containing the entries: For performance reasons, we are loading all (target + source) entries via paged search before comparing and syncing them.
