### ISSUE TITLE
Getting short read error, when client was connected to server on TLS connection, during unbind message

### ISSUE THREAD

**Issue by katul27** [cannatag/ldap3#405]
My server is giving "Getting short error" below is test case:
1. LDAP client is connected to LDAP server.
2. Pump some traffic to LDAP server, (everything is successful).
3. Send UNBIND request to the server, and got "short error" this is because the client is close the connection without handling TLS layer, can't able to close_notify from Client to server.

Please help me out to resolving this issue
LDAP3 version: ldap3-2.3
pyAsn1 version: pyasn1-0.1.9
python version : python2.7

**Comment by cannatag** [comment]
The unbind() operation actually shutdowns and closes the socket either it is plain or secured with TLS.
What LDAP server are you connecting to? There is some more detailed description of the error? Can you give me a trace of the operation?

**Comment by katul27** [comment]
Yes, unbind has to close to connection, but if the connection is in TLS mode then it has to close TLS socket first at both side (client and server). then need to close TCP connection.

This can see in python-LDAP program client but not in python-ldap3.

I

**Comment by cannatag** [comment]
Are you talking about the StartTls operation or about a SSL initiated connection?

**Comment by katul27** [comment]
I am talking about StartTls

**Comment by cannatag** [comment]
So you mean that before unbinding the client should remove the transport layer from the socket and return to the unsecure channel?

For what I know this is not required by the official LDAP RFCs. What LDAP server are you trying to connect to?
