### ISSUE TITLE
Recommendations for using connection pooling with frequent rebinds.

### ISSUE THREAD

**Issue by mikebarris** [cannatag/ldap3#410]
Hi,

This is just a question so hopefully this is the correct place to submit it.

We are looking for recommendations to minimize our open connections to LDAP. Our current configuration involves using pooled connections bound with a service account to make numerous calls to access data contained in our LDAP server. Additionally, we also use the LDAP server to authenticate users. To authenticate users we establish a new connection and attempt to bind with that users uname and password. This current flow causes problems because it establishes many connections to the LDAP server and we would rather utilize the pool since SSL handshakes and other TCP transactions have already been established. One idea is to rebind the pooled connection with the new user report success and then rebind back to the service account.

When reviewing the code rebinding on a pooled connection will be difficult because of two main hurdles.

- When calling rebind on a reusable pooled connection the code iterates over each worker and rebinds with the new user and password. This seems dangerous in our situation since all the connections in the pool will no longer be associated with the service account originally setup and now be bound to the user and password for the one authentication attempt. The fear is in high volume situations requests may come in before rebinding may occur.

- Rebind also appears to be lazy loaded by design which is great feature except we need to rely on a subsequent call to get the results of the bind. This feels problematic in high volume pooled instances.

Thanks for reviewing. Have you encountered any similar flows with the library? Do you have any recommendations to handle our use case?

**Comment by cannatag** [comment]
Hi,
with the Reusable strategy all the connection threads share the same user, so if you perform a rebind it will be propagated to every thread and performed when the thread as some other operation in queue. So this is not feasible in your scenario.

Iif your users use the Simple authentication method I suggest you to compare the password with the userPassword attribute of the user without performing any real authentication. Depending on your Ldap server you may need to prepare the password with some specific transformation. 
This is very fast and can be performed by an "admin" user with valid privileges.

If you uses another authentication method you have to perform the actual bind operation. In this case you can use the get_info=NONE parameter of the Connection object to not read the schema of the LDAP server, the bind should be much faster.

Bye,
Giovanni

**Comment by mikebarris** [comment]
Thanks you confirming my situation. I will look in to your recommendations. One question, did you mean get_info=None on the Server object? I do not see that argument in the Connection object code or documentation?

**Comment by cannatag** [comment]
You're right, it's the Server object.
