### ISSUE TITLE
AD password reset / custom request control

### ISSUE THREAD

**Issue by rbennett91** [cannatag/ldap3#417]
Hello,

My question deals with building and passing a custom request control to Active Directory.

I have a web application that resets AD passwords via an LDAP call. The goal is to enforce a password history constraint (no re-use of passwords) via AD. I've learned that AD has 2 methods of changing passwords:

1. a password _change_ (user enters the previous password & updates it to something new)
2. a password _reset_ (admin user resets a password with no knowledge of previous password)

A password reset does not enforce the password history constraint, per design. From some articles on the web, it appears to be possible to send a request control to AD to force a password reset to check password history, via this control: https://msdn.microsoft.com/en-us/library/hh128228.aspx.

I've thown together a quick 'n dirty script to test this out, but receive this LDAP error describing an unavailable extension:

{
    'description': 'unavailableCriticalExtension',
    'dn': u'',
    'message': u'00000057: LdapErr: DSID-0C090CAD, comment: Error processing control, data 0, v23f0x00',
    referrals': None,
    'result': 12,
    'type': 'modifyResponse'
}

Is there anything egregiously wrong in the following code? I've verified my AD instance supports the LDAP_SERVER_POLICY_HINTS_OID control (running Windows Server 2012). My apologies if this is the wrong place to ask. I'd be appreciative of any guidance.

```
from ldap3 import Server, Connection
from ldap3.extend.microsoft.modifyPassword import ad_modify_password
from ldap3.protocol.controls import build_control
from pyasn1.type.univ import Integer
from pyasn1.type.char import PrintableString
from pprint import pprint

server = Server(
    '<redacted>',
    port=636,
    use_ssl=True
)
connection = Connection(
    server,
    user='<redacted>',
    password='<redacted>',
    auto_bind=True
)

pw_history_control = build_control(
    '1.2.840.113556.1.4.2239',
    True,
    PrintableString(value='0x1'),
    True
)

changed = ad_modify_password(
    connection,
    '<redacted>',
    '<new_password_here>',
    old_password=None,
    controls=[(pw_history_control)]
)

print changed
pprint(connection.result)
```

**Comment by cannatag** [comment]
The asn.1 syntax is:


PolicyHintsRequestValue ::= SEQUENCE {      Flags    INTEGER  }

So you have to set the controlvalue accordingly, a printableString is not valid here because you’re sending the “0x1” value as a string 

You can check the pyasn.1 docs to build a Sequence made up of only an Integer.

I have not access to a Windows server now, will try in the next days.

Bye,
Giovanni

**Comment by etingof** [comment]
Let me offer a quick hint:

    from pyasn1.type.univ import Sequence, Integer
    from pyasn1.type.namedtype import NamedTypes, NamedType

    control = Sequence(
        componentType=NamedTypes(
            NamedType('Flags', Integer(0x1))
        )
    )

Once you have this defined, you can may or may not (here I'm not sure) serialize the above data structure before feeding it to the `ad_modify_password()` function:

    from pyasn1.codec.ber.encoder import encode

    changed = ad_modify_password(
        connection,
        '<redacted>',
        '<new_password_here>',
        old_password=None,
        controls=[encode(control)]
    )

**Comment by rbennett91** [comment]
Thank you both for the quick replies. I've solved my problem by issuing both an administrative password reset (with a random password) immediately followed by a password change (supplying the newly reset password). The history check is enforced on the password change. I'll mark this issue as resolved.
