### ISSUE TITLE
conn.modify documentation issue

### ISSUE THREAD

**Issue by korylprince** [cannatag/ldap3#42]
It looks like there is a documentation error on this page:
http://ldap3.readthedocs.org/en/latest/connections.html

Specifically, the changes structure for the modify operation is listed as:

    {‘attribute1’: [(operation, [val1, val2, ...])], ‘attribute2’: [(operation, [val1, val2, ...])]}

This does not work, giving `ldap3.core.exceptions.LDAPChangesError: malformed change`. Looking at the test code, it should be:

    {‘attribute1’: (operation, [val1, val2, ...]), ‘attribute2’: (operation, [val1, val2, ...])}

Thanks!
(There operation Tuple should not be enclosed in a list.)

**Comment by milliams** [comment]
I reported this two days ago at PR https://github.com/cannatag/ldap3/pull/40 and it looks like it's been fixed now in git at 56ad8d3e23a0cf.

**Comment by korylprince** [comment]
Awesome. Did not think to look for PRs about the issue.

It looks like the page has not updated yet. Is there a manual process to update the readthedocs page?

**Comment by cannatag** [comment]
Hi, there was a problem with the webhook for ReadTheDocs. I've fixed it now. Documentation should be updated.

Thanks,
Giovanni

**Comment by korylprince** [comment]
Thanks!

**Comment by nhoffman** [comment]
Hi - it looks like the examples of modify operations here

https://ldap3.readthedocs.org/modify.html

need to be updated as well.

**Comment by cannatag** [comment]
Hi, I've reverted the modify operation to the older signature (keeping compatibility with the newest) to be compatibile with the LDAP atomic operation (http://ldapwiki.willeke.com/wiki/LDIF%20Atomic%20Operations) that applies two or more changes to the same attribute in the same operation. This will be released in 0.9.8.6 but the docs were automatic rebuilt from the repository. 
I should release 0.9.8.6 very soon.

Thanks,
Giovanni

**Comment by nhoffman** [comment]
Thanks for clarifying! Appreciate your work on this project.

**Comment by cannatag** [comment]
0.9.8.6 released.

Bye,
Giovanni
