### ISSUE TITLE
ldap3.core.exceptions.LDAPInvalidValueError: value '4611686014132427209' non valid for attribute 'rIDAvailablePool'

### ISSUE THREAD

**Issue by gregn610** [cannatag/ldap3#424]
Upgrading versions from 2.2.2 to 2.3 is throwing an exception:
ldap3.core.exceptions.LDAPInvalidValueError: value '4611686014132427209' non valid for attribute 'rIDAvailablePool'

That attribute and value are coming from a Windows AD though. Similar errors on priorSetTime and lastSetTime attributes.

    from ldap3 import Server, Connection, ALL, ALL_ATTRIBUTES, MOCK_SYNC
    REAL_SERVER   = 'ldap://192.168.0.55'
    REAL_USER     = 'CN=Administrator,CN=Users,DC=acme,DC=dev'
    REAL_PASSWORD = 'Password1'
    
    # Retrieve server info and schema from a real server
    server = Server(REAL_SERVER, get_info=ALL)
    connection = Connection(server, REAL_USER, REAL_PASSWORD, auto_bind=True)
    
    # Store server info and schema to json files
    server.info.to_file('dump_ad_server.json')
    server.schema.to_file('dump_ad_schema.json')
    
    # Read entries from a portion of the DIT from real server and store them in a json file
    if connection.search('DC=acme,DC=dev', '(objectclass=*)', attributes=ALL_ATTRIBUTES):
        connection.response_to_file('dump_ad_entries.json', raw=True)
    
    # Close the connection to the real server
    connection.unbind()
    
    # Create a fake server from the info and schema json files
    fake_server = Server.from_definition('my_fake_server', 'dump_ad_server.json', 'dump_ad_schema.json')
    
    # Create a MockSyncStrategy connection to the fake server
    fake_connection = Connection(fake_server, user='cn=my_user,ou=test,o=lab', password='my_password', client_strategy=MOCK_SYNC)
    
    # Populate the DIT of the fake server
    fake_connection.strategy.entries_from_json('dump_ad_entries.json')
    
    # Add a fake user for Simple binding
    fake_connection.strategy.add_entry('cn=my_user,ou=test,o=lab', {'userPassword': 'my_password', 'sn': 'user_sn', 'revision': 0})
    
    # Bind to the fake server
    fake_connection.bind()

-ldap3==2.2.2
-pyasn1==0.2.3
+ldap3==2.3
+pyasn1==0.3.7

Thank you.

**Comment by cannatag** [comment]
Please can you provide the 'dump_ad_server.json' and 'dump_ad_schema.json' files so that I can be able to replicate the issue?

Thanks,
Giovanni

**Comment by gregn610** [comment]
https://gist.github.com/gregn610/e0e69fce688fe7e8a590995d8726635d
Thanks again.

**Comment by cannatag** [comment]
Thanks, I need the "dump_ad_entries.json" file too. Or at least a representation of the involved attributes.

**Comment by cannatag** [comment]
No need for the "dump_ad_entries.json" file. I've found the problem. In 2.4 the mock strategies check the correct value against the schema. In the file the rIDAvailablePool value is quoted but should be a "long integer", without quotes. I think is the same for the other attributes. 

Are you using an entries file generated by the 2.2.2 version of ldap3 against the 2.3 version? 

Will try to fix it in the next version of ldap3.

**Comment by cannatag** [comment]
Fixed in v2.4
