### ISSUE TITLE
Add the option to specify the socket for ldap3 (e.g. Use Socks5 Proxy of SSH)

### ISSUE THREAD

**Issue by Cellebyte** [cannatag/ldap3#429]
## Expected behaviour
* Proxy configuration for socks proxy
  * Easiest way is to pass socket from api to core
    * Object Connection(...,socket=None) in [ldap3/core/connection.py](ldap3/core/connection.py) 
* ldap3 binds through this proxy with the ldap-server to create a connection
with him behind a Firewall

## Outcome
* Use ssh to connect to an ssh Server and create a Dynamic Forward to interarct with a ldap server behind this ssh server
* This DynamicForward is used to pass all ldapsearch queries through the Proxy and get the required ldap information from the locked ldap server

### If this issue is no Issue, feel free to close it.

**Comment by cannatag** [comment]
I would be glad to include this feature, but I don’t use SOCKS in my testing lab, are you able to provide instruction on how to set up the environment to test it?

Thanks,
Giovanni

**Comment by Cellebyte** [comment]
## Setup 
* install openssh-server on your distribution
```bash
apt install openssh-server
```
* install PySocks [https://github.com/Anorov/PySocks](https://github.com/Anorov/PySocks)
```bash
pip install PySocks
```
## Testing local
* connect to this local server using 
```bash 
ssh -D Portnumber_for_socks_proxy $USER@localhost
```
* connect to the open socks port using python
```python
>>> import socks
>>> s = socks.socksocket() # normal socket
>>> s.set_proxy(socks.SOCKS5, "localhost", 5050)
>>> s.connect(("localhost", 636),("localhost", 389))
>>> s.sendall(b"") # speak the ldap protocol with the ldap server
```
## Testing remote
* connect to remote ssh server
```bash 
ssh -D Portnumber_for_socks_proxy $USER@$DN
```
* connect to the open socks port using python
```python
>>> import socks
>>> s = socks.socksocket() # normal socket
>>> s.set_proxy(socks.SOCKS5, "localhost", 5050)
>>> s.connect(("ldap.tls.example.com", 636),("ldap.no_tls.example.com", 389))
>>> s.sendall(b"") # speak the ldap protocol with the ldap server
```

**Comment by Cellebyte** [comment]
Solved by using a Local Forward and a standard tcp connect with your library.
Socks Support is a nice to have, when you do not want to deal with non matching fqdns between certificate and forwarding server.

Problem is that the paramiko library is not supporting socks at the moment.

```bash
ssh -D 8080 hostname.example.com -l username
```

is not supported by paramiko so you need to use this code above to create such a socks proxy socket.

**Comment by georgealverson** [comment]
I would find a pure socks-based solution very useful. I already have socks up and running. Establishing a new tunnel just for ldap is quite clumsy.
