### ISSUE TITLE
Generators for attribute values not accepted by Connection.modify()

### ISSUE THREAD

**Issue by milliams** [cannatag/ldap3#43]
I'm generating data for my database using generators but at the point it's being passed back to the database it's being interpreted incorrectly. I'm more or less doing:

```python
new_values = (i for i in range(3))
changes = {'testAttribute' : new_values}
connection.modify('ou=test,dc=example,dc=com', changes)
```

which ends up writing something like (retrieved using `ldapsearch` on the command line):

    dn: ou=test,dc=example,dc=com
    testAttribute:: PGdlbmVyYXRvciBvYmplY3QgPGdlbmV4cHI+IGF0IDB4N2Y3YTQ0ZjQwYTY4Pg==

which is the base64 encoded version of:

    dn: ou=test,dc=example,dc=com
    testAttribute: <generator object <genexpr> at 0x7f7a44f40a68>

but I would expect:

    dn: ou=test,dc=example,dc=com
    testAttribute: 0
    testAttribute: 1
    testAttribute: 2

So it's writing the `__str__` version of the object rather than iterating its values. This seems to come down to the explicit type testing happening at https://github.com/cannatag/ldap3/blob/master/ldap3/operation/modify.py#L64 by testing against `ldap3.SEQUENCE_TYPES`. Perhaps it would be better to use `collections.abc.Iterable` with a special case to filter out string types?

I expect this applies to `Connection.add()` as well.

**Comment by cannatag** [comment]
HI, I'd prefer to keep the SEQUENCE_TYPES tuple because it's used in different part of the project. Can you try to change the line 217 in __init__.py from::
```python
    SEQUENCE_TYPES = (list, tuple, GeneratorType)
```

to:

```python
    from types import GeneratorType
    SEQUENCE_TYPES = (list, tuple, GeneratorType)
```

and see if this works for your code?

Thanks,
Giovanni

**Comment by milliams** [comment]
That does indeed seem to work and doesn't break anything else.

**Comment by cannatag** [comment]
Thanks, I will include the fix in the next release.

Bye,
Giovanni
