### ISSUE TITLE
How to run ldap3 unit tests?

### ISSUE THREAD

**Issue by etingof** [cannatag/ldap3#436]
I am trying to test the about-to-be-released [pyasn1 0.4.1](https://github.com/etingof/pyasn1) with ldap3 master but my tests seem to fail regardless to pyasn1 version being used.

Here is how I run the ldap3 tests:

    export PYTHONIOENCODING=UTF-8
    export USERDOMAIN=TRAVIS
    export CHECK_NAMES=TRUE
    export LAZY=FALSE
    export STRATEGY=SYNC
    export SERVER=SLDAP
    export DECODER=PYASN1
    nosetests -s test

Many tests fail. Some perhaps because of remote LDAP server connectivity problems:

    Ran 643 tests in 846.223s
    FAILED (errors=157, failures=7)

I tried also the `EDIR` and `AD` servers, but the outcome is similar.

Please advise how should I run tests properly?

Thank you!

**Comment by cannatag** [comment]
Hi Ilya, EDIR at least should work. Anyway I will check pyasn1 0.4.1 in my lab and let you know.

**Comment by etingof** [comment]
Thank you!

The 0.4.1 code is now in [master](https://github.com/etingof/pyasn1).

**Comment by cannatag** [comment]
Hi Ilya, pyasn1 0.4.1 is working with ldap3. I have tested it with python 2.6, 2.7 and 3.6 and got no errors.

Bye,
Giovanni

**Comment by etingof** [comment]
Thank you, Giovanni! Much appreciated! ;-)
