### ISSUE TITLE
Bind request fails when server returns two responses instead of one

### ISSUE THREAD

**Issue by makimat** [cannatag/ldap3#440]
With a certain LDAP server, there's an issue that for certain users it returns two responses to a single bind request. First response is "success", second is "invalidCredentials". For another user, it gives only "success" response and ldap3 library works fine with that.

I reproduced the same behavior with this server using both ldapsearch utility and this ldap3 library. The difference is that ldapsearch considers it a successful binding and can execute LDAP search commands after binding. ldap3 library thinks it's unsuccessful and refuses to continue.

I'm using ldap3==2.3. Unfortunately I don't know exact details of the LDAP server and configuration but I understood it's based on OpenLDAP 2.4.19.

Here are the requests and responses as logged by ldap3 with EXTENDED logging and fast_decoder=False:

```
LDAPMessage:
 messageID=8
 protocolOp=ProtocolOp:
  bindRequest=BindRequest:
   version=3
   name=uid=myuser,ou=People,ou=SOMETHING,o=ELSE
   authentication=AuthenticationChoice:
    simple=<stripped N characters of sensitive data>
  controls=Controls:

LDAPMessage:
 messageID=8
 protocolOp=ProtocolOp:
  bindRequest=BindResponse:
   resultCode=success
   matchedDN=
   diagnosticMessage=
   referral=Referral:
   serverSaslCreds=<stripped 10 characters of sensitive data>
  controls=Controls:

LDAPMessage:
 messageID=8
 protocolOp=ProtocolOp:
  bindRequest=BindResponse:
   resultCode=’invalidCredentials’
   matchedDN=
   diagnosticMessage=
   referral=Referral:
   serverSaslCreds=<stripped 10 characters of sensitive data>
  controls=Controls:
```

Here are requests and responses captured with tcpdump on ldapsearch

```
(real end user):

4	0.000846	222.222.222.222	111.111.111.111	LDAP	129	bindRequest(1) "uid=myuser,ou=People,ou=SOMETHING,o=ELSE" simple
6	0.097554	111.111.111.111	222.222.222.222	LDAP	80	bindResponse(1) success 
8	0.097595	111.111.111.111	222.222.222.222	LDAP	80	bindResponse(1) invalidCredentials

("service" account):

22	29.809932	222.222.222.222	111.111.111.111	LDAP	129	bindRequest(1) "cn=serviceuser,ou=SystemUsers,o=ELSE" simple 
24	29.813218	111.111.111.111	222.222.222.222	LDAP	80	bindResponse(1) success
```

For reference, I also tried end user binding with an intentionally wrong password and it returned only one response, "invalidCredentials".

Is there any way that I can configure ldap3 to treat the binding in this case as a success, like ldapsearch does? I'm even fine with some monkey patching if it's possible in this case.

**Comment by cannatag** [comment]
Hi Matti, 
this is definitely a problem related to a misbehaving server. The LDAP protocol specify that only one LDAP response must be returned for a Bind request even when using SASL. What error do you get from ldap3? It should raise an LDAPSocketReceiveError exception with the "invalid messageID received" message. 
If this is the case and you're using the SYNC strategy you can check  the commented code starting at line 199 of ldap3.strategy.sync.py that handle this specific case. Keep in mind that you will get this exception only when you send the next LDAP request.

I don't know about ldapsearch but I think it works the same. It don't intentionally "merges" the two responses but it ignore the second one.

If you want to monkeypatch it you should catch the exception and manually adjust the ``server._message_counter`` variable to the next valid message id. Also you must set the ``connection.bound`` variable to ``True``. I think this should be enough, but I think that you should fix the server that probably has a SASL method badly configured.

**Comment by makimat** [comment]
I would love to fix the server but unfortunately, it is not in my hands. It is also not likely that it will be fixed; apparently other applications that bind to it are working well enough.

I didn't check the error on the next LDAP request because I thought the request would not succeed anyway because there was no valid binding. Thanks for the quick response and good instructions, I will check the next request error as soon as I get access to the system again and consider monkey patching as per your suggestion.

**Comment by cannatag** [comment]
Please, have a look at line 193 of the ldap3.strategy.sync module. This handle the multiple message id issue but is commented. You can try to comment the raise statement and to uncomment the pass. Let me know what happens. Probably there is something to fix in the bind process.

**Comment by englel-hpe** [comment]
I want to comment on this, because I'm seeing the same issue.

I have a webpage using flask_ldap_login (and ldap3). Based on lots of logging and testing, I've found that my server is sending multiple BindResponse responses, such that the flow looks like:

`message_id: 1, response_dict: {"messageID": 1, ..., "type": "bindResponse"}`
`message_id: 2, response_dict: {"messageID": 1, ..., "type": "bindResponse"}`
`message_id: 3, response_dict: {"messageID": 2, ..., "type": "searchResEntry"}`
`...`

The rest of the responses/data is what I would expect, except the message IDs don't match. Doing what you suggested (comment out the 'raise' call) forced it to ignore the second bind response, which got the message IDs back in sync and thus, return the correct data.

The one thing I haven't been able to narrow down, is why/when the server decides to send multiple responses. _Sometimes_ the server sends a single bind response, and we never hit the else block that raises the exception, but sometimes it _does_ send multiple bind responses. I haven't been able to figure out why it does one or the other. That said, I haven't been able to determine if the issue stems from a configuration issue with the web application, or if it's a transient issue with our ldap server.

**Comment by cannatag** [comment]
What kind of server are you connecting to? 
Are you using the simple bind authentication method or some sasl mechanism?

Can you try the bind with a very simple script without the flask-ldap-login plug-in and with extended logging enabled?

Thanks,
Giovanni

**Comment by englel-hpe** [comment]
I actually don't know. The server isn't owned by our org, so I have no idea what I'm connecting to. However, we use the same server with multiple other ldap authentication methods (different applications, one uses a Java implementation of ldap) and we've never experienced any issues.

I'm using a SIMPLE bind authentication. I have just tried setting up a very simple script (creating the basic server (with use_ssl=True and tls=None) and basic connection, and calling conn.bind()) and have confirmed it raises the same 'Invalid messageId received' error

**Comment by englel-hpe** [comment]
Shoot, I forgot to enable extended logging. As soon as it starts failing again (again, it's transient), then I'll post the details

**Comment by englel-hpe** [comment]
Okay, I've attached the logs of a bind call that failed with a messageId failure. Let me know if I can get anything else.
[Stripped ldap log.txt](https://github.com/cannatag/ldap3/files/6160919/Stripped.ldap.log.txt)

**Comment by englel-hpe** [comment]
Any update here? Or anything I can do to help?

Simplest actual solution would be (if we make it to the else block) to check if the response was a bind response, and our ldap_responses list has a single item in it, which is also a bind response. Not sure if that'd have any undesired side-effects
