### ISSUE TITLE
Allow to "exclude" some objectClass in the Reader

### ISSUE THREAD

**Issue by mcosta74** [cannatag/ldap3#441]
I'd like to be able to use the Reader using a filter like
```
(&
   (objectClass=user)
   (!(objectClass=computer))
)
```

In general, exclude object classes.

Something like
```
obj = ObjectDef(['user', '!computer'], ...)
```
or
```
obj = ObjectDef(['user'], excluded=['computer'], ....)
```

**Comment by cannatag** [comment]
Hi, 
When you define the Reader the Objectclass definition is needed to create the list of attributes available for that kind of entry. If you want to exclude a specific class when retrieving entries you can just use the query parameter of the Reader object:
```
from ldap3 import Reader, Connection
c = Connection('my_server', 'my_user', 'my_password)
c.bind()
r = Reader(c, 'person', 'o=my_base', '(&(objectClass=user)(!(objectClass=computer)))')
r.search()
```
So you will get back a cursor with the "person" objectClass definition (read from the server schema) and a list of entries that excludes entries with the "computer" objectClass.

Let me know if this solves your issue.

Bye,
Giovanni

**Comment by mcosta74** [comment]
Hi,

sorry for the late answer.
reading the code I found the same solution and it works.

Maybe should be more clear in the documentation that, if there's `objectClass` in the filter, the whole query will be replaced

**Comment by cannatag** [comment]
Thanks, will update the docs accordingly.
