### ISSUE TITLE
int fields broken with Python > 3

### ISSUE THREAD

**Issue by brianmay** [cannatag/ldap3#444]
In previous versions, it use to be that I would write a bytes value and read a bytes value for all fields, including integer fields such as UidNumber.

In the latest version however, for Python > 3 I get the following error:

    ldap3.core.exceptions.LDAPInvalidValueError: value 'b'1001'' non valid for attribute 'uidNumber'

Which looks to me like an error converting a byte value to a string value.

**Comment by brianmay** [comment]
For more details on the error, see https://travis-ci.org/Karaage-Cluster

**Comment by brianmay** [comment]
Possibly this change was deliberate. I may need to supply int values now. Fair enough. I don't see this change documented however.

The "bytes" (str) value still works in Python 2. Furthermore the value that I read appears to be a bytes value. A symmetric API where I can read/write the same values would be preferred...

**Comment by etingof** [comment]
Is it anyhow different if you use pyasn1 0.3.7 vs 0.4.2? Just to make sure there is no dependency on that part.

**Comment by brianmay** [comment]
This was pyasn1 0.3.7.

I can try 0.4.2 if desired however.

**Comment by brianmay** [comment]
pyasn1 0.4.2 has same error.

**Comment by cannatag** [comment]
This was done to resolve ambiguity with bytes order. How could I interpreter a multi-byte value? (little endian or big endian). Anyway I could add the conversion again for single-byte value.

What do you think?

**Comment by brianmay** [comment]
Hello,

I would think if byte order is ambiguous writing data, it probably is ambiguous reading the data too?

In any case, I believe this value is an ASCII encoded integer (correct me if I am mistaken), so byte ordering issues shouldn't be a problem. Conversion would be appreciated.

Thanks

**Comment by cannatag** [comment]
Ok, so you mean that the ASCII representation must be converted to integer, not the byte value itself? In this case I think it can be done, because the byte representation is returned by Python. Please try the code in dev, it should allow now the bytes to integer conversion.

**Comment by cannatag** [comment]
Released in version 2.4.1

**Comment by brianmay** [comment]
Apologies for the delay in responding. I had problems finding time to test this. Yes, the current release has fixed this. Thanks!

**Comment by cannatag** [comment]
Thanks for reporting this!

Have fun.
Giovanni
