### ISSUE TITLE
Missing entry_get_dn() function

### ISSUE THREAD

**Issue by anilpai** [cannatag/ldap3#446]
entry_get_dn() function not found in entry.py file. Where did it go ? What is the workaround ?

>  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ldap3/abstract/entry.py", line 192, in __getattr__
>     raise LDAPCursorError(error_message)
> ldap3.core.exceptions.LDAPCursorError: attribute 'entry_get_dn' not found

**Comment by anilpai** [comment]
I see in this commit https://github.com/cannatag/ldap3/commit/464066d2c78fb15a31f47d485b83a30754605290

`entry_get_dn()` function has been changed to `entry_dn` attribute. Needs documentation and then we can close this issue.

**Comment by cannatag** [comment]
Hi, this should already be documented at http://ldap3.readthedocs.io/abstraction.html

DId you find references to the older entry_get_dn() function in other parts of the documentation?

Thanks,
Giovanni
