### ISSUE TITLE
Add object and assign objectGUID

### ISSUE THREAD

**Issue by bmyrtil** [cannatag/ldap3#448]
I'm pretty sure my situation is an edge case but I am in need of being able to create objects and define their objectGUID. I was able to achieve this in python-ldap. With ldap3 I get either a CONSTRAINT_ATT_TYPE error or pyasn1.error.PyAsn1Error: Can't decode string 'b'\x18\r\xae\x9e\xe3\xb0B@\xb5QGDf\xc2\xf1\x14'' with 'utf-8' codec at 'AttributeValue' error.

Is there a certain way to pass in the objectGUID when adding an object?

PS - I have already made the modifications to the AD server to allow this. I am able to do it with python-ldap but cant figure out how to do it with ldap3.

ANY HELP WOULD BE GREATLY APPRECIATED!!!!

**Comment by etingof** [comment]
It may be easier to address this problem if you would paste a simple code snippet to reproduce/illustrate the problem.

**Comment by bmyrtil** [comment]
Sorry about that... here is an example

`server_prod = Server('{ip}', use_ssl=True, get_info=ALL)
    server_dev = Server('{ip}', use_ssl=True, get_info=ALL)
    conn_prod = Connection(server_prod, '{dn}', '{pw}', auto_bind=True, return_empty_attributes=False)
    conn_dev = Connection(server_dev, '{dn}', '{pw}', auto_bind=True, return_empty_attributes=False)

    conn_prod.search('DC=CSUSA,DC=internal', '(distinguishedName=OU=MI - Detroit,DC=CSUSA,DC=internal)', attributes=['objectGUID', 'objectClass', 'distinguishedName'])
    conn_dev.add(
        "OU=MI - Detroit,DC=CSUSADEVAD,DC=internal",
        attributes={"objectGUID": conn_prod.entries[0].objectGUID.raw_values[0], "objectClass": "organizationalUnit"}
    )

    conn_dev.unbind()
    conn_prod.unbind()`

Essentially I am taking an object out of our production environment and copying it over to our dev environment. Circumstances require that we copy it over with the same objectGUID that is in production. I've tried several formats for the objectGUID but can't seem to get it to save.

**Comment by cannatag** [comment]
when the schema is read ldap3 should be able to cope with UUID. What happens if you try to add the formatted value of the GUID?

**Comment by cannatag** [comment]
Please refer to #482. ObjectGUID  is properly managed in version 2.5, still in dev. Can you give a try?

**Comment by cannatag** [comment]
Fixed in v2.5
