### ISSUE TITLE
Get sent & received messages with LDAP server

### ISSUE THREAD

**Issue by UltraPhil** [cannatag/ldap3#45]
Hi,

Is there a way to intercept messages that are sent and received from the LDAP server?
It would be useful for troubleshooting.
Right now I was thinking about extending a client strategy (i.e. extend the SYNC strategy) methods to get the messages but it doesn't seems to be the best way of doing that.  Any idea?

Thanks!
--Phil

**Comment by cannatag** [comment]
Hello Phil, what do you mean with "intercept"? You want the raw binary packet or the decoded messages? In the latter case you can read the result attribute of the connection object. It contains all the data received in the ldapmessage, except for the search operation, where you have the entries found in the response attribute.
Can you give me more info on what you need.? 

By,
Giovanni

**Comment by UltraPhil** [comment]
Hi,

Sorry, re-reading my question I realize I wasn't clear.  Basically, for troubleshooting purposes, I would like to see all messages exchanged between me and the LDAP server (decoded), be it for binding or searches, or whatever.  What I understand is that the result attribute on the connection object would only show me the message(s) from the last operation?

Thanks!
--Phil

**Comment by cannatag** [comment]
Each LDAP operation (except searches) is atomic, so after issuing the operation you always get the relevant message in the result attribute. When performing searches each ldap message (search entry or referral) is stored in the response attribute.

The library performs multiple operations in some specific cases as for sasl bind, schema reading and auto referrals. Are you interested in these? If this is the case I could add a debug or logging option.

Bye,
Giovanni

----- Messaggio originale -----
Da: "Philippe Desmarais" <notifications@github.com>
Inviato: ‎28/‎04/‎2015 02:24
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Cc: "Giovanni Cannata" <cannatag@gmail.com>
Oggetto: Re: [ldap3] Get sent & received messages with LDAP server (#45)

Hi,
Sorry, re-reading my question I realize I wasn't clear. Basically, for troubleshooting purposes, I would like to see all messages exchanged between me and the LDAP server (decoded), be it for binding or searches, or whatever. What I understand is that the result attribute on the connection object would only show me the message(s) from the last operation?
Thanks!
--Phil

**Comment by UltraPhil** [comment]
Yes, a debug/logging option would be great for more in-depth analysis/troubleshooting!


Thanks,
--Phil

**Comment by cannatag** [comment]
I'm working on logging in version 0.9.8.3.

**Comment by cannatag** [comment]
Hi, I've release 0.9.8.3 that includes extensive logging capabilities. You can read more at http://ldap3.readthedocs.org/logging.html 

please give a try and tell me if this helps you.

Bye,
Giovanni

**Comment by UltraPhil** [comment]
I tried it.  It is GREAT!  Thanks a lot!  Great work!

**Comment by cannatag** [comment]
Thanks, I will improve it gradually, maybe there is too much information cluttering the log and something could be missing. Let me know if you have specific requirements for it.

bye,
Giovanni

**Comment by cannatag** [comment]
I added a ldap message level decoding feature, you can check in dev with setting the detail level to EXTENDED. The output of messages is now:

```
| LDAPMessage:
|  messageID=1
|  protocolOp=ProtocolOp:
|   bindRequest=BindRequest:
|    version=3
|    name=b'cn=admin,o=test'
|    authentication=AuthenticationChoice:
|     simple=b'password'
```

Bye,
Giovanni
