### ISSUE TITLE
Long running ldap connections

### ISSUE THREAD

**Issue by profhase** [cannatag/ldap3#451]
I am running a webapp which needs to perform ldap operations. There are two error sources:

1. The ldap-backend is down sometimes 
2. Long running connections without traffic get thrown away by firewall

My actual aproach is: For any operation I create a new connection object, perform a bind and if it fails the frontend gives an error to the user. The downside:

1. expensive binds are performed all the time
2. I can't use 'get_info=SCHEMA' as it would be even more expensive

What I'd rather have is one global connection which:

- always tries to perform an ldapsearch
- if the server does not send any data, it performs a rebind
- if the rebind fails it sends an error

What I tried is:
    
```
  #serverpool with 3 servers (same)
servers = [Server("myserver", connect_timeout=2)]
server_pool = ServerPool(servers=servers, exhaust=10)

con = Connection(user="me", password="pass", server=server_pool, pool_keepalive=10, receive_timeout=10, auto_bind=True, client_strategy=RESTARTABLE)
```

What now happens is:
- `con.bound` is always `True` even when the server is down 
- if `myserver` is not accessible and i perform `con.search(...)`, it does not give any error (means, it waits for the connection to be reestablished).

How do I establish just a single connection which automatically rebinds if the server is gone or the connection is not active anymore?

Thanks a lot (sorry for that much text)

**Comment by cannatag** [comment]
Hi, I missed your issue, sorry for answering late!

I think you can try the REUSABLE connection strategy, that is made for long standing multiple connections. It acts as a ASYNC strategy but keeps a pool of RESTARTABLE connections in multiple threads, that are automatically managed. You can also specify a pool_lifetime parameter for the number os seconds to close and reopen the connection in case your server doesn't allow long standing connections.

Let me know if this helps you.

Bye,
Giovanni

**Comment by profhase** [comment]
Hi Giovanni, thank you for the answer. The reason I don't use the ASYNC connection is that I cannot use `entries` there. Or is there any way to have the `Entry` api for ASYNC?

Thanks, Ilya

**Comment by cannatag** [comment]
Hi, this is something I didn't think about, but it can easy done with the _get_entries() method of the connection object:
```
from ldap3 import Server, Connection, ASYNC
s = Server('myserver')
c = Connection(s, 'my_user', 'my_password', client_strategy=ASYNC)
c.bind()
operation_id = c.search('my_base', 'my_filter', attributes='*')
response, result = c.get_response(operation_id)
entries = c._get_entries(response)
```
The _get_entries is not exposed, but can be used. I'm not sure if this has side effects with the async strategy.

Can you try and give me suggestions on this approach?

Bye,
Giovanni

**Comment by profhase** [comment]
Thanks, I don't know very much about the architecture, so far I haven't noticed negative effects. Just Pycharm inspection complains that I am using a private function ;)

Thanks a lot.
