### ISSUE TITLE
Where is AUTH_SIMPLE?

### ISSUE THREAD

**Issue by detly** [cannatag/ldap3#452]
According to the [connection docs](http://ldap3.readthedocs.io/connection.html), the `authentication` parameter can be eg. `AUTH_SIMPLE`. Where is this constant? I'm using v2.4.

```text
>>> import ldap3
>>> ldap3.AUTH_SIMPLE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ldap3' has no attribute 'AUTH_SIMPLE'
>>> ldap3.core.AUTH_SIMPLE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ldap3.core' has no attribute 'AUTH_SIMPLE'
>>> ldap3.core.connection.AUTH_SIMPLE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ldap3.core.connection' has no attribute 'AUTH_SIMPLE'
```

**Comment by detly** [comment]
Never mind, found it in the [changelog](http://ldap3.readthedocs.io/changelog.html): 

> The following older constants in ldap3 have been removed, please use the suggested ones:
AUTH_ANONYMOUS = ANONYMOUS
AUTH_SIMPLE = SIMPLE
AUTH_SASL = SASL

**Comment by daenney** [comment]
@detly  Could you close the issue in that case?

**Comment by cannatag** [comment]
Sure, will update docs too. 

Thanks,
Giovanni
