### ISSUE TITLE
Not able to add usercertificate to an inetorgperson object in OpenLDAP

### ISSUE THREAD

**Issue by OscarBell** [cannatag/ldap3#459]
I'm able to add the usercertificate to an object in the LDAP server via ldapmodify and ldif file but while trying the same with pyhon/ldap3 version 2.4 I'm getting below error
'usercertificate;binary: value #0 invalid per syntax'

The ldif file I use is (MIIC... is the PEM definition of the usercertificate)
```
dn: cn=testuser,cn=users,dc=example,dc=com
changetype: modify
add: usercertificate;binary
usercertificate;binary:: MIIC.....
```

The same within my python program fails.
```
dn="cn=testuser,cn=users,dc=example,dc=com"
certificate='MIIC...'
ldap_conn.modify(dn,
                 {'usercertificate;binary': [(MODIFY_ADD,certificate)]}
                 )
```
Other attributes can be added or updated without a problem, only the binary one is failing.

How can I add an X509 usercertificate to the LDAP server via python/ldap3?

The error returned via LDAP3 is the same error as I get when using below ldif file (usercertificate;binary: instead of usercertificate;binary::) and the ldapmodify command. Is LDAP3 able to use the :: syntax and therefor can be used to add the usercertificate or is there another option to add the usercertificate?
```
dn: cn=testuser,cn=users,dc=example,dc=com
changetype: modify
add: usercertificate;binary
usercertificate;binary: MIICU....

$ ldapmodify -h localhost -p 389 -D <username> -w <password> -f <ldif_file>                                                         
modifying entry "cn=testuser,cn=users,dc=example,dc=com"
ldap_modify: Invalid syntax (21)
	additional info: usercertificate;binary: value #0 invalid per syntax
```
By the way:
```
ldap_conn.modify(dn, 
        {'usercertificate;binary:': '[(MODIFY_ADD,certificate)]}
    )
``` 
is not accepted by ldap3.
```'usercertificate;binary:: AttributeDescription contains inappropriate characters'```

**Comment by OscarBell** [comment]
Solved myself, I had to decode the pem cert contents into DER format first.
```certificate = base64.b64decode(certificate)```
or directly within the modify statement
```{'usercertificate;binary': [(MODIFY_REPLACE, base64.b64decode(certificate))]}```

**Comment by cannatag** [comment]
Good!

Thanks for using ldap3.

Giovanni
