### ISSUE TITLE
connection fails to fall back to ipv4 if ipv6 fails

### ISSUE THREAD

**Issue by brianmay** [cannatag/ldap3#46]
Hello,

For some reason I thought this was already fixed, but it seems like I was mistaken. I can't find that bug right now.

I get Connection Refused when connecting to localhost, if localhost resolves as ::1 and 127.0.0.1, and when the ldap server is only listening on 127.0.0.1

If the IPv6 connection fails, it should fall back to the IPv4 address automatically.

Regards

**Comment by brianmay** [comment]
I found the previous issue at https://bitbucket.org/python3ldap/python3-ldap/issue/42/doesnt-fall-back-to-ipv4-connection-if - Unfortunately the link is broken, however I still have the emails.

Possibly this should be working, will investigate.

**Comment by brianmay** [comment]
Quick summary of issues I found, before I run out of time:

In ``core/server.py``, ``candidate_addresses()``:

```python
if self.mode == IP_SYSTEM_DEFAULT:
    candidates = addresses
```

Seems better, as otherwise it will only look at the first address.

In ``strategy/base.py``, ``open()``, catching all exceptions hides the real error, suspect we only need to catch ``LDAPSocketOpenError `` exception here.

In ``strategy/base.py, _open_socket()``, we try connecting to ``self.connection.server.address_info[0][4]``, which is incorrect (it seems to always return the first address in the list for every attempt), we should be trying to connect to ``address[4]`` (If I understand correctly).

This function call to ``self.connection.socket.connect`` returns the following exception from ``socket.py`` in Python, which I am still trying to understand, particularly as it seems to work on the first try with the same parameters:

```
TypeError: getsockaddrarg() takes exactly 2 parameters (4 given)
```

Will continue to investigate after my meeting.

**Comment by brianmay** [comment]
I think I can understand the ``TypeError`` now, the problem is the socket was created for the IPv4 address, but given the IPv6 address. Here is a complete patch against 0.9.8.2 which appears to work for me:

```diff
diff -ruN ldap3-0.9.8.2.bak/ldap3/core/server.py ldap3-0.9.8.2/ldap3/core/server.py
--- ldap3-0.9.8.2.bak/ldap3/core/server.py	2015-03-19 08:13:40.000000000 +1100
+++ ldap3-0.9.8.2/ldap3/core/server.py	2015-05-01 13:22:34.445492381 +1000
@@ -417,7 +417,7 @@
         candidates = []
         if addresses:
             if self.mode == IP_SYSTEM_DEFAULT:
-                candidates.append(addresses[0])
+                candidates = addresses
             elif self.mode == IP_V4_ONLY:
                 candidates = [address for address in addresses if address[0] == socket.AF_INET and (address[5] or address[5] is None)]
             elif self.mode == IP_V6_ONLY:
diff -ruN ldap3-0.9.8.2.bak/ldap3/strategy/base.py ldap3-0.9.8.2/ldap3/strategy/base.py
--- ldap3-0.9.8.2.bak/ldap3/strategy/base.py	2015-04-04 06:01:54.000000000 +1100
+++ ldap3-0.9.8.2/ldap3/strategy/base.py	2015-05-01 13:23:17.420491693 +1000
@@ -101,7 +101,7 @@
                         self.connection.server.current_address = candidate_address
                         self.connection.server.update_availability(candidate_address, True)
                         break
-                    except Exception:
+                    except LDAPSocketOpenError:
                         self.connection.server.update_availability(candidate_address, False)
                         exception_history.append((datetime.now(), exc_info()[0], exc_info()[1], candidate_address[4]))
 
@@ -159,7 +159,7 @@
         try:
             if self.connection.server.connect_timeout:
                 self.connection.socket.settimeout(self.connection.server.connect_timeout)
-            self.connection.socket.connect(self.connection.server.address_info[0][4])
+            self.connection.socket.connect(address[4])
             if self.connection.server.connect_timeout:
                 self.connection.socket.settimeout(None)  # disable socket timeout - socket is in blocking mode
         except socket.error as e:
```

**Comment by cannatag** [comment]
Thanks Brian, 
your help is much needed because I have limited access to a IPv6 network. Will try your code and include it in the next release 0.9.8.3.

Bye,
Giovanni

**Comment by brianmay** [comment]
Thanks for your feedback.

I was wondering about this, however thought that IP_SYSTEM_DEFAULT should use the addresses returned in the same order as the OS. I don't feel very strongly about this however, if you feel it should be just the first address, that is fine with me.

The other parts of the patch are still required however.

Also, if should be possible to test this without an IPv6 connection. On my Debian computers, localhost is defined in /etc/hosts as:

```
127.0.0.1 localhost
::1 localhost
```

So just trying to connect to ``localhost`` is enough to test this out. Especially if slapd only listens on ipv4 (seems to happen by default on my test suite - I haven't investigated why).

**Comment by cannatag** [comment]
IP_SYSTEM_DEFAULT means that you get the IP returned by the system, only the first one. This was the original getaddressinfo behaviour before I added the "dual stack" modes. I think this is the most compatible with all version of OS where at least one IP is returned.

Probably I could change the library default from IP_SYSTEM_DEFAULT to IP_V4_PREFERRED.

I will try to replicate the issue on a debian box with openldap.

**Comment by brianmay** [comment]
I would suggest ``IP_V6_PREFERRED`` be the default, as this is matches what is the defacto standard for almost every other dual stack TCP client.

**Comment by cannatag** [comment]
Sorry for being late, next release will have IP_V6_PREFERRED as default. I'm also working on extensive logging in the library, so I can check their address problem.

**Comment by cannatag** [comment]
HI, can you check version 0.9.8.4 in dev? It should fix the problem.

Bye,
Giovanni

**Comment by brianmay** [comment]
Under Python2 my tests seem to pass, perfectly.

Under Python3 however... Oh wait, I didn't install the package under Python3. So no surprise that didn't work.

So far. Does look a lot better... Thanks

**Comment by cannatag** [comment]
Thanks Brian, I will release it soon. And thanks for all the testing you're doing. It's very helpful to me.

Bye,
Giovanni 

----- Messaggio originale -----
Da: "Brian May" <notifications@github.com>
Inviato: ‎18/‎05/‎2015 02:43
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Cc: "Giovanni Cannata" <cannatag@gmail.com>
Oggetto: Re: [ldap3] connection fails to fall back to ipv4 if ipv6 fails (#46)

Under Python2 my tests seem to pass, perfectly.
Under Python3 however... Oh wait, I didn't install the package under Python3. So no surprise that didn't work.
So far. Does look a lot better... Thanks

**Comment by cannatag** [comment]
0.9.8.4 released.

bye,
Giovanni
