### ISSUE TITLE
Unexpected Behavior with receive_timeout

### ISSUE THREAD

**Issue by swtch1** [cannatag/ldap3#461]
Damn amazing library.

Perhaps I'm just missing the way this parameter works, but it does not appear the Connection class parameter "receive_timeout" is working correctly.  I set the timeout parameter for 3 seconds and give the connection a bad port, but the connection hangs for minutes.  I expect the connection to timeout but that's not what happens.  

This is my connection information:
`
c = Connection(
    server=self.server_pool,
    user=str(self.ldap_config['username']),
    password=str(self.ldap_config['password']),
    pool_keepalive=self.ldap_config['pool_keepalive'],
   client_strategy=REUSABLE,
    raise_exceptions=True,
    read_only=True,
    auto_bind=True,
    receive_timeout=3,
)
`

I started looking into the source but couldn't pinpoint it exactly in the limited time I looked.  If you confirm my assumptions of how the setting is supposed to work I will start working on a fix.

**Comment by cannatag** [comment]
Hi, to set the timeout while establishing the connection you must set the ``connect_timeout`` parameter of the server object. The ``receive_timeout`` of the Connection object is used only when the connection is open and ldap3 is awaiting for a response from the server.  

Also, if you are using the RESTARTABLE or REUSABLE strategies the operation is retried for the number of times specified in the RESTARTABLE_TRIES global parameter, that is set to 30 by default. You can change it with the following code:

```
from ldap3 import set_config_parameter
# set number of tries for the RESTARTABLE and REUSABLE strategies
set_config_parameter('RESTARTABLE_TRIES', 5)
```
