### ISSUE TITLE
What is the proper way to close connection in REUSABLE strategy

### ISSUE THREAD

**Issue by kiddick** [cannatag/ldap3#462]
For sync strategy `connection.unbind()` seems is enough.
But for reusable strategy we need to care about created threads under the hood and etc. So seems only `unbinding` isn't enough.

I am using this approach right now:
```
for worker in connection.strategy.pool.workers:
    worker.connection.unbind()
connection.unbind()
connection.strategy.pool.terminate_pool()
```

Any ideas about proper way? I need to prevent collisions on the low level with reintialization connection with new settings (host for examle)

**Comment by cannatag** [comment]
Hi kiddick, bind and unbind are specially managed by the REUSABLE strategy. They are not performed untill needed. If you want to close all the underlying RESTARTABLE connection you must use the terminate_pool() method of the ConnectionPool. It will unbind all the connections and join all the threads back to the main thread.

Also, the connections are automatically unbound when the number of seconds specified in the ``pool_lifetime`` parameter of the Connection object.

**Comment by cannatag** [comment]
Yes, this should be enough. Let me know if you still have issues with it.
