### ISSUE TITLE
Unable to return attributes

### ISSUE THREAD

**Issue by calken** [cannatag/ldap3#464]
Following an upgrade to ldap3 the results of searches show no additional attributes even if they are explicitly stated.

server = ldap3.Server(LDAP_PROVIDER_URL_BASE, port=389, use_ssl=False, get_info=ldap3.ALL)
conn = ldap3.Connection(server,user='cn=%s' % self.username, password=self.password, auto_bind=True)
conn.open()
conn.search(basedn, searchFilter, searchScope, dereference_aliases=ldap3.DEREF_ALWAYS, attributes=ldap3.ALL_ATTRIBUTES)

The search correctly finds the items and validation through apache directory studio and the previous ldap api verify that the details are visible to the account being used.

I've reverted the pyasn1 module back to 0.3.7 as it was suggested in another issue that it may be causing problems but the outcome is the same.

The searchScope is SUBTREE and the filter is hitting a specific UID.  As mentioned, the search does find the correct items.

I feel I have got the scope of something incorrect as no errors are thrown.  The only responses for attributes are givenName, cn, sn and uid.  This is on an internal ldap server.

It would be great if someone could point out what I've down wrong.

Python version 2.7, ldap3 version 2.4.

**Comment by calken** [comment]
After days and days of testing, I removed the conn.open() and it all works......

**Comment by cannatag** [comment]
Hi, this seem a bug to me. When the Connection object has the ``auto_bind`` parameter set it should automatically bind after an open.

**Comment by cannatag** [comment]
I've modified the code in dev to fix this. Can you check it?

Thanks,
Giovanni

**Comment by calken** [comment]
I'll download and test tomorrow and feedback.

**Comment by calken** [comment]
Hi, that fixed the issue.  Thanks.
