### ISSUE TITLE
Question about connection pooling

### ISSUE THREAD

**Issue by shawnmckinney** [cannatag/ldap3#465]
Hi, I have read the docs/examples but still confused about connection pooling.  First my req's:
1. maintain a pool of bound connections to the LDAP server.  
2. These connections will be used synchronously to interact with my LDAP server.
3. When dao function is finished with connection, it simply returns it to the pool, shouldn't need to unbind/close the socket to the server.
4. A worker thread (in my program) may only access one LDAP connection at a time.
5. No two threads may access the same LDAP connection.

Here is how I am (attempting to) initialize the connection the server connection pool:
server = ldap3.Server( host='localhost', port=389 )
c = ldap3.Connection(server, user=service_uid, password=service_pw, auto_bind=True, collect_usage=True, pool_name='blah', pool_size=5, pool_lifetime=600, pool_keepalive=30 )

My confusion is two-fold:
a. how to get a new connection from the pool.  do I just call the code as listed above, or is there another way?
b. how do I return a connection to the pool?

Any samples you can point me to are appreciated.  Thanks in advance for your attention to this.  

Shawn McKinney

**Comment by cannatag** [comment]
Hi, if you want to use a pool of connections you must set ``client_strategy=REUSABLE``. This creates a pool of independent connection to a pool of server, that you can specify in the Connection definition with a ServerPool object instead of a Server object. This is still not well documented on ldap3.readthedocs.org, sorry.

**Comment by shawnmckinney** [comment]
Hello, 

Thanks for replying to my original question. I also work for on open source project (apache fortress) and can definitely relate to imperfect doc.  Assuming I get this working, I’ll help get it documented, if need be.  

Here’s what I’ve done:

*** begin code snippet

server1 = ldap3.Server( host='localhost', port=1389 )
server_pool = ldap3.ServerPool([server1])
c = ldap3.Connection(server_pool, user=service_uid, password=service_pw, client_strategy='REUSABLE', auto_bind=True, collect_usage=True, pool_name=‘xyz', pool_size=5, pool_lifetime=600, pool_keepalive=30 )

*** end code snippet

I can tell by the usage stats (below) that the server pool was initialized with pre-bound connections.  Now I have a different problem as the interaction is async and not sync which won’t work for us.  Is there a way to do this over a synchronous connection?

*** begin connection usage trace:

Connection Usage:
 Time: [elapsed:          0:00:00.018410]
   Initial start time:    2018-01-08T03:13:42.612842
   Open socket time:      2018-01-08T03:13:42.612842
   Last transmitted time: 
   Last received time:    
   Close socket time:     
 Server:
   Servers from pool:     0
   Sockets open:          5
   Sockets closed:        1
   Sockets wrapped:       0
 Bytes:                   106370
   Transmitted:           605
   Received:              105765
 Messages:                19
   Transmitted:           9
   Received:              10
 Operations:              9
   Abandon:               0
   Bind:                  6
   Add:                   0
   Compare:               0
   Delete:                0
   Extended:              0
   Modify:                0
   ModifyDn:              0
   Search:                2
   Unbind:                1
 Referrals:               
   Received:              0
   Followed:              0
   Connections:           0
 Restartable tries:       0
   Failed restarts:       0
   Successful restarts:   0


Thanks,
Shawn

**Comment by cannatag** [comment]
Hi, to use an asynchronous strategy you must get the return value from the operation (that is the operation id) and then use the id in the connection.get_response(id) method that returns the result of the operation and the response in case of a search. Let me know if you need help on this.
