### ISSUE TITLE
Setting binary attributes with entry add operation does not work

### ISSUE THREAD

**Issue by guidow** [cannatag/ldap3#468]
After upgrading to newer versions of pyasn1 (0.4.2) and pyasn1-modules (0.2.1), setting binary attributes (like userCertificate) as part of an entry add operation fails with the following exception:

        File "/home/guido/hse_smime_backend/hse_smime_backend/tasks.py", line 79, in sync_certificate_to_ldap
            "userCertificate;binary": der_certificates
        File "/home/guido/virtualenvs/cp/lib/python3.5/site-packages/ldap3/core/connection.py", line 912, in add
            response = self.post_send_single_response(self.send('addRequest', request, controls))
        File "/home/guido/virtualenvs/cp/lib/python3.5/site-packages/ldap3/strategy/base.py", line 300, in send
            self.connection.request = BaseStrategy.decode_request(message_type, request, controls)
        File "/home/guido/virtualenvs/cp/lib/python3.5/site-packages/ldap3/strategy/base.py", line 619, in decode_request
            result = add_request_to_dict(component)
        File "/home/guido/virtualenvs/cp/lib/python3.5/site-packages/ldap3/operation/add.py", line 63, in add_request_to_dict
            'attributes': attributes_to_dict(request['attributes'])}
        File "/home/guido/virtualenvs/cp/lib/python3.5/site-packages/ldap3/protocol/convert.py", line 41, in attributes_to_dict
            attribute_dict = attribute_to_dict(attribute)
        File "/home/guido/virtualenvs/cp/lib/python3.5/site-packages/ldap3/protocol/convert.py", line 35, in attribute_to_dict
            return {'type': str(attribute['type']), 'values': [str(val) for val in attribute['vals']]}
        File "/home/guido/virtualenvs/cp/lib/python3.5/site-packages/ldap3/protocol/convert.py", line 35, in <listcomp>
            return {'type': str(attribute['type']), 'values': [str(val) for val in attribute['vals']]}
        File "/home/guido/virtualenvs/cp/lib/python3.5/site-packages/pyasn1/type/univ.py", line 886, in __str__
            "Can't decode string '%s' with '%s' codec at '%s'" % (self._value, self.encoding, self.__class__.__name__)
        pyasn1.error.PyAsn1Error: Can't decode string 'b'0\x82\x05B0\x82\x04*\xa0\x03\x02\x01\x02\x02\x11\x00\xcaA\x90\x89\xbdQ]\x8e\xac\xb4\xc2\xd6\x07t\xc0n0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x000\x81\x971\x0b0\t\x06\x03U\x04\x06\x13\x02GB1\x1b0\x19\x06\x03U\x04\x08\x13\x12Greater Manchester1\x100\x0e\x06\x03U\x04\x07\x13\x07Salford1\x1a0\x18\x06\x03U\x04\n\x13\x11COMODO CA Limited1=0;\x06\x03U\x04\x03\x134COMODO RSA Client Authentication and Secure Email CA0\x1e\x17\r170816000000Z\x17\r180816235959Z0,1*0(\x06\t*\x86H\x86\xf7\r\x01\t\x01\x16\x1blederich@hornetsecurity.com0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\xda\xcbO\t\x9f\xa2\xe1\xad\xf1\xaez\x1e\xc7\xbfT\x1c\xf5\x86\xfdm\xe6\xde\xfd\x93\x94\r\xfe6\xbb\xdf\xc4\\\x08\x16\x97\xb4p\x82\xa7\\\x00f\xea\xb8\x82\xc7%G\xf8\xaa@_\x83*\xbeHC@\xd1v\xf1\x9dT\xc7\xb7@~\xf4;e\t\xa8A\xba\xa6J&\x88:aii$\x89@\x19\x85\xaa\xff\x99C\xc8\xe7\xe6\xd1\xe2#q.5\x98VO@\xaf^+\xcc\xfe\xde\x0c\xa9\x17{\x0fR\x98\xa1k\x0ff\x04\xb7\x1em\xdc\xd9$&\x13z\xcdu@\n\x00\xd6\x7f\xaf\xded\xf54}3y\xb4"S\\,\xc2\x8dA5\x1e\xb2\x05\x84 \xb2i\x86\x8a\xf92J\xab\xebL\xa9\x04\xd5\x14\xbe>]\xcf\x16\xbfF\x02\xb8\xec^\xb9\x19\xb2\x8e\x84\x90\xe4 \xd5\x91\x18\xb5\x1f\xc8b\r\xd7i\x0b\x1c\xf1AD\xb4\xcck\xfcq\x16\xd6qhy\r\xa8?I\x85\x01\xda\x9c\xd2\x19\xec\xde\xeaE\xae\xde\x16I\xccZ\xd5\xde,\xce~Y}\xaa\xc8]\'\x03\x13@g{H\x07\x02\x03\x01\x00\x01\xa3\x82\x01\xf10\x82\x01\xed0\x1f\x06\x03U\x1d#\x04\x180\x16\x80\x14\x82\xafl\x8c\xf8\xc5\xfe\x96a|\xe8\x1f=+qH^\xc4\x8b\xc00\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\xb0\xd0O\x03\xff\x97B\x157\xa1\xca<}\x81/\xac\x19\x93\xb8\xe50\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x05\xa00\x0c\x06\x03U\x1d\x13\x01\x01\xff\x04\x020\x000 \x06\x03U\x1d%\x04\x190\x17\x06\x08+\x06\x01\x05\x05\x07\x03\x04\x06\x0b+\x06\x01\x04\x01\xb21\x01\x03\x05\x020\x11\x06\t`\x86H\x01\x86\xf8B\x01\x01\x04\x04\x03\x02\x05 0F\x06\x03U\x1d \x04?0=0;\x06\x0c+\x06\x01\x04\x01\xb21\x01\x02\x01\x01\x010+0)\x06\x08+\x06\x01\x05\x05\x07\x02\x01\x16\x1dhttps://secure.comodo.net/CPS0Z\x06\x03U\x1d\x1f\x04S0Q0O\xa0M\xa0K\x86Ihttp://crl.comodoca.com/COMODORSAClientAuthenticationandSecureEmailCA.crl0\x81\x8b\x06\x08+\x06\x01\x05\x05\x07\x01\x01\x04\x7f0}0U\x06\x08+\x06\x01\x05\x05\x070\x02\x86Ihttp://crt.comodoca.com/COMODORSAClientAuthenticationandSecureEmailCA.crt0$\x06\x08+\x06\x01\x05\x05\x070\x01\x86\x18http://ocsp.comodoca.com0&\x06\x03U\x1d\x11\x04\x1f0\x1d\x81\x1blederich@hornetsecurity.com0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00E\x8b\xb9\xc8:\xddM\x89O\xa1\xa38r\xae\r\xa1C`\xe0\x03\xd100\xa3%Q\xab\x85?\xa9\xf4\x02\xc9"\x98\x1cf\x9eCW\xcb*\x10\xc7\x17\xeaV\x83\xec\x17\x07\xb46\xb9\xcdE=E\xd77!6\x969\x1a9.Mh\xb7\xad$\x955\n\xc0\x8e\xe0P\x83|\n\xad\xbf,\xc7\xec\xeaQ%\r\x8d"kB~YS\xf5\x19\xa1T-uv\xf9\x069\xed\xb8\x0b\xc9\x88\x92l\xb5\xd7\xe8y5\xae\x94\xd6\xe3\x97\xfe\x85:\xea\x98-\xc0\x8f\x85Y]\x17\x82\xcew \xf0\x83\xbc6v\x86\xfe\xc5\xa5\xf4\x90\x9f3(^;\x11\rm\xbd\xa8\xea\x98\xae\xbfH\xb8\x1c\xaa\n\xb2\xbd\x90y\xd1]\x0c[\xefO\x0e&\xa1\xf0\x0f\xc9V\xa2[\xc6\'\x7f\x1f\t\xacf\xc1\x9a\xce,m\x93\xae\ny\xaan\xc0\xefV\x8a\xc8\x95\x1eg\xa4\x06\x16\x8bE!(9\xb0\xc1?\x96\'5\x1b\xe8jxIj\xea\x88\x94\xd6L\x80\x0e\x176\r\xc1\xc0\xe3\x9cg\x14\t\x9c2\x95'' with 'utf-8' codec at 'AttributeValue'

This is the code snippet that does the add operation:

        if not connection.add(
            "cn=%s,%s" % (email_address, LDAP_BASE),
            "inetOrgPerson",
            {"cn": email_address,
             "sn": email_address,
             "mail": email_address,
             "userCertificate;binary": der_certificates
             }):
                raise Exception("Could not add LDAP entry: %s" %
                                connection.result)

(```der_certificates``` is a list of binary arrays here.)

Setting the attribute as part of a modify operation works, so the this works as a workaround:

        if not connection.add(
            "cn=%s,%s" % (email_address, LDAP_BASE),
            "inetOrgPerson",
            {"cn": email_address,
             "sn": email_address,
             "mail": email_address,
             }):
                raise Exception("Could not add LDAP entry: %s" %
                                connection.result)

        if not connection.modify(
            "cn=%s,%s" % (email_address, LDAP_BASE),
            {"userCertificate;binary": [(MODIFY_REPLACE, der_certificates)]}):
                raise Exception("Could not modify LDAP entry: %s" %
                                connection.result)

However, that is still less efficient for large bulk insert operations.

**Comment by cannatag** [comment]
Hi, can you try with the latest code in dev? I made some changes to handle the new pyasn1 versions. Let me know if this problem is still present.

**Comment by guidow** [comment]
Sorry, even with the most recent commit from the branch ```dev```, ```27b01069a7a6e2462be471d8254d0abd5f5aa59c```, the problem is still present.

**Comment by cannatag** [comment]
Hi, could you check code in dev? It should work now.

Sorry for the late answer.

Bye,
Giovanni

**Comment by sscherfke** [comment]
Hi, I am also having this issue.  I tried `dev` and it seems to work now. When will this fix be released?

**Comment by janhh** [comment]
I had trouble figuring out how to add jpegPhoto (InetOrgPerson) with 2.4.1, it appears I was affected with this issue as well. Checked out the latest dev branch (14e7925) today and could add jpegPhoto successfully.

**Comment by cannatag** [comment]
Fixed in v2.5. Sorry for delay.
