### ISSUE TITLE
ConnectionUsage.update_transmitted_message() crash on bind request

### ISSUE THREAD

**Issue by UltraPhil** [cannatag/ldap3#47]
Hi,

I just noticed that when the bind occurs, the message['type'] is empty and makes the method update_transmitted_message() crash.

How to reproduce:
Try to bind with `Connection(..., collect_usage=True, ...)`.
Here is how I init my connection object:
```
self.connection = Connection(self.server,
                                 auto_bind=True,
                                 client_strategy=SYNC,
                                 user=username,
                                 password=password,
                                 authentication=SIMPLE,
                                 check_names=True,
                                 collect_usage=True)
```

It would crash in usage.py on line 161, at the first if:

```
 def update_transmitted_message(self, message, length):
        self.bytes_transmitted += length
        self.operations += 1
        self.messages_transmitted += 1
        if message['type'] == 'abandonRequest':      <---- crashes because message is None
            self.abandon_operations += 1
...
```

It is possible to quick fix by putting the IFs in a try/catch block, but it doesn't fix the issue that message['type'] isn't set for bind requests.

**Comment by cannatag** [comment]
HI, do you have this error with every bind operation?

**Comment by UltraPhil** [comment]
Yes, with or without TLS, and now I remarked that it also does it as anonymous (extendedReq).  I will propose a new better fix that doesn't only address the bind operation.

**Comment by UltraPhil** [comment]
My bad, sorry for the multiple commits referenced here.  I'm still new to this.

**Comment by UltraPhil** [comment]
ok the last one is the fix that resolve my binding problems.

**Comment by cannatag** [comment]
Hello Philippe,
I've found the bug in another part of the library. In the ldap3/strategy/base.py file Just move line 232
```python
self.sending(ldap_message)
```
after line 235:
```python
self._outstanding[message_id] = self.connection.request
self.sending(ldap_message)
```

just before the else: statement. Everything should work again.

Thanks for filing the bug,
Giovanni
