### ISSUE TITLE
Extended PasswordModify operation is not returning a success/fail indicator 

### ISSUE THREAD

**Issue by drochow** [cannatag/ldap3#470]
Hey,

performing an extended password modify operation is currently just returning something in the response if the password generation is used (no new pwd provided). 

I think should be changed to return an indicator if the operation was successful or raise an exception when it failed. The operation could e.g. not be successful when the LDAP Server has an password policy in place and the new password does not match the requirements: 
(e.g. response for such operation)
```
{'result': 19, 'description': 'constraintViolation', 'dn': '', 'message': 'Password fails quality checking policy', 'referrals': None, 'responseName': None, 'responseValue': None, 'type': 'extendedResp'}
```

An easy fix could be to make the following change to return True or False to indicate if the operation was successful or not:
(https://github.com/cannatag/ldap3/blob/master/ldap3/extend/standard/modifyPassword.py)  Line 64
```
    def populate_result(self):
        try:
            self.result['new_password'] = str(self.decoded_response['genPasswd'])
        except TypeError:  # optional field can be absent
            self.result['new_password'] = self.result['result'] == 0
```

Let me know if you would be ok with this change or if you would prefer an exception thrown here. Would be glad to make the fix and do a pull request. 

Kind Regards

**Comment by cannatag** [comment]
Please check code in dev, now ``extend.standard.modify_password()`` honours the ``raise_exception`` parameter of the Connection object and raise an exception or returns False if the change is not successful. Let me know if this is working for you.

**Comment by dkaatz** [comment]
I've the scenarios now:

With  `raise_exception=False` it is working like a charm now. 
With `raise_exception=True`it is also returning an exception when the operation was sucessful:
```
  File "/Users/David/.pyenv/versions/ldap_connector/lib/python3.6/site-packages/ldap3-2.4.1-py3.6.egg/ldap3/extend/__init__.py", line 81, in modify_password
    controls).send()
  File "/Users/David/.pyenv/versions/ldap_connector/lib/python3.6/site-packages/ldap3-2.4.1-py3.6.egg/ldap3/extend/operation.py", line 59, in send
    self.populate_result()
  File "/Users/David/.pyenv/versions/ldap_connector/lib/python3.6/site-packages/ldap3-2.4.1-py3.6.egg/ldap3/extend/standard/modifyPassword.py", line 71, in populate_result
    raise LDAPOperationResult(result=self.result['result'], description=self.result['description'], dn=result['dn'], message=self.result['message'], response_type=self.result['type'])
NameError: name 'result' is not defined
```
 I think there is a check missing at Line 68, it may should be something like:
```if self.result[self.response_attribute] == False and self.connection.raise_exceptions:```

Thank you for the fast response and fixing and this awesome lib 👍

**Comment by dkaatz** [comment]
I can confirm that the patch in commit fe311c6ceb53ac250e5528b4d7be9bf40b016f8b fixed the issue. I've tested both scenarios again. Working like a charm now!

Thank you!

**Comment by cannatag** [comment]
Thanks, will include this fix in the next release of ldap3.
