### ISSUE TITLE
pwdLastSet attribute cannot be set to -1

### ISSUE THREAD

**Issue by thanegill** [cannatag/ldap3#471]
As it fails validate_ad_timestamp. Though -1 is a valid value: https://msdn.microsoft.com/en-us/library/aa746510(v=vs.85).aspx

**Comment by cannatag** [comment]
Hi, this is very peculiar... the syntax of the ldap value is a timestamp only when read but an integer when written...

I've added a specific validator that accepts only the -1 value. Can you check the code in dev?

Thanks.
Giovanni

**Comment by thanegill** [comment]
That’s works! Thanks!
