### ISSUE TITLE
How to search with LDAP Control?

### ISSUE THREAD

**Issue by murasamelabo** [cannatag/ldap3#473]
How to search with LDAP Control?

I want to get  ldap search stats from Active Directory.

my code:

```
from ldap3 import Server, Connection, ALL
stats_controls = ("1.2.840.113556.1.4.970", True , None)


s = Server(host='<hostname>',port=389, get_info=ALL)
c = Connection(s, '<User>', '<Password>', auto_bind=True)
u = c.search('<SearchBase>' ,'<FIlter>',controls=stats_controls)
```

result:
`raise LDAPControlError('control must be a tuple of 3 elements: controlType, criticality (boolean) and controlValue (None if not provided)')
ldap3.core.exceptions.LDAPControlError: control must be a tuple of 3 elements: controlType, criticality (boolean) and controlValue (None if not provided)`

**Comment by cannatag** [comment]
Hi, the controls parameter accepts a list of controls, so the last line of your code should be:
```
u = c.search('<SearchBase>' ,'<FIlter>',controls=[stats_controls])
```

**Comment by murasamelabo** [comment]
Great! I got the stats data.

Many thanks!!
