### ISSUE TITLE
Searching for SINGLE-VALUE attribute with no values returns empty list

### ISSUE THREAD

**Issue by Busuwe** [cannatag/ldap3#477]
If one were to perform a search and explicitly request an attribute that is SINGLE-VALUE according to the schema then the returned value is a single value if the attribute is set on the object but an empty list if the attribute is missing.
I would argue that None would be a more sensible value than an empty list.

```python
conn.search("dc=internal,dc=machines", "(cn=mattias.testgroup)", ldap3.SUBTREE, attributes=["single_value_test_attr"])
```
Response when attribute exists on the object:
```
[{
  'raw_dn': b'cn=mattias.testgroup,ou=Groups,dc=internal,dc=machines',
  'dn': 'cn=mattias.testgroup,ou=Groups,dc=internal,dc=machines',
  'raw_attributes': {'single_value_test_attr': [b'abc']},
  'attributes': {'single_value_test_attr': 'abc'},
  'type': 'searchResEntry'
}]
```
Result when missing:
```
[{
  'raw_dn': b'cn=mattias.testgroup,ou=Groups,dc=internal,dc=machines',
  'dn': 'cn=mattias.testgroup,ou=Groups,dc=internal,dc=machines',
  'raw_attributes': {'single_value_test_attr': []},
  'attributes': {'single_value_test_attr': []},
  'type': 'searchResEntry'
}]
```

Unless this is intended behaviour, replacing [this line](https://github.com/cannatag/ldap3/blob/dev/ldap3/strategy/base.py#L407) with something like the code below seems to correct this

```python
if self.connection.server.schema and attribute_type in self.connection.server.schema.attribute_types and self.connection.server.schema.attribute_types[attribute_type].single_value:
    entry['attributes'][attribute_type] = None
else:
    entry['attributes'][attribute_type] = list()
```
Response after change when attribute is missing:
```
[{
  'raw_dn': b'cn=mattias.testgroup,ou=Groups,dc=internal,dc=machines',
  'dn': 'cn=mattias.testgroup,ou=Groups,dc=internal,dc=machines',
  'raw_attributes': {'single_value_test_attr': []},
  'attributes': {'single_value_test_attr': None},
  'type': 'searchResEntry'
}]
```

**Comment by cannatag** [comment]
Hi, this is controlled by the return_empty_attributes parameter of the Connection object. When it is set to True attributes are returned even if they are missing in the response returned from the server. In my experience  it’s better to set them to an empty list instead that to None because it’s easier to iterate over the whole list of attributes. I could add a global config parameter for specifying if a missing single value must be returned as None or as []. But I prefer to keep the default to [].

Bye,
Giovanni
