### ISSUE TITLE
all binds fail after one failed bind

### ISSUE THREAD

**Issue by profhase** [cannatag/ldap3#480]
Hi, I am experience the following unexpected behavioour:

    from ldap3 import Connection, Server, REUSABLE
    s = Server("myserver", 636, use_ssl=True)
    c = Connection(s, user="my-user", password="wrongPass", client_strategy=REUSABLE, pool_lifetime=30, auto_bind=True)

> /usr/local/lib/python3.4/dist-packages/ldap3/core/connection.py in __init__(self, server, user, password, auto_bind, version, authentication, client_strategy, auto_referrals, auto_range, sasl_mechanism, sasl_credentials, check_names, collect_usage, read_only, lazy, raise_exceptions, pool_name, pool_size, pool_lifetime, fast_decoder, receive_timeout, return_empty_attributes, use_referral_cache, auto_escape, auto_encode, pool_keepalive)
>     335                         if log_enabled(ERROR):
>     336                             log(ERROR, '%s for <%s>', self.last_error, self)
> --> 337                         raise LDAPBindError(self.last_error)
>     338             # else:  # for strategies with a fake server set get_info to NONE if server hasn't a schema
>     339             #     if self.server and not self.server.schema:
> 
> LDAPBindError: automatic bind not successful

But after the next call (in the same session but with correct password):

        c = Connection(s, user="my-user", password="correctPass", client_strategy=REUSABLE, pool_lifetime=30, auto_bind=True)

it results in the same error.

Do you have an idea why this happens? Thanks

PS: This is what happens in `ipython`

**Comment by cannatag** [comment]
Hi, if you don't specify the pool_name in the Connection object a connection pool is shared between connections. I've added the logic to check if the credentials information changes and issue a new bind.
Probably I should change the Reusable strategy to have different pools for connections to different servers.

Please check the code in dev, it should work now. 

Thanks,
Giovanni

**Comment by profhase** [comment]
Thanks, it works now. I am not sure which other implications it has when different connections recycle one connection pool. But this one works now, thank you.
