### ISSUE TITLE
pyasn1.error.PyAsn1Error: Attempted "__bool__" operation on ASN.1 schema object

### ISSUE THREAD

**Issue by ipsec** [cannatag/ldap3#483]
I getting this error while using extend.novell.get_universal_password() on ldap3 2.4.1 with pyasn1 0.4.2
How to fix?

**Comment by etingof** [comment]
I can guess that the root cause is that you are trying to access some optional and non-initialized ASN.1 field.

A reproducer might be helpful here. ;)

**Comment by cannatag** [comment]
Please check code in dev, It should work now.

@etingof This is the same problem I had when checking for presence of a PyAsn1 value without using the ``hasValue()`` method.

**Comment by cannatag** [comment]
Fixed in v2.5.
