### ISSUE TITLE
pwdLastSet Attribute cannot be set to 0

### ISSUE THREAD

**Issue by tbarrettwilsdon** [cannatag/ldap3#484]
It appears that after the most recent change (2.4.1) was pushed, pwdLastSet cannot be set to 0, which is a valid non-timestamp value for Active Directory. Issue #471 references the same issue but for the -1 value, and while the fix for that was shipped in the most recent build, it seems to have caused the 0 value to be rejected. 

0 remains a valid value for the pwdLastSet attribute - ref https://msdn.microsoft.com/en-us/library/aa746510(v=vs.85).aspx

The following code preforms as expected with ldap3==2.4.0:
`set_pls = {"pwdLastSet": (ldap3.MODIFY_REPLACE, ["0"])}
self.connection.modify(distinguished_name, set_pls)
`

However, with ldap3==2.4.1, the same code throws an LDAPException "value '0' non valid for attribute 'pwdLastSet'"

Thanks!

**Comment by cannatag** [comment]
Thanks, I've updated the validator, can you check the code in dev?

**Comment by tbarrettwilsdon** [comment]
Hey @cannatag - thanks for the quick reply! The changes in dev #4aa0a9f002726d41e87ff7bda5a6921818b60888 resolved the issue. I'll keep my production build pinned to 2.4.0 until this is shipped to the master branch. Much appreciated!

**Comment by cannatag** [comment]
Thanks, I will release this fix in the next version of ldap3.

**Comment by anton00706** [comment]
Thank you! Can't wait to get this updated. When about to expect?

**Comment by cannatag** [comment]
Fixed in v2.5.
