### ISSUE TITLE
Better support for LDAP Auxiliary classes?

### ISSUE THREAD

**Issue by mike1158** [cannatag/ldap3#486]
I have an ActiveDirectory 2003 server, in which posixAccount is an "auxilliary" object class.  Because aux classes don't show up as a direct objectClass of an LDAP object, adding "posixAccount" to the list of classes in an ldap3 ObjectDef doesn't work--doing so causes searches to fail to find any objects at all. 

I can read individual attributes (eg. "gecos") by manually adding them to the ObjectDef, but similar to #455, attempting get a writable cursor just raises ldap3.core.exceptions.LDAPCursorError: attribute 'gecos' not in object class.

Direct database operations (eg. conn.modify()) do work, but it would be nice to be able to use the abstraction layer.

References:
https://msdn.microsoft.com/en-us/library/cc223233.aspx
https://msdn.microsoft.com/en-us/library/ms676290(VS.85).aspx

**Comment by cannatag** [comment]
Hi, I'm aware of this, will try to fix in one of the future ldap3 release. The abstract layer was very simple at first, now it's quite complete but is still lacking features. Probably I will add an additional parameter for the auxiliary classes, but still have to elaborate on this.

**Comment by cannatag** [comment]
Please check code in dev. I've added an ``auxiliary_class`` parameter in the ObjectDef and in the Reader and Writer definition where you can add one or more auxiliary_classes whose attributes will be allowed in entries. This still doesn't solve the issue when you add an attributes for a not still used auxiliary class but I'm working on it.

Can you give a try to the code?

**Comment by cannatag** [comment]
Fixed in v2.5.
