### ISSUE TITLE
How to make user must change their password in AD

### ISSUE THREAD

**Issue by ling7334** [cannatag/ldap3#492]
I've try to set `pwdLastSet` to 0, and it return an Error.
Then I found `pwdLastSet in AD is valid only for -1 (thanks Thane)` in the latest changelog.
So, is there any method I can make user must change their password in AD?
Thank!

**Comment by cannatag** [comment]
Sorry, this will be fixed in the upcoming release of ldap3.

Bye,
Giovanni
