### ISSUE TITLE
Checking whether an LDAP entry contains an item raises an LDAPCursorError if the key for the item isn't found

### ISSUE THREAD

**Issue by maxsond** [cannatag/ldap3#493]
```EntryBase.__contains__``` calls ```EntryBase.__getitem__``` and returns false on an ```LDAPKeyError```.

```__getitem__``` appears to have raised an ```LDAPKeyError``` in 2.2.3 and 2.2.4 if the key wasn't found, but at some point between then and now, that was changed to ```LDAPCursorError``` and ```__contains__``` was not updated to reflect that change. 

This has the result of code checking whether LDAP entries contain items that they don't using 2.2.4 to return False as expected, but to raise an unhandled LDAPCursorError exception with later versions of ldap3, such as 2.4.1.

I'd like to request either that ```LDAPCursorError``` be changed back to ```LDAPKeyError``` there, or if that change was intentional then ```__contains__``` be updated to catch that exception and return False when it does. 

Although probably not the best implementation, I have submitted a proposed solution in https://github.com/cannatag/ldap3/pull/491 which I'm using locally as a patch until an official fix for this is released.

**Comment by vimaier** [comment]
Just faced this issue as well.
I was thinking about creating a pull request but the proposed solutions by @maxsond fixes the issue already. Well done!

**Comment by cannatag** [comment]
Thanks, I've changed the code to raise the right exception. Can you check the code in dev?

**Comment by maxsond** [comment]
I gave dev a spin with my application and confirmed the issue is resolved.

**Comment by cannatag** [comment]
Thanks, I will release the fix in the next release of ldap3.

**Comment by cannatag** [comment]
Fixed in v2.5.
