### ISSUE TITLE
Error on non-writable stream on read_only file connection

### ISSUE THREAD

**Issue by xi** [cannatag/ldap3#50]
As far as I understand, I could use this package to parse an LDIF file like this:

```python
from ldap3 import Connection, LDIF
c = Connection(None, client_strategy=LDIF, read_only=True)
c.stream = open('foo.ldif', 'w')
with c:
    ...
```

If the stream object is not writable (i.e. `not stream.writable()`) this won't work. I guess this is the desired effect when talking to a real server. But it is at least confusing when parsing a file.

I can see multiple solutions to this:

-   document the current behavior
-   clearly state in the docs that this library is not meant for parsing LDIF files
-   allow a non-writable stream if `server` is `None` and `read_only` is true
-   provide an altogether separate way to parse files

Maybe a solution is aleady in place and I just did not find it. In that case I would be thankful for a hint.

**Comment by cannatag** [comment]
Hi Tobias, 
The ldif stream is only for output, you can use it for writing the search result. The ldap protocol doesn't provide a standard way to parse an ldif file, but leave this task to the actual ldap server implementation. Furthermore when parsing an ldif file restrictions are a bit relaxed by the server, for example forward reference to still not created object is allowed. 

ldap3 is a client library not tied to any particular ldap server, so it doesn't include any utility to parse ldif file for creating ldap objects. I will clarify this in the docs.

Bye,
Giovanni

----- Messaggio originale -----
Da: "Tobias Bengfort" <notifications@github.com>
Inviato: ‎08/‎05/‎2015 10:58
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Oggetto: [ldap3] Error non non-writable stream on read_only file connection(#50)

As far as I understand, I could use this package to parse an LDIF file like this:
from ldap3 import Connection, LDIF
c = Connection(None, client_strategy=LDIF, read_only=True)
c.stream = open('foo.ldif', 'w')
with c:
    ...If the stream object is not writable (i.e. not stream.writable()) this won't work. I guess this is the desired effect when talking to a real server. But it is at least confusing when parsing a file.
I can see multiple solutions to this:
document the current behavior 
clearly state in the docs that this library is not meant for parsing LDIF files 
allow a non-writable stream if server is None and read_only is true 
provide an altogether separate way to parse files 
Maybe a solution is aleady in place and I just did not find it. In that case I would be thankful for a hint.

**Comment by cannatag** [comment]
I've updated the docs. 

Bye,
GIovanni

**Comment by xi** [comment]
Sorry to bother you again. I ust wanted to check the updated docs and connot find them anywhere. Could you point me to a commit?

**Comment by cannatag** [comment]
You're right. I forgot to merge from dev to master! Now it'updated. You should find the following in the ldif.rst docs:

ldap3 can stream the output of a search (LDIF-CONTENT) or of an operation (LDIF-CHANGE) to a file object. It cannot read a file with LDIF content because this is not in the LDAPv3 standard. Each LDAP searver has its own tools to import an LDIF-CONTENT or perform LDIF-CHANGE.

Do you think this explain the issue correctly?

Bye,
Giovanni

**Comment by xi** [comment]
Sounds good. A link to possible ldif parsers would be helpful, but I do not really know of any I could recommend. btw, there is a typo in "searver".

**Comment by cannatag** [comment]
Thanks for the typo. Will fix it soon. 
Regarding the parsing of LDIF It could definitively be done for the LDIF-CHANGE format (that reflects atomic ldap operations) but not for LDIF-CONTENT, because of forward references (in this case you absolutely need a tool from the specific ldap server). Can you tell me why you think it's important to have it in the library? 

Thanks,
Giovanni

**Comment by xi** [comment]
> Can you tell me why you think it's important to have it in the library?

I am working on a command line tool that can merge adressbook data from different sources (https://github.com/xi/cctool). This is mostly for my own use by I also try to make it useful for others. 

One of the source formats should be LDIF-CONTENT because that is what you can export from thunderbird.

I started with [https://github.com/rbarrois/python-ldap/blob/master/Lib/ldif.py](the ldif module from python-ldap). But that does not have python3 support. It also failed parsing the data exported from thunderbird which I later found was actually a [thunderbird bug](https://bugzilla.mozilla.org/show_bug.cgi?id=230334).

I searched for a LDIF library which supports python3 and came across yours. When you told me that what I wanted was out of the scope of this project I went one creating my own fork of the python-ldap module at https://github.com/xi/ldif3.

That is of course far from ideal because I don't really have the time or the knowledge to maintain a high quality LIDF library. On the bright side I can implement a "less strict mode"  in my own library that works around existing thunderbird bugs.

> A link to possible ldif parsers would be helpful, but I do not really know of any I could recommend.

I guess I just hoped that there is a great LDIF library somewhere and I just failed to find it.

> Regarding the parsing of LDIF It could definitively be done for the LDIF-CHANGE format (that reflects atomic ldap operations) but not for LDIF-CONTENT, because of forward references (in this case you absolutely need a tool from the specific ldap server).

I am not completely sure but I guess you are refering to the cases where the attribute value is a URL. The [spec](https://tools.ietf.org/html/rfc2849) explicitly states that most protocols are optional:

      6) When a URL is specified in an attrval-spec, the following
          conventions apply:

         a) Implementations SHOULD support the file:// URL format.  The
            contents of the referenced file are to be included verbatim
            in the interpreted output of the LDIF file.
         b) Implementations MAY support other URL formats.  The
            semantics associated with each supported URL will be
            documented in an associated Applicability Statement.

The python-ldap module mentioned above simply uses `urllib` for this task.

Sorry for the long answer on an alrady closed issue. I just felt that this might be helpful. It is totally fine if you just ignore this because it seems to be a rather specific issue. Thanks for the good work!

**Comment by cannatag** [comment]
HI, the problem with LDIF-CONTENT is that in the ldif stream you can have forward reference to object still not created. For example you can have a iNetOrgPerson that is member of a group that is defined later in the stream, so adding it with the usual ADD operation would return an error. This is solved by the import tools that are usually part of the LDAP Server that relaxes the control for forward reference and other glitches of the ldif format. 

I understand your problem but don't think there can be a general solution.
