### ISSUE TITLE
I think mocked search should be case insensitive

### ISSUE THREAD

**Issue by kiddick** [cannatag/ldap3#501]
I am talking about especially this part of mocksync https://github.com/cannatag/ldap3/blob/e45a6ad03c2016b3fe7d7cc98f09be38d2f71490/ldap3/strategy/mockBase.py#L664

**Comment by cannatag** [comment]
I agree with you. Also the base should be "normalized" to allow different spacing. 

Will work on this in the next release of ldap3.

Bye,
Giovanni

**Comment by cannatag** [comment]
Please check code in dev. It should work now.

**Comment by cannatag** [comment]
Fixed in 2.5.
