### ISSUE TITLE
Question regarding the "ldap3" package in python2.7

### ISSUE THREAD

**Issue by phu004** [cannatag/ldap3#506]
Hey guys,

I am currently learning how to do ldap queries with the packages called "ldap3". In official tutorial site for "ldap3", it states that we can create a tls object to validate the server certificate:

"tls = Tls(local_private_key_file='client_private_key.pem', local_certificate_file='client_cert.pem', validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1, ca_certs_file='ca_certs.b64')"

I am wondering what cert do we use for "ca_certs_file"? Should it be the Root Cert, intermediate cert, or the end-entity cert that is issued to the ldap server? At the moment, my ldap query would only successful if I use the Root Cert. Otherwise I get [SSL: CERTIFICATE_VERIFY_FAILED].

**Comment by cannatag** [comment]
Hi, it should be the certificate of the authority that issued your certificate or your internal CA. If you don't need to validate the certificate you can just set validate to ssl.CERT_NONE.

**Comment by phu004** [comment]
Thanks for the reply.  The certificate chain looks like this:

QuoVadis Root CA 2 G3                                     <-  root  cert 
    |-- QuoVadis Global SSL ICA G3                     <- Intermediate cert
             |-- myldaps.com                                     <- end-entity cert that is issued to the ldap server

Are you suggesting that the "end-entity" cert should be used for "ca_certs_file"?

Also an interesting observation is that if I omit all the other parameters but "validate=ssl.CERT_REQUIRED" when creating the tls object,  the ldap query will return successful. Does it mean ldap3 could automatically choose the correct certs to validate the ldap server?

**Comment by cannatag** [comment]
Hi, the ca-cert should be made of the public keys of the "QuoVadis Root CA
2 G3" and the "QuoVadis Global SSL ICA G3" in a single file.

If you omit the parameters with "validate=ssl.CERT_REQUIRED"  and you're
usiing a quite recent version of Python, the SSL library will try to use
the CA configured on your system. so if your system is properly configured
your connection will be established in a safe way.

**Comment by phu004** [comment]
Thanks for the clarification!

**Comment by cannatag** [comment]
You’re welcome!

**Comment by HOMiLeee** [comment]
@phu004 Hi, has your problem been solved? Currently I have encountered the same problem as you. Can you provide me with your demo version of the code to study? Thank you very much;
