### ISSUE TITLE
ad_unlock_account raise LDAPInvalidValueError: value '0' non valid for attribute 'lockoutTime'

### ISSUE THREAD

**Issue by francowxu** [cannatag/ldap3#516]
ldap3.extend.microsoft.unlockAccount.ad_unlock_account(connection, user_dn, controls=None)

When I called this function，I got _LDAPInvalidValueError: value '0' non valid for attribute 'lockoutTime'_

I checked the traceback and found problem might be here:
36     result = connection.modify(user_dn,
     37                                {'lockoutTime': [(MODIFY_REPLACE, [0])]},
---> 38                                controls)

The 0 in the parameter should be '0' for the modify function.

Full trace are here:

---------------------------------------------------------------------------
LDAPInvalidValueError                     Traceback (most recent call last)
<ipython-input-62-cc4dbaf2a2a3> in <module>()
----> 1 c1.extend.microsoft.unlock_account('cn=test999, ou=HuaXing, dc=huaxing, dc=com')

~/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/ldap3/extend/__init__.py in unlock_account(self, user)
    267     def unlock_account(self, user):
    268         return ad_unlock_account(self._connection,
--> 269                                  user)
    270 
    271     def add_members_to_groups(self, members, groups, fix=True):

~/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/ldap3/extend/microsoft/unlockAccount.py in ad_unlock_account(connection, user_dn, controls)
     **36     result = connection.modify(user_dn,
     37                                {'lockoutTime': [(MODIFY_REPLACE, [0])]},
---> 38                                controls)**
     39 
     40     if not connection.strategy.sync:

~/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/ldap3/core/connection.py in modify(self, dn, changes, controls)
   1049                                 log(ERROR, '%s for <%s>', self.last_error, self)
   1050                             raise LDAPChangeError(self.last_error)
-> 1051             request = modify_operation(dn, changes, self.auto_encode, self.server.schema if self.server else None, validator=self.server.custom_validator if self.server else None, check_names=self.check_names)
   1052             if log_enabled(PROTOCOL):
   1053                 log(PROTOCOL, 'MODIFY request <%s> sent via <%s>', modify_request_to_dict(request), self)

~/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/ldap3/operation/modify.py in modify_operation(dn, changes, auto_encode, schema, validator, check_names)
     68             if isinstance(change_operation[1], SEQUENCE_TYPES):
     69                 for index, value in enumerate(change_operation[1]):
---> 70                     partial_attribute['vals'].setComponentByPosition(index, prepare_for_sending(validate_attribute_value(schema, attribute, value, auto_encode, validator, check_names=check_names)))
     71             else:
     72                 partial_attribute['vals'].setComponentByPosition(0, prepare_for_sending(validate_attribute_value(schema, attribute, change_operation[1], auto_encode, validator, check_names=check_names)))

~/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/ldap3/protocol/convert.py in validate_attribute_value(schema, name, value, auto_encode, validator, check_names)
    158             validated = validator(value)
    159             if validated is False:
--> 160                 raise LDAPInvalidValueError('value \'%s\' non valid for attribute \'%s\'' % (value, name))
    161             elif validated is not True:  # a valid LDAP value equivalent to the actual value
    162                 value = validated

LDAPInvalidValueError: value '0' non valid for attribute 'lockoutTime'

**Comment by cannatag** [comment]
Thanks, can you check the code in dev? It should work now.

**Comment by cannatag** [comment]
Fixed in 2.5
