### ISSUE TITLE
Cannot use controls with empty control values.

### ISSUE THREAD

**Issue by hbayindir** [cannatag/ldap3#52]
Hello,

I'm trying to implement an LDAP login screen interfacing with an OpenLDAP server. Normal negotiations are executing fine, however the OpenLDAP server I'm negotiating with also implements <code>Password Policy Overlay</code>. This overlay requires its <code>Control Request</code> to contain two fields. The <code>Control Value</code> field should not be sent, otherwise OpenLDAP server returns a <code>ProtocolError</code> (even if the field is empty).

Unfortunately there's no way to not to send the value field with the control requests. Adding the ability to send controls with no value fields is necessary to implement <code>Password Policy Overlay</code>. It's not possible to implement <code>Password Policy Overlay</code>.

**Comment by cannatag** [comment]
Hi Hakan, please try the version in dev, and send None as controlValue when you need no value at all. Let me know if this solve your problem.

Bye,
Giovanni

**Comment by cannatag** [comment]
0.9.8.4 released. Can you check if this works for you?

Bye,
Giovanni

**Comment by hbayindir** [comment]
Sorry for late reply. I will have time to check the new library release. Didn't want to generate new noise in the thread without testing. You can be sure to receive feedback here tomorrow. Thanks for replies and for all the hard work.

Bye,

Hakan

**Comment by hbayindir** [comment]
Hi Giovanni,
Last version works as expected, great! Thanks a lot for your effort!
Thanks again for the library and the work,

Bye,
Hakan

**Comment by cannatag** [comment]
Ok, thanks for testing it.

Bye,
Giovanni
