### ISSUE TITLE
delete_old_dn does not take effect in modify_dn

### ISSUE THREAD

**Issue by Vovaman** [cannatag/ldap3#521]
I'd like to copy entry from one branch to another (setting delete_old_dn flag to False):
```
import ldap3
from ldap3.core.exceptions import LDAPException

ldapServer = ldap3.Server('ldap://localhost:389')
user = 'cn=admin,cn=smt'
pwd = 'OstecSMT'

ldapConn = ldap3.Connection (ldapServer, user=user, password=pwd, auto_bind=True)

dn = 'cn=SimpleObject,cn=templates,cn=model,cn=smt'
rdn = 'cn=SimpleObject'

ldapConn.modify_dn(dn=dn, relative_dn=rdn, new_superior='cn=objects,cn=smt', delete_old_dn=False)
```
...and entry is just moved
Before:
![before](https://user-images.githubusercontent.com/11216787/38765585-2b0b071c-3fcd-11e8-8efb-dd7a7ee393a6.gif)

After:
![after](https://user-images.githubusercontent.com/11216787/38765587-343868de-3fcd-11e8-8810-fdf3f66870a2.gif)

LDAP server - OpenLDAP 2.4.42

**Comment by cannatag** [comment]
delete_old_dn is not for copying , when false it just keeps the old rdn of the object in case you use a multivalue attribute as rds (Relative ditinguished name) when you rename the entry:

Let's say you have the entry ``cn=user1,ou=test,o=mycompany`` and you perform the operation ``modify_dn('cn=user1,ou=test,o=mycompany', 'cn=user2', delete_old_dn=False)`` then the new entry has both ``user1`` and ``user2`` as cn. This happens only if the cn attribute is multivalue.

There is nothing in the ldap protocol that allow you to copy an entry, If you want to copy an object you must read it with a search and create a new entry, taking care of changing the attributes as requested by your ldap server. Obviously you can't create any operational attribute. Also if you're copying some entries that have a "special" meaning for your system (as an user with password or ACL) probably you can't simply copy the attribute values, but have to use some specific procedure.

**Comment by Vovaman** [comment]
Thanx. I see...
