### ISSUE TITLE
Consider submitting ldap3.protocol to pyasn1-modules

### ISSUE THREAD

**Issue by daenney** [cannatag/ldap3#523]
[pyasn1-modules](https://github.com/etingof/pyasn1-modules) (maintained by the pyasn1 maintainer) is a collection of (generated) ASN.1 data structures. It currently contains some, but not all, LDAP related RFCs. Perhaps the `rfc*.py`'s in `ldap3.protocol` could be submitted there to benefit the rest of the community?

**Comment by etingof** [comment]
Just a quick note that I'd be happy to incorporate LDAP structures into pyasn1-modules should you consider contributing them. ;-)

**Comment by daenney** [comment]
From the looks of pyasn1-modules it contains the original RFC 2251 but not all of the updates through by most important RFC 4511, 4512 and 4527

**Comment by cannatag** [comment]
The rfc* modules in ldap3.protocol are quite stable, so I think they can be included in the pyasn1-modules package too. 

There is some specific coding or formatting rule or they can be simply added to the pyasn1-modules package?
