### ISSUE TITLE
cannot import name 'LDAPBindError'

### ISSUE THREAD

**Issue by marcosgeorgopoulos** [cannatag/ldap3#528]
Hi I am using ldap3 and do not seem to be able to import LDAPBind Error.

pip3.6 list |grep ldap3
ldap3 (2.5)

python3.6 --version
Python 3.6.4

```
from ldap3 import Server, Connection, ALL, LDAPBindError, SUBTREE, ALL_ATTRIBUTES,MODIFY_REPLACE
ImportError: cannot import name 'LDAPBindError'
```

**Comment by cannatag** [comment]
Hi, starting with version 2 exceptions are stored in the ldap3.core.exceptions namespace. Just import from that path.

Bye,
Giovanni
