### ISSUE TITLE
Reference cycles in RestartableStrategy

### ISSUE THREAD

**Issue by kxt** [cannatag/ldap3#529]
RestartableStrategy has an _add_exception_to_history method, which stores exception objects in a list, which is a subtle way to leak objects in python.

Exceptions contain a reference to the traceback object, which has references to the objects on the stack frame. If a reference is taken to the exception object by another object already in one of the stack frames, a reference cycle is immediately created.

Here is an example, where connection is a Connection with RESTARTABLE strategy, and get it's exception history:

    >>> exception_history = connection.strategy.exception_history

Let's take one of the exceptions from the history:

    >>> exception = exception_history[0][2]

It has a traceback object with a stack frame, lets have a look at its variables:

    >>> exception.__traceback__.tb_frame.f_locals
    {'self': <ldap3.strategy.restartable.RestartableStrategy object at 0x7f9e0fb5bac8>, 'counter': 0, 'unix_socket': False, 'address': [<AddressFamily.AF_INET: 2>, <SocketKind ...

We can see that it has a reference to 'self', which is the very same RestartableStrategy object that we are inspecting, thus it is a reference cycle:

    >>> id(connection.strategy)
    140316845128392
    >>> id(exception.__traceback__.tb_frame.f_locals['self'])
    140316845128392

These leaked stack frames contain references to socket objects, causing severe fd leakage (by default, every unsuccessful connection attempt will create 30 fds that are never closed).

This blog post has a nice writeup about the general issue with taking references to exceptions in Python. 
https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/

~~One of the possible workarounds can be `del`eting the traceback object from the exceptions, although usually I avoid taking references to exceptions at all cost.~~ edit: you can't delete the traceback from the object.

**Comment by cannatag** [comment]
Thanks for pointing this out. Will read the blog and will try to find a solution.

**Comment by cannatag** [comment]
Hi, I've followed the suggestion in the blog to avoid the circular reference. Now the __traceback__ attribute is set to None. Can you check the code in dev?

Thanks,
Giovanni

**Comment by cannatag** [comment]
Hi, how do you check for leaks? Do you use any additional package?

**Comment by kxt** [comment]
I'm using the builtin gc module.

Here is a piece of code that outputs the objects caught up in the reference cycles. After clearing the exception history (which should clean up all the objects if it weren't for the cycles), a manual garbage collectoin is triggered by gc.collect(). After that, gc.garbage contains the objects that are unreachable but not collected.

Please note that this code uses DEBUG_SAVEALL, which marks every unreachable reference cycle as garbage. This does not necessary mean leakage, as reference cycles can be gc-d if they do not involve any objects with __del__ methods. If you change it to DEBUG_UNCOLLECTABLE, it only gathers uncollectable objects (permanent leaks), which is an empty list for this test case (because it does not involve any objects with __del__).

In a more involved case, I can produce uncollectable cycles too, with demonstrable fd leaks, but apparently it needs SSL with validated certificates (that fail in very specific kind of ways), it would need a more complex test code to reproduce that. I assume that the ssl module has some uncollectable objects that get caught up in the reference cycles, resulting in the fd leaks.

```import socketserver
import threading
from ldap3 import Server, Connection, RESTARTABLE, set_config_parameter, ServerPool

import gc, pprint
gc.set_debug(gc.DEBUG_SAVEALL)

set_config_parameter("RESTARTABLE_TRIES", 2) # number of attemps
set_config_parameter("POOLING_LOOP_TIMEOUT", 1) # sleep between attempts

#dummy server that accepts a connection and closes it immediately
sock_server = socketserver.TCPServer(("127.0.0.1", 0), socketserver.BaseRequestHandler)
threading.Thread(target=sock_server.serve_forever).start()

server = Server(sock_server.server_address[0], sock_server.server_address[1], use_ssl=False)
connection = Connection(ServerPool([server], active=1), client_strategy=RESTARTABLE)

try:
    connection.bind()
except Exception as e:
    print("Exception was caught: ", e)

sock_server.shutdown()

connection.strategy._reset_exception_history()
gc.collect()
pprint.pprint(gc.garbage, indent=4)```

**Comment by kxt** [comment]
I tried to find where can the way exceptions are handled cause reference cycles, please have a look at this patch:  
https://github.com/kxt/ldap3-1/commit/3932eddd2d3f7657ee91884664ab167071ed0e0b

Not sure if this is a good way to solve the problem, but it highlights the places where something needs to be done. Perhaps the exception_history should not contain exceptions at all, just strings with the error messages. The tracebacks are already lost, and not really meaningful anyway for the callers.

Also noticed that there are exception factories, creating new, unique exception types for every exception thrown (along with some validation on the type), I could not figure out what their use case is.

With this patch, the exception related reference cycles are gone. There are still present some involving FilterNode objects created by parse_filter. I could not figure out where exactly the cycle is, but they might be benign (as long as no objects with __del__ methods can appear in the cycle).

**Comment by cannatag** [comment]
Thank you. I was working on this right now. I looked at your code and it makes sense. I agree with you that probably it would be enough to store in the exception_history list the exception type and the string message of the catched exception. 

The idea of the "exception factory" was to merge the ldap3 specific exception with th exception raised by python itself. This is because in the former versions of ldap3 I had only a few specific ldap3 exceptions, later I created all the exceptions in ldap3.core.exceptions, but for backward compatibility I created the "factory" code to merge the ldap3 exception with the python one. In this way existing code that catched the python exception would work anyway.

Will look at your patch immediately.

thanks,
Giovanni

**Comment by cannatag** [comment]
Hi, can you check the code in dev? I've applied your patches.

Thanks,
Giovanni

**Comment by kxt** [comment]
I did a quick test with a testcase similar to the one I posted here.

dev current (c1dd79d3850458d3f34125435da925899afebacb) state is significantly better, only 9 objects have refcycles, all of them ldap3 exceptions, but no stack frames, so there is basically no risk of uncollectable cycles.

I will do a check with proper environment soon.

**Comment by kxt** [comment]
Looks good, I could not reproduce the socket leakage in the real-world scenario, either!

**Comment by kxt** [comment]
Wrong button, didn't mean to close the issue :).

**Comment by cannatag** [comment]
Thanks, will release this patch in the next version of ldap3.

Bye,
Giovanni

**Comment by cannatag** [comment]
v 2.5.1 released.
