### ISSUE TITLE
ldap search smears in clunky status messages...

### ISSUE THREAD

**Issue by flynn1973** [cannatag/ldap3#532]
how can i get rid of this STATUS:READTIME stuff which i never requested?

>>> conn.entries[3]
DN: cn=XDB_STAFF,ou=SUDOers,ou=apps,dc=my,dc=domain - STATUS: Read - READ TIME: 2018-05-07T14:29:48.747241
    sudoCommand: /usr/bin/su - ora*
    sudoUser: blue
              neydwa
              schama
              wimm
              oberwa
              flecal
              dattju
              etzean
              pomaan

**Comment by cannatag** [comment]
Hi, that is just the representation of the entry status when in interactive mode or using the repr() function. If you want you can print out only the attributes you want. If the attributes is "sudoUser" and sudoCommand  you can use conn.entries[3].sudoUser and conn.entries[3].sudoCommand.

**Comment by flynn1973** [comment]
ok, got time to play around with this again, and of course i cant get my way through it. for example i want to get a list of all "cn"'s in my test directory but it seems impossible to do.  i always get only one.
`
'def index():
    searchParameters = { 'search_base':
                        'ou=SUDOers,ou=apps,dc=sozialversicherung,dc=at',
                        'search_filter': '(objectclass=SudoRole)',
                        'attributes': ['cn' ] }

    server = Server('lpgaixmgmtlx01.test.*.*', get_info=ALL)
    conn = Connection(server, 'cn=roots,dc=*,dc=*','***', auto_bind=True)
    conn.search(**searchParameters)
    r = conn.entries
    return (r[1].entry_to_json())
`
only gives this...

{ "attributes": { "cn": [ "XAIX_STAFF" ] }, "dn": "cn=XAIX_STAFF,ou=SUDOers,ou=apps,dc=*,dc=*" }

how to get a list of all cn's without using any for loops, and why this dn crap is always printed?

example output should be like this ->
{ "attributes": { "cn": [ "XAIX_STAFF" ] }
  "attributes": { "cn": [ "next cn" ]}
  "attributes": { "cn": [ "next cn" ] } 
  ...
}
