### ISSUE TITLE
Exceptions in PooledConnectionThread

### ISSUE THREAD

**Issue by kxt** [cannatag/ldap3#539]
When using REUSABLE strategy, certain errors arising inside PooledConnectionThread.run() can propagate to the top of the call stack without the caller's thread being notified. Thus such errors (thrown from open, start_tls or bind) are not catchable by the caller, resulting in tracebacks and the termination of the pooled connection thread.

**Comment by kxt** [comment]
On a tangential note, it seems that in ReusableStrategy.validate_bind() makes one of the worker connections in the pool lazy.

        temp_connection = self.pool.workers[0].connection
        temp_connection.lazy = False
        if not self.connection.server.schema or not self.connection.server.info:
            result = self.pool.workers[0].connection.bind(controls=controls)
        else:
            result = self.pool.workers[0].connection.bind(controls=controls, read_server_info=False)
        temp_connection.unbind()
        temp_connection.lazy = True

This seems weird, because neither the master connection nor any other worker connections are lazy. Is this the intended behavior? Isn't it supposed to be something likes this:

        saved_lazy = temp_connection.lazy
        temp_connection.lazy = False
        if not self.connection.server.schema or not self.connection.server.info:
            result = temp_connection.bind(controls=controls)
        else:
            result = temp_connection.bind(controls=controls, read_server_info=False)
        temp_connection.lazy = saved_lazy

**Comment by cannatag** [comment]
Thanks, will check this in the weekend.

Giovanni
