### ISSUE TITLE
Using Search Controls - Subentries (RFC3672)

### ISSUE THREAD

**Issue by johnnysheppard-isode** [cannatag/ldap3#548]
Hi, 

I was wondering if you could help me. I'm trying to run an ldap search using this great library. I'm trying to set the Subentries control to "True", but it doesn't seem to be working.

According to the [RFC](https://tools.ietf.org/html/rfc3672), the True value has the:

> three octet encoding { 01 01 FF }

How do I set this in the control Tuple? I've tried just setting `True`, but that doesn't seem to be working.

My Code Sample is:

```python
server = ldap3.Server("myhost", 389)
connection = ldap3.Connection(server, user="cn=DSA Manager,cn=config", password="mypassword")
connection.search(search_base="cn=US",
                  search_filter="(objectClass=*)",
                  search_scope=ldap3.SUBTREE,
                  controls=[("1.3.6.1.4.1.4203.1.10.1", False, True)])
```

Any ideas what I'm doing wrong?

**Comment by mochanliu** [comment]
[('1.3.6.1.4.1.4203.1.10.1',True,b'\x01\x01\xFF')]
Try this

**Comment by johnnysheppard-isode** [comment]
Thanks @mochanliu, that was very helpful. It was a little neater than my solution.
