### ISSUE TITLE
LDAPBindError: automatic bind not successful - unavailable

### ISSUE THREAD

**Issue by SofianeB** [cannatag/ldap3#549]
Hi, 

I am getting this after I updated jupyterhub-ldapauthenticator, which is related to ldap3. 
I also reproduced the error without jupyterhub and the error is: 

LDAPBindError: automatic bind not successful - unavailable

error in bind {'type': 'bindResponse', 'referrals': None, 'description': 'unavailable', 'message': '[Original error=52] Unable to retrieve a backend BIND connection.', 'dn': '', 'result': 52, 'saslCreds': None}

Thank you.

**Comment by cannatag** [comment]
Are you able to connect to the ldap in another way? (ldapsearch or an ldap browser)?

The main difference in 2.5 is how non ascii characters are sent to the server,  what version of ldap3 did you migrate from?
