### ISSUE TITLE
loading smb schema

### ISSUE THREAD

**Issue by raveenpl** [cannatag/ldap3#552]
Hi,

I'd like to perform whole configuration of the database using ldap3 library. One of my first steps is to prepare database to cooperate with Samba.

Is there any option to load Samba schema (ideally at once) without applying each rule from the samba.ldif file? 

regards,
raveenpl

**Comment by cannatag** [comment]
You can read the schema from the server once it is configured. But LDAP doesn't provide any standard method for configuring the server itself, each server has a different way of configuring itself. LDAP is a communication protocol so it is not aware of the actual implementation of the server.
