### ISSUE TITLE
AD Group retrieval

### ISSUE THREAD

**Issue by mailtokuttu** [cannatag/ldap3#553]
Dear sir,

Could you please give me a hint how to retrieve the Active Directory users group list? I would like to do this in Python 3.6 on Windows. I would need a simple Py example file, so that I could understand and develop further. 

Thanks very much in advance as I am fairly new to Python 3.6.

**Comment by cannatag** [comment]
I don't user AD, but I think you must perform a search with a filter similar to '(&(objectClass=GROUP)(cn=group_name))' where group_name is the name of your group or you can query all the member of a group object if you know the full dn of the group.

**Comment by mailtokuttu** [comment]
Thanks very much for the hint. Let me try and come back to you. Appreciate it.
