### ISSUE TITLE
Base Strategy with auto_bind=True will bind twice

### ISSUE THREAD

**Issue by nwalsh1995** [cannatag/ldap3#556]
We have an LDAP server that validates OTP. The essence of OTP is that the same token is only ever valid once. On the first bind, it approves the token, and then on the second bind, it fails since it has already been used. This breaks the authentication.

# Code flow

`do_auto_bind` will first call `.open` for your strategy.
https://github.com/cannatag/ldap3/blob/43234e26909cd3a07e1570934d65752a9b3726de/ldap3/core/connection.py#L331-L336

The problem is that if you use the BaseStrategy (or anything that extends BaseStrategy that doesn't change this method), it will also call `do_auto_bind` near the end of its `open`:
https://github.com/cannatag/ldap3/blob/43234e26909cd3a07e1570934d65752a9b3726de/ldap3/strategy/base.py#L151-L155

This causes two binds to be performed. I'm not sure on what kind of fix you want, but adding a simple check for `if self.bound: return` in `do_auto_bind` should be sufficient. You can also protect the `.bind` method if it has already been bound.

**Comment by cannatag** [comment]
v 2.5.1 released.
