### ISSUE TITLE
LDAPAttributeError: invalid attribute type -

### ISSUE THREAD

**Issue by VikramNS** [cannatag/ldap3#557]
Python Code: 

retrive_attrs = ['*',
                 '-'
                ]

searchParameters = {'search_base': base_dn,
                        'search_filter': lw_filter,
                        'attributes': retrive_attrs,
                        'paged_size': page_size}

conn.search(**searchParameters)

Error:
Traceback (most recent call last):
  File "./ldap_export.py", line 105, in <module>
    for entry in entries:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ldap3/extend/standard/PagedSearch.py", line 64, in paged_search_generator
    None if cookie is True else cookie)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ldap3/core/connection.py", line 762, in search
    raise LDAPAttributeError('invalid attribute type ' + attribute_name_to_check)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type -

Version: 
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
ldap3      2.5

**Comment by VikramNS** [comment]
@cannatag what answer you are looking for ?

**Comment by cannatag** [comment]
Sorry, the message was lost. I asked to change the -  to + that means “include operational attributes”. The minus sign has no meaning in ldap.

**Comment by VikramNS** [comment]
we have use case for *, + and -, - fetches secure attribute

FYI: it was working in python2 and ldap, during porting to python3 and ldap3 I faced this issue

**Comment by VikramNS** [comment]
I am using https://github.com/vmware/lightwave

**Comment by VikramNS** [comment]
Hi Goivaani, let me know if you need any more information

**Comment by VikramNS** [comment]
Hi, wanted to see if you have gone through the lightwave project

**Comment by cannatag** [comment]
Sorry for the late answer. You can simply add the '-' value to the list of attributes not checked by the ldap3 library:
```
from ldap3 import set_config_parameter, get_config_parameter

set_config_parameter('ATTRIBUTES_EXCLUDED_FROM_CHECK', get_config_parameter('ATTRIBUTES_EXCLUDED_FROM_CHECK') + ['-'])
```
With this configuration you can query the '-' attribute without any additional check.
