### ISSUE TITLE
Schema attribute case insensitive

### ISSUE THREAD

**Issue by ipsec** [cannatag/ldap3#559]
Hi,

How can I get if attribute is case insensitive?

The raw objectDef of "cn" attribute return:
'( 2.5.4.3 NAME ( \\'cn\\' \\'commonName\\' ) SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{64} X-NDS_NAME \\'CN\\' X-NDS_LOWER_BOUND \\'1\\' X-NDS_UPPER_BOUND \\'64\\' X-NDS_NONREMOVABLE \\'1\\' )'

The syntax 1.3.6.1.4.1.1466.115.121.1.15 is "Directory String".

How check if is case sensitive or insensitive?

Thanks.

**Comment by cannatag** [comment]
Hi, in case of eDirectory this is something that is described externally to the ldap schema
```

SYN_CI_STRING | Directory String | 1.3.6.1.4.1.1466.115.121.1.3  1.3.6.1.4.1.1466.115.121.1.11 1.3.6.1.4.1.1466.115.121.1.15  1.3.6.1.4.1.1466.115.121.1.16 1.3.6.1.4.1.1466.115.121.1.17  1.3.6.1.4.1.1466.115.121.1.54 1.3.6.1.4.1.1466.115.121.1.57  1.3.6.1.4.1.1466.115.121.1.30 1.3.6.1.4.1.1466.115.121.1.31  1.3.6.1.4.1.1466.115.121.1.32 1.3.6.1.4.1.1466.115.121.1.33  1.3.6.1.4.1.1466.115.121.1.34 1.3.6.1.4.1.1466.115.121.1.35  1.3.6.1.4.1.1466.115.121.1.37 1.3.6.1.4.1.1466.115.121.1.38  1.3.6.1.4.1.1466.115.121.1.39 | 7.xx
```
all this syntaxes are case insensitive in eDirectory. You can have a look at 

https://www.novell.com/documentation/developer/ldapover/ldap_enu/data/a3xfo7x.html
