### ISSUE TITLE
LDAP3

### ISSUE THREAD

**Issue by bobgho** [cannatag/ldap3#561]
Hi Giovanni,

I am having issues with ldap3 as follows:
1. unable to connect to the domain when I use: conn = Connection(server, 'uid=makmark,cn=users,cn=accounts,dc=mydomain,dc=domainname,
˓→dc=com', 'somepassword', auto_bind=True), I get invalid credentials error. I changed the "uid" to sAMAccountName I still got the same error. However, when I use this: conn = Connection(server, user="Domain\\User", password="password") I have no issues.

2. In the docs, you showed how to move, delete, add user to AD, would you be able to provide a link where I can have a reference to what attributes to use to add or remove a user to a group? Does ou or OU refer to group or Organisation Unit? I am new to Active Directory and has basic knowledge on it. I hope that my questions do not sound too silly.

Due to security reasons I am unable to provide you the logs, however, the server that I connect to supports LDAP 2, 3

Any help would be appreciated in pointing me to the right way to perform tasks in updating and modifying the AD.

Thanks in advance.

Bob

**Comment by bobgho** [comment]
In addtion, here is the error message:
Traceback (most recent call last):
  File "C:/Python36/ldapped.py", line 3, in <module>
    conn = Connection(server, 'uid=myusername,cn=users,cn=accounts,dc=dcm,dc=korp,dc=ads', 'password', auto_bind=True)
  File "C:\Python36\lib\site-packages\ldap3\core\connection.py", line 321, in __init__
    self.do_auto_bind()
  File "C:\Python36\lib\site-packages\ldap3\core\connection.py", line 336, in do_auto_bind
    self.open(read_server_info=False)
  File "C:\Python36\lib\site-packages\ldap3\strategy\sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "C:\Python36\lib\site-packages\ldap3\strategy\base.py", line 153, in open
    self.connection.do_auto_bind()
  File "C:\Python36\lib\site-packages\ldap3\core\connection.py", line 349, in do_auto_bind
    raise LDAPBindError(self.last_error)
ldap3.core.exceptions.LDAPBindError: automatic bind not successful - invalidCredentials

**Comment by cannatag** [comment]
Invalid credentials means that the user does not exist or that the password is wrong. You should check the distinguished name for the user. You should be able to access using the domain\name or name@domain syntax.

I’m sorry but I can’t help you with active directory because I don’t use it in my activities.

**Comment by bobgho** [comment]
Thank you for your respond. 
I will look into it.
