### ISSUE TITLE
Search for user existence without OU specified.?

### ISSUE THREAD

**Issue by Edlopushansky** [cannatag/ldap3#563]
Hello Giovanni, 
Thank you for your help with my previous problem.
I have encountered one more issue.

I 'm trying to search for random generated user in entire AD domain without specifying OU or group .  I get a True from search()  even though there is no user exists with that name. 

code snippet: 

```
 try:
            # checking is user already exists in AD, if not creates a user with attributes
            if not self.c.search('DC=company,DC=com, '(&(objectClass=User)(sAMAccountName={}))'.format(user_login),attributes=ALL_ATTRIBUTES):
```

This script works if I do provide 'OU =Users,DC=company,DC=com'

---------------------------------------------------------------------------------------------------------

--- Also one more thing: 
I need to create an user with userAccountControl: ['66048'] ( enabled , password doesn't expire) 

```
self.c.add(dn, attributes={
                            'objectClass': 'User',
                            'userPassword': '1234',
                            'userAccountControl': ['66048'],
                            'sn': lname,
                            'description': 'Auto created with LDAP3',
                            'displayName': display_name,
                            'givenName': fname,
                            'mail': email,
                            'sAMAccountName': user_login,
                            'userPrincipalName': '%s.%s@%s' % (fname.lower(), lname.lower(), self.domain)
                            })
```
User is not created.

Please , can you point out what is wrong ?

**Comment by cannatag** [comment]
What errors do you get? I don’t use AD so I’m not sure if I can help you.

**Comment by Edlopushansky** [comment]
It doesn't give me any error, it just goes further on. That search method returns True ,but should return False since user doesn't exist.

**Comment by cannatag** [comment]
If the search returns True try to print the c.search.response attribute. It should contain the response returned from the search, maybe there are some referrals that you want to exclude.

**Comment by Edlopushansky** [comment]
when I use CN=USERS,DC=TEST-ACME,DC=COM  I do not get any response. It' an empty list.

**Comment by Edlopushansky** [comment]
I eliminated search function and did the same to add function:

`self.c.add('DC=test-acme,DC=com', attributes={
                'objectClass': 'User',
                'userPassword': self.password,
                'userAccountControl': ['66080'],
                'sn': lname,
                'description': 'Auto created with LDAP3',
                'displayName': display_name,
                'givenName': fname,
                'mail': email,
                'sAMAccountName': user_login,
                'userPrincipalName': '@'.join(['.'.join([fname.lower(), lname.lower()]), domain])
            })`

And now it throws me an error: 

('Exception', LDAPSocketOpenError('invalid server address',)).
So search function doesn't check for the server address?

**Comment by cannatag** [comment]
This means that the server is not reachable. Are you sure that the bind is successful? Check your server name.

**Comment by Edlopushansky** [comment]
Unfortunately I'm sure , because as soon as I change add OU to dn : OU=Users,Dc=company,DC=com everything works fine.

**Comment by Edlopushansky** [comment]
So actually , I figured it out. When you use add function you do need to specify whole DN . 
when you search providing DC=COMPANY,DC=COM will suffice.

**Comment by cannatag** [comment]
You’re right. When searching  you can provide the “scope” base (single object), level (single container), or subtree (the whole tree, starting at the specified base. When modifying you must specify the object you want to change, so it must be the full dn.
