### ISSUE TITLE
[2.5.1] Dependency for pyasn1 are to old

### ISSUE THREAD

**Issue by tuxmaster** [cannatag/ldap3#567]
Using 0.1.8 which are noted at the test section as an minimum version will fail with:

>   File "./import_TB", line 3, in <module>
>     from ldap3 import Server, Connection, ALL
>   File "/usr/lib/python3.4/site-packages/ldap3/__init__.py", line 138, in <module>
>     from .core.connection import Connection
>   File "/usr/lib/python3.4/site-packages/ldap3/core/connection.py", line 37, in <module>
>     from ..extend import ExtendedOperationsRoot
>   File "/usr/lib/python3.4/site-packages/ldap3/extend/__init__.py", line 45, in <module>
>     from .standard.whoAmI import WhoAmI
>   File "/usr/lib/python3.4/site-packages/ldap3/extend/standard/whoAmI.py", line 27, in <module>
>     from pyasn1.type.univ import NoValue

on the sample code:
`from ldap3 import Server, Connection, ALL`

Using 0.4.4 works fine. I don't know which is the working minimal version.

**Comment by tmarlok88** [comment]
I had the same issue.
The first occurence of NoValue was in this commit: https://github.com/etingof/pyasn1/commit/f9ffeac602b042fc98fb3ef7accc0f97350ed3af
The first version containing this is: 2.1
(Tried with the mentioned version and looks ok)

**Comment by cannatag** [comment]
fixed in ldap3 v2.5.2
