### ISSUE TITLE
LDAP search for wellKnownObjects fails

### ISSUE THREAD

**Issue by dmulder** [cannatag/ldap3#583]
`
import ldap3
  
realm = 'froggy.suse.de'
realm_dn = ','.join(['DC=%s' % part for part in realm.lower().split('.')])

l = ldap3.Connection('WIN-DW0OHW3XQB9.froggy.suse.de', user='FROGGY\\Administrator', password='PASSWORD', authentication=ldap3.NTLM, auto_bind=True)

wkguiduc = 'A9D1CA15768811D1ADED00C04FD8D5CD' # Users container
ret = l.search('<WKGUID=%s,%s>' % (wkguiduc, realm_dn), '(objectClass=container)', attributes=['distinguishedName'])
`
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    ret = l.search('<WKGUID=%s,%s>' % (wkguiduc, realm_dn), '(objectClass=container)', attributes=['distinguishedName'])
  File "/usr/lib/python2.7/site-packages/ldap3/core/connection.py", line 725, in search
    search_base = safe_dn(search_base)
  File "/usr/lib/python2.7/site-packages/ldap3/utils/dn.py", line 323, in safe_dn
    for component in parse_dn(dn, escape=True):
  File "/usr/lib/python2.7/site-packages/ldap3/utils/dn.py", line 289, in parse_dn
    if not _validate_attribute_type(attribute_type):
  File "/usr/lib/python2.7/site-packages/ldap3/utils/dn.py", line 163, in _validate_attribute_type
    raise LDAPInvalidDnError('character \'' + c + '\' not allowed in attribute type')
ldap3.core.exceptions.LDAPInvalidDnError: character '<' not allowed in attribute type

This is a MS-ism: https://docs.microsoft.com/en-us/windows/desktop/ad/binding-to-well-known-objects-using-wkguid
Maybe this should be available in extend.microsoft?

**Comment by dmulder** [comment]
There is an alternate way to search for these, which works, fyi:
l.search('DC=froggy,DC=suse,DC=de', '(objectClass=domain)', search_scope='BASE', attributes=['wellKnownObjects'])

**Comment by cannatag** [comment]
not sure if add this to the extend.microsoft or ease the checking of characters in attribute name. Will work on this in the next release of ldap3

**Comment by cannatag** [comment]
Hi David, sorry for being so late! Can you try the code in dev? It should works now.

**Comment by cannatag** [comment]
released in v2.6.1
