### ISSUE TITLE
Changelog says ldap3 version 2.5.1 is not released

### ISSUE THREAD

**Issue by Adam-Origamiiris** [cannatag/ldap3#585]
According to https://ldap3.readthedocs.io/changelog.html 
ldap3 2.5.1 is not released, but my ldap3 version is 2.5.1

```
pip show ldap3
Name: ldap3
Version: 2.5.1
Summary: A strictly RFC 4510 conforming LDAP V3 pure Python client library
Home-page: https://github.com/cannatag/ldap3
```

**Comment by cannatag** [comment]
You’re right! I forgot to update the date. Will fix it soon.

Thanks,
Giovanni
