### ISSUE TITLE
Errors while using persistent_search in rfc2849.py

### ISSUE THREAD

**Issue by ldesplat** [cannatag/ldap3#587]
I am seeing two errors while streaming the results of persistent_search:

```python
    server = Server(url, use_ssl=True, get_info=ALL, tls=tls_configuration)
    conn = Connection(server, user=user, password=password, auto_bind=True, client_strategy=ASYNC_STREAM)
    conn.stream = open('myfile.log', 'w+')
    p = conn.extend.standard.persistent_search(
        search_base='OU=Groups,DC=company,DC=com',
        search_filter='(objectclass=group)'.
        search_scope= SUBTREE,
        attributes=[
            'distinguishedName',
            'cn',
            'objectClass',
            'description',
            'member',
            'managedBy'
        ]
    )
```

The following two errors happen:
1.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "ldap3\strategy\asynchronous.py", line 128, in run
    self.connection.strategy.accumulate_stream(message_id, dict_response)
  File "ldap3\strategy\asyncStream.py", line 81, in accumulate_stream
    ldif_lines = persistent_search_response_to_ldif(change)
  File "ldap3\protocol\rfc2849.py", line 281, in persistent_search_response_to_ldif
    ldif_lines += operation_to_ldif('searchResponse', [change])
  File "ldap3\protocol\rfc2849.py", line 209, in operation_to_ldif
    lines = search_response_to_ldif(entries, all_base64, sort_order)
  File "ldap3\protocol\rfc2849.py", line 129, in search_response_to_ldif
    lines.extend(add_attributes(entry['raw_attributes'], all_base64))
  File "ldap3\protocol\rfc2849.py", line 112, in add_attributes
    for val in attributes[attr]:
TypeError: 'NoneType' object is not iterable
```

with a workaround by doing like so:
```
    # remaining attributes
    for attr in attributes:
        if attr != oc_attr:
            if attributes[attr]:
                for val in attributes[attr]:
                    lines.append(_convert_to_ldif(attr, val, all_base64))
```

This happens with a group with at least 1500 members. If I change the query above by removing the `member` attribute then I can get around it as well without any code changes. I don't fully understand what this has to do with the member attribute though. Maybe something else changes when I request the member attribute...

EDIT: 
> I forgot to just debug it and check it out. So, if I print out the attributes, then sure enough `'member': > None` but then it shows `'member;range=0-1499' : [...lots of members]`
> 
> So, not sure if there's similar code somewhere to put together into member or just my workaround is enough.

and then
2.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "\ldap3\strategy\asynchronous.py", line 128, in run
    self.connection.strategy.accumulate_stream(message_id, dict_response)
  File "\ldap3\strategy\asyncStream.py", line 81, in accumulate_stream
    ldif_lines = persistent_search_response_to_ldif(change)
  File "ldap3\protocol\rfc2849.py", line 282, in persistent_search_response_to_ldif
    ldif_lines += operation_to_ldif('searchResponse', [change])
  File "ldap3\protocol\rfc2849.py", line 210, in operation_to_ldif
    lines = search_response_to_ldif(entries, all_base64, sort_order)
  File "ldap3\protocol\rfc2849.py", line 130, in search_response_to_ldif
    lines.extend(add_attributes(entry['raw_attributes'], all_base64))
KeyError: 'raw_attributes'
```

This one is caused due to the following error (entries in search_response_to_ldif): `[{'result': 4, 'description': 'sizeLimitExceeded', 'dn': '', 'message': '', 'referrals': None, 'type': 'searchResDone'}]`

Sure enough there are over 1k results from this search, so that makes some sense except that how do I get the log of changes if I need to check that many groups? I've also set the `changes_only` option to True, but it still returns the inital state even though it should only tell me what is changing not the existing information?

Thank you for any help!

**Comment by cannatag** [comment]
Hi, Active Directory has a server limit of 1500 members on group membership. The ldap3 library has an auto_range option that is set to True in the Connection object that automatically performs additional searches when the range limit is reached. I'm not sure if this properly works in persistent_search because I cannot test it in my lab. Can you try with auto_range=False when defining the connection?
