### ISSUE TITLE
LDAPSocketOpenError 

### ISSUE THREAD

**Issue by Edlopushansky** [cannatag/ldap3#588]
Hi Giovanni, 
I have LDAPSocketOpenError with 2 out of  6 of my servers.
Can you please point what differences to look for?

**Comment by Edlopushansky** [comment]
more then that. these servers are AWS

**Comment by cannatag** [comment]
Hi, SocketOpenError means that the connection cannot be established. Are you sure you have configured the Server object correctly and that you can reach the port on the servers?

**Comment by Edlopushansky** [comment]
I can connect to all other boxes except AWS. Maybe it's has something with firewall or something else?

**Comment by cannatag** [comment]
Are you able to ping or ssh the awe machine? Are they reachable from their public ip?

**Comment by Edlopushansky** [comment]
Yes, I can reach them through Microsoft Remote Desktop. I was thinking maybe ports 389 and 636 are not open?

**Comment by cannatag** [comment]
It’s almost sure that ports are not open. You have to check the AWS console.

**Comment by Edlopushansky** [comment]
OK . Ill check

**Comment by Edlopushansky** [comment]
Nope , We checked , all ports are open .....  What else, if you know,  can cause this damn problem....?

**Comment by cannatag** [comment]
Hi, did you fixed this problem?

**Comment by Edlopushansky** [comment]
Unfortunately not. We still cannot figure it out. May be it has something with some kind of aws permissions ?
