### ISSUE TITLE
ldap3

### ISSUE THREAD

**Issue by since19861019** [cannatag/ldap3#59]
In Python 3.x on OpenBSD 5.7, socket.AI_V4MAPPED is not defined.  I am afraid AI_V4MAPPED is not supported by the OS.
As a result, core/server.address_info()'s reference to the constant causes an error.
I would like you to remove the flag unless it it is absolutely needed,

**Comment by cannatag** [comment]
Hi, this is already been fixed in 0.9.7.11. Which version are you using? Are you sure you have the latest 0.9.8.4?

**Comment by since19861019** [comment]
Yes, I am using 0.9.8.4.
I have confirmed core/Server.address_info() calls socket.getaddrinfo() with socket.AI_V4MAPPED flag.

**Comment by cannatag** [comment]
You're right. I've checked it againsta OpenBSD 5.7. It returns a different exception than FreeBSD. Please change line 204 in /usr/local/lib/python3.4/site-packages/ldap3/core/server.py
from:
except socket.gaierror:

to
except (socket.gaierror, AttributeError):

and let me know if this works for you. In my lab it's working now.

Thanks.
Giovanni

**Comment by since19861019** [comment]
I have confirmed that it works on OpenBSD 5.7.

**Comment by cannatag** [comment]
Thanks, I will include the fix in the next release of ldap3.

Bye,
Giovanni 

----- Messaggio originale -----
Da: "since19861019" <notifications@github.com>
Inviato: ‎04/‎06/‎2015 10:20
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Cc: "Giovanni Cannata" <cannatag@gmail.com>
Oggetto: Re: [ldap3] ldap3 (#59)

I have confirmed that it works on OpenBSD 5.7.

**Comment by cannatag** [comment]
releasing 0.9.8.5. bye
