### ISSUE TITLE
Read CN from DN 

### ISSUE THREAD

**Issue by cinguva** [cannatag/ldap3#593]
Can you tell us what function gives me the CN value from DN
CN=Abbie Giles,OU= Employees,OU=example,OU=Accounts,DC=astro,DC=local

In this case, i would like to retrieve Abbie Giles.

Also, is there any way i can get manager sAMAccountName for a user using ldap3 ?

Any help here is appreciated.

Thanks

**Comment by Edlopushansky** [comment]
Hi
Do you need to find CN in AD or just get user name from DN string? 
In the first case you need to use a search function with specified filter such as :
self.c.search(dn, '(&(objectClass=User)(|(sAMAccountName={})(cn={})))'.format(user_login, user_login),
                                 attributes=ALL_ATTRIBUTES)
and then retrieve cn   user_cn =  self.c.entries[0]['cn']

For the second case just dn.split(",")[0][3:] string and get CN from it

For a sAMAccountName use the same search ,but to retrieve it use:
user_sam =  self.c.entries[0]['sAMAccountName']

I hope that I got your questions right.

**Comment by cinguva** [comment]
Hey,
I actually wanted the managers' sAMAccountName

like 
if i search an OU for employees, i need employee sAMAccountName, mail, employee's manager's sAMAccountName

c.search(search_base='ou=Accounts,dc=example,dc=local',search_filter='(&(objectClass=User)(employeeType=Employee*)(extensionAttribute8=Active*))',search_scope=SUBTREE,attributes=['sAMAccountName','mail','sn','manager','pwdLastSet'])

right now for user's manager attribute i am getting DN

**Comment by Edlopushansky** [comment]
Probably this is a format set in AD. Did you tried to pull all attributes  'attributes=ALL_ATTRIBUTES' to see what you get from AD?
Or probably you need to get one more step to retrieve manager sAMAccountName by searching for its DN and pull sAMAccountName from entries
