### ISSUE TITLE
How to install/deploy LDAP3 2.5.1 without easy_install?

### ISSUE THREAD

**Issue by ohaya** [cannatag/ldap3#596]
Hi

We noticed that the distributions for ldap3 2.5.1 (for Python 2.6) are only available as .egg files.  Unfortunately, we are not able to assume that easy_install is available, so can someone tell me how we can install ldap3 2.5.1, either from the .egg file or from the tar.gz file (on Redhat)?

Thanks,
Jim

**Comment by cannatag** [comment]
Hi, ldap3 is pure python code, so you can install from the source. Its only dependence is the pyasn1 library and you should use the latest version on pypi.

So it safe to use it with the latest pyasn1 version. 

Bye,
Giovanni

**Comment by ohaya** [comment]
Hi Giovanni,

Even when I edit the requirements.txt and requires.txt to the pyasn1 version that is on our system (0.4.2), when I run the "python setup.py install" it is giving me msgs about not finding the dependency, .e.g.:

`zip_safe flag not set; analyzing archive contents...
creating 'dist/ldap3-2.5.1-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ldap3-2.5.1-py2.6.egg
removing '/usr/lib/python2.6/site-packages/ldap3-2.5.1-py2.6.egg' (and everything under it)
creating /usr/lib/python2.6/site-packages/ldap3-2.5.1-py2.6.egg
Extracting ldap3-2.5.1-py2.6.egg to /usr/lib/python2.6/site-packages
ldap3 2.5.1 is already the active version in easy-install.pth

Installed /usr/lib/python2.6/site-packages/ldap3-2.5.1-py2.6.egg
Processing dependencies for ldap3==2.5.1
Searching for pyasn1>=0.4.2
Reading http://pypi.python.org/simple/pyasn1/
Couldn't find index page for 'pyasn1' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for pyasn1>=0.4.2
error: Could not find suitable distribution for Requirement.parse('pyasn1>=0.4.2')
`
Do you know why that is the case?

FYI, the reason I am asking is that I am trying to document how to do the ldap3 2.5.1 installation for our people, and they do not want to see warnings like that, so I will need to tell them how to edit the installation files after they untar the tar.gz so they can get a "clean" installation.  

I know this sound strange, but it is the way that they are going to require.

Thanks,
Jim

P.S.  We (several of us who write the Python code) love ldap3 vs. the original ldap 👍 !

**Comment by cannatag** [comment]
Where are you getting the ldap3 source from ?

Have you tried cloning the master from github and running setup from there?

**Comment by ohaya** [comment]
I got the tar.gz from here:

https://pypi.org/project/ldap3/#files

FYI, cannot run the setup from an remote site (no connections), so I can only download the tar.gz and then untar it, etc.

I will try download from your github and see if that makes a difference?

Thanks,
Jim

**Comment by ohaya** [comment]
I tried downloading the ZIP from the github page but when I unzip it the contents are structured somewhat differently compared to the tar.gz file?

So can I install the 2.5.1 ldap3 if I just do "python setup.py install" using the setup.py that is in the root of the unzippped ZIP file (that is the directory with tut1.py-tut4.py)?

**Comment by ohaya** [comment]
I just tried:

- download ZIP from your github page
- Unzip it
- Change dir to ldap3-master
- Run: python setup.py install

and it installed ldap3, but at the end of the output it had:

`Processing ldap3-2.5.1-py2.6.egg
removing '/usr/lib/python2.6/site-packages/ldap3-2.5.1-py2.6.egg' (and everything under it)
creating /usr/lib/python2.6/site-packages/ldap3-2.5.1-py2.6.egg
Extracting ldap3-2.5.1-py2.6.egg to /usr/lib/python2.6/site-packages
ldap3 2.5.1 is already the active version in easy-install.pth

Installed /usr/lib/python2.6/site-packages/ldap3-2.5.1-py2.6.egg
Processing dependencies for ldap3==2.5.1
Searching for pyasn1>=0.1.8
Reading http://pypi.python.org/simple/pyasn1/
Couldn't find index page for 'pyasn1' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for pyasn1>=0.1.8
error: Could not find suitable distribution for Requirement.parse('pyasn1>=0.1.8')
`

So it was the same problem as using the tar.gz file.

**Comment by cannatag** [comment]
Which version of setuptools is installed on your system? I’ve tried on a 2.6 system and had no problem to run python2.6 setup.py install.

**Comment by ohaya** [comment]
Hi,

How do I check that (the setuptools version)?

Jim

**Comment by ohaya** [comment]
Also, can I ask:  Why was ldap3 available as .egg files before but not for ldap3 version 2.5.1?  Just curious because that (using pip install and the .egg file) previously.

**Comment by cannatag** [comment]
What is the content of your libs/site-packages directory? It should contain the additional libraries you have installed with they relevant versions. You should find the path with sys.path.

**Comment by cannatag** [comment]
Because wheel and tar.gz should be enough for all versions. Did you mean that you’re able to install the previous ldap3 version?

**Comment by ohaya** [comment]
Re. "Because wheel and tar.gz should be enough for all versions. Did you mean that you’re able to install the previous ldap3 version?" - Yes, that is what I was trying to convey to you (via my question).  

We were able to install the python-ldap3 (v 2.5.0) previously, using the .whl file and "pip install xxxx.whl", but apparently "pip install" doesn't work with .egg files.

**Comment by ohaya** [comment]
Re. "What is the content of your libs/site-packages directory? It should contain the additional libraries you have installed with they relevant versions. You should find the path with sys.path.":

We have a small file, "setuptools-0.6c11-py2.6.egg-info" and a directory, "setuptools" under the site-packages directory.
The small file "setuptools-0.6c11-py2.6.egg-info" has:
`Metadata-Version: 1.0
Name: setuptools
Version: 0.6c11
Summary: xxxx
Home-page: xxx
Author: xxx
Author-email: xxx
License: xxx
Description: xxx
`
The "setuptools" directory has the following contents:

`-rw-r--r--.  1 root root  5927 Jul 14  2010 archive_util.py
-rw-r--r--.  2 root root  5767 Jul 14  2010 archive_util.pyc
-rw-r--r--.  2 root root  5767 Jul 14  2010 archive_util.pyo
drwxr-xr-x.  2 root root  4096 Jul 14  2015 command
-rw-r--r--.  1 root root  6209 Jul 14  2010 depends.py
-rw-r--r--.  2 root root  6815 Jul 14  2010 depends.pyc
-rw-r--r--.  2 root root  6815 Jul 14  2010 depends.pyo
-rw-r--r--.  1 root root 30266 Jul 14  2010 dist.py
-rw-r--r--.  1 root root 30544 Jul 14  2010 dist.pyc
-rw-r--r--.  1 root root 30482 Jul 14  2010 dist.pyo
-rw-r--r--.  1 root root  1100 Jul 14  2010 extension.py
-rw-r--r--.  2 root root  1612 Jul 14  2010 extension.pyc
-rw-r--r--.  2 root root  1612 Jul 14  2010 extension.pyo
-rw-r--r--.  1 root root  3434 Jul 14  2010 __init__.py
-rw-r--r--.  2 root root  3876 Jul 14  2010 __init__.pyc
-rw-r--r--.  2 root root  3876 Jul 14  2010 __init__.pyo
-rw-r--r--.  1 root root 29140 Jul 14  2010 package_index.py
-rw-r--r--.  2 root root 27883 Jul 14  2010 package_index.pyc
-rw-r--r--.  2 root root 27883 Jul 14  2010 package_index.pyo
-rw-r--r--.  1 root root  8186 Jul 14  2010 sandbox.py
-rw-r--r--.  2 root root 10929 Jul 14  2010 sandbox.pyc
-rw-r--r--.  2 root root 10929 Jul 14  2010 sandbox.pyo
`

**Comment by ohaya** [comment]
Hi,

We are having one additional problem with the installation.  

We have been installing the ldap3 2.5.1 on a machine that has a user, 'orcladmin'.

When we instatll the ldap3, we:

- su - (become root)
- umask 022
- tar xvf ldap3 tar.gz file
- cd ldap3 dir
- Run "python setup.py install"

After that, when we run "pip freeze | grep ldap3" or "pip show ldap3" we can see the ldap3 listed and the version (2.5.1).

However, if we su to the 'orcladmin' user and then run pip freeze or pip show, it is not showing the ldap3 package at all!

However, it DOES appear that the ldap3 package is "working" (we ran a test Python app that uses the ldap3 package and that test Python app worked).  

It is just showing the package and package version using pip that is not working.

I have another machine (our "sandbox" machine) that I think I was originally using to test the installation, and on that sandbox machine, when we run pip freeze or pip show it DOES show the ldap3 and version 2.5.1.

I was trying to figure out why, checking perms, etc., and those look ok.

However, I just found that on the sandbox machine, where the pip freeze/show works, there are TWO directories:

- ldap3-2.5.1-py2.6.egg
- ldap3-2.5.dist-info

whereas on the machine where the pip freeze/show is not showing the ldap3 package, there is only this one dir:

- ldap3-2.5.1-py2.6.egg

NOTE that if I (literally) copy the ldap3-2.5.dist-info dir from the sandbox machine to the site-packages dir on the non-sandbox machine, THEN the pip freeze/show DOES SHOW the ldap3 package and the version.


Is there a way to create the dist.info directory from either the tar.gz or the ZIP of the project?

Thanks,
Jim

**Comment by cannatag** [comment]
Hi,
I was able to install "offline" on a clean python 2.6 machine. I followed the following steps:
1. Download setuptools 36.8.0 from https://files.pythonhosted.org/packages/b8/04/be569e393006fa9a2c10ef72ea33133c2902baa115dd1d4279dae55c3b3b/setuptools-36.8.0.zip (latest working on python 2.6) and unzip it
2. cd to the setuptools-36.8.0
3. Install setuptools with python setup.py install
4. Download pyasn1 0.4.3 from https://files.pythonhosted.org/packages/10/46/059775dc8e50f722d205452bced4b3cc965d27e8c3389156acd3b1123ae3/pyasn1-0.4.4.tar.gz and untar it
5. cd to pyasn1-0.4.4 
6. install pyasn1 with python setup.py install
7 download ldap3 2.51 from https://files.pythonhosted.org/packages/86/ff/439de3a80632ba187511dbdcac43c9d8e1649271f5af5e997d9ed1410291/ldap3-2.5.1.tar.gz
8 cd to ldap3-2.5.1
9 https://files.pythonhosted.org/packages/86/ff/439de3a80632ba187511dbdcac43c9d8e1649271f5af5e997d9ed1410291/ldap3-2.5.1.tar.gz

optionally you can download and install pip 9.0.3 from https://files.pythonhosted.org/packages/c4/44/e6b8056b6c8f2bfd1445cc9990f478930d8e3459e9dbf5b8e2d2922d64d3/pip-9.0.3.tar.gz and install it with the same procedure.

Before starting this procedure I suggest to remove any reference to ldap3, pyasn1 and setuptools in your lib/site-packages folder. Also searching the whole filesystem for ldap3 or pyasn1 should help you to find additional installed packages.

Let me know if this helps you.

Bye,
Giovanni
