### ISSUE TITLE
REUSABLE strategy intermittently fails on an AWS instance behind a NAT gateway

### ISSUE THREAD

**Issue by dnmvisser** [cannatag/ldap3#597]
Hi

I'm deploying some system on an EC2 instance in AWS, which uses ldap3 to do LDAP queries to a remote host on the internet, using ldaps. The strategy is REUSABLE. This worked fine when the host was directly connected to the internet. However, as part of making things more robust, we're now moving towards a set-up whereby we have multiple EC2 instances in a private network behind an haproxy instance. They access the internet through an AWS "NAT Gateway" (https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html).
In this scenario, things intermittently start to fail with an exception `no response from worker threads in Reusable connection`.
I wonder if other people have experienced this, and if so, what they had done to fix/work around.
Thanks

Dick

**Comment by cannatag** [comment]
I’m sorry, I can’t help with aws cloud. I suggest you to change strategy to something simpler so you can check communication problems more easily.
