### ISSUE TITLE
Problem with authentication failure

### ISSUE THREAD

**Issue by leavest** [cannatag/ldap3#599]
A ldap account with a blank attribute of displayName authenticate failed.

error message: LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1 - bindResponse - None

After I set something to displayName, authenticate success.

But in other package like cas can authenticate success when a ldap account has a blank attribute of displayName

**Comment by leavest** [comment]
cas 
https://github.com/apereo/cas

**Comment by cannatag** [comment]
Hi, what kind of authentication are you performing? In simple authentication you must pass the object dn as username. If you want you can try the ntlm authentication with authentication=‘NTLM’ in the connection object.
