### ISSUE TITLE
get user  PasswordExpirationDate ?

### ISSUE THREAD

**Issue by santosshen** [cannatag/ldap3#601]
Hi cannatag
get user  PasswordExpirationDate ?

obj_person = ObjectDef(['person', 'posixAccount'], conn)
print(obj_person)
```
OBJ : person, posixAccount
AUX : <None>
OID: person (Structural) 2.5.6.6, top (Abstract) 2.5.6.0, posixAccount (Auxiliary) 1.3.6.1.1.1.2.0, top (Abstract) 2.5.6.0
MUST: instanceType, nTSecurityDescriptor, objectCategory, objectClass
MAY : USNIntersite, adminDescription, adminDisplayName, allowedAttributes, allowedAttributesEffective, allowedChildClasses,
```
obj_person = ObjectDef(['person', 'posixAccount', 'krbprincipalaux'], conn)
print(obj_person)
```
 File "C:\Program Files\Python35\lib\site-packages\ldap3\utils\ciDict.py", line 68, in __getitem__
    return self._store[self._case_insensitive_keymap[self._ci_key(key)]]
KeyError: 'krbprincipalaux'
```
https://ldap3.readthedocs.io/tutorial_abstraction_reader.html

**Comment by SamGenTLEManKaka** [comment]
I also encountered the same problem, which has bothered me for a long time, pay attention to this problem.

**Comment by santosshen** [comment]
https://docs.microsoft.com/en-us/windows/desktop/adschema/a-msds-userpasswordexpirytimecomputed
"msDS-UserPasswordExpiryTimeComputed": 9223372036854775807
