### ISSUE TITLE
please let us specify the krb5 cred store

### ISSUE THREAD

**Issue by clhedrick** [cannatag/ldap3#602]
If the cred store extension is present, it's possible to specify the specific credential cache to be used for a Kerberos authentication. For some services we want to make ldap requests on behalf of specific users or hosts. This could be supported trivially if you'd add an argument 'store' to Connection. It would simply be stored in the connection map. Kerberos.py when it does gssapi.Credentials would pass the store value if any.

Usage would be user='person@domain', store={'ccache': 'FILE:/tmp/krb5cc_xxx'}

user='service/host@DOMAIN' works just as well.

I've tested it myself, and verified that this works.

**Comment by clhedrick** [comment]
Also, store={'cient_keytab': '/etc/krb5.keytab'}. You may want to specify ccache also. Otherwise the credentials are put in your default ccache collection.

**Comment by clhedrick** [comment]
Unfortunately I don't see any easy way to do a kerberized connection with password. My code is  based on Freeipa's ldap and kinit code. Their kinit code uses the approach here for key tables, but calls kinit in a process to deal with passwords. Trying to do a full password authentication complete with one-time passwords would bury me in GSSAPI further than I want to go. Ccache and keytab are easy because of the new store extension to GSSAPI, which fortunately your low-level code already supports.

**Comment by cannatag** [comment]
This is awesome! I will include it in the documentation! I don’t actually use Kerberos so I cannot test your solution.

Thanks!
Giovanni

**Comment by clhedrick** [comment]
I've got some more info, so wait until later today.

**Comment by cannatag** [comment]
fixed in ldap3 v2.5.2
