### ISSUE TITLE
Can't seach Chinese

### ISSUE THREAD

**Issue by X-Mars** [cannatag/ldap3#613]
Dear Giovanni Cannata:
      Thank you for releasing ldap3.
      I get some error when i search with Chinese, like this

#### search_base
```
 (&(uid=北京未来有限公司)(objectclass=*))

return 
```

#### return
```
{

 "entries": []

}
```

I can't get anything.
Longing for you reply.

Yours Mars

**Comment by X-Mars** [comment]
sorry, i giving a bad search_base. 
close.

**Comment by cannatag** [comment]
No problem!

Bye
