### ISSUE TITLE
Parallel concurrent.futures search throwing random invalid attribute type exceptions

### ISSUE THREAD

**Issue by hodgigre** [cannatag/ldap3#614]
Hello.  First, thank you very much for your work with ldap3.  Despite me being a total hack, your pure Python library is looking like it will provide a much simpler and better performing solution to my queries than the various attempts I have made with OpenLDAP ldapsearch, alternatives and batch/shell scripts.

The website/documentation is first rate too!  Thank you.

My issue is with the following parallel concurrent.futures attempt.  With a single worker thread (or even a basic loop without futures) the search queries below return consistent results with no exceptions.

However, as soon as I move to 2 or more worker threads I end up with random exceptions like below.  With 3 threads, 11 occurrences in 200 searches.

I'm not sure if I have something scoped wrong perhaps - or if there is something internal awry.  The attribute associated with exception varies by exception and again, run in serial, the same search produces results without exception.

'1efdb2469f62975b138dc5a7867a41f0\n' generated an exception: invalid attribute type imString55

Thanks for any help.

```
import concurrent.futures
from ldap3 import Server, Connection

n=0
SINS=[]
f = open('./sins200', 'r')
SINS = f.readlines()
f.close()
print(len(SINS))


def ldap_search(SIN, timeout):
    
        server = Server('ldap.server.com', port =19289, use_ssl=False)
        conn = Connection(server, 'uid=ldapreporting,ou=people,ou=bus,ou=im,ou=ca,o=com', 'password',
                      check_names=True, read_only=True, raise_exceptions=True, return_empty_attributes=True, auto_bind=True)
        
        conn.search('ou=people,ou=bus,ou=im,ou=ca,o=com', '(imString62=' + SIN + ')', 
                    attributes=['imEnabledState','imString52','imString67','employeeNumber','givenName','initials','sn',
                                'imEmployeeStatus','employeeType','imString59','imString54','imCostCenter','imString53',
                                'imString50','street','l','st','postalCode','imString55','imManagerEmployeeNumber','imString56',
                                'imString62','imString61','imString66','imString57','imString58','imString68','imString64','imString71',
                                'imString72','imString51','imString69','departmentNumber','imLoginID','mail'])
        
        return conn.entries
 
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:

    future_to_ldap = {executor.submit(ldap_search, SIN, 30): SIN for SIN in SINS}
    for future in concurrent.futures.as_completed(future_to_ldap):
            
            searchresults = future_to_ldap[future]
            try:
                data = future.result()
            except Exception as exc:
                print('%r generated an exception: %s' % (searchresults, exc))
            else:    
                n=n+1
                #data.stream = open('poutput.ldif', 'w')
                print(n)
                print(data)
```

**Comment by hodgigre** [comment]
What is this two variables Python construct called so I can read about it?
Are both response and result set to a connection response.  I hope that as
my last question - and clearly it's not an LDAP question. :-)

  response, result = conn.get_response(response_id)

**Comment by cannatag** [comment]
That’s a “sequence unpacking”. Have a look at https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences

Basically the function on the right side of the equal sign returns a number of values and they are sequentially assigned to the variable on the left.
