### ISSUE TITLE
KeyError when trying to use paged search

### ISSUE THREAD

**Issue by br0cky** [cannatag/ldap3#615]
I'm writing a program to simply add users to an AD group.

Using ldap3.extend.microsoft.addMembersToGroups doesn't return if someone is already a member so i need to run a search to check first.

At the moment i'm using this method to loop through the group and extract the members email attribute. I then use an if statement to determine if an email already exists.

```
def get_group():
    conn = connection()
    with conn:
        conn.search(search_base='DC=DOMAIN,DC=COM,
        search_filter='(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberof=CN=GROUP NAME,OU=GROUP,DC=DOMAIN,DC=COM))',
        attributes = ['mail'])

    for e in conn.entries:
        ... if statement here
```

This works fine but i presume when the groups grows this will get slower and slower.

My understanding from the docs is to use something like this so entries are added to a list and i can use an if in list (which i think is faster?)

```
total_entries = 0
entry_generator = c.extend.standard.paged_search(search_base = 'o=test',
                                                 search_filter = '(objectClass=inetOrgPerson)',
                                                 search_scope = SUBTREE,
                                                 attributes = ['cn', 'givenName'],
                                                 paged_size = 5,
                                                 generator=True)
for entry in entry_generator:
    total_entries += 1
    print(entry['dn'], entry['attributes'])
print('Total entries retrieved:', total_entries)
```

I've adapted my function but no matter what i try, i get KeyErrors when trying to select attributes.

**Comment by br0cky** [comment]
Hi,

After some research i've adapter my original function to the below:

def get_group():
    conn = connection()
    with conn:
        conn.search(search_base='DC=DOMAIN,DC=COM,
        search_filter='(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberof=CN=GROUP NAME,OU=GROUP,DC=DOMAIN,DC=COM))',
        attributes = ['mail'])
    list = {}
    list = set()
    for e in conn.entries:
        email_list.add(e.mail.value)

    if "blah" in list:
        ...do something

**Comment by cannatag** [comment]
so. this is working right now?

**Comment by br0cky** [comment]
No, using the paged search i still get key errors when trying to select a particular key value. However i'm using my workaround.

**Comment by cannatag** [comment]
Probably the attribute you're trying to read is a multi-valued attribute, so it is returned as a list. Have you tried with ```entry['attributes']['givenname][0]```?

**Comment by cannatag** [comment]
I'm closing this issue. Please reopen if you still have problems.

**Comment by timrcase** [comment]
I'm having this same issue. I'm using the sample code provided in the documentation and getting a `KeyError: 'attributes'` when trying to print the attributes. If it `print(entry)` I can confirm it's returning a dictionary with an `attributes` key.

**Comment by timrcase** [comment]
Adding to this, if I do `print(entry.get('attributes'))` it works fine but `print(entry['attributes'])` throws the KeyError.
