### ISSUE TITLE
OPERATIONAL_ATTRIBUTES

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [cannatag/ldap3#626]
I have a question.
I am trying to change the format of the date that is displayed when i call lastLogoff attribute, but the error is AttributeError: 'Attribute' object has no attribute 'split'
So, my question is , what type of data is Attribute?

**Comment by cannatag** [comment]
Try to use the .value property of the attribute (or values for multi-valued) attributes.

**Comment by BrunoTeixeira1996** [comment]
hmm ok later i will try that.
One more question, is there a way i can see if an account is locked? i cant find that attribute

**Comment by BrunoTeixeira1996** [comment]
Still doesnt work ...
[https://gyazo.com/1ff22dce88edeec572e74f123bd246e4](url)
when i use .value the same value is displayed and when i used .values the print screen value is displayed.

**Comment by BrunoTeixeira1996** [comment]
OK! 
I managed to solve the problem.
i used 
from dateutil.parser import parse
a = conn.entries[0]['lastLogon'].value.strftime('%Y-%m-%d %H:%M:%S')
date = parse(a)
print(date) and thats it 💃 
@cannatag  you can close the issue and you should upload this to LDAP3 documentation
