### ISSUE TITLE
ldap3 - Get the date when a user got added to an Active Directory group

### ISSUE THREAD

**Issue by ramprasadkolla4** [cannatag/ldap3#627]
Hi,
I'm working on a python script which gathers the list of members(user name, user id, email id, date-when-user-got-added) for each of of AD groups supplied via a .txt file.

I'm able to get (using ldap3 module) all the information except "date-when-user-got-added".

Is it possible in python to get this information using ldap3?

**Comment by cannatag** [comment]
Hi, I don’t think that AD stores this information, at least in the active directory database, maybe you can get it from a log or the event viewer of the domain controller.

And for what I know no LDAP server store this information too. It’s something you can probably find in an auditing system or in the log service of the server.


Bye,
Giovanni

**Comment by ramprasadkolla4** [comment]
Hi Giovanni,

Thanks for the information.

I'm closing this issue.
