### ISSUE TITLE
paged_search not following referrals

### ISSUE THREAD

**Issue by kprativa** [cannatag/ldap3#628]
https://github.com/cannatag/ldap3/issues/155
I'm trying to query an Active Directory 2016 on port 389 that returns a list of groups defined by itself as well as references to another Domain Controller. Both DC's have parent-child relationship.
When I use standard.paged_search, it correctly returns all the groups created by itself but doesn't follow the referrals to fetch groups belonging to the other DC.
I'm creating server object as
          [ ldap3.Server(
                host=host,
                port=port,
                use_ssl=use_ssl,
                get_info=ldap3.ALL,
                connect_timeout=3,
                allowed_referral_hosts=[("*", True)]

**Comment by cannatag** [comment]
Hi, what happens if you try a simple search (not paged?). Do you get referrals back in the response?

**Comment by kprativa** [comment]
Yes, I get referrals back in the response.

**Comment by kprativa** [comment]
Hi,
Please let me know if you need any further information. The status shows 'waiting answer from user' flag.

**Comment by cannatag** [comment]
Hi, sorry for the long delay. Can you check the code in dev? It should work now.

Giovanni

**Comment by cannatag** [comment]
released in v2.6.1

**Comment by kprativa** [comment]
Hi Cannatag,
Sorry for the delayed response. My email server was blocking some emails and I didn't notice the update.
I'll test it now and confirm the results.

Thanks agian.
