### ISSUE TITLE
entry_to_json() leaves entries in unicode?

### ISSUE THREAD

**Issue by mtdeguzis** [cannatag/ldap3#629]
Maybe I am missing something here, but when I do `get_config_parameter('DEFAULT_CLIENT_ENCODING')` I see 'utf-8'. 

command after getting entries:
```
result_json = json.loads(openldap_connection.entries[0].entry_to_json()
```

Results
```
print(result_json)
test_crosscheck_adldap (__main__.TestLDAP) ... {u'dn': 'uid=user,ou=people,dc=domain,dc=edu',  
 u'attributes': "{u'cn': [u'LNAME, FNAME.'], u'objectClass': [u'posixAccount', u'inetOrgPerson', u'top',  
 u'organizationalPerson', u'person'], u'loginShell': [u'/bin/bash'], u'uidNumber': [0000], 
  u'gidNumber': [000], u'sn'
...
```

Also tried setting the config to force it, and `auto_encode=True` in the Connection parameters. Having to encode entries to unicode for individual entries is far from optimal. Any idea if I am just misusing the library?

**Comment by cannatag** [comment]
Hi, I don't understand your problem. The ldap protocol works with unicode strings, so you're receiving back the unicode values. The default client encoding means that when you're sending data to the server they are automatically converted from your encoding to utf-8. In your case there will be no conversion, but you don't have to encode entries manually.

**Comment by mtdeguzis** [comment]
I misunderstood, sorry. Please close.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
