### ISSUE TITLE
Modify  nTSecurityDescriptor??

### ISSUE THREAD

**Issue by santosshen** [cannatag/ldap3#631]
Hi cannatag,
    Modify nTSecurityDescriptor ,I hope you provide an example。
‘’‘
def get_attributes():
    with ldap3RESTARTABLE as conn:
        conn.search(search_base=ladp3search_base,search_filter="(&(objectClass=user)(objectCategory=person) (sAMAccountName=scj*))",attributes=['nTSecurityDescriptor'])
        response = conn.response
        result = conn.result
        for i in response:
            print(i.get('dn'))
            print(i.get('attributes'))
    return 1

print(get_attributes())
’‘’
{'nTSecurityDescriptor': b'\x01\x00\x14\x8c\xf8\x18\x00\x00\x14\x19\x00\x00\x14\x00\x00\x00\x8c\x00\x00\x00\x04\x00x\x00\x02\x00\x00\x00\x07Z8\x00 ...

```
![image](https://user-images.githubusercontent.com/25058112/50442470-0e0d0c00-093a-11e9-93b3-4d3d407b5d9c.png)

https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/ldapattack.py
https://msdn.microsoft.com/en-us/library/cc220993.aspx?f=255&MSPPError=-2147217396

**Comment by santosshen** [comment]
https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/ldapattack.py

**Comment by santosshen** [comment]
![image](https://user-images.githubusercontent.com/25058112/50442531-47457c00-093a-11e9-948b-1e10550ff0da.png)

**Comment by santosshen** [comment]
![image](https://user-images.githubusercontent.com/25058112/50442553-59bfb580-093a-11e9-92a5-d3132f143946.png)
![security-tab-in-user-properties-active-directory](https://user-images.githubusercontent.com/25058112/50442557-6217f080-093a-11e9-9540-120e6312aa3c.gif)

**Comment by Nocturem** [comment]
Hey I am not sure if this is plans for an extension to read and write ntSecurity descriptors I know miketeo's pysmb has some code that might be integrated around decoding and encoding the nTSecurityDescriptor.
https://github.com/miketeo/pysmb/blob/master/python3/smb/security_descriptors.py

**Comment by santosshen** [comment]
Hi Nocturem ,
    Thank you for your documentation。I can provide ,but in python2.7 
[https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/ldapattack.py](url)

**Comment by santosshen** [comment]
https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/ldapattack.py
[https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/ldapattack.py](url)

**Comment by santosshen** [comment]
HI,Nocturem
   Thank you for your documentation，I can provide an example ,but python2.7
[https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/ldapattack.py](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/examples/ntlmrelayx/attacks/ldapattack.py)

**Comment by santosshen** [comment]
thanks all,
[https://github.com/SecureAuthCorp/impacket/blob/python36/impacket/examples/ntlmrelayx/attacks/ldapattack.py](https://github.com/SecureAuthCorp/impacket/blob/python36/impacket/examples/ntlmrelayx/attacks/ldapattack.py)
this python36
