### ISSUE TITLE
get Activity directory server ip and site ??

### ISSUE THREAD

**Issue by santosshen** [cannatag/ldap3#634]
get  Server IP
'''
server = Server('yun.cn', use_ssl=True, get_info=ALL)
conn =Connection(server=server,user='yun\\admin',password='adminian',auto_bind=True)

current_address   = server.current_address  
address_info = server.address_info
print(current_address)
print(address_info)
'''
[<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.0.2', 636), True, datetime.datetime(2018, 12, 29, 17, 11, 50, 682396)]
[[<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.0.2', 636), True, datetime.datetime(2018, 12, 29, 17, 11, 50, 682396)], [<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.10.1', 636), None, None], ...

'''
I need to know which site this IP belongs to.

tks.

**Comment by cannatag** [comment]
If you want to get the hostname associated to an IP you can use the socket.gethostbyaddr() function. Have a look at https://docs.python.org/3.7/library/socket.html
