### ISSUE TITLE
KeyError: 'controls'_

### ISSUE THREAD

**Issue by maxibillion** [cannatag/ldap3#635]
Using Python 3.7.2 -- getting error:
_cookie = conn.result['controls']['1.2.840.113556.1.4.319']['value']['cookie']
KeyError: 'controls'_

**_Code snippet:_**
from ldap3 import Server, Connection, SUBTREE
total_entries = 0
server = Server('ldaps:/server')
conn = Connection(server, user='user', password='pwd!')
conn.bind() 
while True:
	conn.search(search_base = 'ou=test',
         search_filter = '(objectClass=inetOrgPerson)',
         search_scope = SUBTREE,
         attributes = ['cn', 'givenName'],
         paged_size = 5)
	for entry in conn.entries:
		print(entry)
	cookie = conn.result['controls']['1.2.840.113556.1.4.319']['value']['cookie']
	if cookie:
		searchParameters['paged_cookie'] = cookie
	else:
		break
conn.unbind()

**Comment by cannatag** [comment]
Hi, probably you're receiving an error from the server. If this is the case the connection.result doesn't contain the "controls" key. So you have to check if the key is present before trying to use it.
