### ISSUE TITLE
ldap3/protocol/sasl/digestMd5.py is empty in the released 2.5.2 tarball

### ISSUE THREAD

**Issue by sscherfke** [cannatag/ldap3#636]
The `tar.gz` sdist for the 2.5.2 release contains an empty `ldap3/protocol/sasl/digestMd5.py`.  It is not empty in the wheel package, so I guess this is an error?

**Comment by cannatag** [comment]
Thanks, will fix this soon.

**Comment by mprahl** [comment]
@cannatag any news on this?

**Comment by mcescalante** [comment]
I just manually repopulated this file because when manually compiling some packages that I grabbed with `pip download <package> --no-binary :all:` I ran into `exceptions.ImportError: cannot import name sasl_digest_md5` which wasn't immediately apparent until I looked at what the file did and noticed that it was empty.

**Comment by nielslaukens** [comment]
I just stumbled upon this same issue... Some additional information that I figured out before finding this bug:

There seem to be two source tarballs in circulation:
* The one currently up on GitHub releases (https://github.com/cannatag/ldap3/archive/v2.5.2.tar.gz, SHA256: e842247dea702368bdecded0ee71c19081cd376c3567fdc7b0eb4546c06ae803)
* The one currently up on PyPi (https://files.pythonhosted.org/packages/c9/41/1c982033eb0355e0aa7da3a070d7869ca4705181012c10737a20b283913d/ldap3-2.5.2.tar.gz, SHA256 3f67c83185b1f0df8fdf6b52fa42c55bc9e9b7120c8b7fec60f0d6003c536d18)

The first one (SHA e842..) seems to be correct, while the second one (SHA 3f67..) contains an empty `digestMd5.py` file.

**Comment by cg505** [comment]
@cannatag Could you please reupload the PyPI package? This is an easy fix and real headache to debug.

**Comment by cannatag** [comment]
You’re right, I’m sorry for this silly problem. I’ve been quite busy on other (non open source) projects, but will try to fix it and other minor issues this week.

Sorry for troubles.
Giovanni

**Comment by cg505** [comment]
Thanks! Looking forward to it.

**Comment by martbhell** [comment]
One month later. Is there some way I can help with getting this fixed?

**Comment by cannatag** [comment]
You’re right, I’ve not been able to work on this project in the last months, will try to work on this in the weekend.

Bye,
Giovanni

**Comment by charisz** [comment]
It will be very good if you could fix this issue, It is about only one corrupted (empty) file (ldap3/protocol/sasl/digestMd5.py).

**Comment by cannatag** [comment]
I’m about to release a new version of ldap3 in the next weekend, please hold on for a few days.

Thanks,
Giovanni

**Comment by cannatag** [comment]
Fixed in next release of ldap3

**Comment by cannatag** [comment]
Fixed in version 2.6.
