### ISSUE TITLE
Unable to delete a user from below code

### ISSUE THREAD

**Issue by Charannm** [cannatag/ldap3#637]
from ldap3 import Server, Connection, ALL
s = Server('servername', get_info=ALL)
c = Connection(s, user='user_dn', password='user_password')
c.bind()
c.delete('cn=user1,ou=users,dc=company,dc=com')
print(c.result)
c.unbind()

**Comment by cannatag** [comment]
Probably you are binding with a user that doesn’t have the right to delete other users. Try with the Administrator user or add the right to delete other object to your current user.

**Comment by Charannm** [comment]
Thank you and able to delete the object now
