### ISSUE TITLE
protocolError when trying to authenticate

### ISSUE THREAD

**Issue by yuvipanda** [cannatag/ldap3#638]
Heya! I'm trying to authenticate against an LDAP server.

The following ldapvi command works (by which I mean it tells me invalid credentials, even though it is valid):

```
ldapvi -h ldap://<server>  -b "uid=yt37,ou=People,ou=hpc,<base>" -D "uid=yt37,ou=People,ou=hpc,<base>"  --out
```

However, the following python script gives me protocolError:

```
from ldap3 import Server, Connection, ALL, Tls
import ldap3
import ssl

server_address = "ldap://<server>"
bind_dn_template = 'uid=yt37,ou=People,ou=hpc,<base>'

server = Server(server_address, get_info=ALL, use_ssl=False)
conn = Connection(server, bind_dn_template, 'my-password', auto_bind=True)
```

Upon tcpdumping and looking at the hex requests (plus wireshark), both the requests being sent are *almost* same - except there is an additional `a000` at the end for the request from ldap3. Wireshark tells me this is a 'controls: 0' field that isn't present in the request from ldap3 - maybe. 

Any suggestions?

**Comment by cannatag** [comment]
I don't see any error in your code. What kind of ldap server are you connecting to? What is the pyasn1 version you're using?
