### ISSUE TITLE
Where is search_sub_tree() ?

### ISSUE THREAD

**Issue by satreix** [cannatag/ldap3#64]
Documentation mentions a `.search_sub_tree()` method on `Reader` in _abstraction.rst:146_ but the code is nowhere to be found. Is the function still available ?

I would really like to take advantage of this in an ongoing project.

**Comment by cannatag** [comment]
this is a typo in the documentation, it should be search_subtree(). Can you try?

**Comment by satreix** [comment]
Nice fix. Works great for me! :+1:
