### ISSUE TITLE
NTLM Not specifying digestmod

### ISSUE THREAD

**Issue by adawalli** [cannatag/ldap3#640]
When using NTLM with Python 3.6, a warning is generated at the following call to `hmac.new()`

https://github.com/cannatag/ldap3/blob/43234e26909cd3a07e1570934d65752a9b3726de/ldap3/utils/ntlm.py#L486

As explained in the Python 3.6 docs (https://docs.python.org/3.6/library/hmac.html#hmac.new)

> Deprecated since version 3.4: MD5 as implicit default digest for digestmod is deprecated.

Even worse - it appears by Python 3.7 that the NTLM util will completely stop working since I believe the digest becomes mandatory (https://docs.python.org/3.7/library/hmac.html#hmac.digest)

As the code is currently written, we get the following warning (on 3.6):

>   /usr/local/lib/python3.6/hmac.py:144: PendingDeprecationWarning: HMAC() without an explicit digestmod argument is deprecated.
    return HMAC(key, msg, digestmod)
  /usr/local/lib/python3.6/hmac.py:144: PendingDeprecationWarning: HMAC() without an explicit digestmod argument is deprecated.
    return HMAC(key, msg, digestmod)

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by cannatag** [comment]
Thanks, can you check the code in dev?

**Comment by cannatag** [comment]
Fixed in version 2.6.
