### ISSUE TITLE
Unable to pull out all email IDs of users

### ISSUE THREAD

**Issue by Charannm** [cannatag/ldap3#644]
Need to pull out list of all email IDs from Active directory and i got below script but problem is some email IDs are not showing or printing. 

instead of email id of users it's printing empty string i think.

I tried "objectclass=user" as search attribute but no use and i did not try with administrator account but my id having "domain admin" access.

Please guide me for any changes in script.

from ldap3 import Server, Connection, ALL, NTLM, ALL_ATTRIBUTES, ALL_OPERATIONAL_ATTRIBUTES
from ldap3.core.exceptions import LDAPCursorError
server_name = 'test'
domain_name = 'domain'
user_name = 'username'
password = "password"
list=[]

server = Server(server_name, get_info=ALL)
conn = Connection(server, user='{}\\{}'.format(domain_name, user_name), password=password, authentication=NTLM,auto_bind=True)
conn.search('dc={},dc=com'.format(domain_name), '(objectclass=person)', attributes=[ALL_ATTRIBUTES, ALL_OPERATIONAL_ATTRIBUTES])
for e in conn.entries:
    try:
        Email_id = e.mail
    except LDAPCursorError:
        Email_id = ""
    x=((str(Email_id)).split("@"))[0]
    list.append(x)
print(list)

**Comment by Charannm** [comment]
tried with given for loop still i not able pull all emails. out of 812 and i am getting only 400 emails attributes.

I have installed latest version of LDAP3

**Comment by cannatag** [comment]
Hi, do you still have this problem?

**Comment by Charannm** [comment]
I checked last month Jan 21st with above given code and still unable to retrieve all emails

**Comment by Charannm** [comment]
Yes still unable to pull out all email address.  tried with PYAD module and it's pulling all email addresses.

Please do the needful.

**Comment by Charannm** [comment]
I have created 1300 users account in Lab server, but result is limited to 1000 only.
Earlier I thought email IDs not pulling, sorry for that

Please let me know how to exceed the limit. 

Thank you in advance

**Comment by Charannm** [comment]
can you please let me know is it correct code to extract all objects from AD?

from ldap3 import Server, Connection, ALL, NTLM, ALL_ATTRIBUTES, ALL_OPERATIONAL_ATTRIBUTES,AUTO_BIND_NO_TLS,SUBTREE
def get_ldap_info():
    with Connection(Server('mysore', port=636, use_ssl=True),auto_bind=AUTO_BIND_NO_TLS,read_only=True,check_names=True,user='mysore\Administrator', password='password') as c:
        results = c.extend.standard.paged_search(search_base='dc=mysore,dc=com',search_filter='(objectClass=person)',search_scope=SUBTREE,attributes=ALL_ATTRIBUTES,get_operational_attributes=True)

        for row in results:
            if row.get("attributes"):
                #print(row.get("attributes"))
                x=row.get("attributes")
                print(x.get('samaccountname')+'|'+str(x.get('mail'))+'|'+str(x['cn']))
get_ldap_info()
