### ISSUE TITLE
Connection success with wrong domain in the username

### ISSUE THREAD

**Issue by lean0708** [cannatag/ldap3#646]
Hi everyone!

I am working on a "check ldap connection" feature using this library, and I ran into a weird behavior:
When I check a connection with this params:
-user=WRONGDOMAIN\right_user 
-password=right_password 
-server_ip=right_server_ip
-port=right_port
(all params ok but WRONGDOMAIN in the user param)
Then the connection is successful

In this case, how is posible a successful connection? 
Keep in mind that if I try the same values but against the actual ldap server, I can't log in.

I will apreciate any information
Thanks

**Comment by cannatag** [comment]
Hi, probably the server checks only the name of the user and don't check the domain. "Domains" are related to Active Directory, not to LDAP so your server could simply ignore that when trying to bind.

Bye,
Giovanni

**Comment by lean0708** [comment]
Perfect! thanks Giovanni!
