### ISSUE TITLE
Limit or offset results on search

### ISSUE THREAD

**Issue by psychomantys** [cannatag/ldap3#647]
There is any way to use a limit and offset on search?

Is has, is a good thing to write on documentation too ^^

**Comment by okin** [comment]
At least for limiting the search results there is the option size_limit for the search (https://ldap3.readthedocs.io/searches.html).

If you want to use the offset for making a paged search you can use the kwargs starting with paged_. 

Am 18. Januar 2019 21:51:39 MEZ schrieb Psycho Mantys <notifications@github.com>:

**Comment by cannatag** [comment]
>> Will return the elements between position 40 and 50 of the search?

No, that means that in every subsequent paginated search it will return the next 4 element, with a limit of 10. But the "meaning" of that 10 is meant by the server. So it could send back 10 element in 3 searches or simply ignore it.
