### ISSUE TITLE
Password with special characters

### ISSUE THREAD

**Issue by Dubrzr** [cannatag/ldap3#651]
Hello,

I'd like to know how to handle simple bind with passwords containing special characters, lets say for example that the password contains spaces " " I always get the following error: 

While with other passwords it works!

```
{'type': 'bindResponse', 'message': '80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1\x00', 'saslCreds': None, 'referrals': None, 'description': 'invalidCredentials', 'dn': '', 'result': 49}
```

Also, should I encode the password in a special manner?

My code:

```python
        temp_co = Connection(
            server=self.server_pool,
            user=DOMAIN + '\\' + username,
            password=password,
            authentication=SIMPLE,
            client_strategy=RESTARTABLE,
        )
        temp_co.bind()
        return temp_co.result['result'] == 0

```

**Comment by cannatag** [comment]
In the LDAP protocol password are "prepared" (pre-processed) with th SASLprep profile of the StringPrep RFC4013 (https://tools.ietf.org/html/rfc4013). It should accepts ASCII spaces in the password without problem. I see you connect to an Active Directory server. Have you tried the NTML authentication method of the ldap3 Connection object?

**Comment by Olu93** [comment]
Hello,

I have the same issue. My password relies heavily on special chars.
Special chars are  !@;.$+ and ^

My error message talks about invalid credentials.

My previous pasword worked fine


```python

from helper.constants import LDAP_DOMAIN, LDAP_PASSWORD, LDAP_PORT, LDAP_SERVER, LDAP_USER
from ldap3 import Server, Connection, SASL, ALL, NTLM, ALL_ATTRIBUTES, NONE, RESTARTABLE, REUSABLE, get_config_parameter, set_config_parameter
from helper.setup import logger
from urllib import parse
from ldap3.core import exceptions as ldap_exceptions
import json
import re

def connect():
    conn = None
    try:
        conn = Connection(
            server=f"{LDAP_SERVER}:{LDAP_PORT}",
            auto_encode=True,
            auto_escape=True,
            user=f'{LDAP_DOMAIN}\\{LDAP_USER}',
            password=LDAP_PASSWORD,
            authentication=NTLM,
            client_strategy=RESTARTABLE,
            receive_timeout=5)
        logger.debug(conn.bind())
    except ldap_exceptions.LDAPBindError as ex:
        logger.error(f"Couldn't bind connection for the search queries: {ex}")
        return None
    return conn

**Comment by rossKayHe** [comment]
If it's one of those characters my guess the period that's the issue you can control what special characters you use.  ```
`random.choice('@#$%&*')````

**Comment by Olu93** [comment]
Hi, 
is there any information on this? 

I found out based on the old working password that period and exclamation mark cannot be the cause.
So it must be one of those @;$+ and ^

And how can I escape these characters, because \ doesn't seem to capture anything. It was part of the old password.

**Comment by cannatag** [comment]
Hi I've not found any problem in password with any of the following special characters: "@;$+^"

Do you still have this problem?

**Comment by benclark158** [comment]
I know this is closed, but I am having the same issue. I can connect and bind to a AD server with a username and password that doesn't contain a `$` but as soon as I try to bind with a user who has a password containing `$` I get the invalid credentials error:

```python
import ldap3
server = ldap3.Server(host='ldap://' + server_address, use_ssl=True)

conn = ldap3.Connection(server, auto_bind=True, version=3, auto_encode=True, auto_escape=True, authentication=ldap3.SASL, sasl_mechanism='DIGEST-MD5', sasl_credentials=(None, username, password, None, 'sign'))
```

Where the `password` variable is the valid password (tested in Windows - I am using it with MS AD) that contains the character `$`. From this I get the error: `ldap3.core.exceptions.LDAPBindError: automatic bind not successful - invalidCredentials`. I assume like Olu93 that there is some sort of escaping I need to do, but not sure what that would be? I am running `ldap3==2.9.1` in a conda environment.
