### ISSUE TITLE
unnecessary underscore in documentation

### ISSUE THREAD

**Issue by Lightyagami1** [cannatag/ldap3#653]
[link to documentation](https://github.com/cannatag/ldap3/blob/dev/docs/manual/source/searches.rst#search-scope-and-aliases)
at third line : containers, but not in a leaf object. It must be _clear that containers and le
                                                                                                     ^^^^^^
 
underscore before clear is not needed as per my understanding.

**Comment by cannatag** [comment]
Fixed! Thanks!
