### ISSUE TITLE
How to best provide access to Active Directory for testing? 

### ISSUE THREAD

**Issue by jmsmtn** [cannatag/ldap3#656]
I noticed this comment by you:

> Now I don't have easy access to an Active Directory server, so I didn't tested it with the latest updates.  _Originally posted by @cannatag in https://github.com/cannatag/ldap3/issues/329#issuecomment-372073311_

And this commit: 

https://github.com/cannatag/ldap3/commit/d17f34a148c2a2ccef67378291fbe6494fd46997

And I was just wondering if I could provide a test Active Directory instance for you? And if so, what would be the best way?

Thanks!

**Comment by cannatag** [comment]
Hi, sorry for the late answering. The tests suite of ldap3 includes a configuration specific for AD, but I don't use it anymore. If you want provide a lab for testing AD you can adapt the configuration to your needs. IF the lab is reachable in Internet the test can automatically run on Travis.

Let me know if you're still interested in it.

Thanks,
Giovanni
