### ISSUE TITLE
ldap3 invalidCredentials

### ISSUE THREAD

**Issue by assafd** [cannatag/ldap3#659]
Hi,

After the below lines i'm getting this error message (ldap3 invalidCredentials)

conn = Connection(server, 'uid=administrator,cn=users,dc=ad,dc=local', 'password', auto_bind=True)

But, when im connected with the below method its OK  :

conn = Connection(server, "user=AD\\administrator" , password="password" ,authentication=NTLM , auto_bind=True)

WHY??? 

thanks

**Comment by cannatag** [comment]
You're connecting to an AD server. Using the NTLM you use the DOMAIN\user pattern and it will find the real user in the Active Directory. When using the Simple LDAP authentication you must provide the dn of the user. Maybe you have a different DN associated to AD\administrator.
