### ISSUE TITLE
Search fails from version 2.1.0 onwards

### ISSUE THREAD

**Issue by gdevanla** [cannatag/ldap3#661]
Hello,

We have been using ldap3 since version 1.3.3. I use the library for a very simple search operation against a ActiveDirectory server. (using Python 3.5) and it works fine.

When I upgrade to the latest version (or to 2.1.0), I see the same search query returning the following error:

ldap3.core.exceptions.LDAPNoSuchObjectResult: LDAPNoSuchObjectResult - 32 - noSuchObject - DC=foo, DC=local  - 0000208D: NameErr: DSID-031001E4, problem 2001 (NO_OBJECT), data 0, best match of:  'DC=foo ,DC=local'

Here is a stripped down version of the code that used to work in version 1.3.3

```
server = Server(host, use_ssl=True, port=636)
conn = Connection(server, user='jane@foo.local' % user, password='password',                                                                                                                                                                      
            client_strategy=SYNC, authentication=SIMPLE,                                                                                                                                                                                       
            check_names=True, raise_exceptions=True)
conn.bind()
search_base = 'OU="Foo Users",DC=foo,DC=local'                                                                                                                                                                                               
search_filter = '(mailNickName=jane)'         
conn.search(search_base, search_filter)
```
My first guess is some default parameters to the connection object that might have changed could be causing the change in behavior. It would be nice if someone in this group can throw some light on this.

Thanks

Edit: Added missing closing double quote

**Comment by cannatag** [comment]
Hi, can you set the log level to debug for the library, so we can see what’s going wrong in the connection?

Have a look at https://ldap3.readthedocs.io/logging.html to see how to activate logging.

Thanks,
Giovanni

**Comment by gdevanla** [comment]
@cannatag Thank you for the tip on logging. I have identified what causes the difference in behavior.

The code snippet
```
search_base = 'OU="Foo Users",DC=foo,DC=local'   
```

works in version 1.3.3  Since the "double quotes" are not escaped. 

I notice that in the new version the double quotes are escaped.  I remove the double-quoted from the string above and everything works out fine. 

```
search_base = 'OU=Foo Users,DC=foo,DC=local'   
```
