### ISSUE TITLE
invalid CA public key file

### ISSUE THREAD

**Issue by fpatterson55** [cannatag/ldap3#665]
ldap3.core.exceptions.LDAPSSLConfigurationError: invalid CA public key file

I have tried to specify a .der, .b64 and .pem file.

t= Tls(validate=ssl.Cert_REQUIRED, version=ssl.PROTOCOL_TLSv1, valid_names='*', ca_certs_file='cert.pem', ca_certs_path='/home/ralph/dev/tls/cacerts/')

server = Server('10.0.0.5', tls=t, get_info=ALL)
conn.bind()

When trying to do it over 389, it works fine. In the past I have tried the full path of the file with no luck.

Python3 is 3.6.7
ldap3-2.6 pyasn1-0.4.5

File "/opt/penv/lib/python3.5/site-packages/ldap3/core/tls.py", line 90, in __init__
web_1    |     raise LDAPSSLConfigurationError('invalid CA public key file')

the /opt/penv/lib/python3.5/site-packages ... is odd to me as I am running 3.6.7... Which is also wierd as I thought I would have 3.7 but maybe ubuntu doesn't do 3.7 yet. Would this be a mixed version issue?

If this sounds very newbish, I apologize. This application I am trying to run is an angular program with python in the middlewhere layer. So docker is involved. I am trying to take an example project with unsecure LDAP and make it secure.

**Comment by cannatag** [comment]
Hi, probably you have multiple version of the Python interpreter on your PC. Anyway tls should work with 3.5 and 3.6. Path is the "opt/penv" path? Maybe a virtual environment for a specific project? You said you're using docker, mabye you're running the interpreter inside the container and the '/home/ralph/dev/tls/cacerts/ is on your PC. 

If this is not the case can you replicate this in a Dockerfile? I would try to find what's going wrong.

Giovanni

**Comment by fpatterson55** [comment]
Thank you. I will try to test this outside of a docker container first.

The project I am trying to implement as a base for customization is: https://github.com/MicroFocus/CX

I am going through their steps to setup the environment. Unfortunately I am new to docker. I am running this on an opensuse environment and it is using btrfs. I was able to find btrfs subvolumes, and that they reference /opt/penv, but I haven't made the connection on where to copy the public cert to so that it is seen or /opt/penv. I also need to see how to work in that virtual environment. I hope to do more research into docker this week. 

It makes sense that this is a virtual environment / container issue and that my file is not in the right path for the environment, etc.

I also need to figure out a way to deploy with docker to a production web server, such as tomcat or django, etc.

Thanks,
Fred
