### ISSUE TITLE
Trailing Space in DN

### ISSUE THREAD

**Issue by phi1010** [cannatag/ldap3#667]
As far as I can tell, parse_dn from ldap3.utils.dn (from 2.4.1 via 2.5.* up to 2.6) doesn't handle DNs with trailing escaped spaces well:

```
import ldap3
from ldap3.utils import dn
dn.parse_dn(r"bar=\ baz\ ")
# causes: ldap3.core.exceptions.LDAPInvalidDnError: invalid final character
```

According to RFC4514 the (R)DN `bar=\ baz\ ` should be okay, according to BNF the value is a `string`, whose last item is a `pair` (`pair` = `ESC special` = `ESC SPACE` = `"\" " "`) instead of a `trailchar`. 

Other escaped trailing characters (backslash and plus) seem to be okay, though.

**Comment by cannatag** [comment]
Hi, can you check the code in dev? It should work now.

**Comment by phi1010** [comment]
Sorry for the delay -- i'm currently writing some unit tests; as far as I can tell double backslashes also fail in the current master, but only if there is a comma or plus afterwards, spaces are now okay.

I'll create a pull request with tests as soon as I have covered the usual edge cases.

**Comment by cannatag** [comment]
Hi Phillip, sorry for the long delay, can you check the code in dev? It should work now.

**Comment by phi1010** [comment]
Seems good, thanks.

I don't care too much about the escape and strip options -- they aren't defined in any RFC, are they?

For completeness:
Using the escape option on valid DNs works well, too. (It does add obviously missing escapes?)

I can only guess what the strip option does: remove spaces at the beginning and end of keys and values, to allow user friendly input like `name = John Doe , ou = IT , company = Wonka Industies`? If that's the case, the behaviour of not accepting `abc=def\ ,ghi=jkl` (LDAPInvalidDnError: invalid final character) might still be a bit confusing to some users, because they probably intentionally escaped the space -- they might have learnt this behaviour from regex engines (option /x in PCRE).
