### ISSUE TITLE
ldap3==2.6 is incompatible with Python 3.7.1

### ISSUE THREAD

**Issue by jonfen** [cannatag/ldap3#668]
Issue is back: https://github.com/cannatag/ldap3/issues/428

work around:

$ pip install ldap3==2.5.1

**Comment by cannatag** [comment]
what problem are you facing? I tested with 3.7 and got no errors. Or do you mean that some file is missing^

**Comment by jonfen** [comment]
@cannatag this reserved keyword issue (https://github.com/cannatag/ldap3/issues/428) was reintroduced in version 2.6, version 2.5.1 doesn't have that issue.

`from ..strategy.async import AsyncStrategy`

**Comment by cannatag** [comment]
In which file do you find this line? I cannot find it in the 2.6 codebase.
