### ISSUE TITLE
SASL:[GSSAPI]: Sign or Seal are required.

### ISSUE THREAD

**Issue by JonathonReinhart** [cannatag/ldap3#669]
I'm running a Samba 4 domain controller (version 4.9.4-Debian).

- Operating system: Debian Buster
- Python version: Python 3.7.3rc1
- python-ldap version: 3.2.0

I can successfully use `ldapsearch` with GSSAPI SASL authentication to search for users:
```
$ kinit someone
...

ldapsearch -Y GSSAPI -H "ldap://samba-dc.ad.example.com" -b "dc=ad,dc=example,dc=com" "(objectClass=user)" sAMAccountName
```

However, when I attempt to use this Python snippet:
```python
import ldap3

srv = ldap3.Server('ldap://samba-dc.ad.example.com')

sasl_creds = (True,)    # perform reverse DNS lookup
conn = ldap3.Connection(srv,
        sasl_credentials=sasl_creds,
        authentication=ldap3.SASL,
        sasl_mechanism=ldap3.GSSAPI,
        raise_exceptions=True,
        )

with conn:
    search_base = "dc=ad,dc=example,dc=com"
    search_filter = "(objectClass=user)"

    ok = conn.search(search_base, search_filter)
    pprint(conn.entries)
```

It doesn't work, and I get this error:
```
ldap3.core.exceptions.LDAPStrongerAuthRequiredResult: LDAPStrongerAuthRequiredResult - 8 - strongerAuthRequired - None - SASL:[GSSAPI]: Sign or Seal are required. - bindResponse - None
```

FWIW: I can't get this to work with `python-ldap` either: https://github.com/python-ldap/python-ldap/issues/275

**Comment by tiran** [comment]
Your server requires a secure SSF, but ldap3 does not support any security layers (neither data integrity nor encrypted SASL tunnel).

https://github.com/cannatag/ldap3/blob/43234e26909cd3a07e1570934d65752a9b3726de/ldap3/protocol/sasl/kerberos.py#L45-L49

**Comment by JonathonReinhart** [comment]
@tiran Thanks a lot for pointing that out. I opened #671 to add a note in the documentation.

I don't know much about SASL, but I see this check a little bit further down:

https://github.com/cannatag/ldap3/blob/43234e26909cd3a07e1570934d65752a9b3726de/ldap3/protocol/sasl/kerberos.py#L104-L105

Is there another check that `ldap3` could make to detect this error?
