### ISSUE TITLE
ldap search have a problem

### ISSUE THREAD

**Issue by zepprebel** [cannatag/ldap3#670]
hello, sorry for my bad english

i have a problem with manage ldap3.Connection.search
i dont understand  how that work
`
var = connect.search(search_base, search_filter="(&(objectClass=organizationalUnit)(name=anyName))") # Regardless of whether there is an OU with the name anyName, the return value in the VAR is true, false only if the request is not made correctly
`
just i want use that request one more time

how to best practice?
via self function?

from Russia with love)

**Comment by cannatag** [comment]
The result (True or False) means that the search has found some entries (True) or not (False). You then can check the ‘response’ attribute to get each entry. You can also use the ‘entries’ attribute to get a more object oriented representation of the entries.
