### ISSUE TITLE
Can't read configurationNamingContext from RootDSE (MS AD)

### ISSUE THREAD

**Issue by lonelyDog** [cannatag/ldap3#672]
Good day!

I use latest version of ldap3. When I try to search for the RootDSE and read configurationNamingContext I see error 'Invalid attribute type'. I check server.schema.attribute_types and indeed, this attribute was not present.

Ok, I add 'check_names=False' to the constructor of Connection object. As result it fail in other place (in search operation) with same exception.

I fix it by adding 'configurationNamingContext' to the 'ATTRIBUTES_EXCLUDED_FROM_CHECK'. Can you tell me why 'check_names' doesn't help?

Btw, same code work without issue with ldap3 version 1.3.3

Thanks

**Comment by dirkjanm** [comment]
The attribute is in `server.info.other` in recent versions.

**Comment by lonelyDog** [comment]
Thank you.
