### ISSUE TITLE
Always return single valued attributes as array

### ISSUE THREAD

**Issue by lonelyDog** [cannatag/ldap3#673]
Good day!

I am try to upgrade ldap3 library from 1.3.3 to the latest version.
It seems that old library always return array of values even for single valued attributes. But in the latest version it check schema and return just value for such attributes. As result a lot of our code was broken. For example:

c.search(search_base=search_base,
                        search_filter='(&(objectcategory=crossref)(dnsRoot=%s)(netBIOSName=*))' % dns_root,                        
search_scope=LEVEL,
                        attributes=['netbiosname'])
name = c.response[0]['attributes'].get('nETBiosName', [None])[0]

When I run it with ldap3 1.3.3 I have NetBIOS name in 'name'. When I run it with latest version I have just first letter. Is it possible to enable old behavior? I know I can do it with check_names=False, but I think its not good idea to disable schema checks.

Thanks

**Comment by cannatag** [comment]
That’s because the netbiosname is single-valued in ldap. You can access the raw_attributes dictionary to get a non formatted list of values. I suggest you to modify your code to use the single value attribute because it’s validated by the ldap3 library.
