### ISSUE TITLE
Can not bind noninteractively using SASL EXTERNAL over socket

### ISSUE THREAD

**Issue by mrvanes** [cannatag/ldap3#677]
I can't seem to make passwordless SASL EXTERNAL authentication as root to work for local sockets.

I need something like ```# ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:///``` to work (passwordless), but the ldap logs show the lib doesn't offer a correct authcid and authzid.

In contrary to the ldapsearch commandline, I did specify the real path to the socket (/var/run/slapd/ldapi) in my test code for the initial connection to work, the authentication/bind however, sort of fails silently, because the first search returns ```SASL bind in progress```:

```
Apr 16 13:45:20 ldap slapd[76]: conn=3038 fd=18 ACCEPT from PATH=/var/run/slapd/ldapi (PATH=/var/run/slapd/ldapi)
Apr 16 13:45:20 ldap slapd[76]: conn=3038 op=0 BIND dn="" method=163
Apr 16 13:45:20 ldap slapd[76]: conn=3038 op=0 RESULT tag=97 err=14 text=SASL(0): successful result: 
Apr 16 13:45:20 ldap slapd[76]: connection_operation: error: SASL bind in progress (tag=99).
Apr 16 13:45:20 ldap slapd[76]: conn=3038 op=1 SEARCH RESULT tag=101 err=1 nentries=0 text=SASL bind in progress
```
The forementioned ldapsearch commandline successfully authenticates like this:
```
Apr 17 07:34:58 ldap slapd[76]: conn=3470 fd=18 ACCEPT from PATH=/var/run/slapd/ldapi (PATH=/var/run/slapd/ldapi)
Apr 17 07:34:58 ldap slapd[76]: conn=3470 op=0 BIND dn="" method=163
Apr 17 07:34:58 ldap slapd[76]: conn=3470 op=0 BIND authcid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth"
Apr 17 07:34:58 ldap slapd[76]: conn=3470 op=0 BIND dn="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" mech=EXTERNAL sasl_ssf=0 ssf=71
Apr 17 07:34:58 ldap slapd[76]: conn=3470 op=0 RESULT tag=97 err=0 text=
Apr 17 07:34:58 ldap slapd[76]: conn=3470 op=1 SRCH base="dc=client,dc=vnet" scope=2 deref=0 filter="(cn=*)"
Apr 17 07:34:58 ldap slapd[76]: conn=3470 op=1 SRCH attr=dn
Apr 17 07:34:58 ldap slapd[76]: conn=3470 op=1 SEARCH RESULT tag=101 err=0 nentries=31 text=
Apr 17 07:34:58 ldap slapd[76]: conn=3470 op=2 UNBIND
Apr 17 07:34:58 ldap slapd[76]: conn=3470 fd=18 closed
```

**Comment by cannatag** [comment]
Hi, can you show the code you’re using?

**Comment by mrvanes** [comment]
I don't have the actual code anymore, because as soon as I understood ldap3 wasn't going to cooperate I switched to python-ldap. The code I tried was the exact example found on https://ldap3.readthedocs.io/ssltls.html, but without the TLS preparation:
```
server = Server(host = 'ldapi:///var/run/slapd/ldapi')
connection = Connection(server, authentication = SASL, sasl_mechanism = 'EXTERNAL')
connection.bind()
```

The working python-ldap code example looks exactly what I would expect from a passwordless noninteractive external sasl login (executed as root).
```
l = ldap.initialize('ldapi:///var/run/slapd/ldapi')
l.sasl_external_bind_s()
```
