### ISSUE TITLE
fast  Active Directory connection ??

### ISSUE THREAD

**Issue by santosshen** [cannatag/ldap3#679]
hi cannatag,

python 3.5
Active Directory

![image](https://user-images.githubusercontent.com/25058112/56640244-19cccd00-66a5-11e9-9261-9799af751763.png)

**Comment by santosshen** [comment]
hi cannatag

**Comment by cannatag** [comment]
Hi, probably  this is related to your server, the connection is slow. Can you try without the “with” context? Just define the connection and issue a bind().

You can also define the Server object with get_info=NONE. In this case the schema is not read from the server.

**Comment by santosshen** [comment]
![image](https://user-images.githubusercontent.com/25058112/56885096-32225a80-6a9e-11e9-9ca6-90e4a6122be5.png)

tks, cannatag
