### ISSUE TITLE
Malformed filter when searching for value containing parens

### ISSUE THREAD

**Issue by dclar43** [cannatag/ldap3#680]
ldap3 verison: 2.6
Server: Active Directory  
  
I'm attempting to search for an attribute whose value contains parentheses.  
  
Example:  
  
```python
...
obj_person = ObjectDef(['person'])
query_str = 'distinguishedName: Bob Smith (smithb)'
r = Reader(conn, obj_person, 'o=test', query_str)
# LDAPInvalidFilterError: malformed filter
```

For more information on my use case:  
  
I'm attempting to determine the organizational structure starting at an arbitrary person. e.g. find all people who report to bob.  
  
To do so I'm accessing an entry's [directReports attribute](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adls/f7cd6943-872d-423c-8009-bc8502485fab) which is a list containing the DN of all people who report to that given user.
  
Our CNs follow the pattern of `FirstName LastName (username)`. This causes the malformed filter exception to be thrown, due to the parens.  
  
Am I overlooking something here? I've tried some work arounds such as escaping the filter via `utils.conv.escape_filter_chars` but that results in no entries being returned.

**Comment by cannatag** [comment]
Hi, sorry for the late answer. In your case you have to escape only the value portion of the filter with the escape_filter_chars function from the ldap3.utils.conv package:

```
from ldap3.utils.conv import escape_filter_chars
value = 'Bob Smith (smithb)'
escaped = escape_filter_chars(value)
query_str = 'distinguishedName: %s' % escaped
```

If you still get no entries from the server you can try with a simpler filter and check the attribute names, usually the distinguishedName is called DN and is in the form of cn=xxx,ou=xxx,o=xxx,dc=xxx or something similar.

Bye,
Giovanni
