### ISSUE TITLE
tls check_hostname=False and do_handshake=False

### ISSUE THREAD

**Issue by enricoba** [cannatag/ldap3#687]
Hi,

I have a question regarding the tls module. Is there a particular reason for setting "ssl_context.check_hostname = False" and "do_handshake=False"? And do you think it is worth mapping those to the tls object level for individual configuration? 

As well I don't know how to access SSLContext.wrap_socket methods like "cipher()" or "getpeercert()" from your connection object. I would like to perform further security driven checks for my ldap connection. How to do that? 

Thanks for reply!

**Comment by cannatag** [comment]
hi, if you set check_hostname to False the name in the certificate is not checked against the server name. If you check do_handshake to False you must wrap the ssl socket by yourself. The first option is useful with non valid certificates, the second one is for internal use inside the wrap_socket method.

As for your second question you should be able to access the ssl socket at connection.socket after you have a valid ssl connection.

Bye,
Giovanni
