### ISSUE TITLE
ldap3 version 2.6 python3.6

### ISSUE THREAD

**Issue by sgr-smile2015** [cannatag/ldap3#694]
use c.extend.microsoft.modify_password() method change user passworld 

hash_pwd = hashed(HASHED_SHA256, 'test')
c.extend.microsoft.modify_password(dn, hash_pwd)
But i got this result:
**{'result': 17, 'description': 'undefinedAttributeType', 'dn': '', 'message': 'unicodePwd: attribute type undefined', 'referrals': None, 'type': 'modifyResponse'}**

Thinks a lot.

**Comment by cannatag** [comment]
Three questions:

1. Are you sure you’re accessing an Active Directory server? 

2. Are you using a protected connection (tls)?

3. Do you have administrative rights to modify the user object?

**Comment by sgr-smile2015** [comment]
1. use openLDAP server(openldap-2.4.31, ubuntu14.04)
2. not use tls
3. have admin permission 
thanks for you reply..

**Comment by cannatag** [comment]
you’re trying to modify an Active Directory password. For openLDAP try with c.extend.standard.modify_password().

Bye,
Giovanni

**Comment by sgr-smile2015** [comment]
thanks
