### ISSUE TITLE
How should work 'rebind' using 'reusable' connection?

### ISSUE THREAD

**Issue by charisz** [cannatag/ldap3#697]
I would like to use a connection with REUSABLE strategy.

If I use a simple  (RESTARTABLE) connection calling 'rebind' returns 'False' if the 'user' or 'password' is incorrect. That is the desired behavior.

When I use a reusable connection 'rebind' returns always 'True' even if the 'user' or 'password' is incorrect. I should do an extra 'bind' to get information about unsuccessfully bind.

What do I wrong or is it a bug?

**Comment by cannatag** [comment]
You're right. RESTARTABLE connections are lazy, they bind only when a real operation is performed. I suggest to try a simple search when starting up the connection, or try reading the schema that should trigger the bind.

Bye,
Giovanni
