### ISSUE TITLE
Unusually slow response

### ISSUE THREAD

**Issue by tugofpeas** [cannatag/ldap3#698]
I'm getting very slow result fetching, over ~500k records while using paged search, with generator=True. The results are the same on Windows/Linux.
It takes about 20-25 min for per page, regardless of size_limit/paged_size settings. 
The LDAP implementation is Netiq eDirectory. The same search in ldapsearch takes about a minute to filter and return about ~80k records over 500k recordset.
Any ideas what could be happening other than ldap3 being a pure Python implementation and not as fast as C?

**Comment by tugofpeas** [comment]
Apparently the eDirectory (4.5) implementation of LDAP does not support paged search. From what I gathered the cookie is always returned and therefore the while loop goes into an infinite one. Hopefully this may help someone.

**Comment by cannatag** [comment]
Hi, eDirectory should support paged search. Are you sure are you using tha 4.5 version? Current version is 9.1.
