### ISSUE TITLE
slapd ACL parser

### ISSUE THREAD

**Issue by sscherfke** [cannatag/ldap3#699]
Hi @cannatag ,

I have written a (nearly, but not fully) feature complete [LDAP ACL](https://www.openldap.org/doc/admin24/access-control.html) parser and checker.

Would this be something that you would add to this project?

**Comment by sscherfke** [comment]
Context: I have written an “LDAP contacts“ app and we want to check on the client side whether a user can write an entry or not. So the app bundles a (reduced) copy of the slapd ACLs which we evaluate with Python.

**Comment by cannatag** [comment]
Hi, ldap3 strictly follows the LDAP standard described in IETF RFC 4510. For what I know the slapd ACL format is not in the standard track of the IETF, but your project seem interesting, maybe it could be added in the ldap3.extend namespace. Can you give me more details on how it works? 

Thanks,
Giovanni

**Comment by sscherfke** [comment]
The (part of the) project reads and parses a slapd ACL file. It generates a Python object representation of that ACL.

It then provides the a function to check if a certain action (e.g., a Write to an entry by the current user) would be allowed by the server or not. The check is run against the locally parsed ACL and not against the actual server.

The parser can—in theory—parse 100% of the ACL grammar, but for practical reasons I simplified it a bit. The `ldap3.extend` might be a suitable place for this.

**Comment by peppelinux** [comment]
Hi @sscherfke, Is there a public repository to take a look to your project?

**Comment by sscherfke** [comment]
I finally had time to extract and "obfuscate" the code. Here it is: https://gitlab.com/sscherfke/slapd-acl-parser :)

**Comment by peppelinux** [comment]
That's something similar but completely different
https://github.com/peppelinux/slapd_acl
