### ISSUE TITLE
"DN cannot change while performing moving", although it should

### ISSUE THREAD

**Issue by fab0l1n** [cannatag/ldap3#703]
By design, it is not possible to simultaneously move and rename and entry:

https://github.com/cannatag/ldap3/blob/08810e435392a1f1a96d5e65bb444b9cb9e96ae3/ldap3/core/connection.py#L1118-L1122

Although according to [RFC4511 ](https://tools.ietf.org/html/rfc4511#section-4.9)it should be possible:

> The Modify DN operation allows a client to change the Relative
> Distinguished Name (RDN) of an entry in the Directory **and/or** to move
> a subtree of entries to a new location in the Directory.

Is there a reason for this?

**Comment by cannatag** [comment]
Hi, you're right. The 4511 RFC allows to move and rename at the same time. I misinterpreted the RFC in a too restrictive way. 

Will remove the restriction in the next release of ldap3.

Thanks,
Giovanni

**Comment by cannatag** [comment]
Can you try the code in dev? I've removed the restriction. Thanks.

**Comment by fab0l1n** [comment]
> Can you try the code in dev? I've removed the restriction. Thanks.

Worked for me. 
Tried both True and False for delete_old_rdn, but no controls.

**Comment by cannatag** [comment]
released in v2.6.1
