### ISSUE TITLE
Exception if serverpool is empty after x retries?

### ISSUE THREAD

**Issue by Netzvamp** [cannatag/ldap3#704]
Hi, 
maybe i just overlooked something, but i tried to get an error handling if all servers in an serverpool are unreachable. This code is running forever without any timeout, there seems no limit:

```
set_config_parameter('RESTARTABLE_TRIES',` 1)
set_config_parameter('POOLING_LOOP_TIMEOUT', 1)
dc1 = Server("somethinginvalid", port=636, use_ssl=True, get_info=ALL, connect_timeout=2)
dc2 = Server("somethinginvalid2", port=636, use_ssl=True, get_info=ALL, connect_timeout=2)
server_pool = ServerPool([dc1, dc2], active=True, exhaust=True)
conn = Connection(server_pool, user="something", password="something", receive_timeout=2, auto_bind=True, raise_exceptions=True)
```
How can i get a timeout with an exception?

Thanks,
Robert

**Comment by cannatag** [comment]
Hi, sorry for the late answer. When you define the ServerPool you can specify the number of cycles of trying before giving up with the "active" parameter. If you set active=2 the ServerPool will try two cycles when all servers are unavailable before giving up. If you set active=True it will try forever.

I know that the name of the "active" parameter is not meaningful, but you can find more information https://ldap3.readthedocs.io/server.html#server-pool.

Bye,
Giovanni
