### ISSUE TITLE
Does Simple bind support queries to trusted forests/domains?

### ISSUE THREAD

**Issue by minli1** [cannatag/ldap3#705]
I've asked this question below:
https://github.com/cannatag/ldap3/issues/120#issuecomment-502014581
Any help will be appreciated. Thank you!

**Comment by scsi050** [comment]
I also have this question.


```
from ldap3 import Server, Connection, ALL
server = Server('domainA')
conn = Connection(server, 'account', 'pwd', auto_bind=True, raise_exceptions=False)
conn.search('CN=Computers,DC=DomainA', '(objectclass=computer)', attributes=[ 'name' ])
```
This works great.  However, When I modify conn.search and enter the path to a CN but in a domain that is trusted with DomainA, I get:

```
>>> conn.result
{'result': 1, 'description': 'operationsError', 'dn': '', 'message': '000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580\x00', 'referrals': None, 'type': 'searchResDone'}
>>>
```

**Comment by cannatag** [comment]
You're trying to access another domain so you must perform the bind with a proper account. I don't use AD but I think you should query the "global catalog" the includes the whole AD forest.

Bye,
Giovanni
