### ISSUE TITLE
Make py3.7 wheel pls

### ISSUE THREAD

**Issue by aachurin** [cannatag/ldap3#706]
Please, make py3.7 wheel

**Comment by cannatag** [comment]
The wheel should be for python2 and python3. The source is exactly the same. You can find the file at  https://files.pythonhosted.org/packages/b5/3c/57f87ba620248f003e36cbc2f7b163d9a865bcfe13a82272b0543f72a09b/ldap3-2.6-py2.py3-none-any.whl
