### ISSUE TITLE
Correct way to access and query a trusted domain

### ISSUE THREAD

**Issue by glaterza6** [cannatag/ldap3#712]
Hi,

I have an account in my domain **test.priv**.

```
from ldap3 import Server, Connection, ALL, NTLM
 
user = 'test\\user'
user_dn = 'CN=user,OU=Standard Users,OU=New York,DC=test,DC=priv'
password = 'password'
server = Server( 'test.priv', use_ssl=True, get_info=ALL )
```

I have no problem accessing my domain with:
```
conn = Connection( server, user=user, password=password, authentication=NTLM, auto_bind=True )
```
or alternatively with:
```
conn = Connection( server, user_dn, password, auto_bind=True )
```

I tried some tests querying around and everything goes well.

But my domain has a trusted domain I would like to access (bidirectional trust): **services.local**.

If I try:
```
server = Server('services.local', use_ssl=True, get_info=ALL)
conn = Connection( server, user_dn, password, auto_bind=True )
```

I got:

> LDAPSocketOpenError: ('unable to open socket', [(LDAPSocketOpenError("socket ssl wrapping error: [WinError 10054] [...])

or deleting **use_ssl=True** in the server definition:

> LDAPBindError: automatic bind not successful - invalidCredentials

Using NTLM instead:
```
server = Server('services.local', use_ssl=True, get_info=ALL)
conn = Connection( server, user=user, password=password, authentication=NTLM, auto_bind=True )
```

I receive LDAPSocketOpenError again but if I delete **use_ssl=True**, everything works.
Any idea why? Is there a suggested and secure way to connect and query a trusted domain with ldap3?
Thank you very much.

**Comment by cannatag** [comment]
Hi, do you still have this problem?

**Comment by nerocui** [comment]
I'm having this issue as well, any updates on this?
I can connect to server with username, password and NTLM without using auto_bind, but it fails with this error when use_ssl is set to True.
