### ISSUE TITLE
Invalid check for hexdigits

### ISSUE THREAD

**Issue by godis-michael** [cannatag/ldap3#714]
https://github.com/cannatag/ldap3/blob/08810e435392a1f1a96d5e65bb444b9cb9e96ae3/ldap3/utils/dn.py#L177

Characters check for being hexdigit is invalid, redundant quotes.

**Comment by cannatag** [comment]
thanks, can you check the code in dev?

**Comment by cannatag** [comment]
released in v2.6.1
