### ISSUE TITLE
Cursor stays unmodified when issuing a ModifyDn message.

### ISSUE THREAD

**Issue by Jo-Con-El** [cannatag/ldap3#716]
I have a program that tries to sync a list of attributes from another source of truth into AD through its LDAP interface, including the full name of the person.  displayName is changed, but **cn** or **name** are not.  I'm not sure if this is another bug, but AD simply ignores my updates on those attributes over and over without any message from ldap3.  To show a simplified version of my code:

```
server = ldap3.Server(server_name, use_ssl=True, get_info=ldap3.ALL)
conn = ldap3.Connection(server, user=username,
        password=password, authentication=ldap3.NTLM,
        auto_bind=True, auto_range=True, auto_referrals=False)
# We specify the base object and the two cursors.
obj_user = ldap3.ObjectDef('user', conn)
r = ldap3.Reader(conn, obj_user, base_dn)
r.search(attributes=attributes_for_search)
w = ldap3.Writer.from_cursor(r)
w = update_ad(employee_dict, w)
w.commit()

def update_ad(employee_dict, write_cursor):
    # Example with 'cn' but this loops over various LDAP attributes.
    for ad_record in write_cursor:
        empl_id = ad_record.employeeId.value
        empl_attr_value = employee_dict[empl_id]['cn']
        if (ad_record, 'cn') != empl_attr_value:
            setattr(ad_record, 'cn', empl_attr_value)

    return write_cursor
```

Then I decided to solve this by issuing `modify_dn` calls when I see changes in **cn**, but (of course) the information already stored in the cursor didn't change:
```
>>> w[12].distinguishedName.value
'CN=Joseph Pesci,OU=Actors,DC=hollywood,DC=internal'
>>> w.connection.modify_dn(w[12].distinguishedName.value,'CN=Joe Pesci')
True
>>> w[12].distinguishedName.value
CN=Joseph Pesci,OU=Actors,DC=hollywood,DC=internal
>>> w.write_commit()
False
>>> w[12].distinguishedName.value
CN=Joseph Pesci,OU=Actors,DC=hollywood,DC=internal
```

If I want to run a unit test on this function, it gets very complicated, because the final state of the cursor won't reflect the actual state of the LDAP server because of the ModifyDn messages.  How am I supposed to do this?  Should the modify_dn code somehow track who's holding data and update their CN and DN (that sounds far-fetched)?  Should I just make those changes in both places (through `entry.cn` and a `modify_dn()` call)?

**Comment by cannatag** [comment]
Hi, in the abstraction layer when you have to change the "naming attribute" you have to use the ``entry.entry_move()`` (for moving the entry in a different context) and ``entry.entry_rename()`` (for renaming the entry) methods because the ObjectDef doesn't know what is the attribute used in the distinguishedName.

So, in your example instead of ``w.connection.modify_dn(w[12].distinguishedName.value,'CN=Joe Pesci')`` you should use ``w[12].entry_rename('cn=Joe Pesci,ou=...')`` and then commit the changes in the cursor.

Let me know if this fix your issue.

Bye,
Giovanni
