### ISSUE TITLE
Log file in sibling dir doesn't fill

### ISSUE THREAD

**Issue by TcaManager** [cannatag/ldap3#717]
Hi,
In my configuration, I use this code.
* file MyPackage/tests/test.py
```python
from config.settings import LOG_FILE
import logging
logging.basicConfig(filename=LOG_FILE, level=logging.CRITICAL)
from ldap3.utils.log import set_library_log_activation_level,set_library_log_detail_level, EXTENDED
set_library_log_activation_level(logging.CRITICAL)  # ldap3 will emit its log only when you set level=logging.CRITICAL in your log configuration
set_library_log_detail_level(EXTENDED)
```
The rest of that script contains actions on a OpenLdap Dir that works perfectly.
* file MyPackage/config/settings.py
```python
import os
SETTINGS_DIRECTORY = os.path.dirname(os.path.realpath(__file__))
ROOT_DIRECTORY = os.path.abspath(os.path.join(SETTINGS_DIRECTORY, os.pardir))
LOG_DIRECTORY = os.path.join(ROOT_DIRECTORY,'log')
LOG_FILE = os.path.join(LOG_DIRECTORY,'client_application.log')
```
What is strange here, is that logging works perfectly if I let the log file in the same dir as test.py, but as soon as I use this code to move the log file into another dir, it doesn't fill up anymore, though the script is still working and actions performed on the OpenLdap server.

Any idea what I did wrong? Is it impossible to move the log file in a dedicated directory? Thanks for your answers, and for that awesome package.

**Comment by cannatag** [comment]
Hi, do you still have this problem?

**Comment by TcaManager** [comment]
Something changed? Do I need to upgrade the package? Thanks anyway, sorry for answering so late, I was on vacation

**Comment by cannatag** [comment]
Sorry, I didn't mean to close this issue! I was workin on another one. Are you sure you have the rights to write in the target directory?

**Comment by cannatag** [comment]
I've tested your code and it's logging properly. 

I've slightly modified it to run in my environment:

```
import os
SETTINGS_DIRECTORY = os.path.dirname(os.path.realpath(__file__))
ROOT_DIRECTORY = os.path.abspath(os.path.join(SETTINGS_DIRECTORY, os.pardir))
LOG_DIRECTORY = os.path.join(ROOT_DIRECTORY,'log')
LOG_FILE = os.path.join(LOG_DIRECTORY,'client_application.log')

import logging
logging.basicConfig(filename=LOG_FILE, level=logging.CRITICAL)
from ldap3.utils.log import set_library_log_activation_level,set_library_log_detail_level, EXTENDED
set_library_log_activation_level(logging.CRITICAL)  # ldap3 will emit its log only when you set level=logging.CRITICAL in your log configuration
set_library_log_detail_level(EXTENDED)
```

In the client_application.log (that resides in a different directory) I get the following:

CRITICAL:ldap3:ERROR:detail level set to EXTENDED

The path for the directory where the logging file will be stored must exist (in this case I create the "log" directory).

Can you try my code and tell me if you still have the error? 

Thanks,
Giovanni

**Comment by TcaManager** [comment]
Fixed! Thanks a lot, I close this.
