### ISSUE TITLE
Try to change Ldap attribute's value using python.

### ISSUE THREAD

**Issue by khushbooaggarwal12** [cannatag/ldap3#721]
Hello, I am trying to modify the openldap's attributes value using python, but in result I am getting False and modification in openldap is not done.

Code:
------------------------
	from ldap3 import MODIFY_ADD, MODIFY_REPLACE, MODIFY_DELETE

    server = ldap_server()
    if server:
        con = ldap3.Connection(server, dn, password)
        if (password and con.bind()):

            result = con.modify('uid=testopenldap1,ou=user,dc=auth,dc=edu',
                                {'givenName': [(MODIFY_REPLACE, ['givenname-1-replaced'])],
                                 'sn': [(MODIFY_REPLACE, ['sn-replaced'])]})
           print(result)

------------------------
Output: False

Can someone guide me how to modification can be done in openldap using python ?

**Comment by cannatag** [comment]
Hi, do you still have this problem? Can you print out the value of con.result after the unsuccessful modify operation?
