### ISSUE TITLE
Issue with Superior class in schema defined as OID not as name

### ISSUE THREAD

**Issue by ahoffm11** [cannatag/ldap3#722]
Hi,

we have some custom object classes defined in our schema and the superior class is defined as OID:
 c.server.schema.object_classes['mpipzuser']
Object class: 1.3.6.1.4.1.48081.1.2.1
  Short name: mpipzuser
  Description: MPIPZ Custom User
  Type: Auxiliary
  Superior: 2.5.6.0
  May contain attributes: 1.3.6.1.4.1.48081.1.1.1, 1.3.6.1.4.1.48081.1.1.2, 1.3.6.1.4.1.48081.1.1.3
  Extensions:
    X-ORIGIN: MPIPZ

I am trying to use ObjectDef:
person = ObjectDef(['mpipzuser'],c)

this fails with ldap3.core.exceptions.LDAPObjectError: object class '2.5.6.0' not defined in schema

also even using person as posixAccount fails when running Reader.search :
person = ObjectDef(['posixaccount'],c)
>>> person
OBJ : posixAccount
AUX : <None>
OID: posixAccount (Auxiliary) 1.3.6.1.1.1.2.0, top (Abstract) 2.5.6.0
MUST: cn, gidNumber, homeDirectory, objectClass, uid, uidNumber
MAY : authPassword, description, gecos, loginShell, userPassword
>>> q='uid: garcia'
>>> person_reader = Reader(c, person, 'dc=mpiz-koeln,dc=mpg,dc=de',q)
>>> person_reader.search()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/vdir/venvs/ams/lib/python3.7/site-packages/ldap3/abstract/cursor.py", line 620, in search
    self._execute_query(query_scope, attributes)
  File "/local/vdir/venvs/ams/lib/python3.7/site-packages/ldap3/abstract/cursor.py", line 369, in _execute_query
    self.definition._populate_attr_defs(object_class)
  File "/local/vdir/venvs/ams/lib/python3.7/site-packages/ldap3/abstract/objectDef.py", line 109, in _populate_attr_defs
    self._populate_attr_defs(sup)
  File "/local/vdir/venvs/ams/lib/python3.7/site-packages/ldap3/abstract/objectDef.py", line 119, in _populate_attr_defs
    raise LDAPObjectError(error_message)
ldap3.core.exceptions.LDAPObjectError: object class '2.5.6.0' not defined in schema

>>> person_reader
CURSOR : Reader
CONN   : ldaps://mpizldap-01.mpipz.mpg.de:636 - ssl - user: cn=xxx,dc=mpiz-koeln,dc=mpg,dc=de - not lazy - bound - open - <local: 10.1.21.23:42410 - remote: 10.1.0.64:636> - tls not started - listening - SyncStrategy - internal decoder
DEFS   : posixAccount [AUX: sambaSamAccount, perditionPopMap, shadowAccount, inetMailUser]
ATTRS  : ['authPassword', 'cn', 'description', 'gecos', 'gidNumber', 'homeDirectory', 'loginShell', 'objectClass', 'uid', 'uidNumber', 'userPassword']
BASE   : 'dc=mpiz-koeln,dc=mpg,dc=de' [SUB]
QUERY  : 'uid: garcia' [AND]
PARSED : 'uid: =garcia' [AND]
FILTER : '(&(objectClass=posixAccount)(uid=garcia))'

**Comment by ahoffm11** [comment]
Even if the class definition contains name and not OID the same issue arises with attributes defined as OID

ldap3.core.exceptions.LDAPAttributeError: invalid attribute type 1.3.6.1.4.1.48081.1.1.1

**Comment by cannatag** [comment]
Hi, can you check the code in dev? It should work now.

**Comment by ahoffm11** [comment]
Hi,
I have tested it and it seems to work, the representation is a bit funny though :

person = ObjectDef(['mpipzuser'],c)
person
OBJ : mpipzuser
AUX : <None>
OID: mpipzuser (Auxiliary) 1.3.6.1.4.1.48081.1.2.1, 2.5.6.0 (Abstract) 2.5.6.0
MUST: objectClass
MAY : 1.3.6.1.4.1.48081.1.1.1, 1.3.6.1.4.1.48081.1.1.2, 1.3.6.1.4.1.48081.1.1.3

person.NextcloudQuota
1.3.6.1.4.1.48081.1.1.3 - mandatory: False - single_value: True
  Attribute type: 1.3.6.1.4.1.48081.1.1.3
    Short name: NextcloudQuota
    Description: NC User Quota
    Single value: True
    Usage: User Application
    Equality rule: 2.5.13.5
    Syntax: 1.3.6.1.4.1.1466.115.121.1.15 [('1.3.6.1.4.1.1466.115.121.1.15', 'LDAP_SYNTAX', 'Directory String', 'RFC4517')]

query = 'NextcloudQuota: 2 TB'
person_reader.search() returns Entries like this:
P=person_reader.search()[0]
P.entry_attributes
['objectClass', '1.3.6.1.4.1.48081.1.1.1', '1.3.6.1.4.1.48081.1.1.2', '1.3.6.1.4.1.48081.1.1.3', 'uid', 'sambaSID', 'cn', 'sambaLMPassword', 'sambaNTPassword', 'sambaPwdLastSet', 'sambaLogonTime', 'sambaLogoffTime', 'sambaKickoffTime', 'sambaPwdCanChange', 'sambaPwdMustChange', 'sambaAcctFlags', 'displayName', 'sambaHomePath', 'sambaHomeDrive', 'sambaLogonScript', 'sambaProfilePath', 'description', 'sambaUserWorkstations', 'sambaPrimaryGroupSID', 'sambaDomainName', 'sambaMungedDial', 'sambaBadPasswordCount', 'sambaBadPasswordTime', 'sambaPasswordHistory', 'sambaLogonHours', 'imapHost', 'mailSendasAddress', 'authPassword', 'userPassword', 'shadowLastChange', 'shadowMin', 'shadowMax', 'shadowWarning', 'shadowInactive', 'shadowExpire', 'shadowFlag', '2.16.840.1.113730.3.1.778', '2.16.840.1.113730.3.1.692', '2.16.840.1.113730.3.1.17', 'uidNumber', 'gidNumber', 'homeDirectory', 'loginShell', 'gecos', 'mail', 'mailEquivalentAddress', 'mailHost', 'mailRoutingAddress']

so there is no oid to name translation but at least it is not throwing errors
and i can  access those by  name as well :
P.nextcloudquota
1.3.6.1.4.1.48081.1.1.3: 2 TB
P.nextcloudquota.value
'2 TB'

**Comment by cannatag** [comment]
Probably your server doesn’t return the names but only the OIDs. Can you send me the output of the connection.server.schema _to_jjson() method?

**Comment by ahoffm11** [comment]
Sent you the output via e-mail not sure if you have got it though.

**Comment by cannatag** [comment]
released in v2.6.1
