### ISSUE TITLE
How to create an user in eDirectory using ldap3 ? 

### ISSUE THREAD

**Issue by Edlopushansky** [cannatag/ldap3#723]
Hey Jovanni,

Need your help of figuring out how to modify existing AD script to work with eDirectory. 

As I understand In order to connect to eDirectory we need to change  user login email to user login dn like so:

`connection = Connection(server, 'your_user_name_dn', 'your_password')`

is it correct?

This is what I do to create user in AD:
              

```
self.c.add(dn, attributes={
                     'objectClass': 'User',
                     'userPassword': user_password,
                     'userAccountControl': ['66080'],
                     'sn': lname,
                     'description': 'Auto created with LDAP3',
                     'displayName': display_name,
                     'givenName': fname,
                     'mail': email,
                     'sAMAccountName': user_login}
```

then I confirm that user was created: 
                 
```
self.c.search(dn, '(&(objectClass=*)(sAMAccountName={}))'.format(user_login), 
                                      attributes=ALL_ATTRIBUTES)
                user_dn = str(self.c.entries[0]['distinguishedName'])
                user_guid = str(self.c.entries[0]['objectGUID'])
                user_guid = user_guid.strip('{}')
                user_first_name = str(self.c.entries[0]['givenName'])
                user_last_name = str(self.c.entries[0]['sn'])
                self.c.unbind()  # disconnects from the server
                return user_dn, user_guid, user_login, str(user_password), user_first_name, 
                user_last_name)
```

What should be changed in order to work with eDirectory?

**Comment by fpatterson55** [comment]
I am new to Python, so excuse the code. Do feel free to give any ideas on
improving it.


your code could use the input statements with something like:

import ldap3
from ldap3 import Server, Connection, ALL, Tls
from ldap3.core.exceptions import LDAPSocketOpenError


    try:
        server = Server("idv1.tscc.org", port=636, use_ssl="True")
        print('Trying LDAP Bind')
        conn = Connection(server, user="cn=admin,ou=sa,o=system",
password="NetIQ1234")
        conn.bind()
    except LDAPSocketOpenError as e:
        print("error in bind", conn.result)
    print('\n\n LDAP CONNECTION SUCCESSFUL\n --------------------------')





Hope this helps,
Fred

**Comment by Edlopushansky** [comment]
My main question was how should I modify existing script ,  for instance : add user , to work with eDirectory.

**Comment by cannatag** [comment]
Hi, eDirectory is usually simpler than Active Directory. You're right about the connection object, you have to pass the DN and the password of the admin user (usually you need admin to create users').

Creating users in eDirectory is easy, just provide the mandatory attributes: cn, sn and password. The objectclass is inetorgperson. Keep in mind that eDirectory uses ou and o as containers object and the cn as the naming attribute, so to create a user you must have a dn in the format of "cn=myuser,o=myorg', or 'cn=myusrs,ou=mydept,o=myorg'.

**Comment by Edlopushansky** [comment]
Hey Giovanni, Please help me to understand.
These are attributes I have while creating user in AD.        AD                                                  eDirectoryself.c.add(dn, attributes={
    'objectClass': 'User',                         'objectClass': 'Person'
    'userPassword': user_password,                          ?
    'userAccountControl': ['66080'],                        ?
    'sn': lname,                                        same sn
    'description': 'Auto created with LDAP3',               ?
    'displayName': display_name,                            ?
    'givenName': fname,                                     ?
    'mail': email,                                          ?
    'sAMAccountName': user_login,                           ?
    'userPrincipalName': '@'.join(['.'.join                 ? ([fname.lower(), lname.lower()]), self.domain])})
What are the corresponding attributes in eDirectory?How to retrieve GUID  ? 
    On Friday, August 9, 2019, 12:21:23 PM PDT, Giovanni Cannata <notifications@github.com> wrote:  
 
 
Hi, eDirectory is usually simpler than Active Directory. You're right about the connection object, you have to pass the DN and the password of the admin user (usually you need admin to create users').

Creating users in eDirectory is easy, just provide the mandatory attributes: cn, sn and password. The objectclass is inetorgperson. Keep in mind that eDirectory uses ou and o as containers object and the cn as the naming attribute, so to create a user you must have a dn in the format of "cn=myuser,o=myorg', or 'cn=myusrs,ou=mydept,o=myorg'.

**Comment by Edlopushansky** [comment]
These attribute I've got from AD user ( attachment AD)  and from eDir user ( attachment eDir). AD is very visual and easy to see all attributes compared to eDir.

    On Monday, August 12, 2019, 10:55:37 PM PDT, Eduard Lopushansky <eduard_l@ymail.com> wrote:  
 
  Hey Giovanni, Please help me to understand.
These are attributes I have while creating user in AD.        AD                                                  eDirectoryself.c.add(dn, attributes={
    'objectClass': 'User',                         'objectClass': 'Person'
    'userPassword': user_password,                          ?
    'userAccountControl': ['66080'],                        ?
    'sn': lname,                                        same sn
    'description': 'Auto created with LDAP3',               ?
    'displayName': display_name,                            ?
    'givenName': fname,                                     ?
    'mail': email,                                          ?
    'sAMAccountName': user_login,                           ?
    'userPrincipalName': '@'.join(['.'.join                 ? ([fname.lower(), lname.lower()]), self.domain])})
What are the corresponding attributes in eDirectory?How to retrieve GUID  ? 
    On Friday, August 9, 2019, 12:21:23 PM PDT, Giovanni Cannata <notifications@github.com> wrote:  
 
 
Hi, eDirectory is usually simpler than Active Directory. You're right about the connection object, you have to pass the DN and the password of the admin user (usually you need admin to create users').

Creating users in eDirectory is easy, just provide the mandatory attributes: cn, sn and password. The objectclass is inetorgperson. Keep in mind that eDirectory uses ou and o as containers object and the cn as the naming attribute, so to create a user you must have a dn in the format of "cn=myuser,o=myorg', or 'cn=myusrs,ou=mydept,o=myorg'.
