### ISSUE TITLE
Retrieve results in batched fashion for LDAP server wihtout paging support

### ISSUE THREAD

**Issue by JerryPan** [cannatag/ldap3#725]
Hi,
I am exploring the wonderful library for production use, It has been amazing in all aspect but I encountered an issue that I can not solve and hoping you can give me some guidance.

The issue: if a server does not support paging, I could not figure out a way to retrieve my search result one record at a time. I want to do that  because client needs to batch processing the result due to memory constraints,  I used to use the python ldap lib and it can do it that way, so I figure there might be a way to do that in your library

I would greatly appreciate any help or pointer you may offer.

Thanks, and thank you for the fantastic library you have created!

**Comment by cannatag** [comment]
Hi Jerry, regarding your question If the server doesn’t support the paged search the only other solution I know is the range option in the search operation. This is usually used in AD because it returns only 1500 entries in a search operation. I’m not sure if this is what you used with the python-ldap library, can you give me some code samples or a link to the relevant python-ldap documentation?

Thanks for evaluating ldap3!
Giovanni

**Comment by JerryPan** [comment]
Hi Giovanni,

First thanks so much for your quick reply. I did not know there is a ranged
API, how does that work?

here is the code I am using with the standard search operation:

First I connect as like below:

connection = ldap3.Connection(
    server,
    user=bind_dn_str,
    password=password_str,
    read_only=True,
    auto_bind=ldap3.AUTO_BIND_TLS_BEFORE_BIND,
    client_strategy=self.ldap_strategy, # tried both ldap3.ASYNC,
SYNC, ASYNC_STREAM
    receive_timeout=RECEIVE_TIMEOUT

Then I search like below (for the case of ASYNC)

handle = conn.search(
    search_base=search_base,
    search_filter=search_filter,
    search_scope=ldap3.SUBTREE,
    attributes=ldap3.ALL_ATTRIBUTES,
    size_limit=size_limit
)

resp_data, resp_type = conn.get_response(handle, timeout=RECEIVE_TIMEOUT)

the problem is that one call above returned all data in resp_data, which is
where I wish to have an API to fetch one at a time or like you said, fetch
a range and go next range.  The particular server I am testing with does
not support page (I need to support for that case) and when it has over
several hundreds of thousand records (like over 100k), my client env can
not handle it.


Thanks for any help!
-Jerry

**Comment by cannatag** [comment]
Hi, do you have the code that works with python-ldap?

**Comment by JerryPan** [comment]
Yes, as below. I put it in a while loop to retrieve the results and when
reach my locally set limit I dump it to db and clean the buffer and
continue. The retrial line is:

restype, rdata = self.conn.result(msgid=msgid, all=all, timeout=self.timeout)

and the body of the program  (search and retrieval) is in a while look like:

batch_size = self._get_batch_size()
record_count = 0
try:
    # Return all attributes which you have permissions to access
    msgid = self.conn.search_ext(search_base_dn, ldap.SCOPE_SUBTREE,
search_filterstr,
                                 attrlist=search_attrlist, sizelimit=sizelimit)
except ldap.LDAPError as e:
    qpylib.log("LDAP search failed: %s" % e, "error")
    raise e

# If we have a sizelimit, we'll get results one by one so that we
# can stop processing once we've hit the limit.
# all - as long as none 0, the search result will get the entire
result set, so has to be 0 for mem consideration
all = 0 if sizelimit else 1
batch_data_to_upload = []
batches = 0
qpylib.log("Retrieving LDAP search result and processing with batch
size {0}".format(batch_size))
while True:
    try:
        restype, rdata = self.conn.result(msgid=msgid, all=all,
timeout=self.timeout)
    except ldap.SIZELIMIT_EXCEEDED:
        # size limit exceeded, process what we have and break out
        current_size = len(batch_data_to_upload)
        if current_size > 0:
            processor.process(batch_data_to_upload)
            record_count += len(batch_data_to_upload)
        break
    if not rdata or rdata == []:
        # in case API does not raise SIZELIMIT_EXCEEDED, process what
we have and break out
        current_size = len(batch_data_to_upload)
        if current_size > 0:
            processor.process(batch_data_to_upload)
            record_count += len(batch_data_to_upload)
        break
    if restype == ldap.RES_SEARCH_ENTRY:
        batch_data_to_upload += rdata
        current_size = len(batch_data_to_upload)
        if processor and current_size >= batch_size:
            processor.process(batch_data_to_upload)
            record_count += current_size
            batches += 1
            del rdata
            batch_data_to_upload = []
    elif restype == ldap.RES_SEARCH_RESULT:
        break

    if sizelimit and record_count >= sizelimit:
        self.conn.abandon_ext(msgid)
        break

    sleep(SLEEP_TIME_NO_PAGING)

**Comment by JerryPan** [comment]
Also, you mentioned possibility of an range parameter in the API, could you
explain?

Thanks!

**Comment by cannatag** [comment]
Range is only for multi value attribute, for example if you have a group with thousands of members the server can send them in multiple responses. I’m not sure that you need this.

Looking at the code you sent I see that the only difference is that the python-ldap code uses an asynchronous search, and maybe it returns the entries while it is receiving  the response messages from the servers.

Have you tried with the ASYNC strategy in LDAP3?

**Comment by JerryPan** [comment]
Yes I was using the ASYNC strategy.  I get the returned handle of the
search and then call get response.  Is it possible, or if easy to expose
the internal API in ldap3 to do similar thing as in python ldap library?
 anyways my code for search - retrieval is as below, which I can see for
large records, without paging, it accumulates all the records in memory. I
was hoping there is an API to fetch records in stream fashion

record_count = 0
handle = conn.search(
    search_base=search_base,
    search_filter=search_filter,
    search_scope=ldap3.SUBTREE,
    attributes=ldap3.ALL_ATTRIBUTES,
    size_limit=size_limit
)

resp_data, resp_type = conn.get_response(handle, timeout=RECEIVE_TIMEOUT)

**Comment by cannatag** [comment]
Hi, I've been working on this. Can you try the following code with the dev repository?

```
from ldap3 import Connection, ASYNC_STREAM
c = Connection('myserver', 'cn=admin,o=resources', 'password', client_strategy=ASYNC_STREAM, pool_size=8)
c.bind()
p = c.extend.standard.funnel_search('o=test', '(cn=*)', attributes=['cn', 'sn'], streaming=False)
for entry in p.funnel(block=True):
    print(entry)
c.unbind()
```
This code should create a queue of 8 entries when performing the searches. Each time you make an entry pass in the "funnel" it gets removed from the queue and another one is put in the queue.

You can change the queue size with the pool_size option of the Connection object. This search cannot follow referrals or perform an auto-range on members group, but should work as a normal search. At the end of the search you get a "searchResultDone" entry type that usually contains "success" even if no entries are found. If you have an error in the search the last entry contains the error. The search runs in an asynchronous thread, so it's a quite harder to debug.

This should effectively limit the memory usage of the python app. Let me know if this is good for your use-case.

Bye,
Giovanni

**Comment by JerryPan** [comment]
That is awesome,  Thanks.  I will test it in next couple

**Comment by cannatag** [comment]
released in v2.6.1, but still not documented. Let me know if this works for you.

**Comment by JerryPan** [comment]
Thanks very much. I will test it.

I have a side question, What is the benefit using ASYNC strategy, when
using paged search with generator, would it be better with SYNC or ASYNC?

Thanks again

**Comment by cannatag** [comment]
Because the “funnel” works as a pipeline to the server and this is best done with the async strategy (as for persistent search). I’ve tried to adapt the SYNC strategy to this pattern but it is more difficult because there should be two generators, one for each block of packets received and one for the entries returned. Also the SYNC strategy waits internally for all entries returned to perform some additional checks (mainly creating the result variable) while the ASYNC returns each entry as soon as it appear over the wire.

Let me know if this works for you. If you find it useful I will update the public docs.

Bye,
Giovanni

**Comment by cannatag** [comment]
To be clear, ASYNC_STREAM is the strategy that returns each ldap message as it is received, and is used in the “persistent search” that is a kind of log of the performed operations. The ASYNC strategy waits for receiving all message, as the SYNC one, but is not blocking because it runs in another thread.

**Comment by JerryPan** [comment]
I want to know which strategy to use in case of Paged Search (when server
supports it) - I want to limit memory consumption. Should I use
ASYNC_STREAM, or ASYNC?  Or if SYNC is ok too?
For none-paged I guess needs to be ASYNC_STREAM, right?

Thanks again,
-Jerry

**Comment by cannatag** [comment]
The funnel works only with the ASYNC_STREAM. You should open a connection specific for this operation as in the code sample.

**Comment by JerryPan** [comment]
Got it, thanks.
I have a different question, I notice in paged search, if last page is less
than the paged size, it will not be returned. I am using 2.6.0, does 2.6.1
have that fixed?

**Comment by JerryPan** [comment]
Hi Giovanni, thanks for all the good work
ON test funnel results:  works but many duplicates returned:  I used pool
size of 8, and when I pull from a test server with size limit ==1000, I
only get 7 unique users (dn) back, the rests are duplicates.
Please advise.

Also my previous question, it was on paged search not non-paged with funnel
- I was asking when paged, should I use SYNC or ASYNC, which one is better.
thanks

-Jerry

**Comment by cannatag** [comment]
Hi Jerry. sorry for not answering before. I don't get any duplicates in the "funnel" response. Can you try the following code witht the code in dev?

```
from ldap3 import Connection, ASYNC_STREAM

MY_SERVER = 'server'
MY_USER = 'user'
MY_PASSWORD = 'password'
BASE = 'o=test'

c = Connection(MY_SERVER, MY_USER, MY_PASSWORD, client_strategy=ASYNC_STREAM, pool_size=5)
c.bind()
p = c.extend.standard.funnel_search(BASE, '(objectClass=*)', attributes=['objectClass'])
t = set()
for i, entry in enumerate(p.funnel(block=True), 1):
    if entry['type'] == 'searchResEntry':
        t.add(entry['dn'])
        print(i, entry['dn'])
c.unbind()
print('Different DNs:', len(t))
```

You get a list of the entries returned and the total number of different DN. In my tests this numbers match.

For the paged search I suggest to use the SYNC strategy because it doesn't use threads.
