### ISSUE TITLE
Names with ß not returned correctly

### ISSUE THREAD

**Issue by marcosfreccia** [cannatag/ldap3#728]
Hello,

I have few names in my Active Directory that contain this special German character **ß**, which when my application queries it, it returns something like this.

`Mu\xdfler`, where in my AD it shows `Mußler`

Strange enough, in my local laptop with the when I execute the same function call, I get the correct name `Mußler`.

Would you have any tips on what it could possibly be?

**Comment by cannatag** [comment]
Probably you have different encodings on different machines. ldap3 can handle different "streams" of data with different encodings at the same time, have a look at https://ldap3.readthedocs.io/encoding.html

Bye,
Giovanni

**Comment by marcosfreccia** [comment]
That's what I thought as well, but I was checking and both my local machine and the PROD Server are using `utf-8` encoding. So, I was thinking this is something else.

I will keep searching for a solution.

**Comment by cannatag** [comment]
There are various place where you can set the encoding. are you sure that the terminal and the python interpreter are using the utf-8 (Unicode) encoding? Also the file system has its own encoding, at least for the file name representation. It’s quite hard to find the right place to fix this problem.

Also, python 3 and Python 2 treat encoding in a totally different way. ldap3 works well with both.  Have you tried your code with both versions?

Giovanni
