### ISSUE TITLE
Add support for bulk modify and delete operations

### ISSUE THREAD

**Issue by TcaManager** [cannatag/ldap3#729]
Would it be possible and good, to make bulk operations for modify and delete operations? I have no idea how heavy the new code would be. Thanks.

**Comment by cannatag** [comment]
Hi, bulk operations are not defined in the LDAP standard. Usually an LDAP server has some utility to perform bulk operation, probably from LDIF files.

**Comment by TcaManager** [comment]
Ok, it means I can only do this by generating LDIF files and perform operations by calling such an utility with subprocess or sh package. Thank you. I close the question.

**Comment by TcaManager** [comment]
One thing I don't get is that Writer cursor in abstraction layer does performs bulk operations, doesn't it? If not, it runs an ldap command for each entry?

**Comment by cannatag** [comment]
Yes, the Abstraction Layer "hides" the real LDAP operations, when you modify multiple entries a modify operation is generated for each entry that is changed.

**Comment by TcaManager** [comment]
Just to be sure, when I look at the LDIF part of ldap3 docs, I see I can get the output as LDIF when I do operations (modify, add, delete) on a connection.
Does it mean that I can put this operations in a ldif file without executing those?
Would it be better performance (faster) solution to generate an ldif file with the ldif output stream than executing add, delete or modify methods on a connection?

**Comment by cannatag** [comment]
You can create an ldif file with all the modifications you need and then you can use some utility of your ldap server to perform the execution of the modifications. Quite surprisingly the LDAP standard specifies only the format of LDIF but doens't define an operation for "loading" entries from an LDIF file.

**Comment by TcaManager** [comment]
Yes, it works, I had to trigger ldap-tools commands using subprocess or sh. I found the sh way much better, it looks like this. The different Python functions execute ldap commands, like ldapadd, ldapdelete,ldapmodify and return 4 vars about result, c,r,o,e,t.
- c is the name of the triggered command
- r is the result code, 0 if everything worked fine, it's an int
- o is a string, it's the output of the triggered command
- e is a string too, it's the error of the triggered command
- t is the time it took to run the command

Of course args passed to each function is standard args host,port,admin_dn,password,ldif_file_path

- host is the ldap host
- port is the port of the ldap host
- admin_dn is the dn used for the connection
- password is the password of this dn
- ldif_file_path is the os path of the ldif file

```python
import sh
    
def get_command(cmd):
    return sh.Command(cmd)

def ldap_add(host,port,admin_dn,password,ldif_file_path):
    try:
        t0 = time()
        ldapadd = get_command('ldapadd')
        p = ldapadd('-x','-w', password, '-h',host,'-p',port,'-D',admin_dn,'-f',ldif_file_path)
        p.wait()
        c = p.cmd
        r = p.exit_code
        o = p.stdout
        e = p.stderr
        t1 = time()
        t = t1-t0
    except:
        c = 'ldapadd'
        r = -1
        o = None
        e = None
        t = None
    return c,r,o,e,t

def ldap_delete(host,port,admin_dn,password,ldif_file_path):
    try:
        t0 = time()
        ldapdelete = get_command('ldapdelete')
        p = ldapdelete('-x','-w', password,'-h',host,'-p',port,'-D',admin_dn,'-f',ldif_file_path)
        p.wait()
        c = p.cmd
        r = p.exit_code
        o = p.stdout
        e = p.stderr
        t1 = time()
        t = t1-t0
    except:
        c = 'ldapdelete'
        r = -1
        o = None
        e = None
        t = None
    return c,r,o,e,t

def ldap_modify(host,port,admin_dn,password,ldif_file_path):
    try:
        t0 = time()
        ldapmodify = get_command('ldapmodify')
        p = ldapmodify('-x','-w', password,'-h',host,'-p',port,'-D',admin_dn,'-f',ldif_file_path)
        p.wait()
        c = p.cmd
        r = p.exit_code
        o = p.stdout
        e = p.stderr
        t1 = time()
        t = t1-t0
    except:
        c = 'ldapmodify'
        r = -1
        o = None
        e = None
        t = None
    return c,r,o,e,t
```
