### ISSUE TITLE
Abstraction Layer Writer Cursor writes multiple values attributes as string

### ISSUE THREAD

**Issue by TcaManager** [cannatag/ldap3#730]
Hi, I use a list of dicts to write many users in a ldap.
Users both have multiple value attributes.
Everything works fine except that the multiple value attribute is stored as a string in the DSEE 7 LDAP Directory.
Any Idea why? Is it a DSEE 7 problem?
Here is the code, the multiple attribute is  "FrEduRneResp":
```
bozo = {
    'uid':'bleclown',
    'FrEduAca': 'ac-caen',
    'givenName':'Bozo',
    'sn':'Le Clown',
    'cn':'Bozo Le Clown',
    'userPassword':hashed(HASHED_SALTED_SHA, 'Oulalalalalalalala!'),
    'FrEduRneResp': ['aaaaa','bbbbbb']
}

agathe = {
    'uid':'atheblues',
    'FrEduAca': 'ac-aix-marseille',
    'givenName':'Agathe',
    'sn':'The Blues',
    'cn':'Agathe The Blues',
    'userPassword':hashed(HASHED_SALTED_SHA, 'OhYeah!'),
    'FrEduRneResp': ['eeeee','fff']
}

entries = [bozo,agathe]

#connection and object definition depend on your schema
writer = Writer(connection,objDef)
for entry in entries:
    e = writer.new('uid=%s,ou=people,o=machin,c=fr' % (entry['uid']))
    for k,v in entry.items():
        e[k] = v
writer.commit()
```

**Comment by cannatag** [comment]
Hi, I've tested your code in my lab (adapted to a different kind ldap server) and the multivalue attributes are stored as 2 different values. Are you sure that the FrEduRneResp attribute is tagged as Multivalued?

**Comment by TcaManager** [comment]
Ok, I have to check this. In DSEE 7 we only tag single value attributes, if we don't the attribute is considered multi value, as a default behaviour. Thanks.
