### ISSUE TITLE
persistent_search and paged results

### ISSUE THREAD

**Issue by ebourgeois** [cannatag/ldap3#732]
Hi,

We have an LDAP server (OpenLDAP) that has size limits on our searches and I am trying to leverage the persisted_search function, however, I keep hitting `sizeLimitExceeded` (even when I set `size_limit=10`, e.g.).

Is there a way to combine` .standard.PagedSearch` and `.standard.PersistentSearch`?

**Comment by cannatag** [comment]
Hi, in openldapthe search limit is global, in paged search the limit is relevant to all the entries in the search result, not in the singl search page. I don’t think that persistent search is available in openldap. 

Have you tried to limit the search filter? Maybe you can get all the empntries with multiple searches.
