### ISSUE TITLE
Abstraction layer doc is lacking examples for new objects

### ISSUE THREAD

**Issue by bfleming-ciena** [cannatag/ldap3#734]
I'm horrible at coming up with my own code without examples.  I wanted to use the abstraction layer, but it's unclear to me how to create a brand new object...  Like a new group.

I was able to easily create new groups using the standard model of ldap3.  I thought I could simplify my code using the abstraction layer, but turns out it's harder for me to use the abstraction layer due to the lack of examples.

Thanks!!!

**Comment by cannatag** [comment]
Ok, I'll work on this!

**Comment by stonefury** [comment]
Oh, thank you so much!  I've been struggling to figure this out.  If I just had an example on how to create a new group I think that would be a huge help.  Without the abstraction it's still pretty easy as long as you know how to create the dn. I just use add().

Anyway, will be great. Thank you.

**Comment by cannatag** [comment]
This is a quick and dirty example of how to create a group with members. In this case I create a group named "cn=grp6,ou=fixtures,o=test" that includes all members in the 'ou=fixtures,o=test' context:
```
from ldap3 import Connection, Writer, Reader
c = Connection('myserver', 'cn=admin,o=resources', 'password')
r = Reader(c, 'inetorgperson', 'ou=fixtures,o=test')
r.search()
members_to_add = [entry.entry_dn for entry in r.entries]

w = Writer(c, 'groupOfNames')
g = w. new('cn=grp6,ou=fixtures,o=test')
g.member = members_to_add
w.commit()
```

"members_to_add" is just a list of strings, you don't need the Reader cursor if you already know the dn of the members to add.

Keep in mind that different LDAP servers can have different schema for the "groupOfNames" objectClass and if they strictly follow the LDAP RFCs they prohibit the creation of a group with no members.

Hope this helps.
