### ISSUE TITLE
client strategy SYNC confusion

### ISSUE THREAD

**Issue by stonefury** [cannatag/ldap3#735]
Probably misunderstanding this.

I thought client_strategy=SYNC means the object is created and the routine will not return until the object exists?

If that isn't true, then what's the recommended way to wait for an object to exist? I can't create a group and immediately set attributes.

Thanks for any ideas.

**Comment by cannatag** [comment]
Hi, this is not a simple question. The sync strategy ensure that the operation methods return only when the server “states” that the operation is completed. What this means is completely up to the server, what is really done by the server is not known to the ldap3 library. Maybe it uses a cache or a queue or there are other servers that must be synchronized, so the data is not immediately available, but you need to wait for a few seconds. This is usually not a problem with ldap operations like searches (that actually return the found entries) or with creation and  modification that you fire-and-forget but if you need to immediately access a just created or modified entry you must check that it exists and contains the needed data with a search operation. If you must be sure that a created or modified data is available I suggest to use a loop in your code after the operation method (with some delay, one second should suffice) that exits when the object is found or after a reasonable timeout.

Bye,
Giovanni

**Comment by stonefury** [comment]
@cannatag very helpful and excellent description. Thank you very much.
