### ISSUE TITLE
tls not starting

### ISSUE THREAD

**Issue by jonmannn** [cannatag/ldap3#738]
I am establishing a connection to an Active Directory server that uses a self signed CA certificate and TLS does not seem to start. Here's how I'm establishing the connection:

```
SSL_CERT_PATH = 'certificate.pem'

tls_configuration = Tls(ca_certs_file=SSL_CERT_PATH, version=ssl.PROTOCOL_TLS, validate=ssl.CERT_REQUIRED)

server = Server(host='pdc.sub-domain.example.com', use_ssl=True, tls=tls_configuration)
conn = Connection(server, 'CN=test.user,OU=Users,DC=sub-domain,DC=example,DC=com', "password", auto_bind=AUTO_BIND_TLS_BEFORE_BIND, raise_exceptions=True)

print(conn)
```

I receive the following output, indicating that although it's an SSL connection, TLS is not started:
```
ldaps://pdc.sub-domain.example.com:636 - ssl - user: CN=test.user,OU=Users,DC=sub-domain,DC=example,DC=com - not lazy - bound - open - <local: x.x.x.x:52229 - remote: x.x.x.x:636> - tls not started - listening - SyncStrategy - internal decoder
```

Do you happen to spot anything configuration that could be causing the issue? Or is this perhaps a bug?

**Comment by cannatag** [comment]
You’re doing it right. Opening the connection on port 636 with use_ssl=True use an ssl socket from the very beginning. Instead if you open a connection on an insecure port (usually 389) and then you want to “upgrade” the connection to ssl you must use the start_tls() method.

The tls not started message refers to the second case.

Bye,
Giovanni

**Comment by jonmannn** [comment]
Thank you for the response @cannatag 

Being that I am opening the connection on port 636 is it possible to start the connection with TLS enabled instead of SSL? I know the terms are sometimes used interchangeably but I'd like to ensure I am using the TLS protocol for the most effective security. 

I've found that even if I use the start_tls() method that the output still displays 'tls not started' (although I'd expect to not need to do this since my connection is starting on port 636).

**Comment by cannatag** [comment]
Ssl and tls are just the terms used by the ldap protocol. What is really used as security protocol is defined by the operating system.

If you open the connection with use_ssl=True the connection is established by the operating system with the latest tls version available.

**Comment by jonmannn** [comment]
Just to confirm. Although the output is stating 'tls not started', this is not necessarily true?

**Comment by cannatag** [comment]
Tls not started means that the start_tls() method has not been issued. But this is useless if the connection Is already secure.

**Comment by jonmannn** [comment]
@cannatag I am still receiving that message even if issuing the start_tls() method. Here is that complete code block:
```
SSL_CERT_PATH = 'certificate.pem'

tls_configuration = Tls(ca_certs_file=SSL_CERT_PATH, version=ssl.PROTOCOL_TLS, validate=ssl.CERT_REQUIRED)

server = Server(host='pdc.sub-domain.example.com', use_ssl=True, tls=tls_configuration)
conn = Connection(server, 'CN=test.user,OU=Users,DC=sub-domain,DC=example,DC=com', "password", auto_bind=AUTO_BIND_TLS_BEFORE_BIND, raise_exceptions=True)
conn.start_tls()

print(conn)
```

**Comment by cannatag** [comment]
A socket can be “wrapped” in a secure connection only once. So if you open the connection with use_ssl=True then the starl_tls() operation doesn’t do anything because the connection is already secure.
