### ISSUE TITLE
ldap3.core.exceptions.LDAPInvalidDnError: character ' ' not allowed in attribute type

### ISSUE THREAD

**Issue by jpyams** [cannatag/ldap3#739]
In v2.6.1, calling `Connection.search()` with a space (` `) in the DN gives an `LDAPInvalidDnError`.  In v2.6 `Connection.search()` returns the expected result.

```
>>> conn.search('uid=USERNAME, ou=employees, o=example.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.7/site-packages/ldap3/core/connection.py", line 735, in search
    search_base = safe_dn(search_base)
  File "lib/python3.7/site-packages/ldap3/utils/dn.py", line 351, in safe_dn
    for component in parse_dn(dn, escape=True):
  File "lib/python3.7/site-packages/ldap3/utils/dn.py", line 315, in parse_dn
    if not _validate_attribute_type(attribute_type):
  File "lib/python3.7/site-packages/ldap3/utils/dn.py", line 179, in _validate_attribute_type
    raise LDAPInvalidDnError('character \'' + c + '\' not allowed in attribute type')
ldap3.core.exceptions.LDAPInvalidDnError: character ' ' not allowed in attribute type
```

**Comment by ShubhamKhandare** [comment]
https://tools.ietf.org/html/rfc4514

**Comment by ShubhamKhandare** [comment]
[RFC LDAP: Distinguished Names Link](https://tools.ietf.org/html/rfc4514#page-13)
Whitespace in DN string is not advised.

**Comment by jpyams** [comment]
@ShubhamKhandare that may be, but it worked up to and including v2.6.  I don't know if ldap3 follows semantic versioning, but it is concerning when breaking changes occur in a bugfix version.

**Comment by ShubhamKhandare** [comment]
@jpyams  Not really sure , they must have changed in ldap3 !
Currently https://github.com/cannatag/ldap3/blob/master/ldap3/utils/dn.py#L177
it is not supporting spaces and it should not as per RFC !

**Comment by ShubhamKhandare** [comment]
@jpyams  I think you should close this ticket !

**Comment by jpyams** [comment]
> @jpyams Not really sure , they must have changed in ldap3 !

If you're not sure, you should test the package before commenting.  ldap3 version 2.6 supports it.  It breaks in ldap3 version 2.6.1.

**Comment by cannatag** [comment]
HI, sorry for answering late. ldap3 was supposed to strictly follow the RFCs for the LDAP protocol. These RFCs states that spaces must be escaped in the DN. For a bug in the code this was not happening and version 2.6.1 fixed it. 

I understand your disappointment if you think that this requirement should be relaxed I could include a global config for allowing spaces in DN, defaulting to False. So you could achieve the previous behavior setting it to True.

Let me know if you need it.

Bye,
Giovanni

**Comment by jpyams** [comment]
Thanks for the clarification, @cannatag.  If this behavior is considered a bug that got fixed, I understand that.

If the spec says there should be no spaces, I can just run a `.replace(' ', '')` whenever I use the DNs.

**Comment by cannatag** [comment]
Please be advised that the space is not allowed only in the attribute name non in the value of the attribute. If you use ``replace(' ','')`` on the whole DN you'll probably will change the value too. For example ``cn=user,o=main organization' is a valid DN, while 'cn=user, o=organization' is not valid.
There are some helper function in the ldap3.utils.dn namespace to handle DN. For example you should use the parse_dn(dn, strip=True):

```
from ldap3.utils.dn import parse_dn

def validate_dn(dn):
    elements = parse_dn(dn, strip=True)
    valid_dn = ''
    for attribute_name, value, separator in elements:
        valid_dn += attribute_name + '=' + value + separator
    return valid_dn

print(validate_dn(' cn=John Smith,o=Main organization'))
print(validate_dn('cn =John Smith,o=Main Organization'))
print(validate_dn(' cn =John Smith,o=Main organization'))
print(validate_dn('cn=John Smith,o =Main organization'))
print(validate_dn('cn=John Smith, o=Main organization'))
print(validate_dn('cn=John Smith, o =Main organization'))
print(validate_dn(' cn =John Smith,  o =Main organization'))
```
The ``validate_dn(dn)`` parses the DN and strips any leading or trailing space in the attribute name, but not in the value.

Let me know if this helps

Bye,
Giovanni

**Comment by Nedmon12** [comment]
> [RFC 4514 LDAP: Distinguished Names](https://tools.ietf.org/html/rfc4514#page-13) Whitespace in DN string is not advised.

Yeah man my issue was that, thank you man i appreciate the nudge in the right direction

**Comment by cannatag** [comment]
Attribute type name cannot have a space, usually they follow the CamelCase rule, for example GivenName or EmployeeType. What is your query?Il giorno 24 mar 2023, alle ore 09:59, Nedmon12 ***@***.***> ha scritto:﻿

RFC 4514 LDAP: Distinguished Names Whitespace in DN string is not advised.

Yeah man my issue was that, thank you man i appreciate the nudge in the right direction
