### ISSUE TITLE
Enabling user cant change password permission using ldap3

### ISSUE THREAD

**Issue by iamshanmukha** [cannatag/ldap3#743]
Hi team,

I am using ldap3 module to create user in AD and resetting password. I want user not to change his password. But I am unable to do so.

Please let me know to do it using ldap3 module.

**Comment by cannatag** [comment]
This is something specific to AD, not to the ldap3 library. Have a look at this document from Microsoft: https://docs.microsoft.com/it-it/windows/win32/adsi/modifying-user-cannot-change-password-ldap-provider that explains how to change this setting via ldap.
