### ISSUE TITLE
ldap3 Active Directory server with the NTLM v2 protocol

### ISSUE THREAD

**Issue by DeanRother** [cannatag/ldap3#744]
I'm getting the following error.  I'm following the code example from https://ldap3.readthedocs.io/tutorial_intro.html (#Accessing Active Directory: with ldap3 you can also connect to an Active Directory server with the NTLM v2 protocol:).  Is there a dependency I need to install? 

Traceback (most recent call last):
  File "ActiveDirectoryQuery.py", line 50, in <module>
    main(sys.argv)
  File "ActiveDirectoryQuery.py", line 30, in main
    queryad_secure()
  File "ActiveDirectoryQuery.py", line 25, in queryad_secure
    conn = Connection(server, user=usr, password=_pwd, authentication=NTLM)
NameError: name 'NTLM' is not defined

**Comment by cannatag** [comment]
Probably the example is missing the import statement. You must import NTLM from the ldap3 package:

from ldap3 import NTLM

at the beginning of your .py file.

Let me know if this fix your problem. 

Bye,
Giovanni

**Comment by DeanRother** [comment]
That solved it.  Thank you.
________________________________
