### ISSUE TITLE
simplified query does not work with DN syntax attribute

### ISSUE THREAD

**Issue by hamano** [cannatag/ldap3#745]
Hi.
I tried simplified query with DN ayntax. ex:

"memberDN: cn=user,dc=example,dc=com"

but the query transtated to ldap filter '(memberDN=cn=user)'

In this case, expected filter is ''(memberDN=cn=user,dc=example,dc=com)"

Thank you!

**Comment by cannatag** [comment]
Hi, you have to escape the comma in the value of memberDN. Try something like:
```
from ldap3.utils.conv import escape_bytes
value = escape_bytes(bytes('cn=user,dc=example,dc=com', 'utf-8'))
filter = memberDN: ' + value
```
