### ISSUE TITLE
change OffsetTzInfo

### ISSUE THREAD

**Issue by fekoh** [cannatag/ldap3#747]
I can not figure out how to change the timezone for my query results. An example from the documentation:

>>> entry.krbLastPwdChange.values
[datetime.datetime(2016, 10, 9, 10, 1, 18, tzinfo=OffsetTzInfo(offset=0, name='UTC'))]

how would i change the results to OffsetTzInfo(offset=-2, name='Europe/Berlin')

I think it would be a great addition to the documentation to give an example (if it is even possible with ldap3)

**Comment by cannatag** [comment]
Timezone handling is quite hard with the standard Python library, I suggest you to use some additional library [(arrow,](https://arrow.readthedocs.io/en/latest/) [pendulum](https://pendulum.eustace.io/docs/)) for handling date and time objects.

Bye,
Giovanni
