### ISSUE TITLE
ldap3.extend.microsoft package -- "user must change password at next logon" 

### ISSUE THREAD

**Issue by motod** [cannatag/ldap3#754]
https://ldap3.readthedocs.io/ldap3.extend.microsoft.html

Would it be possible to add a module for "user must change password at next logon"  or is there a way to do it with the already existing modules?

**Comment by cannatag** [comment]
Sorry I don't have a lab to check AD specific features, Anyway I think it should be easy with a standard ldap operation, just set the pwdLastSet attribute to 0. (https://docs.microsoft.com/it-it/windows/win32/adsi/user-must-change-password-at-next-logon?redirectedfrom=MSDN)

**Comment by liangguo** [comment]
this function can be implimented with:
```
    changeUACattribute = {"PwdLastSet":  (MODIFY_REPLACE, ["-1"]) }
    conn.modify('CN=xxx,DC=com', changes=changeUACattribute)
    print(conn.result)
```
