### ISSUE TITLE
Regression: `ssl.SSLError` exception not raised on certificate error

### ISSUE THREAD

**Issue by jerrykan** [cannatag/ldap3#755]
I've been trying to update the version of `ldap3` used with a library of mine and seem to have hit a regression introduced in v2.5.1

This is essentially the same problem as issue #15 (with the same test cases exhibiting the problem) and seems to have been re-introduced in commit c1dd79d3850458d3f34125435da925899afebacb

**Comment by cannatag** [comment]
Hi, I've re-enabled the check for raising the exception in the single server connection. Can you check the code in dev? 
Thanks.
Giovanni

**Comment by cannatag** [comment]
Fixed in ldap3 v2.7.
