### ISSUE TITLE
ldap server certificate accessable?

### ISSUE THREAD

**Issue by cornelinux** [cannatag/ldap3#756]
Is there a way to get the actual LDAP server certificate in an LDAPS or STARTTLS connection - maybe from the tls context after doing 

~~~~python
tls_context = Tls(validate=ssl.CERT_REQUIRED,
                           version=self.tls_version,
                           ca_certs_file=self.tls_ca_file)
~~~~

This might be out of scope of ldap3, but I am looking for an easy way to actually check how long the server certificate is still valid, and if I could find the server certificate in the tls_context or somewhere else, this could be fairly easy.
Thanks a lot.

**Comment by zorn96** [comment]
once you have a connection, you can directly access the socket within the connection and get it from there
if you do
```
conn = Connection(whatever args)
conn.open()
conn.start_tls()  // necessary if not using 'ldaps' for the connection
```

then later you can do
```
conn.socket
```
to access the ssl socket and use standard python socket stuff to get the certificate
