### ISSUE TITLE
ad_modify_password to reset password, but it failed

### ISSUE THREAD

**Issue by Shylin** [cannatag/ldap3#758]
Hi guys,
 I foud in the source code,it could be reset password.
def ad_modify_password():
....
    else:  # admin users can reset password without sending the old one

when i use the method, it raise "raise LDAPAttributeError('invalid attribute type ' + attribute_name_to_check)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type unicodePwd
", and I added attribute type unicodePwd in  config.py>_ATTRIBUTES_EXCLUDED_FROM_CHECK;
it didn't raise any exception; but  it  failed;
so I print the response, it shows ''message': 'unicodePwd: attribute type undefined','

version:   ldap3==2.6

Pls tell me how to solve it, thx.

**Comment by santosshen** [comment]
ldap3 修改密码，应该使用636端口。 TSL=True  ，389端口没权限

**Comment by Shylin** [comment]
> ldap3 修改密码，应该使用636端口。 TSL=True ，389端口没权限

修改密码我弄好了，不是端口的问题；但是重置密码实现不了。
