### ISSUE TITLE
Document prevention of LDAP injection via escape_filter_chars

### ISSUE THREAD

**Issue by KevinHock** [cannatag/ldap3#759]
This is mentioned around the internet, https://www.linkedin.com/pulse/ldap-injection-django-jerin-jose

But could be more explicit in the docs, [as one person on stackoverflow stated](https://stackoverflow.com/questions/47397341/how-to-prevent-ldap-injection-in-ldap3-for-python3), 

e.g. "Make sure to call escape_filter_chars on any user input before placing it into a `.search()` call." or something like that

**Comment by cannatag** [comment]
Thanks for the reference to the excellent article. Willreference it in the ldap3 docs.
