### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by D1CED** [cannatag/ldap3#761]
The error message in ldap3/utils/conv.py to_unicode takes the type of the unconvertible object twice printing `type` or the objects metaclass instead of its actual type.

    raise UnicodeError("Unable to convert type %s to unicode: %r" % (type(obj).__class__.__name__, obj))

Either `type(obj).__name__` or `obj.__class__.__name__` should do the job.

https://github.com/cannatag/ldap3/blob/9e74a3d6dc17722c5ae6d618012eeb4a41db1836/ldap3/utils/conv.py#L75

**Comment by cannatag** [comment]
Thanks! Will fix this in the next release of ldap3.

Bye,
Giovanni

**Comment by cannatag** [comment]
Fixed in ldap3 v2.7.
