### ISSUE TITLE
Computer Objects created with ldap3 are being created with incorrect samAccountType attribute

### ISSUE THREAD

**Issue by jyothidat** [cannatag/ldap3#764]
I am trying to automate creating Computer in Active Directory and utlizing ldap3 module for that.

My Connect and then add look like following

 server = Server(ldap_server)
 conn = Connection(server, user, password, 'NONE', 3, 'SIMPLE', 'SYNC', True, True, False, False, True)
computer = conn.add(group_dn,['Computer'],  {"samAccountName" : ldap_machine_name})

While the Computer object is created in the Active Directory, it is created with an incorrect samAccountType

samAccountType 805306368 (NORMAL_USER_ACCOUNT)

This looks like a bug to me. If I create a Computer object directly it creates it with samAccountType 805306369 and if of type MACHINE_ACCOUNT

**Comment by zorn96** [comment]
I'm going to guess you're trying to automate part of the process of joining an AD domain using the ldap3 package?

This is actually something a little more AD-esque than ldap-y.
A Computer object in Active Directory is capable of also being a User object, which fulfills the case of machines in a domain that act as both a server within the domain (computer that others talk to) as well as a client within the domain (a user that talks to others over potentially kerberos and can have a userPrincipalName).
There's also some nuances around computer accounts that are created with Pre-Windows 2000 compatibility enabled (or in a domain that enables that for the entire domain) vs. accounts that are not compatible.
Here's the list of object classes set on the account for a machine that joins a domain to act as an SMB file server via "net ads join" on linux (kerberos for users to talk to it, kerberos for it to lookup info about users): _["top", "person", "organizationalPerson", "user", "computer"]_


This means that Active Directory can be fairly sensitive to how you actually create the account.
Here's how to resolve your issue. I made 2 accounts to demonstrate
```
>>> conn.add('CN=example,CN=Computers,DC=jenkins-w2k12r2,DC=dev,DC=example,DC=com', ['top', 'person', 'organizationalPerson', 'user', ], {"samAccountName" : 'exampleAccount'})
True
>>> conn.add('CN=example2,CN=Computers,DC=jenkins-w2k12r2,DC=dev,DC=example,DC=com', ['top', 'person', 'organizationalPerson', 'user', 'computer'], {"samAccountName" : 'exampleAccount2', 'userAccountControl': 69632})
True
```

then I looked up the records and printed them
```
>>> pprint(example)
[['CN=example,CN=Computers,DC=jenkins-w2k12r2,DC=dev,DC=example,DC=com',
  {'accountExpires': ['9223372036854775807'],
   'badPasswordTime': ['0'],
   'badPwdCount': ['0'],
   'cn': ['example'],
   'codePage': ['0'],
   'countryCode': ['0'],
   'dSCorePropagationData': ['16010101000000.0Z'],
   'distinguishedName': ['CN=example,CN=Computers,DC=jenkins-w2k12r2,DC=dev,DC=example,DC=com'],
   'instanceType': ['4'],
   'lastLogoff': ['0'],
   'lastLogon': ['0'],
   'logonCount': ['0'],
   'name': ['example'],
   'objectCategory': ['CN=Computer,CN=Schema,CN=Configuration,DC=jenkins-w2k12r2,DC=dev,DC=example,DC=com'],
   'objectClass': ['top', 'person', 'organizationalPerson', 'user', 'computer'],
   'objectGUID': ['e¤Æá\x94NØB¯\x0b\x1dì¹9´\x18'],
   'objectSid': ['\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00îò-86Øæ\x92Q8|\x8c\x8d\x04\x00\x00'],
   'primaryGroupID': ['513'],
   'pwdLastSet': ['0'],
   'sAMAccountName': ['exampleAccount'],
   'sAMAccountType': ['805306368'],
   'uSNChanged': ['288942'],
   'uSNCreated': ['288941'],
   'userAccountControl': ['546'],
   'whenChanged': ['20191215064512.0Z'],
   'whenCreated': ['20191215064512.0Z']}]]
>>> pprint(example2)
[['CN=example2,CN=Computers,DC=jenkins-w2k12r2,DC=dev,DC=example,DC=com',
  {'accountExpires': ['9223372036854775807'],
   'badPasswordTime': ['0'],
   'badPwdCount': ['0'],
   'cn': ['example2'],
   'codePage': ['0'],
   'countryCode': ['0'],
   'dSCorePropagationData': ['16010101000000.0Z'],
   'distinguishedName': ['CN=example2,CN=Computers,DC=jenkins-w2k12r2,DC=dev,DC=example,DC=com'],
   'instanceType': ['4'],
   'isCriticalSystemObject': ['FALSE'],
   'lastLogoff': ['0'],
   'lastLogon': ['0'],
   'localPolicyFlags': ['0'],
   'logonCount': ['0'],
   'name': ['example2'],
   'objectCategory': ['CN=Computer,CN=Schema,CN=Configuration,DC=jenkins-w2k12r2,DC=dev,DC=example,DC=com'],
   'objectClass': ['top', 'person', 'organizationalPerson', 'user', 'computer'],
   'objectGUID': ['{\x0b{~V\x14\x90N\x941kû°\x80\x96S'],
   'objectSid': ['\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00îò-86Øæ\x92Q8|\x8c\x8e\x04\x00\x00'],
   'primaryGroupID': ['515'],
   'pwdLastSet': ['0'],
   'sAMAccountName': ['exampleAccount2'],
   'sAMAccountType': ['805306369'],
   'uSNChanged': ['288949'],
   'uSNCreated': ['288948'],
   'userAccountControl': ['69632'],
   'whenChanged': ['20191215064705.0Z'],
   'whenCreated': ['20191215064705.0Z']}]]
```

setting the account controls makes the difference. when you create the account with controls specified, they'll default to 546 which notably includes "normal account"

to contrast, the record that got the sam account type you wanted has 69632 which notably includes "workstation trust account"
see: http://rajnishbhatia19.blogspot.com/2008/11/active-directory-useraccountcontrol.html for some details on these controls.
if you set the controls, you'll end up with the sam account type you want

hope this helps to understand the issues you're seeing and resolve them!
