### ISSUE TITLE
AD objectGUID conversion

### ISSUE THREAD

**Issue by bimalkharel** [cannatag/ldap3#773]
#482 

Hi,

I tried the methods in conv.py but could not figure out how to convert
FROM

objectGUID: {7d3f7bd6-820e-403f-85ea-1c913ab7a15e} 

TO

\\d6\\7b\\3f\\7d\\0e\\82\\3f\\40\\85\\ea\\1c\\91\\3a\\b7\\a1\\5e\\
(the above result was from powershell conversion routine)

Could you point me to a Linux/Python3/ldap3 solution to this

Thanks!

**Comment by cannatag** [comment]
You can use the validate_uuid_le() function in ldap3.protocols.formatters.validators:

```
>>> from ldap3.protocols.formatters.validators import validate_uuid_le
>>> print(validate_uuid_le('{7d3f7bd6-820e-403f-85ea-1c913ab7a15e}')
b'\xd6{?}\x0e\x82?@\x85\xea\x1c\x91:\xb7\xa1^'
>>> print([hex(b) for b in bytearray(v('{7d3f7bd6-820e-403f-85ea-1c913ab7a15e}'))]
['0xd6', '0x7b', '0x3f', '0x7d', '0xe', '0x82', '0x3f', '0x40', '0x85', '0xea', '0x1c', '0x91', '0x3a', '0xb7', '0xa1', '0x5e']
```

**Comment by bimalkharel** [comment]
Thanks - I tried it but am getting "NameError: name 'v' is not defined" on the hex(b) line execution

**Comment by cannatag** [comment]
Please substitute v with validate_uuid_le.
