### ISSUE TITLE
attribute '__len__' not found

### ISSUE THREAD

**Issue by bazcurtis** [cannatag/ldap3#774]
Hi,

I am not sure if this is just me or it is a bug. I am returning every computer in my AD. It seems to come back as a list, but PyCharm reports this error.

Unable to display children:Error resolving variables Traceback (most recent call last):
File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 1208, in do_it
xml.write(pydevd_xml.var_to_xml(val, k, evaluate_full_value=evaluate_full_value))
File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_xml.py", line 369, in var_to_xml
elif hasattr(v, "__len__") and not is_string(v):
File "/Users/sm/Documents/_personal files/Folder/Python/GitHub/venv/lib/python3.8/site-packages/ldap3/abstract/entry.py", line 196, in __getattr__
raise LDAPCursorError(error_message)
ldap3.core.exceptions.LDAPCursorError: attribute '__len__' not found

My code is

`
from ldap3 import Server, Connection, ALL
ad_computer_list = []  

def get_ad_computers(): 
search_domain = ('dc=uk,dc=co,dc=uk')    search_user = ('CN=Lady DAP,OU=mc_u_service_,OU=mc,DC=uk,DC=co,DC=uk')    search_password = ('password')
   
ldap_server = Server('10.0.1.2', port = 636, use_ssl = True, get_info=ALL)    
server_query = Connection(ldap_server, search_user, search_password, auto_bind=True)    
 
if server_query.bind() == True:      
server_query.search(search_domain, '(objectclass=computer)')             
computer_names = server_query.entries        
print(server_query.entries)    
else:        
server_query.search(search_domain, '(objectclass=computer)')        
computer_name = server_query.entries        
print("389: ",computer_name)
`

Sorry if this my issue and not understanding it correctly.

**Comment by cannatag** [comment]
Hi, do you have this problem if you run your code outside of PyCharm?

**Comment by bazcurtis** [comment]
I will have to try that. I have worked around it for the time being. Why would it be different outside Pycharm?

**Comment by cannatag** [comment]
Because the error is from ``File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_xml.py", line 369, in var_to_xml``. 

This is a file from the PyCharm IDE.

**Comment by mreivu** [comment]
I have the same issue and can confirm that the exception only happens when "debugging" through IntelliJ. When I hit "play" it works as expected. Is this a bug in IntelliJ? It seems like it wants to convert the data into a xml representation and fails.

**Comment by cannatag** [comment]
Thanks. This should be fixed in the next release of ldap3.

**Comment by cannatag** [comment]
Fixed in ldap3 v2.7.
