### ISSUE TITLE
AttributeError: module 'ldap3.core.connection' has no attribute 'check_names'

### ISSUE THREAD

**Issue by fziae** [cannatag/ldap3#775]
Hi There,

I'm trying to remove a group and I get this error.

my code:
ldap3.extend.microsoft.removeMembersFromGroups.ad_remove_members_from_groups(connection, 'Test 1', 'Tech', fix=True, raise_error=False)

error message:
    if connection.check_names:  # builds new lists with sanitized dn
AttributeError: module 'ldap3.core.connection' has no attribute 'check_names'

Could you please advise? Thanks

**Comment by fziae** [comment]
@cannatag Good Morning, any clue why I'm getting this error?

**Comment by cannatag** [comment]
Hi, to call the extend namespace you must create a connection object, open it and issue the extend operation:
```
from ldap3 import Connection

c = Connection('my_server', 'my_user', 'my_password')
c.bind()
c.extend.microsoft.removeMembersFromGroups.ad_remove_members_from_groups(connection, 'Test 1', 'Tech', fix=True, raise_error=False)
...
```

Can you try to adapt this example to your code?
