### ISSUE TITLE
Unclosed socket in case of LDAPBindError Exception

### ISSUE THREAD

**Issue by hrishikeshtak** [cannatag/ldap3#777]
Hi,
I am experiencing the following unexpected behavior when I am providing the wrong password or empty password for the ldap3 connection which is running as a **systemd service**.
I am using ldap3 version: **2.6.1**

> import ldap3
> server = ldap3.Server(host=myhost, use_ssl=False, get_info=ldap3.ALL)
> with ldap3.Connection(server=server, user=my_user, password=wrong_pwd, auto_bind=True) as conn:
>     # search query

The socket opened by connection object is not closed and this is running as a service so it continuously opens new socket connections.
In [connection.py](https://github.com/cannatag/ldap3/blob/master/ldap3/core/connection.py#L354) it raises LDAPBindError in the __init__ method because of that it does not enter into the __exit__ method to unbind the connection so the socket remains open.

I have checked the status of socket using the following command in the Linux environment:
> $ sudo netstat -natu | grep -i established | grep 389
> tcp        0      0 x.x.x.x:58152      y.y.y.y:389        ESTABLISHED
> tcp        0      0 x.x.x.x:58148      y.y.y.y:389        ESTABLISHED
> tcp        0      0 x.x.x.x:58140      y.y.y.y:389        ESTABLISHED
> tcp        0      0 x.x.x.x:58144      y.y.y.y:389        ESTABLISHED

And when I am running some unit test cases to check negative cases like an incorrect password or empty password, I am getting following warning message and the connection remains opened:
> ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('x.x.x.x', 57982), raddr=('y.y.y.y', 389)>

And In the case of the correct password, the connection gets closed properly.

**Comment by cannatag** [comment]
Hi, can you check the code in dev? Now connection is unbound (closed) when auto_bind fails.

**Comment by hrishikeshtak** [comment]
Thanks for the update.
Can you also check connection in case if [bind_operation](https://github.com/cannatag/ldap3/blob/5a7370618e58cede520829aa4e0d11acc0c0d360/ldap3/operation/bind.py#L36) failed, scenarios like LDAPPasswordIsMandatoryError, LDAPUserNameIsMandatoryError etc. The connection remains open as it raises an exception in init method.
And in the [exit](https://github.com/cannatag/ldap3/blob/dev/ldap3/core/connection.py#L517) method when the connection gets established and the stream is None, a scenario like LDAPInvalidValueError, the connection still remains open, as we are in __exit__ method, it should get closed right?

**Comment by cannatag** [comment]
Fixed in ldap3 v2.7.
