### ISSUE TITLE
Add operation does not document add of attribute consisting of an empty list

### ISSUE THREAD

**Issue by kpinc** [cannatag/ldap3#780]
Hello,

The documentation does not say what happens if one of the attributes added is multivalued, but there are no values.  It's pretty obvious that this should result in the attribute not being part of the new entry but it would be nice if this was documented.

https://ldap3.readthedocs.io/add.html

**Comment by cannatag** [comment]
Hi, I've added this in the docs:
```
If you try to add an attribute with an empty value or a multi-valued attributes with all empty values, the attribte won't
be created, because the LDAP protocol doens't support NULL values.
```
