### ISSUE TITLE
connection.add() fails with mock sync connections

### ISSUE THREAD

**Issue by kpinc** [cannatag/ldap3#789]
```
server = ldap3.Server.from_definition('localhost', 'examples/dummy_server_info.json',
        'examples/dummy_server_schema.json')
 connection = ldap3.Connection(server, user='user',password='password',
        return_empty_attributes=False, auto_bind=ldap3.AUTO_BIND_NO_TLS,
        client_strategy=ldap3.MOCK_SYNC)
connection.add('uid=joe', attributes={'cn': 'joe', 'objectClass': ['person']})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kop/biz/aic/ldap/psoft2ldap2/psoft2ldap2/devel/pytest/lib/python3.7/site-packages/ldap3/core/connection.py", line 937, in add
    response = self.post_send_single_response(self.send('addRequest', request, controls))
  File "/home/kop/biz/aic/ldap/psoft2ldap2/psoft2ldap2/devel/pytest/lib/python3.7/site-packages/ldap3/strategy/mockBase.py", line 899, in send
    raise LDAPSocketOpenError(self.connection.last_error)
ldap3.core.exceptions.LDAPSocketOpenError: unable to send message, connection is not open
```

Strangely, when using the mock connection in testing I can do a connection.add().  But the code I am testing always does a connection.search() first.

If necessary I can privately supply you with the dummy_server*.json files.

**Comment by cannatag** [comment]
I don't understand. In your code snippet you are creating the dummy server and then try to add an object without opening the connection. So the ``ldap3.core.exceptions.LDAPSocketOpenError: unable to send message, connection is not open`` is correct. You should try to bind() with a valid user before adding the object.

Can you clarify the issue with a complete snippet to run?

**Comment by kpinc** [comment]
On Fri, 21 Feb 2020 09:29:32 -0800
Giovanni Cannata <notifications@github.com> wrote:

> I don't understand. In your code snippet you are creating the dummy
> server and then try to add an object without opening the connection.
> So the ``ldap3.core.exceptions.LDAPSocketOpenError: unable to send
> message, connection is not open`` is correct. You should try to
> bind() with a valid user before adding the object.

The connection has auto_bind set.

> Can you clarify the issue with a complete snippet to run?
> 

That is a complete snippet.  (Although the 2nd statement
has a leading space that shouldn't be there.  I find the
github markup difficult to work with.)

(Well, and I'm missing "import ldap3" at the top.)

If you add the following statement to what's already there:

connection.strategy.add_entry('uid=joe', attributes={'cn': 'joe', 'objectClass': ['person']})

You'll find that the entry adds.  (Run in the interpreter,
so that you can keep going after getting a traceback.)
So connection.strategy.add_entry() works but connection.add() does not.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by kpinc** [comment]
To give you an update, I'm thinking that the problem
is that when running tests I'm not adding an entry
to the dit that can later be used to bind/autobind.
And I'm not setting my mock test connection to raise
exceptions.

But the strange thing is that the tests still succeed,
the search works and returns the result I added
with connection.strategy.add_entry() even though
I'm apparently not successfully binding.

So I think there's a problem but it's not the
problem I reported.  I'll let you know more when I figure
things out.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by kpinc** [comment]
I've investigated and the problem is exactly as described.

Attached are files which demonstrate the problem.  There are 2 programs, one which uses the MOCK_SYNC strategy and the other which uses an actual ldap server.  The MOCK_SYNC strategy fails on connection.add() where the actual server using the SYNC strategy succeeds.

This is on a stock Debian (10, buster) system.  The ldap server is openlap (the slapd package).  It is configured with a DIT rooted at 'dc=example,dc=com'.  The database's root user is 'cn=admin,dc=example,dc=com' and the password is 'hello'.

[ldap3_bug_789.zip](https://github.com/cannatag/ldap3/files/4248299/ldap3_bug_789.zip)

**Comment by kpinc** [comment]
Hello,

I noticed that my bind user is not in the DIT loaded
for the mock test.  So I tried again, using the
"mock_test.py" file below instead of the one included
in the zip file.  The problem still exists.

-----------------<snip>---------------
# To be pasted into an interactive python session, so that
# additional commands can be executed after errors.

import ldap3

server = ldap3.Server.from_definition('localhost', 'dummy_server_info.json',
                                      'dummy_server_schema.json')

connection = ldap3.Connection(
    server, user='cn=admin,dc=example,dc=com',
    password='hello',
    return_empty_attributes=False, auto_bind=ldap3.AUTO_BIND_NO_TLS,
    client_strategy=ldap3.MOCK_SYNC)

connection.strategy.entries_from_json('dummy_server_data.json')

connection.strategy.add_entry(
    'cn=admin,dc=example,dc=com',
    # None of the following passwords work either.
    # attributes={'userPassword': 'hello',
    # attributes={'userPassword': '{SSHA}POeGG5/JF/HCV4+dmgh1EA8jS/gc/HgE',
    attributes={'userPassword':
                'e1NTSEF9UE9lR0c1L0pGL0hDVjQrZG1naDFFQThqUy9nYy9IZ0U=',
                'objectClass': 'simpleSecurityObject'})

# This fails with:
# ldap3.core.exceptions.LDAPSocketOpenError: unable to send message, connection\
 is not open
connection.add('cn=my_user,dc=example,dc=com',
               attributes={'cn': 'Some User',
                           'sn': 'User',
	                   'objectClass': [
                               "person",
                           ]})

# This succeeds.
connection.strategy.add_entry('cn=another_user,dc=example,dc=com',
                              attributes={'cn': 'Another User',
                                          'sn': 'User',
                                          'objectClass': [
                                              "person",
                                          ]})
-----------------<snip>---------------

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by cannatag** [comment]
Auto_bind doens't work because data aren't the server object yet. You must issue a bind() operation before of connection.add(...).

Also to create the admin user you must set the userPassword attribute to "hello". Then the code works.

**Comment by kpinc** [comment]
On Sat, 29 Feb 2020 08:43:44 -0800
Giovanni Cannata <notifications@github.com> wrote:

> Auto_bind doens't work because data aren't the server object yet. You
> must issue a bind() operation before of connection.add(...).

The data is in the server because I loaded it with 
connection.strategy.entries_from_json() and
connection.strategy.add_entry().  So the auto_bind option
should work when I do a connection.add().

> Also to create the admin user you must set the userPassword attribute
> to "hello". Then the code works.

I am no longer sure what code you are referring to because I tried
setting the userPassword attribute to "hello" and the code failed,
both on master and dev.

So let's single thread this.  Here is the code I'm talking
about.  (You should already have dummy_server_info.json
and dummy_server_schema.json in the zip file.)

----------------<snip>-------------
import ldap3

server = ldap3.Server.from_definition('localhost',
'dummy_server_info.json', 'dummy_server_schema.json')

connection = ldap3.Connection(
    server, user='cn=admin,dc=example,dc=com',
    password='hello',
    return_empty_attributes=False, auto_bind=ldap3.AUTO_BIND_NO_TLS,
    client_strategy=ldap3.MOCK_SYNC)

connection.strategy.entries_from_json('dummy_server_data.json')

connection.strategy.add_entry(
    'cn=admin,dc=example,dc=com',
    attributes={'userPassword': 'hello',
                'objectClass': 'simpleSecurityObject'})

# This fails with:
# ldap3.core.exceptions.LDAPSocketOpenError: unable to send message,
# connection is not open
connection.add('cn=my_user,dc=example,dc=com',
               attributes={'cn': 'Some User',
                           'sn': 'User',
                           'objectClass': [
                               "person",
                           ]})

----------------<snip>-------------

The connection.add() should have everything it needs in the DIT
to auto-bind.  But auto-bind does not work, connection.add() fails.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein

**Comment by eoyilmaz** [comment]
In this [help page](https://ldap3.readthedocs.io/en/latest/mocking.html) it says that you can not use ``auto_bind`` with a ``MOCK_SYNC`` strategy. May be it is related with that.

**Comment by kpinc** [comment]
Hello,

I don't know why this was closed.  The documentation may say that
you can't use auto_bind with MOCK_SYNC but that just means that
mocking is broken by design.  Mock objects should be able to replace
the actual object in all cases or you can't mock.  If there is a way
to use a mock object when the code tested auto_bind-s then that should
be documented.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein
