### ISSUE TITLE
extend.standard.modify_password need some special authentication?

### ISSUE THREAD

**Issue by davechina** [cannatag/ldap3#79]
I  define my connection look like this:

        self.conn = Connection(self.server,
                               user=user,
                               password=str(password),
                               authentication=AUTH_SIMPLE,
                               auto_bind=AUTO_BIND_NO_TLS)

the result of self.conn is OK:
    {'result': 0, 'description': 'success', 'saslCreds': None, 'referrals': None, 'message': '', 'dn': '', 'type': 'bindResponse'}

but when i use this self.conn to modify my userPassword,  it returned a different result, and the modify action failed.

            with self.conn as c:
                c.extend.standard.modify_password(user=dn,
                                                  old_password=old_password,
                                                  new_password=new_password)

the result looks like this:

   {'dn': '', 'type': 'extendedResp', 'responseName': None, 'referrals': None, 'result': 50, 'description': 'insufficientAccessRights', 'message': '', 'responseValue': b''}

why the the value of result changes to 50? should i need something special when i do an extend request?

**Comment by cannatag** [comment]
Hi, what lmao server are you connecting to? Modification of user password is not simple as it seems, for example the server could require a stronger authentication method or a secure channel. You should check the  server documentation and configuration to see if there are specific restrictions

Bye,
Giovanni

-------- Messaggio originale --------
Da:daveli <notifications@github.com>
Inviato:Fri, 03 Jul 2015 09:53:16 +0200
A:cannatag/ldap3 <ldap3@noreply.github.com>
Oggetto:[ldap3] extend.standard.modify_password need some special authentication? (#79)

**Comment by davechina** [comment]
Thanks a lot.   
I login as an admin, and everything is OK.
