### ISSUE TITLE
"Thread safety" with Cursor?

### ISSUE THREAD

**Issue by ilovetacos** [cannatag/ldap3#791]
Is there a way to "lock" an attribute on an ldap by a Cursor?
I have a web application to create new users on an ldap; I need to read an ID number (lastID) and set it +1 for each newly created user. If two people are using the application to create users simultaniously, how can I assure that this ID is set correctly?

**Comment by cannatag** [comment]
No, locking is not provided by the LDAP v3 Protocol. Some LDAP servers have extended operation or controls to manage "transactions" but you must check with your server docs. 

Also RFC4525 specifies the MODIFY_INCREMENT type of Modify operation: All existing values of the specified attribute are to be incremented by the listed value. The attribute must be appropriate for the request (e.g., it must have INTEGER or other increment-able values), and the modification must provide one and only one value. But you must check with your server docs if this kind of modify operation is supported.
