### ISSUE TITLE
Search fails when filtering on a property flag

### ISSUE THREAD

**Issue by rverhoev** [cannatag/ldap3#792]
When trying to filter on a flag the LDAPInvalidFilterError('malformed filter') error is raised.

'search_filter': '(&(objectcategory=person)(objectclass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))'

**Comment by cannatag** [comment]
your filter is incorrect, you're missing the parenthesis for the negation of useraccountcontrol. It should be:

```
(&(objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
```
