### ISSUE TITLE
pyasn1 dependency too lax

### ISSUE THREAD

**Issue by Sohalt** [cannatag/ldap3#794]
The `requirements.txt` lists `pyasn1>=0.1.8` but using `pyasn1==0.4.5` gives `ImportError: cannot import name 'PyAsn1UnicodeDecodeError' from 'pyasn1.error'`

**Comment by cannatag** [comment]
Thanks, will update the requirements soon in 2.7.1.

**Comment by ethompsy** [comment]
I can confirm that using `pyasn1==0.4.4` gives this same error.

**Comment by richvdh** [comment]
I see this is still an issue on the `master` and `dev` branches: any chance of the fix being merged to at least one of those branches - and ideally a 2.7.1 release being made?

It's a bit frustrating to see the PR which fixes it (#802) closed without being merged.

**Comment by richvdh** [comment]
(I see it's been fixed on the `dev` branch, as of https://github.com/cannatag/ldap3/commit/391aa243cadfc3f68fa079f95e0375e05839c90f. Still no 2.7.1 release yet)

**Comment by richvdh** [comment]
(v2.8, which fixes this bug, was released on 2020/08/07.)
