### ISSUE TITLE
ldap3.core.exception.LDAPSSLNotSupportedError:SSL not supported in this Python interpreter

### ISSUE THREAD

**Issue by qq719862911** [cannatag/ldap3#799]
What should I do
In Ubuntu 16.04, python2.7.5, install from the source, and then execute import ldap3 in python2.5.7 to report an error: ldap3.core.exception.ldapsslnotsupportederror: SSL not supported in this Python interpreter

**Comment by cannatag** [comment]
Probably you have to add some packages to your distribution for enabling ssl in python.

**Comment by qq719862911** [comment]
Excuse me, can you elaborate?

**Comment by qq719862911** [comment]
thank you.
This article can solve this problem
https://blog.csdn.net/NGUever15/article/details/100102501
