### ISSUE TITLE
modify'ing binary attributes

### ISSUE THREAD

**Issue by jspin** [cannatag/ldap3#8]
Hello,
It's entirely possible I'm doing it wrong, but I've been unsuccessful updating the thumbnailPhoto attribute.

The following code works using ldap with python 2.x
f = open('path/to/img.jpg', 'rb')
img = f.read()
ok = ldap_obj.modify(dn, [(ldap.MOD_REPLACE, 'thumbnailPhoto', img)])

I realize that f.read() in python3 returns bytes so i've tried casting to str or calling .decode with both utf-8 and cp437 as the format, in all cases, this fails:

foto = str(img)
#foto = img.decode('cp437')
ok = ldap_obj.modify(dn, {'thumbnailPhoto': (ldap3.MODIFY_REPLACE, [foto]) })

using version 0.9.7.2 on python 3.4.2

**Comment by cannatag** [comment]
Hi jspin.
you should just pass the binary data to the modify operation:

from ldap3 import Server, Connection, MODIFY_REPLACE
s = Server('server')
c = Connection(s, 'user', 'password')
c.bind()

f = open('a.png', 'br')
img = f.read()
c.modify('cn=abc,o=test', {'photo': (MODIFY_REPLACE, [img])})

Bye,
Giovanni

**Comment by jspin** [comment]
Hello Giovanni and thanks for the reply!

That's exactly what I tried initially, but it wasn't working.  I'm 
embarrassed to admit this, but it was something about the images I 
chose.  I happened to try a different one and it worked.

So this leads me to another question.

ok = c.modify(....)

With the initial images I chose, ok was False.  No exceptions were 
raised so is there a way to get any details about why the modify 
operation failed?

thx

**Comment by cannatag** [comment]
You can check the connection.result to get the result code from the server. You should find a dictionary with the error code and the description from the server. There is also an Exception mode' in the library: If you set the raise_exceptions argument to True in the connection you can get a detaild exception when anything goes wrong, 

Bye,
Giovanni 

----- Messaggio originale -----
Da: "Joe Spinney" <notifications@github.com>
Inviato: ‎25/‎01/‎2015 09:27
A: "cannatag/ldap3" <ldap3@noreply.github.com>
Cc: "Giovanni Cannata" <cannatag@gmail.com>
Oggetto: Re: [ldap3] modify'ing binary attributes (#8)

Hello Giovanni and thanks for the reply!

That's exactly what I tried initially, but it wasn't working. I'm 
embarrassed to admit this, but it was something about the images I 
chose. I happened to try a different one and it worked.

So this leads me to another question.

ok = c.modify(....)

With the initial images I chose, ok was False. No exceptions were 
raised so is there a way to get any details about why the modify 
operation failed?

thx
