### ISSUE TITLE
Issue with auxiliary_class "securityPrincipal"

### ISSUE THREAD

**Issue by bvaradinov-c** [cannatag/ldap3#804]
Hi,
I'm facing an issue with the auxiliary_class and "securityPrincipal" to Active Directory

# Code without issue:
``` Python
user = ObjectDef(['user'], self.connection, auxiliary_class=["posixAccount"])
reader = Reader(self.connection, user, self.connection.server.info.naming_contexts[0], query=query)
reader.search()
```
# Code with issue:
``` Python
user = ObjectDef(['user'], self.connection, auxiliary_class=["posixAccount", "securityPrincipal"])
reader = Reader(self.connection, user, self.connection.server.info.naming_contexts[0], query=query)
reader.search()
```
# Another code without issue:
``` Python
user = ObjectDef(['user'], self.connection, auxiliary_class=["posixAccount", "securityPrincipal"])
reader = Reader(self.connection, user, "<full user object dn>", query=query)
reader.search_object()
```

# Additional information
This is value of **reader.operations** with  auxiliary_class=["posixAccount", "securityPrincipal"]
[
    [
        {
            "base": "DC=dev,DC=local",
            "scope": 2,
            "dereferenceAlias": 3,
            "sizeLimit": 0,
            "timeLimit": 0,
            "typesOnly": false,
            "filter": "(&(objectClass=user)(SamAccountName=vagrant))",
            "attributes": [
                "ou",
                "msRASSavedFramedRoute",
                "desktopProfile",
                "pwdLastSet",
                "msRADIUSFramedIPAddress",
                "msDS-PhoneticLastName",
                "possibleInferiors",
                "msDS-ObjectReferenceBL",
                "allowedChildClasses",
                "msDS-OperationsForAzTaskBL",
                "description",
                "preferredDeliveryMethod",
                "manager",
                "scriptPath",
                "middleName",
                "msRADIUSServiceType",
                "sIDHistory",
                "pager",
                "tokenGroups",
                "altSecurityIdentities",
                "masteredBy",
                "preferredOU",
                "msTSLicenseVersion",
                "employeeNumber",
                "msIIS-FTPDir",
                "userCertificate",
                "o",
                "msRASSavedFramedIPAddress",
                "otherIpPhone",
                "displayName",
                "thumbnailLogo",
                "msIIS-FTPRoot",
                "msNPAllowDialin",
                "userSharedFolder",
                "wbemPath",
                "allowedChildClassesEffective",
                "userSMIMECertificate",
                "badPasswordTime",
                "otherMailbox",
                "wWWHomePage",
                "userParameters",
                "msRADIUS-SavedFramedIpv6Route",
                "msDS-KrbTgtLinkBl",
                "isCriticalSystemObject",
                "msDS-IsDomainFor",
                "msDS-NCReplCursors",
                "otherHomePhone",
                "msTSSecondaryDesktops",
                "tokenGroupsGlobalAndUniversal",
                "msDS-ReplAttributeMetaData",
                "msDS-PSOApplied",
                "st",
                "msTSProperty01",
                "msTSExpireDate2",
                "msPKI-CredentialRoamingTokens",
                "userAccountControl",
                "groupsToIgnore",
                "msDS-TasksForAzTaskBL",
                "groupMembershipSAM",
                "msTSExpireDate3",
                "msDS-SourceObjectDN",
                "msNPCallingStationID",
                "roomNumber",
                "uSNDSALastObjRemoved",
                "queryPolicyBL",
                "msTSLSProperty01",
                "uidNumber",
                "fromEntry",
                "bridgeheadServerListBL",
                "msTSManagingLS3",
                "msDS-LastKnownRDN",
                "lastLogonTimestamp",
                "objectSid",
                "uSNLastObjRem",
                "otherTelephone",
                "msDS-PhoneticFirstName",
                "initials",
                "uSNSource",
                "codePage",
                "destinationIndicator",
                "loginShell",
                "sAMAccountType",
                "facsimileTelephoneNumber",
                "homeDrive",
                "modifyTimeStamp",
                "nTSecurityDescriptor",
                "nonSecurityMemberBL",
                "lmPwdHistory",
                "allowedAttributesEffective",
                "msDS-HostServiceAccountBL",
                "msRADIUS-FramedIpv6Route",
                "preferredLanguage",
                "serverReferenceBL",
                "frsComputerReferenceBL",
                "msTSBrokenConnectionAction",
                "houseIdentifier",
                "whenCreated",
                "msDS-PrincipalName",
                "serialNumber",
                "msRASSavedCallbackNumber",
                "msDS-LastSuccessfulInteractiveLogonTime",
                "msTSProfilePath",
                "defaultClassStore",
                "msRADIUS-SavedFramedIpv6Prefix",
                "msTSAllowLogon",
                "proxyAddresses",
                "accountExpires",
                "terminalServer",
                "msRADIUS-FramedInterfaceId",
                "labeledURI",
                "unixHomeDirectory",
                "cn",
                "msCOM-UserPartitionSetLink",
                "displayNamePrintable",
                "jpegPhoto",
                "msDS-FailedInteractiveLogonCount",
                "employeeType",
                "profilePath",
                "msDRM-IdentityCertificate",
                "msTSInitialProgram",
                "objectGUID",
                "msDFSR-ComputerReferenceBL",
                "msDS-MembersForAzRoleBL",
                "msDS-Cached-Membership-Time-Stamp",
                "showInAdvancedViewOnly",
                "mS-DS-ConsistencyChildCount",
                "telexNumber",
                "dynamicLDAPServer",
                "msDS-Site-Affinity",
                "msTSRemoteControl",
                "msTSConnectClientDrives",
                "instanceType",
                "userPKCS12",
                "msTSConnectPrinterDrives",
                "dBCSPwd",
                "gidNumber",
                "whenChanged",
                "fRSMemberReferenceBL",
                "mSMQDigestsMig",
                "telephoneNumber",
                "msCOM-PartitionSetLink",
                "dSASignature",
                "repsFrom",
                "proxiedObjectName",
                "msDS-AllowedToDelegateTo",
                "adminDisplayName",
                "rid",
                "mS-DS-ConsistencyGuid",
                "replUpToDateVector",
                "logonHours",
                "msTSManagingLS2",
                "msTSLicenseVersion4",
                "msPKIRoamingTimeStamp",
                "attributeCertificateAttribute",
                "lastKnownParent",
                "msDS-ReplValueMetaData",
                "msDS-NC-RO-Replica-Locations-BL",
                "street",
                "msDS-RevealedListBL",
                "ownerBL",
                "otherPager",
                "co",
                "streetAddress",
                "employeeID",
                "msDS-PhoneticDepartment",
                "logonWorkstation",
                "operatorCount",
                "managedObjects",
                "msDS-NCReplOutboundNeighbors",
                "msDS-NonMembersBL",
                "msRADIUSCallbackNumber",
                "msDS-OperationsForAzRoleBL",
                "canonicalName",
                "postalCode",
                "msDS-Approx-Immed-Subordinates",
                "msRADIUS-FramedIpv6Prefix",
                "msTSExpireDate4",
                "postalAddress",
                "lastLogoff",
                "msDS-HABSeniorityIndex",
                "fSMORoleOwner",
                "msDS-TasksForAzRoleBL",
                "msDS-SupportedEncryptionTypes",
                "msSFU30NisDomain",
                "msDS-Cached-Membership",
                "msTSLicenseVersion3",
                "msDS-AuthenticatedAtDC",
                "unicodePwd",
                "partialAttributeSet",
                "postOfficeBox",
                "unixUserPassword",
                "primaryTelexNumber",
                "msTSMaxIdleTime",
                "msPKIAccountCredentials",
                "badPwdCount",
                "objectCategory",
                "uSNChanged",
                "msDS-LocalEffectiveDeletionTime",
                "company",
                "mobile",
                "internationalISDNNumber",
                "aCSPolicyName",
                "generationQualifier",
                "uid",
                "mhsORAddress",
                "ipPhone",
                "msDS-NcType",
                "sAMAccountName",
                "createTimeStamp",
                "netbootSCPBL",
                "businessCategory",
                "uSNCreated",
                "msTSHomeDrive",
                "groupPriority",
                "msDS-FailedInteractiveLogonCountAtLastSuccessfulLogon",
                "logonCount",
                "replPropertyMetaData",
                "url",
                "userSharedFolderOther",
                "msDS-KeyVersionNumber",
                "structuralObjectClass",
                "msTSReconnectionAction",
                "msSFU30Name",
                "msDS-AuthenticatedToAccountlist",
                "msDS-LastFailedInteractiveLogonTime",
                "otherWellKnownObjects",
                "userPassword",
                "USNIntersite",
                "memberOf",
                "assistant",
                "msRADIUS-SavedFramedInterfaceId",
                "mSMQDigests",
                "isDeleted",
                "seeAlso",
                "primaryGroupID",
                "ntPwdHistory",
                "givenName",
                "msTSMaxConnectionTime",
                "msTSProperty02",
                "msTSPrimaryDesktop",
                "departmentNumber",
                "primaryInternationalISDNNumber",
                "mSMQSignCertificatesMig",
                "msTSLSProperty02",
                "countryCode",
                "gecos",
                "siteObjectBL",
                "personalTitle",
                "lastLogon",
                "secretary",
                "directReports",
                "msNPSavedCallingStationID",
                "msDS-RevealedDSAs",
                "adminCount",
                "lockoutTime",
                "sn",
                "flags",
                "registeredAddress",
                "msExchHouseIdentifier",
                "msDS-PhoneticDisplayName",
                "msDS-SecondaryKrbTgtNumber",
                "msTSManagingLS4",
                "otherMobile",
                "tokenGroupsNoGCAcceptable",
                "controlAccessRights",
                "msTSHomeDirectory",
                "msRADIUSFramedRoute",
                "supplementalCredentials",
                "allowedAttributes",
                "carLicense",
                "msDS-NCReplInboundNeighbors",
                "homePhone",
                "msDS-IsFullReplicaFor",
                "department",
                "x500uniqueIdentifier",
                "subRefs",
                "subSchemaSubEntry",
                "msTSMaxDisconnectionTime",
                "teletexTerminalIdentifier",
                "msDS-ResultantPSO",
                "division",
                "objectClass",
                "msSFU30PosixMemberOf",
                "dSCorePropagationData",
                "comment",
                "repsTo",
                "extensionName",
                "msDs-masteredBy",
                "partialAttributeDeletionList",
                "mS-DS-CreatorSID",
                "securityIdentifier",
                "userPrincipalName",
                "msDS-IsPartialReplicaFor",
                "systemFlags",
                "otherLoginWorkstations",
                "accountNameHistory",
                "msCOM-UserLink",
                "otherFacsimileTelephoneNumber",
                "localeID",
                "revision",
                "msPKIDPAPIMasterKeys",
                "name",
                "homePostalAddress",
                "msTSWorkDirectory",
                "distinguishedName",
                "isRecycled",
                "homeDirectory",
                "l",
                "msTSDefaultToMainPrinter",
                "msTSManagingLS",
                "audio",
                "servicePrincipalName",
                "sDRightsEffective",
                "msDFSR-MemberReferenceBL",
                "maxStorage",
                "msDS-OIDToGroupLinkBl",
                "adminDescription",
                "msDS-User-Account-Control-Computed",
                "msTSExpireDate",
                "isPrivilegeHolder",
                "userWorkstations",
                "msDS-UserPasswordExpiryTimeComputed",
                "title",
                "mail",
                "msDS-LocalEffectiveRecycleTime",
                "networkAddress",
                "msDS-PhoneticCompanyName",
                "physicalDeliveryOfficeName",
                "c",
                "x121Address",
                "thumbnailPhoto",
                "msDS-EnabledFeatureBL",
                "msTSLicenseVersion2",
                "wellKnownObjects",
                "objectVersion",
                "mSMQSignCertificates",
                "photo"
            ],
            "type": "searchRequest",
            "controls": null
        },
        {
            "result": 1,
            "description": "operationsError",
            "dn": "",
            "message": "00002120: SvcErr: DSID-031402FD, problem 5012 (DIR_ERROR), data 0\n\u0000",
            "referrals": null,
            "type": "searchResDone"
        },
        []
    ]
]

Related to #486

**Comment by cannatag** [comment]
Hi, can you give more detail on the error you receive? I cannot test against Active Directory.
