### ISSUE TITLE
connection.search() returns 'top' as an objectclass for mock connections

### ISSUE THREAD

**Issue by kpinc** [cannatag/ldap3#806]
Hi,

When I make a connection using client_strategy=ldap3.MOCK_SYNC and do an ldapsearch I always get back an objectClass attribute of 'top'.

But when I connect to a openldap 2.4 slapd backend and do the same search
I only get an objectClass: top attribute if a 'top' value has been explicitly
put in an entry.  (Of course if I search for '(objectClass=top)' as a filter I
get all entries.  The 'top' objectclass, and I presume other ancestor
abstract classes, are implied.)

The mock connection should behave like the actual connection
and only return objectClass: top if the value has been explicitly
put into the entry.

Regards,
Karl

**Comment by cannatag** [comment]
Hi, other LDAP servers return always "top" as a structural class of every object, because the server follows the objectclass's hierarchy to define attributes of the entry. The mock strategy doesn't mimic a specific server, but try to follow the more generic LDAP RFCs.

**Comment by kpinc** [comment]
On Wed, 08 Jul 2020 15:14:53 -0700
Giovanni Cannata <notifications@github.com> wrote:

> Hi, other LDAP servers return always "top" as a structural class of
> every object, because the server follows the objectclass's hierarchy
> to define attributes of the entry. The mock strategy doesn't mimic a
> specific server, but try to follow the more generic LDAP RFCs.

Ok, fair enough.  Since the mock behavior may differ from
actual behavior if it were up to me I'd document this.
It requires special handling in my code that uses the mock.

Thanks for the help.

Regards,

Karl <kop@karlpinc.com>
Free Software:  "You don't pay back, you pay forward."
                 -- Robert A. Heinlein
