### ISSUE TITLE
Error modifying user memberof attribute with modify in ldap3

### ISSUE THREAD

**Issue by qq719862911** [cannatag/ldap3#808]
Hello, 
I want to try to modify it through the modify method in ldap3. The domain user in window server2012r2 belongs to the group (memberof), but an error is reported.
Excuse me, I want to modify the memberof attribute in AD users. What should I do?

The code is as follows:
self.__ldapconn.modify(dn='CN=xcv453,CN=Users,DC=test,DC=cdt,DC=com', changes={'memberOf': [('MODIFY_REPLACE', [u'CN=testGroup2,OU=\u8f6f\u4ef6\u7814\u53d1\u90e8,DC=test,DC=cdt,DC=com'])]})

The error is as follows:
{'dn': u'', 'referrals': None, 'description': 'unwillingToPerform', 'result': 53, 'message': u'0000209A: SvcErr: DSID-031A10E7, problem 5003 (WILL_NOT_PERFORM), data 0\n\x00', 'type': 'modifyResponse'}

**Comment by cannatag** [comment]
Please try to use the connection.extend.microsoft.add_members_to_groups() function to add members to an AD group.

**Comment by azornberg-ps** [comment]
@qq719862911 to give some detail on why what you're doing will never work with any ldap library - memberOf is a constructed attribute in active directory, meaning its not stored anywhere and is actively built from other records whenever its queried, and thus it cannot be modified directly.
