### ISSUE TITLE
Modify passwd,doesn't have hash method choose.

### ISSUE THREAD

**Issue by woshihaoren** [cannatag/ldap3#81]
Hi:
   I use ldap3, but doesn't have hash method choose for modify passwd.I need choose md5 hash...

**Comment by cannatag** [comment]
Hi, which ldap server are you trying to store passwords? Hashing password
is not in ldap standard, but you can hash the password with some crypto
modules, have a look at:

http://stackoverflow.com/questions/4070601/use-python-to-create-compatible-ldap-password-md5crypt-on-windows

Tell me if you think this should be included in the ldap3 library.

Bye,
Giovanni

**Comment by woshihaoren** [comment]
I use openldap for server and  Apache Directory Studio for client，,the client support many hash....
And, This problem has been solved,my  partner use java handle it.

I think don‘t included in the ldap3, ssha is good.

**Comment by cannatag** [comment]
Hi,
I've added this capability in 0.9.8.7. Please check the documentation for the extended operations
