### ISSUE TITLE
invalid class in objectClass

### ISSUE THREAD

**Issue by schlitzered** [cannatag/ldap3#811]
searching for (objectClass=automountMap) gives:

ldap3.core.exceptions.LDAPObjectClassError: invalid class in objectClass attribute: automountMap

IMHO, this should not give an error, since these objectClasses are valid according to:

https://help.ubuntu.com/community/AutofsLDAP

**Comment by cannatag** [comment]
Are you sure you’ve extended the schema with the automountMap definition?

**Comment by schlitzered** [comment]
i am not sure, i am working with on ald AD server, and colleagues told me that they have some kind of automount info stored in this ldap.

so if these schemas had been imported into this ldap, there would not be this stack trace?

**Comment by cannatag** [comment]
You should read server.schema.object_class after the connection with AD is established.  Or you could use the check_name=False parameter in the connection object to disable all checkings in the schema.

**Comment by schlitzered** [comment]
ok thanks!
