### ISSUE TITLE
error using ldap3

### ISSUE THREAD

**Issue by paulobruck1** [cannatag/ldap3#814]
Hi Cannata

First, let me thank you for this project. I have been using python-ldap and as I am starting playing wthin flask  I could find this nice project. Of course that I'll have to rework, but it will be for better. 80)

Studying  doc I stop with a little problem and I hope you can help me.

https://serverfault.com/questions/1012651/ldapstarttlserror-wrap-socket-error-ssl-internal-error-ssl-c1108

Traceback (most recent call last): File "", line 1, in File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 56, in open BaseStrategy.open(self, reset_usage, read_server_info) File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 141, in open raise exception_history0(exception_history[0][2]) ldap3.core.exceptions.LDAPSocketOpenError: (LDAPSocketOpenError('socket ssl wrapping error: [SSL] internal error (_ssl.c:1108)'),)

Have you seen this message error?

As you'll see using ldapsearch -xLLLZZ I can access my ldap base. How can I do the same using ldap3? Certanly I am doing something wrong..8)

Best regards

**Comment by Nazarii** [comment]
Hi  @paulobruck1 , looks like there is smth wrong with your SSL cert, the reason your ldapsearch works may be that it has disabled cert validation, please try enabling it with editing /etc/ldap/ldap.conf: 
TLS_REQCERT demand
TLS_CACERT /path/to_certs.pem
And try to rerun ldapsearch if that works.

You can also disable cert validation in ldap3 when creating ldap3.Tls(validate=ssl.CERT_NONE...) , but that is not secure.

**Comment by paulobruck1** [comment]
Hi Nazarii

Fortunately it is not a problema w/ ssl certs.

My ldap.conf
BASE	dc=xxx,dc=com,dc=br
URI	ldap://zeus7.xxx.com.br 
SIZELIMIT	0
TIMELIMIT	0
TLS_REQCERT demand
TLS_CACERT	/etc/ssl/xxx.com.br/cacert.pem

root@zeus7:~# ldapsearch -xLLLZZ | wc -l
5927

One think that I have done to work w/ python3-ldap3 was change auto_bind because I use start_tls + strong autentication.

Here is my new server and connection that is working:

tls_configurations = Tls(
        ca_certs_file = cacert, 
        local_private_key_file = serverkey, 
        local_certificate_file = servercrt, 
        validate=ssl.CERT_REQUIRED)

server = Server( hostnamef,
        get_info=ALL, 
        tls=tls_configurations),

**# changed auto_bind to work w/  start_tls + strong autentication**
conn = Connection(server, user=cn, password=password, 
                                      auto_bind=**AUTO_BIND_TLS_BEFORE_BIND** )
conn.start_tls()

By the way It would be nice to include this info about start_tls+strong autentication with docs 8)

But original problem persists. 
Probably I'm doing something wrong w/ python3-flask-ldapconn configuration... 8(

Thank's for helping

I'll try  a help with flask-ldapconn as I already using ldap3 and running smoothly

And many thanks for creating ldap3. I already migrate my scripts from python-ldap ( package python3-ldap /Ubuntu) to ldap3 ( package python3-ldap3/Ubuntu) 80)
