### ISSUE TITLE
Better examples of pushing a ldif file into AD using ldap3

### ISSUE THREAD

**Issue by dierkp512** [cannatag/ldap3#816]
Can you give me a heads up on where I can find a better example of taking an ldif or json file generated by ldap3 and adding it back into AD? 

For some reason I am not finding a good example on how to make this work easily without parsing the ldif file and push each field in using a normal add.

Thanks

**Comment by dierkp512** [comment]
I am using the latest library 2.7 and python 3.8.2

**Comment by cannatag** [comment]
ldif is just a format for describing entries and operation on entries. The LDAP protocol by itself doesn't specify how ldif can be exported and imported in LDAP servers, this depends on the LDAP server vendor. I suggest you to start reading https://support.microsoft.com/en-us/help/555636

bye,
Giovanni
