### ISSUE TITLE
LDAP3 Search in trusted domain

### ISSUE THREAD

**Issue by krevedka-jpg** [cannatag/ldap3#819]
Hello there! 

I have several domains that trusts have with each other. For example domain1.com. domain2.com. I can use my domain1 account to view accounts from domain2 through the Active Directory Users and Computers console. 

How can I do this via python + ldap3?

**Comment by Nazarii** [comment]
You'd probably want to have a look at the `auto_referrals` settings or configure your LDAP server to use that.
