### ISSUE TITLE
Is it possible to specify the krb5.conf?

### ISSUE THREAD

**Issue by minli1** [cannatag/ldap3#828]
Hi, is it possible in ldap3 to specify a different krb5.conf in params or other ways?
For example, I need to change some settings in krb5.conf in one isolation VM or Container but also used LDAP3 in another different VM or Container to do the query with the keytab file and the config file.
But seems LDAP3 cannot specify the krb5.config from another place?
I see there is a question about specifying the krb5 cred store, but not sure about specify the krb5.conf.
https://github.com/cannatag/ldap3/issues/602

**Comment by minli1** [comment]
Or is there any way to specify the `KDC` in ldap3?

**Comment by cannatag** [comment]
Kerberos is supported by a third party package (gssapi). I'm not involved in developing it. Have a look at its documentation at https://pythongssapi.github.io/python-gssapi/stable/index.html
