### ISSUE TITLE
__str__ returned non-string in class Attribute

### ISSUE THREAD

**Issue by hogneh** [cannatag/ldap3#83]
Hi

When I print an Attribute which holds a non-string value (an int in this case) I get this error:

```
__str__ returned non-string (type int)
```

I believe the following will fix the issue:

```
@@ -63,7 +63,7 @@ class Attribute(object):
 
     def __str__(self):
         if len(self.values) == 1:
-            return self.values[0]
+            return str(self.values[0])
         else:
             return str(self.values)
```

**Comment by cannatag** [comment]
Hi, hogneh, thanks for your message and your fix.  I know that there are some issues with the attributes representation, either with int and either with unicode characters. I will fix both in the next release of ldap3.

**Comment by cannatag** [comment]
Hi, can you check version in dev? It should fix the problem.

Bye,
Giovanni

**Comment by cannatag** [comment]
Please check 0.9.8.7. It should fix the problem.

Bye,
Giovanni

**Comment by hogneh** [comment]
Hi, yes it seems to work now.
