### ISSUE TITLE
Modifying multiple attributes

### ISSUE THREAD

**Issue by ilovetacos** [cannatag/ldap3#834]
I have a dictionary with` {'attribute_name': 'new attribute value'} `pairs and want to modify an entry.
This doesn't work:
```
for k, v in kwargs.items():
    if w[0][k] != kwargs[k]:
        w[0][k] += v
    else:
        pass
```
The syntax for modifying seems to be `w[0].attribute_name += 'new attribute value'`
and not `w[0][attribute_name] += 'new attribute value'`
Am I right? Am I overseeing something? How can I achieve this?
Thank you!

EDIT:
I kept trying and now  it's working with  `w[0][attribute_name] = 'new attribute value'`. However, I have to commit after each loop. Is there another way of doing it?

**Comment by cannatag** [comment]
Hi, have you checked the docs at https://ldap3.readthedocs.io/en/latest/tutorial_abstraction_writer.html ?

If you’re using the abstraction layer it should be quite simple to modify multiple attributes.

Let me know if you still have problems.

Bye,
Giovanni

**Comment by ilovetacos** [comment]
Hi, I have read the docs, I keep reading them almost every day 😆 
That's why I was clueless - Problem was something else. It's now working perfectly. Thank you again for the lib!
