### ISSUE TITLE
LDAPSocketOpenError: ("('socket ssl wrapping error: [SSL] PEM lib (_ssl.c:4012)',)",)

### ISSUE THREAD

**Issue by hrishy** [cannatag/ldap3#839]
Hi

```
import ssl
from ldap3 import AUTO_BIND_DEFAULT, AUTO_BIND_TLS_BEFORE_BIND, Server, Connection, ALL,Tls
tls = Tls(local_certificate_file='myldapservercert.pem', \
    ca_certs_file = 'digicertEVRootCA.cer', \
    validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1_2)
server = Server(host='myldapserver.com', port=636, use_ssl=True, get_info=ALL, tls=tls)
conn = Connection(server, user='cn=xxx,ou=yyyy,o=zzz',\
         password='mypassword')
conn.bind()
```

And i get this error
**LDAPSocketOpenError: ("('socket ssl wrapping error: [SSL] PEM lib (_ssl.c:4012)',)",)**

I am not sure but the documentation talks about passing a private key to the tls function.

And if i generate a privateKey and pass it to the to tls function what i get is
```
tls = Tls(local_certificate_file='myldapservercert.pem', \
    ca_certs_file = 'digicertEVRootCA.cer', \
    validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1_2,local_private_key_file='privateKey.key')
```
**LDAPSocketOpenError: ("('socket ssl wrapping error: [X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:4012)',)",)**

I am not sure why private key is required and why i get the key values mismatch error.

I generated the private key and certificate on my local client using openSSL Utility.
And if i generate a privateKey and pass it to the to tls function what i get is

```
tls = Tls(local_certificate_file='certificate.cer', \
    ca_certs_file = 'digicertEVRootCA.cer', \
    validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1_2,local_private_key_file='key.pem')
server = Server(host='myldapserver.com', port=636, use_ssl=True, get_info=ALL, tls=tls)
conn = Connection(server, user='cn=xxx,ou=yyyy,o=zzz',\
         password='mypassword')
**conn.start_tls()  
False**             
```

Any ideas what i am doing wrong ?
Because with private key local_private_key_file='key.pem'
and client certificate local_certificate_file='certificate.cer 
generated via open SSL on my laptop
`openssl req -x509 -nodes -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365`
I still get conn.start_tls false.

print(conn)
ldaps://myldapserver.com:636 - ssl - user: cn=xxx,ou=yyy,o=zzz - not lazy - unbound - open - <local: 1.1.1.1:63184 - remote: 1.1.1.1:636> - **tls not started** - listening - SyncStrategy - internal decoder

**Comment by cannatag** [comment]
Hi, if the server is reached on the 636 port with use_ssl=True you don't need start_tls(). Start_tls() is used when you open the connection on the unsecure port (usually 389) and then want to "upgrade" the connection to a secure socket.
