### ISSUE TITLE
check_json_dict is destructive when calling entry_to_json

### ISSUE THREAD

**Issue by dirkjanm** [cannatag/ldap3#844]
Hi,

When running in python2 and calling the `entry_to_json` function, this function modifies the entry and changes the attributes.
For example an entry containing a `timedelta` type attribute, after exporting the entry to JSON, the attibute will suddenly have type `str` on the original object. I don't think this is intended.

The issue is probably here: https://github.com/cannatag/ldap3/blob/master/ldap3/utils/conv.py#L173

**Comment by cannatag** [comment]
Thank, I've fixed it. Can you check the dev branch?

Bye,
Giovanni

**Comment by cannatag** [comment]
Fixed in ldap3 v2.8.
