### ISSUE TITLE
Document and possibly check Connection.start_tls return value

### ISSUE THREAD

**Issue by pcworld** [cannatag/ldap3#845]
It seems that [Connection.start_tls](https://github.com/cannatag/ldap3/blob/afa62995290cdcbde2019ecd26f5c961a8b4492d/ldap3/core/connection.py#L1244) returns a boolean. Is it correct that a return value of `False` implies that switching to a secure connection has failed and thus all subsequent commands will be run over a plain connection? If so, this should be documented as it has severe security consequences. Note that [Tls.start_tls](https://github.com/cannatag/ldap3/blob/afa62995290cdcbde2019ecd26f5c961a8b4492d/ldap3/core/tls.py#L245) (which is called from Connection.start_tls) raises an exception for some failures, for others it returns `False`. It's not clear to me when it returns instead of raising an exception. Maybe it should always raise an exception if setting up a secure connection has failed.

The [Connection documentation](https://github.com/cannatag/ldap3/blob/afa62995290cdcbde2019ecd26f5c961a8b4492d/docs/manual/source/connection.rst) currently doesn't document the return value of or exceptions raised from Connection.start_tls.

Note that if not checking the return value of Connection.start_tls is indeed a security issue, there are usages of the function within ldap3 where the return value is not checked, e.g. in [Connection.do_auto_bind](https://github.com/cannatag/ldap3/blob/afa62995290cdcbde2019ecd26f5c961a8b4492d/ldap3/core/connection.py#L374-L378).

**Comment by cannatag** [comment]
You're right. I've added additional checkings in the code for start_tls operation. Now it should raise an exception when it's not working. Can you try the code in dev branch?

Will add docs.

Thanks,
Giovanni

**Comment by cannatag** [comment]
Fixed in ldap3 v2.8.
