### ISSUE TITLE
Make certificate validation the default

### ISSUE THREAD

**Issue by pcworld** [cannatag/ldap3#846]
Certificate validation is currently [disabled by default](https://github.com/cannatag/ldap3/blob/afa62995290cdcbde2019ecd26f5c961a8b4492d/ldap3/core/tls.py#L73). This is an insecure preset, further it goes against user expectations as other software such as the OpenLDAP client [verifies certificates by default](https://www.openldap.org/doc/admin24/tls.html#TLS_REQCERT%20{%20never%20|%20allow%20|%20try%20|%20demand%20}).

It should be changed to verify the certificate and hostname by default.

**Comment by cannatag** [comment]
I know. Look at #481. For now it's disabled, maybe in version 3 will be enabled by default. Enabling it now would compromise many programs that uses ldap3 with self signed certificates.
