### ISSUE TITLE
SASL DIGEST-MD5 incorrect digest-uri

### ISSUE THREAD

**Issue by splinehip** [cannatag/ldap3#848]
When i try to bind to AD:
servers = ldap3.ServerPool(servers=[dc01, dc02, dc03], pool_strategy="ROUND_ROBIN", exhaust=3000)
connect = ldap3.Connection(servers,
                                              fast_decoder=False,
                                              read_only=True,
                                              authentication="SASL",
                                              sasl_mechanism="DIGEST-MD5",
                                              sasl_credentials=(DOMAIN, login, password, None))

connect.bind(read_server_info=True)

I'll get error: 
'message': "80090303: LdapErr: DSID-0C0904DD, comment: The digest-uri does not match any LDAP SPN's registered for this server., data 0, v2580\x00"

Reason is:
Digest_responce string contein incorrect digest-uri: "ldap/" but should be "ldap/**_host_**".
log:
>>LDAPMessage:
>> messageID=8
>> protocolOp=ProtocolOp:
>>  bindRequest=BindRequest:
>>   version=3
>>   name=
>>   authentication=AuthenticationChoice:
>>    sasl=SaslCredentials:
>>     mechanism=DIGEST-MD5
>>     credentials=username="MYUSER",realm="MYREALM",nonce="+Upgraded+v13869bcbfdfe65c3d519d107d507a40f1bd44a3735767d601d815fa537c7b8103240036aa6c3335b2b15d9fca73e46b2c8fca58e61eb2fc34",cnonce="d5232dacf81154adbae052203a6d88db",**digest-uri="ldap/"**,qop=auth,nc=00000001,charset="utf-8",response="e7f0e0e4eabfb30403344a83d328de2e"

In digestMd5.py module, line 97 has hard coded value:
uri = b'ldap/'

FYI: in line 98 has hard coded value qop = b'auth', but in line 114 has:
a2 = b'AUTHENTICATE:' + uri + (':00000000000000000000000000000000' if qop in [b'auth-int', b'auth-conf'] else b'')

1. if always will be False
2. concat bytestring and string will raise exception

When i changed this line 97 to: uri = b'ldap/' + connection.server.host.encode(charset) - digest-uri came correct and that error was gone.

But i got new error that was the same error when i tried to use SASL NTLM: 
'message': '00002028: LdapErr: DSID-0C090202, comment: The server requires binds to turn on integrity checking if SSL\\TLS are not already active on the connection, data 0, v2580\x00'

I checked posability bind to my ldap server with sasl digest-md5 through ldapsearch - all fine.

**Comment by cannatag** [comment]
Hi, can you try the code in dev? If you have problems try with "auth-int" as qop or establish an ssl connection (use_ssl=True)

**Comment by cannatag** [comment]
Fixed in ldap3 v2.8.

**Comment by splinehip** [comment]
Hi, thank you for answer. Yes if manualy set qop is "auth-int" authentication is succeeds. I am using digest-md5 connection because our servers not use ssl.
