### ISSUE TITLE
license term contradiction

### ISSUE THREAD

**Issue by tsen2020** [cannatag/ldap3#851]
https://pypi.org/project/ldap3/ mentions the license is "LGPL v3 license"
However the COPYING.txt mentions "GNU GENERAL PUBLIC LICENSE"

It need to be rectified.

**Comment by cannatag** [comment]
The additional "lesser" portion is included in the "COPYING.LESSER.txt" file. This is how it is suggested to do by GNU.org at https://www.gnu.org/licenses/gpl-howto.html
