### ISSUE TITLE
SASL DIGEST-MD5: not work of ldap search 

### ISSUE THREAD

**Issue by splinehip** [cannatag/ldap3#860]
Hi, tnhak you for answer. Yes if manualy set qop is "auth-int" authentication is succeeds. I am using digest-md5 connection because our servers not use ssl.
I changed qop to:
qop = b'auth-int' if 'qop' in server_directives and 'auth-int' in server_directives['qop'] else b'auth'
Authentication getting succeesfull.

But search is wrong, after long waiting:
>>>....
connect.bind(read_server_info=False)
....
DEBUG:ldap3:BASIC:done SASL BIND operation, result <{'result': 0, 'description': 'success', 'dn': '', 'message': '', 'referrals': [], 'saslCreds': b'rspauth=2badaeec9cba6e7990ba32d1bf5670d5', 'type': 'bindResponse'}>
DEBUG:ldap3:PROTOCOL:BIND response <{'result': 0, 'description': 'success', 'dn': '', 'message': '', 'referrals': [], 'saslCreds': b'rspauth=2badaeec9cba6e7990ba32d1bf5670d5', 'type': 'bindResponse'}> received via <ldap://dc03:389 - cleartext - user: None - not lazy - unbound - open - <local: 172.31.0.3:32811 - remote: 10.0.77.1:389> - tls not started - listening - SyncStrategy - pyasn1 decoder>
DEBUG:ldap3:BASIC:done BIND operation, result <True>
True
>>>connect.search(search_base=SEARCH_BASE,search_filter=SEARCH_FILTER.format(login),attributes=SEARCH_ATTRIBUTES,search_scope=ldap3.SUBTREE)
>>LDAPMessage:
>> messageID=59
>> protocolOp=ProtocolOp:
>>  searchRequest=SearchRequest:
>>   baseObject=OU=my-OU,DC=my,DC=server,DC=com
>>   scope=wholeSubtree
>>   derefAliases=derefAlways
>>   sizeLimit=0
>>   timeLimit=0
>>   typesOnly=False
>>   filter=Filter:
>>    and=And:
>>     Filter:
>>      equalityMatch=EqualityMatch:
>>       attributeDesc=objectClass
>>       assertionValue=user
>>     Filter:
>>      equalityMatch=EqualityMatch:
>>       attributeDesc=sAMAccountName
>>       assertionValue=myUser
>>   attributes=AttributeSelection:
>>    cn    mail    sAMAccountName    memberOf    objectGUID
DEBUG:ldap3:NETWORK:sent 166 bytes via <ldap://dc03:389 - cleartext - user: None - not lazy - bound - open - <local: 172.31.0.3:32811 - remote: 10.0.77.1:389> - tls not started - listening - SyncStrategy - pyasn1 decoder>
DEBUG:ldap3:NETWORK:closing connection for <ldap://dc03:389 - cleartext - user: None - not lazy - bound - open - <local: 172.31.0.3:32811 - remote: [None]:None> - tls not started - listening - SyncStrategy - pyasn1 decoder>
DEBUG:ldap3:NETWORK:connection closed for <ldap://dc03:389 - cleartext - user: None - not lazy - bound - closed - <no socket> - tls not started - not listening - SyncStrategy - pyasn1 decoder>
DEBUG:ldap3:ERROR:<error receiving data: [Errno 104] Connection reset by peer> for <ldap://dc03:389 - cleartext - user: None - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - pyasn1 decoder>
ConnectionResetError: [Errno 104] Connection reset by peer

If I use connect.bind(read_server_info=TRUE), bind will be unsucceesfull with the same error.

I see successfull authentication request on the server side but I can't see the search request.

_Originally posted by @splinehip in https://github.com/cannatag/ldap3/issues/848#issuecomment-671124125_

**Comment by cannatag** [comment]
Hi, "ConnectionResetError: [Errno 104] Connection reset by peer" means that the server has closed the connection. Can you check if you have any server-side error?

**Comment by splinehip** [comment]
Hi, after was sended the bind request I see that authentication request with successfull result on the my server-side.
After was sended the search request I have not  that request in server-side log and have not any server-side error..
If I use ldapsearch, a have both request in server-side log with successfull result.

**Comment by Augustin-FL** [comment]
Hi @splinehip, 

The error  ```00002028: LdapErr: DSID-0C090202, comment: The server requires binds to turn on integrity checking if SSL\TLS are not already active on the connection, data 0, v2580\x00``` is caused because your MS Controllers do require LDAP Signing.

A new feature ( #899 ) will be relased in the next ldap3 version (which is expected in 1 or 2 week). This feature allows ldap3 to perform signed queries. A new parameter,  `enable_signing` must be set to enable this feature.
Please check https://ldap3.readthedocs.io/en/latest/bind.html#digest-md5 for more information.

I'd propose to close this issue as the new feature resolves the problem

**Comment by zorn96** [comment]
thanks for the comment @Augustin-FL!

@splinehip another workaround if you don't want to wait for the next release is to either use an "ldaps://" uri to define your server/connection (defaults to port 636) or to change your flow to open a connection and start TLS before binding
```
connect.open(read_server_info=False)
connect.start_tls()
connect.bind(read_server_info=False)
```
there's also a "bind strategy" for start tls before binding that you can use. this snippet is a little more explicit.

If your domain requires signing, then using StartTLS or LDAPS will also fulfill the requirement.

**Comment by splinehip** [comment]
Thank you @Augustin-FL for your job!
