### ISSUE TITLE
SSL connection to LDAP server not working with ldap3 on CentOS 8.1 running in docker container

### ISSUE THREAD

**Issue by kushaal-veijay** [cannatag/ldap3#861]
We were using ldap3 to connect to LDAP server over SSL with CentOS 6.8 running in docker container and everything was working fine. However, after we have upgraded to base image of CentOS 8.1, SSL connection to LDAP server has stopped working. 

This is the mechanism with which we create the connection 
tls = Tls(ca_certs_file='/store/auth/isimldapcert.pem', validate=ssl.CERT_REQUIRED)
server = Server(host, port, use_ssl=True, tls=tls, get_info=ALL)
conn = Connection(server, bind_dn, password, auto_bind=True)

We have read about stricter crypto policy with CentOS 8.1 and hence we tried setting the crypto policy to legacy using **update-crypto-policies --set LEGACY**, but even that didn't work.

Moreover, if I use validate=ssl.CERT_NONE, the code just hangs trying to obtain the connection.

How to debug this problem?

**Comment by azornberg-ps** [comment]
hi @kushaal-veijay ! you might want to try leaving out the TLS config entirely. so 
server = Server(host, port, use_ssl=True, get_info=ALL)
and see if that can bind. if it can, then it means there's still an issue somewhere in your SSL stack. I'd recommend checking for any known issues in your underlying libraries - for example there's a version of gnu-tls that can trip up on certain certificate signature types even when explicitly not validating certificates, while openssl does not have that issue.

So I'd look at what changed in your SSL stack between 6.8 and 8.1 and check what library you use. If it's openssl, you can try using openssl s_client command line tools to figure out why you're failing TLS negotiation with the server (I imagine gnu-tls has similar tools, but I'm unfamiliar with them)

**Comment by zorn96** [comment]
hi @kushaal-veijay ! if there's nothing further here, then I'll close this issue :)
