### ISSUE TITLE
When auto_range is set to True, by default the attribute 'member' ranging 1500-* is returned

### ISSUE THREAD

**Issue by Arsathar** [cannatag/ldap3#868]
Hello, I am trying to read 'member' attribute from AD and I am using RESTARTABLE as client_strategy.

When the auto_range is set to False, 'member';range=0-1499 is returned.
When the auto_range is set to True, 'member';range=1500-* is returned.

Is there a way I can fetch all the 'member' attribute ranging 0-* ?
Below is the sample code:

conn = Connection(server, user=args.username, password=args.password, client_strategy=RESTARTABLE)
    conn.bind()
    conn.search(search_base=SEARCH_BASE, search_filter='(&(objectClass=GROUP)(cn=%s))' % args.group,
                attributes=['member'], search_scope=SUBTREE, size_limit=0, time_limit=0)
    return conn.entries[0].member

Kindly suggest.

**Comment by cannatag** [comment]
Hi, what version of ldap3 are you using? Do you have the same behavior with a previous version?

**Comment by Arsathar** [comment]
Hi, I am using ldap3 version 2.8.
Yes, same with the previous version as well.

My similar powershell script is able to fetch 2000 plus members from the AD group, but with python I am facing this issue.

Is there a chance that conn.entries is getting overwritten?

**Comment by Arsathar** [comment]
Hello Giovanni, Thanks for letting know that this regression will be fixed in next release.

I just verified that in version 2.8, using SYNC strategy we are not able to fetch 'member' attribute from AD, except member attribute we are able to fetch all other attributes.

I just downgraded ldap3 to 2.7, tested my script and it fetched member attribute now.

Please consider this issue as well.

**Comment by cannatag** [comment]
FIxed in 2.8.1
