### ISSUE TITLE
pyinstaller problem

### ISSUE THREAD

**Issue by Nisutec** [cannatag/ldap3#869]
Hello,
I use ldap3 in one of my projects. But I have a problem how I can import the ldap3 package into pyinstaller. It will not automatically imported by pyinstaller the dependency pyasn has not this problem. How I can import ldap3 into pyinstaller.

**Comment by cannatag** [comment]
sorry, I don't know how pyinstaller works. I suggest you to read the pyinstaller docs at https://pyinstaller.readthedocs.io/en/stable.

bye,
Giovanni
