### ISSUE TITLE
Modifying user account - password never expire value?

### ISSUE THREAD

**Issue by sureshbyella** [cannatag/ldap3#873]
Hi,

I am able to create user/service account in AD using ldap3 module, Any suggestions on how to modify the user/service account with password never expire value?

conn.add(currentUser, 'User',  # add user in OU
                 {'givenName': rd_AD_User_Name,
                  'sn': "surname",
                  'departmentNumber': 'DEV',
                  'telephoneNumber': 1111,
                  'Logon Information':rd_AD_User_Name})
        password_expire = {"pwdLastSet": (MODIFY_REPLACE, [-1])}
        conn.modify(dn=currentUser, changes=password_expire)

**Comment by azornberg-ps** [comment]
hi @sureshbyella !
in AD, stuff like password expiry is controlled via the userAccountControl attribute, which is an integer value (representing a bit string) that it's best to set during creation.
see: https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/useraccountcontrol-manipulate-account-properties for the different values that you can add up to get the userAccountControl you want

you seem to want NORMAL_ACCOUNT and DONT_EXPIRE_PASSWORD which are 512 and 65536, so you'd use 512+65536 (though there may be other things you want too)
