### ISSUE TITLE
Dont throw away operational attributes if explicitly requested

### ISSUE THREAD

**Issue by Busuwe** [cannatag/ldap3#881]
A while back I submitted a pull request (https://github.com/cannatag/ldap3/pull/805) that made it so that the MockBase strategy didn't throw away operational attributes when they were explicitly requested (as opposed to using "+"). This was merged, but later reverted. However, looking at the commit messages and history for MockBase.py, (https://github.com/cannatag/ldap3/commits/dev/ldap3/strategy/mockBase.py) it feels like it possibly wasn't intended to revert my commit, but that the intent was to revert a different commit.

Was it intended? :-)

**Comment by cannatag** [comment]
Hi, sorry for the late answer. I've reinserted your code in the mockBase.py file.  Can you test the "dev" brach to see if it works as inteded?

Thanks,
Giovanni

**Comment by cannatag** [comment]
Fixed in ldap3 v2.9
