### ISSUE TITLE
Modify password fail：{'result': 19, 'description': 'constraintViolation'}

### ISSUE THREAD

**Issue by benddzz** [cannatag/ldap3#882]
Hello,
Excuse me, I want to modify the password attribute in AD users. What should I do?

The code is as follows:
def band():
            server = Server(self.cnf('LDAP_HOST'), get_info=ALL,use_ssl=True)
            conn = Connection(server, user=ldap_username, password=ldap_password, auto_bind=True, authentication=NTLM)
            print('conn：',conn)

def update_password(self, ldap_username: str,newpw,old_pwd):
        assert self.cnf('LDAP_BASE_DN') in ldap_username, f'ldap_username required full userdn: {ldap_username}'
        with self.bind() as conn:
            conn.extend.microsoft.modify_password(ldap_username, new_password=newpw,old_password=old_pwd)
            print("result",conn.result)

res2 = ad_obj.update_password("CN=yuanjing222,OU=testOu,DC=szad,DC=sunline","Sunline123",old_pwd="Sunline123")
    print(res2)

The error is as follows:
conn： ldaps://10.22.50.8:636 - ssl - user: szad\Administrator - not lazy - bound - open - <local: 10.18.88.16:51266 - remote: 10.22.50.8:636> - tls not started - listening - SyncStrategy - internal decoder

result ： {'result': 19, 'description': 'constraintViolation', 'dn': '', 'message': '0000052D: AtrErr: DSID-03190F80, #1:\n\t0: 0000052D: DSID-03190F80, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)\n\x00', 'referrals': None, 'type': 'modifyResponse'}

Use java to modify the same ad, this password can be modified successfully！

**Comment by gurkin33** [comment]
Hello, 
The answer on your question is here #130 . But I will take the main information for you (many thanks to @cannatag):
0000052D error code is about a minimum age of a password. Default policy - you cannot change password more than once per 1 day. To solve it use next command `net accounts /MINPWAGE:0` in powershell (run as Administrator).

00000056 that should mean that the old password is not the right one.

Hope it helps
