### ISSUE TITLE
LDAP3 Search Results different than Apache Directory Studio

### ISSUE THREAD

**Issue by smitchell** [cannatag/ldap3#884]
Looking for guidance on where to look to determine if I found an LDAP3 bug. I wrote an app for a client security group that is a portal for NetIQ and Active Directory. It works great except for one NetIQ query. All queries share the same connection manager and NetIQ search method. The only difference is the search base, LDAP filter, and attribute list passed into the search method.

The query looks for users who are members of a role, below. I changed the client attribute name for this post. The user roles field is a multi-value attribute.

(&(objectClass=MyUser)(My-Roles=Adolescent Services Registered Nurse))

The same LDAP Filter and Search Base works correctly in Apache Directory Studio but fails to return results with LDAP3.

The search filter is generated with the escape filter.

`        if self.role_name is not None and len(self.role_name) > 0:
            f += f'(My-Roles={escape_filter_chars(self.role_name)})'`

This LDAP filter works in the C# app I am replacing, and it works in Apache Directory Studio. I presume the next step is to set a breakpoint and step into LDAP3. Any suggestions on where to start? I was unsuccessful in getting LDAP3 logging to work.

**Comment by cannatag** [comment]
Hi Steve, can you try to get the EXTENDED log from the ldap library? Have a look at https://ldap3.readthedocs.io/en/latest/logging.html on how to do that. Then send me the part relevant to the search operation.

Thanks,
Giovanni

**Comment by smitchell** [comment]
Thank you, @cannatag. I tried unsuccessfully to enable extended logging but will try again over the weekend. The NetIQ Admin is going to get logs for me tomorrow. Also, my mock LDAP server includes the customer's LDAP schema, so I will attempt to recreate the problem in a unit test. I will share any meaningful information that I find.

**Comment by smitchell** [comment]
Sorry for the delay. I won't be able to get back to this until Thursday, but it is important to the client, so will get back to this issue once I put out some other fires.

**Comment by smitchell** [comment]
This was a false alarm. The results are being returned correctly. The issue was on the frontend.
