### ISSUE TITLE
Opening connection to IBM TDS crashes

### ISSUE THREAD

**Issue by marconfus** [cannatag/ldap3#9]
When opening a connection to an IBM TDS your code crashes with:
...
File "/.../site-packages/ldap3/protocol/rfc4512.py", line 80, in quoted_string_to_list
    return string
IndexError: string index out of range

The problem is, that the quoted_string_to_list function is called with an empty string.
Adding something like
````python
    if len(string) == 0:
        return string
````
before accessing string[0] fixes the problem.

**Comment by cannatag** [comment]
thanks I will include:
is not string:

**Comment by cannatag** [comment]
will be available in 0.9.7.3
