### ISSUE TITLE
ERROR:  Error in python: KeyError. DETAIL:  'attributes'

### ISSUE THREAD

**Issue by alexnur** [cannatag/ldap3#917]
Hi Im use ldap3 over multicorn for postgresql 11. 8 to get data from Active Directory.

CREATE EXTENSION multicorn; 
CREATE SERVER ldap_srv foreign data wrapper multicorn options (
    wrapper 'multicorn.ldapfdw.LdapFdw'
);

CREATE FOREIGN TABLE ldapexample2 (
objectGUID text,
    mail character varying,
    cn character varying,
    sAMAccountname text,
) server ldap_srv options (
    uri 'ldap://mydomain.ru',
    path 'dc=mydomain,dc=ru',
    scope 'sub',
    binddn 'cn=myuser,ou=ou_name,dc=mydomain,dc=ru',
    bindpwd 'mypassword',
    --objectClass '*'
    objectClass 'person'
);

select * from ldapexample2 limit 1000;
is ok.

select * from ldapexample2
 where samaccountname = 'username';
ERROR:  Error in python: KeyError
DETAIL:  'attributes'

select * from ldapexample2 limit 5000;
select * from ldapexample2;
ERROR:  Error in python: KeyError
DETAIL:  'attributes'
if you restrict the search to not allow null values in columns (objectClass), then 'where' works. 

Nullable values look like as '[]'.
I made changes to the file ldap3-dev/ldap3/core/connection.py, specified a value False for parameter return_emplty_attributes instead of True and compile ldap3.

Null values are now returned as valid NULL values.
However, the request
select * from ldapexample2
 where samaccountname = 'username' limit 100;
still returns an error 
ERROR:  Error in python: KeyError
DETAIL:  'attributes'

I've tried ldap3 branches master (2.9) and dev (2.9).
Using python 2.7.

How do I fix the error?

**Comment by zorn96** [comment]
hi @alexnur ! this doesn't sound like an issue in the ldap3 library, but rather an issue in how the library is used by multicorn or whatever wrapper it's working with

it seems that the extension library you're using expects a fixed data structure to be returned, with keys always present and populated in the same format, regardless of the result of an ldap query. but it doesn't seem like it utilizes the ldap3 library properly to ensure that that happens.

I recommend taking this question to multicorn. let me know if you have any further questions
