### ISSUE TITLE
Debugging add failure ?

### ISSUE THREAD

**Issue by nyue** [cannatag/ldap3#919]
```
def addEntry(conn):
    basedn = 'OU=Automation_Test,OU=IT Staff,OU=All Atomic Cartoons Staff,DC=atomiccartoons,DC=net'
    status  = conn.add(basedn,
                       'organizationalUnit',
                       {'givenName': 'Beatrix',
                        'sn': 'Young',
                        'departmentNumber': 'DEV',
                        'telephoneNumber': 1111}
                       )
    if not status:
        print('Failed to add entry')
```

Is there a way to get more feedback from the failed call to conn.add() rather than just True/False ?

I am not the AD admin, just a developer so it is difficult for me to know if the failure is a query failure, permission issue or AD setup requisite.

Cheers

**Comment by zorn96** [comment]
hi @nyue ! you can print/log "conn.result" and that should give you some more details. it should include an error code from the failure, as well as some somewhat human-readable details (ex: "LDAP: Error 50 - Insufficient Access Rights")

hope that helps!

**Comment by nyue** [comment]
Great, it provides the much needed details I was looking for. :-)
