### ISSUE TITLE
Sorry for that, but I have a question

### ISSUE THREAD

**Issue by jedi2light** [cannatag/ldap3#926]
For example
I have these two entries:
```
dn: cn=user1,ou=company,dc=...
cn: user1
...

dn: cn=user2,ou=company,dc=...
cn: user2
manager: cn=user1,ou=company,dc=...
...
```

And I have the next Python code

```
c = Connection(...)
c.search(['ou=company,dc=...'], '(objectClass=whatever)', ldap3.SCOPE_SUBTREE, attributes=['cn', 'manager'])`.

e = c.entries[<index-of-user2-entry>]
```

Now, I can access to `user2` CN attribute like `e.cn`. And okay, it's good.

But, how can I easily access `e.manager.cn`?

Maybe, I have to tell the library "hey, see this attribute value? yes, it's a DN, resolve that entry by DN for me, please".

But how can I do this using the `.search()` method? Can you give me a place in the documentation where it's described?

**Comment by zorn96** [comment]
hi! unfortunately this isn't something that is native to the LDAP protocol. the `manager` field is just a string. even though you and I can see it as a reference to another object somewhere in the system, the protocol (and thus the library) doesn't natively recognize it as such.
so you'd need to do this programmatically. this will also let you better handle users that don't have managers.
there's functions for checking if the value in `manager` is a valid DN, so you can use that to decide whether to do a BASE search for it or not. if you know the manager's DN will always lead with CN then you can also use the library's DN parsing functions to extra the CN from the DN

does that help at all?

**Comment by jedi2light** [comment]
Can you tell me what the function is?

**Comment by zorn96** [comment]
the function is `parse_dn`
you could do something like
```
import ldap3.utils.dn as dn_utils
...
# ldap entries often come back as single-valued lists even if the entry only has 1 value, so I'm assuming that's the case here
manager = 'UNKNOWN'
manager_dn_list = entry_currently_being_processed['manager']
if manager_dn_list:
    manager_dn = manager_dn_list[0]
    manager_pieces = dn_utils.parse_dn(manager_dn)  # there's kwargs for stripping whitespace and escaping ldap special characters if you could have those
    attribute, value, _ = manager_pieces[0]
    # handling in case there's a malformed manager value. you could log a warning or throw an error in the else clause
    if attribute.lower() == 'cn':
        manager = value
```

does that make sense?

**Comment by zorn96** [comment]
no problem, happy to help
