### ISSUE TITLE
Set logon denied in active directory

### ISSUE THREAD

**Issue by vandnanegi** [cannatag/ldap3#927]
I am not able to set logon denied in Active directory using python
![logon enied](https://user-images.githubusercontent.com/64529079/109469315-e1159000-7a93-11eb-96cb-f7218fa71158.JPG)

**Comment by zorn96** [comment]
hi @vandnanegi  I think that you're generally confused.
across both this question and a few others, it seems that there's been confusion between the ldap3 package as a python implementation of the LDAP protocol, the protocol itself, and Active Directory-specific schemas and attributes.

this is something that's AD-specific, and any questions on how its modification work or how the attribute works are better answered by consulting microsoft active directory documentation on it.

if it's alright, I'm going to close this.
if you have a specific piece of ldap3 python code that's causing issues, please open a new question with the details of the code and the issue, thanks
