### ISSUE TITLE
Slow connection with Host Name instead IP

### ISSUE THREAD

**Issue by vahidmafi** [cannatag/ldap3#937]
Connection function takes more than 20 seconds while using host name in Server function, however it takes less than a second in case of using IP address instead.

```
server = Server('192.168.xxx.yyy', use_ssl=True, get_info=ALL)
conn = Connection(server, 'someuser', 'somepass', client_strategy=SAFE_SYNC, auto_bind=True, authentication=NTLM)

```
_Executed in  0.58  seconds_

```
server = Server('dc1.mydomain.local', use_ssl=True, get_info=ALL)
conn = Connection(server, 'someuser', 'somepass', client_strategy=SAFE_SYNC, auto_bind=True, authentication=NTLM)

```
_Executed in  21.55  seconds_

What is the cause and how it should be fixed?

**Comment by zorn96** [comment]
hi @vahidmafi ! it sounds like this is an issue with your DNS/network.

I recommend doing an nslookup (or equivalent) of dc1.mydomain.local, checking the timing of that, and then checking reachability of all the results returned.

the lookup to the dns server could be slow. it's also possible that the dns server returns numerous ip addresses for that hostname but many of them are unreachable. if that's the case, then binding using the hostname will try those other ips and fail each in turn until it finds one that works.
this can considerably slow the bind process, and may be common in scenarios where 1 hostname represents numerous servers but some are behind a firewall.

**Comment by vahidmafi** [comment]
hi @zorn96 !

You are right. 
nslookup returns 2 IPs of which one is in 172.16.xxx.yyy range and it is unreachable for this client. This is by design and cannot be changed. 
So the only option would be to use IP address instead, wouldn't it?

**Comment by zorn96** [comment]
basically yeah. you could try messing with the underlying system dns config/networking config, which could shorten the time it takes to establish the connection. but using an IP will produce the most reliable standalone behavior

the `ldap3` library supports SNI options for TLS and also supports specifying canonical names for kerberos via sasl_credentials, so using an IP address shouldn't stop you from properly utilizing things that rely on hostnames :)

**Comment by zorn96** [comment]
forgot to mention - you could also change the order of addresses in dns, or setup another dns server for these clients, but that affects the entire data center. so I'm assuming you wouldn't want to
