### ISSUE TITLE
Encoding error when parsing referrals that contain non ascii characters

### ISSUE THREAD

**Issue by JonScibelli** [cannatag/ldap3#942]
Looks like an error will occur on line 51 of `ldap3/protocol/convert.py` if a referral was found on an AD server and it contains one or more non-ascii characters.  This line is forcing the text of each valid referral to be converted to a string using Python's built in `str(...)` function.  However, in the case with non-ascii characters, the ldap3 search will fail with the following error:

> UnicodeEncodeError: 'ascii' codec can't encode character u'\u0102' in position 40: ordinal not in range(128)

In this case the `str(...)` function did not like the Romanian character denoted by the unicode value u'\u0102' which caused my `paged_search` generator to fail completely.

Full Traceback of issue:

> Traceback (most recent call last):
>   File "/home/jon/ADSync/ADSync.py", line 147, in get_group_users
>     for entry in entry_gen:
>   File "/usr/lib/python2.7/site-packages/ldap3/extend/standard/PagedSearch.py", line 64, in paged_search_generator
>     None if cookie is True else cookie)
>   File "/usr/lib/python2.7/site-packages/ldap3/core/connection.py", line 788, in search
>     response = self.post_send_search(self.send('searchRequest', request, controls))
>   File "/usr/lib/python2.7/site-packages/ldap3/strategy/sync.py", line 139, in post_send_search
>     responses, result = self.get_response(message_id)
>   File "/usr/lib/python2.7/site-packages/ldap3/strategy/base.py", line 325, in get_response
>     responses = self._get_response(message_id)
>   File "/usr/lib/python2.7/site-packages/ldap3/strategy/sync.py", line 165, in _get_response
>     dict_response = self.decode_response_fast(ldap_resp)
>   File "/usr/lib/python2.7/site-packages/ldap3/strategy/base.py", line 512, in decode_response_fast
>     result = ldap_result_to_dict_fast(ldap_message['payload'])
>   File "/usr/lib/python2.7/site-packages/ldap3/utils/asn1.py", line 179, in ldap_result_to_dict_fast
>     response_dict['referrals'] = referrals_to_list([to_unicode(referral[3], from_server=True) for referral in response[3][3]])  # referrals
>   File "/usr/lib/python2.7/site-packages/ldap3/protocol/convert.py", line 49, in referrals_to_list
>     return [str(referral) for referral in referrals if referral] if referrals else None
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u0102' in position 40: ordinal not in range(128)

The line that fails:
https://github.com/cannatag/ldap3/blob/78c449dded29dad54e4e68055f7290ad8689fbd1/ldap3/protocol/convert.py#L51

**Comment by zorn96** [comment]
PR is out to fix this https://github.com/cannatag/ldap3/pull/969

however I'll note that this is only an issue in python 2. python 2 is EOL and won't be supported forever, so I recommend moving to python 3

**Comment by zorn96** [comment]
fix will come in the next version
