### ISSUE TITLE
I ran the script below to bind and I am getting this as my output "Process finished with exit code 0" and nothing else. How will I know that my connection is successful?  New to all of this thing. 

### ISSUE THREAD

**Issue by RobinMalhotraa** [cannatag/ldap3#957]
from ldap3 import Server, Connection, ALL

s = Server(host='myserver', port=389, use_ssl=False, get_info='ALL')
c = Connection(s, user='uid=idmsa,ou=People,ou=auth,o=csun', password='my password', auto_bind='NONE', version=3, authentication='SIMPLE', \
client_strategy='SYNC', auto_referrals=True, check_names=True, read_only=False, lazy=False, raise_exceptions=False)

if not c.bind():
    print('error in bind', c.result)

**Comment by zorn96** [comment]
@RobinMalhotraa  the exit code of 0 is purely related to how scripts execute on the command line, and it means the script didn't error out. this does not have to do with the ldap3 library at all, so I'm closing this
