### ISSUE TITLE
Please help me to resolve this. I don't know what I am doing wrong. 

### ISSUE THREAD

**Issue by RobinMalhotraa** [cannatag/ldap3#959]
import ldap3
from ldap3 import Server, Connection

# clear connection
my_server = 'XXXX'
my_user = 'uid=idmsa,ou=People,ou=auth,o=csun'
my_password = 'password'
search_filter = 'uid=ssy03858'

s0 = Server(my_server)
c0 = Connection(s0, my_user, my_password)
c0.bind()

c0.search('o=csun'), "(&(cn=person)(sAMAccountName=" + my_user + "))", ldap3.SUBTREE,
attributes = ['mail', 'sn', 'givenName']

ERROR 

 c0.search('o=csun'), "(&(cn=person)(sAMAccountName=" + my_user + "))", ldap3.SUBTREE,
TypeError: search() missing 1 required positional argument: 'search_filter'

**Comment by zorn96** [comment]
hi @RobinMalhotraa it looks like what you wrote isn't even proper python. your parentheses are in the wrong place. this isn't an issue in the library, but rather in your code
