### ISSUE TITLE
FAIL: test_valid_simple_alphanumeric_password_with_non_ascii_characters (test.testSaslPrep.Test)

### ISSUE THREAD

**Issue by midnightlynx** [cannatag/ldap3#96]
I saw these tests failing on python 2.x in your travis CI.
It's failing at your assertion comparing a bytes literal to the variable 'validated'.

ldap3.protocol.sasl.sasl.validate_simple_password will give any non-bytes password a pass through sasl_prep, then if it's not running in python 3.x, it will byte encode the prepped result.

The problem is, in python 2.x sasl_prep also returns a unicode string instead of 2.x's standard byte-based str. So it needs encoded to bytes either way, and it's not being done running on 2.x.

I forked and fixed it, I'll submit the pull request when my own CI tests finish running.

**Comment by midnightlynx** [comment]
I see some other failing tests. Mind if I keep poking those until the build passes, then do a pull request for all of it in one go?

**Comment by midnightlynx** [comment]
..Oh. All the pypy3 tests, and only the pypy3 tests, are failing now.

**Comment by cannatag** [comment]
Thanks, I know that on pypy3 tests are failing. The cause is pyasn 0.1.8. With 0.1.7 all tests passes. I have asked to the phase maintainer to check it.

**Comment by cannatag** [comment]
pls check in dev. I've fixed the validate_simple_password() function.

**Comment by midnightlynx** [comment]
Fixed.

**Comment by cannatag** [comment]
temporary removed pypy3 testing from Travis-CI. I will re.enable it when pyasn1 works again with pypy3. (pyasn1 0.1.7 doesn't suffer this issue).

**Comment by midnightlynx** [comment]
Looks like pypy3 is still only up to implementing python 3.2.x.
3.3 added some things having to do with strings that aren't backwards compatible to 3.0-3.2, but are backwards compatible to 2.x. That might be part of the issue.

**Comment by cannatag** [comment]
Yes, that's the problem. Pyasn1 (0.1.8) uses an incompatible syntax in its code. Hope the maintainer fix it or a newer pypy3 is released soon.
