### ISSUE TITLE
Error retrieving entries from Connection object.

### ISSUE THREAD

**Issue by w-p** [cannatag/ldap3#98]
On Samba and Windows, when attempting to retrieve entries with __entries()__, a KeyError is thrown for the __attributes__ key.

> `>>>` connection.entries()
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/venv/lib/python3.4/site-packages/ldap3/core/connection.py", line 1174, in entries
>    self._entries = self._get_entries(self.response)
>  File "/venv/lib/python3.4/site-packages/ldap3/core/connection.py", line 1184, in _get_entries
>    resp_attr_set = set(response['attributes'].keys())
> KeyError: 'attributes'

It appears that the issue is in the __response__ object.  __connection.py__ iterates over __connection.response__ and uses the key __attributes__ to access the dictionary.  However, on Samba and Windows, __connection.response__ also contains elements of __type: searchResRef__ with referral uri's for other naming contexts.  For example:

`[{'attributes': {'givenName': 'john'},`
`  'dn': 'CN=jbaker,OU=Engineering,OU=departments,DC=mydomain,DC=com',`
`  'raw_attributes': {'givenName': [b'john']},`
`  'type': 'searchResEntry'},`
` {'type': 'searchResRef',`
`  'uri': ['ldap://mydomain.com/CN=Configuration,DC=mydomain,DC=com']},`
` {'type': 'searchResRef',`
`  'uri': ['ldap://mydomain.com/DC=DomainDnsZones,DC=mydomain,DC=com']},`
` {'type': 'searchResRef',`
`  'uri': ['ldap://mydomain.com/DC=ForestDnsZones,DC=mydomain,DC=com']}]`

Am I missing something?  I'm really enjoying this module.  Thanks for the great work you've done.

**Comment by cannatag** [comment]
Hi Will, thanks for opening a ticket for this problem. I will fix it in the next release ol ldap3.

Bye,
Giovanni

**Comment by cannatag** [comment]
please check 0.9.8.8 (released today). it should solve your problem.

Bye,
Giovanni
