### ISSUE TITLE
Print search progress

### ISSUE THREAD

**Issue by tschroeder13** [cannatag/ldap3#980]
Hey all
is there a way to print out the progress of a LDAP search during the process? 
Similar to tqdm for iterables?

thx in advance and kind regards
Tobias

**Comment by zorn96** [comment]
hi @tschroeder13 ! unfortunately, servers don't report back their progress, and so there's no way to print any kind of accurate progress on a search.

you could try approximations, like if you have a fixed size limit on the response, and your request is paginated, you can print some % after each page you receive, but there's no guarantee that all pages will take the same amount of time to find and return, so it's really just a guess.

hope that helps!
