### ISSUE TITLE
Can't authenticate to AD server using ldap3 and kerberos

### ISSUE THREAD

**Issue by blardyblar** [cannatag/ldap3#994]
You closed the other issue saying it should work, so let's start a new one and maybe you can help me with why it doesn't work.
I just installed ldap3 from pip today (ldap3-2.9.1-py2.py3-none-any) and it pulled in pyasn1-0.4.8-py2.py3-none-any as a dependency. I also installed winkerberos from pip today as well (winkerberos-0.8.0-cp38-cp38-win_amd64)

Here's a minimum example:

from ldap3 import Server, Connection, Tls, SASL, GSSAPI
import ssl

tls = Tls(validate=ssl.CERT_NONE, version=ssl.PROTOCOL_TLSv1_2)
server = Server("ldaps://(FQDN of ldap server):3269", use_ssl=True, tls=tls)

BIND_USER = "[DOMAIN]\\[username]"
BIND_PASSWORD = "[password]"
#connection = Connection(server, user=BIND_USER, password=BIND_PASSWORD, auto_bind=True)
connection = Connection(server, authentication=SASL, sasl_mechanism=GSSAPI, auto_bind=True)

If I uncomment the top connection line that uses the username and password (and comment the second one), the connection works, and I can query the ldap server and get valid results back.

If I uncomment the second line which uses SASL and GSSAPI (and comment the first connection line), I get this stack trace:

C:\temp\ldaptest>python ldaptest.py
Traceback (most recent call last):
  File "ldaptest.py", line 14, in <module>
    connection = Connection(server, authentication=SASL, sasl_mechanism=GSSAPI, auto_bind=True)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\ldap3\core\connection.py", line 363, in __init__
    self._do_auto_bind()
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\ldap3\core\connection.py", line 389, in _do_auto_bind
    self.bind(read_server_info=True)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\ldap3\core\connection.py", line 615, in bind
    response = self.do_sasl_bind(controls)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\ldap3\core\connection.py", line 1343, in do_sasl_bind
    result = sasl_gssapi(self, controls)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\ldap3\protocol\sasl\kerberos.py", line 111, in sasl_gssapi
    return _windows_sasl_gssapi(connection, controls)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\ldap3\protocol\sasl\kerberos.py", line 279, in _windows_sasl_gssapi
    status = winkerberos.authGSSClientStep(ctx, base64.b64encode(in_token).decode('utf-8'),
winkerberos.GSSError: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable

So what am I doing wrong?

**Comment by zorn96** [comment]
Hi! So the issue here seems to be your local system configuration.

The winkerberos library does not support dynamic initialization of kerberos contexts (i spoke to this in another thread a while back). So you need to initialize a kerberos credential cache before initiating the connection. 

If your computer is domain-joined, then this mostly ties into needing the program to run in the right user context.
If your computer isn’t a domain member, then you can use the python subprocess library to run the windows kinit.exe program with appropriate arguments based on the domain and your user context. I’m assuming system dns, encryption types, etc are all pre-configured since that would be necessary on posix too. If not, you’ll need to do that external to your program

**Comment by blardyblar** [comment]
The machine is definitely domain joined. It's running as the same user that's actively logged in (the same user/password that I supplied for the other connection using username and password instead of kerberos). Does it have to run as a user with some elevated privs? 

Do you have any links that point me to more info, or even to the other thread where you were discussing this?
